"undefined"==typeof ExposureUtil&&(ExposureUtil={});
(function(){ExposureUtil.calculateExposure=function(b,c,d,a,e,f,g,k){var n=new HashMap,m=f.selections,l=parseInt(f.numberOfWinners),h=parseInt(f.numberOfActiveRunners);parseInt(f.numberOfRunners);f=ExposureUtil.getNotActiveSelectionIdArr(m);if(0==l||1<l)0<b.length&&ExposureUtil.appendToShow(g,b),!k&&0<c.length&&ExposureUtil.appendToShow(g,c),0<d.length&&ExposureUtil.appendToShow(g,d);b=ExposureUtil.genTicketArray(b,!0);c=ExposureUtil.genTicketArray(c,!1,!0);d=ExposureUtil.genTicketArray(d,!0);ExposureHandler.initMarketInfo(a,
e.replace("_","."),m,l,h,f);e=a=null;0<d.length&&(ExposureHandler.calculateExposure(d),h=ExposureHandler.getMarketExposure(),a=h.betSelections,ExposureHandler.setMarketExposure(h));!k&&0<c.length&&(ExposureHandler.calculateExposure(c),h=ExposureHandler.getMarketExposure(),a=h.betSelections,ExposureHandler.setMarketExposure(h));0<b.length&&(ExposureHandler.calculateExposure(b),k=ExposureHandler.getMarketExposure(),e=k.betSelections);for(var p in m)k=m[p].selectionKey,h={withoutBet:0,withBet:0,lossWithoutBet:0,
lossWithBet:0},null!=a&&(null!=a[k]?0==l||1<l?(h.withoutBet=a[k].selectionWinPL,h.lossWithoutBet=a[k].selectionLossPL):h.withoutBet=a[k].minExposure:h.withoutBet=null==a[0]?0:a[0].minExposure),null!=e&&(null!=e[k]?0==l||1<l?(h.withBet=e[k].selectionWinPL,h.lossWithBet=e[k].selectionLossPL):h.withBet=e[k].minExposure:h.withBet=null==e[0]?0:e[0].minExposure),n.put(k,h);return n};ExposureUtil.calculatePlTable=function(b){if(null==b||"ASIAN_HANDICAP"!=b.marketType)return 0;var c=b.eventId,d=b.marketId,
a=DataBase.unMatchTicket.getByMarketId(c,d,null,CategoryType.BETFAIR.unique()),e=[MyTransactionStatusType.Active.unique()];c=DataBase.txn.getByMarketId(c,d,null,e,CategoryType.BETFAIR.unique());if(0==a.length&&0==c.length)return ExposureHandler.clearPlTable(),0;ExposureHandler.initPlTable(b.marketType,b.selections);b=ExposureUtil.genTicketArray(a,!1,!0);ExposureHandler.calculateAsianHandicapExposure(b);b=ExposureUtil.genTicketArray(c,!0,!1);ExposureHandler.calculateAsianHandicapExposure(b);b=ExposureHandler.getMarketExposure().marketExposure;
return Math.abs(b)};ExposureUtil.getNotActiveSelectionIdArr=function(b){var c=[];if(0<b.length)for(var d in b){var a=b[d];null==a||null==a.status||SelectionUtil.isActive(a.status)||c.push(a.selectionKey)}return c};ExposureUtil.genTicketArray=function(b,c,d){var a=[],e;for(e in b){var f=b[e];var g=d?f.lastPrice:f.stake;0!=g&&null!=g&&(f=ExposureHandler.generatorBetTicketObj(f.eventId,f.marketId.replace("_","."),f.selectionKey,f.odds,g,f.sideType,c,f.status,f.result,f.selectionId,f.handicap),a.push(f))}return a};
ExposureUtil.appendToShow=function(b,c){for(var d in c){var a=c[d];MyTransactionStatusType.Active.unique()==a.status&&1!=a.summary&&-1==ArrayUtil.indexOf(b,a.selectionKey)&&b.push(a.selectionKey)}};ExposureUtil.calculateFancyBetExposure=function(b,c,d,a){d=ExposureUtil.genFancyBetTicketArray(d,!0);a=ExposureUtil.genFancyBetTicketArray(a,!0);FancyBetExposureHandler.initMarketInfo(b,c);c=b=null;0<a.length&&(FancyBetExposureHandler.calculateExposure(a),b=FancyBetExposureHandler.getMarketExposure(),FancyBetExposureHandler.setMarketExposure(b));
0<d.length&&(FancyBetExposureHandler.calculateExposure(d),c=FancyBetExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.calculateFancyBetLotteryExposure=function(b,c,d,a){d=ExposureUtil.genFancyBetLotteryTicketArray(d,!0);a=ExposureUtil.genFancyBetLotteryTicketArray(a,!0);FancyBetLotteryExposureHandler.initMarketInfo(b,c);c=b=null;0<a.length&&(FancyBetLotteryExposureHandler.calculateExposure(a),b=FancyBetLotteryExposureHandler.getMarketExposure(),FancyBetLotteryExposureHandler.setMarketExposure(b));
0<d.length&&(FancyBetLotteryExposureHandler.calculateExposure(d),c=FancyBetLotteryExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.calculateFancyBetKhaddaExposure=function(b,c,d,a,e){d=ExposureUtil.genFancyBetKhaddaTicketArray(a,!0);e=ExposureUtil.genFancyBetKhaddaTicketArray(e,!0);FancyBetKhaddaExposureHandler.initMarketInfo(b,c);c=b=null;0<e.length&&(FancyBetKhaddaExposureHandler.calculateExposure(e),b=FancyBetKhaddaExposureHandler.getMarketExposure(),
FancyBetKhaddaExposureHandler.setMarketExposure(b));0<d.length&&(FancyBetKhaddaExposureHandler.calculateExposure(d),c=FancyBetKhaddaExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.genFancyBetTicketArray=function(b){var c=[],d;for(d in b){var a=b[d];a=FancyBetExposureHandler.generatorBetTicketObj(a.eventId,a.marketId,a.runs,a.odds,a.stake,a.sideType,a.status);c.push(a)}return c};ExposureUtil.genFancyBetLotteryTicketArray=function(b){var c=[],d;for(d in b){var a=
b[d];if(null!=a.lotteryBall&&0<a.lotteryBall.length)for(var e in a.lotteryBall){var f=FancyBetLotteryExposureHandler.generateBetTicketObj(a.eventId,a.marketId,a.lotteryBall[e],a.odds,a.stake);c.push(f)}else f=FancyBetLotteryExposureHandler.generateBetTicketObj(a.eventId,a.marketId,a.runs,a.odds,a.stake),c.push(f)}return c};ExposureUtil.genFancyBetKhaddaTicketArray=function(b){var c=[],d;for(d in b){var a=b[d];if(0!=a.runs){var e=DataBase.fancyBetMarkets.get(a.eventId,a.marketId);null!=e&&(e=FancyBetMarketUtil.getKhaddaExtendedRuns(a.runs,
e.runsRange),a=FancyBetKhaddaExposureHandler.generateBetTicketObj(a.eventId,a.marketId,a.runs,e,a.odds,a.stake),c.push(a))}}return c};ExposureUtil.calculateFeedingSiteBetExposure=function(b,c,d,a,e,f,g){e=ExposureUtil.genFeedingSiteBetTicketArray(e,!0);f=ExposureUtil.genFeedingSiteBetTicketArray(f,!1);g=ExposureUtil.genFeedingSiteBetTicketArray(g,!0);IBCExposureHandler.initMarketInfo(b,c,d,a);c=b=null;0<g.length&&(IBCExposureHandler.calculateExposure(g),b=IBCExposureHandler.getMarketExposure(),IBCExposureHandler.setMarketExposure(b));
0<f.length&&(IBCExposureHandler.calculateExposure(f),b=IBCExposureHandler.getMarketExposure(),IBCExposureHandler.setMarketExposure(b));0<e.length&&(IBCExposureHandler.calculateExposure(e),c=IBCExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.genFeedingSiteBetTicketArray=function(b,c){var d=[],a;for(a in b){var e=b[a];e=IBCExposureHandler.generatorBetTicketObj(e.eventId,e.marketId,e.selectionId,e.odds,null==e.lastPrice?e.stake:e.lastPrice,c);d.push(e)}return d};
ExposureUtil.isEnableShowSportsBookExposure=function(b,c,d){return ApiSiteType.OW.unique()==b&&d||ApiSiteType.SPORTRADAR.unique()==b&&c?!0:!1};ExposureUtil.calculateSportsBookExposure=function(b,c,d,a,e,f,g){return ApiSiteType.SPORTRADAR.unique()==b?ExposureUtil.calculateSportradarExposure(c,d,a,e,f,g):ApiSiteType.OW.unique()==b?ExposureUtil.calculateOwExposure(c,d,a,e,f,g):null};ExposureUtil.calculateSportradarExposure=function(b,c,d,a,e,f){e=ExposureUtil.genSportradarTicketArray(e);f=ExposureUtil.genSportradarTicketArray(f);
SportradarExposureHandler.initMarketInfo(b,c,d,a);c=b=null;0<f.length&&(SportradarExposureHandler.calculateExposure(f),b=SportradarExposureHandler.getMarketExposure(),SportradarExposureHandler.setMarketExposure(b));0<e.length&&(SportradarExposureHandler.calculateExposure(e),c=SportradarExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.genSportradarTicketArray=function(b){var c=[],d;for(d in b){var a=b[d];a=SportradarExposureHandler.generatorBetTicketObj(a.eventId,
a.marketId,a.selectionId,a.odds,null==a.lastPrice?a.stake:a.lastPrice);c.push(a)}return c};ExposureUtil.calculateOwExposure=function(b,c,d,a,e,f){e=ExposureUtil.genOwTicketArray(e);f=ExposureUtil.genOwTicketArray(f);OwExposureHandler.initMarketInfo(b,c,d,a);c=b=null;0<f.length&&(OwExposureHandler.calculateExposure(f),b=OwExposureHandler.getMarketExposure(),OwExposureHandler.setMarketExposure(b));0<e.length&&(OwExposureHandler.calculateExposure(e),c=OwExposureHandler.getMarketExposure());return{exposureBeforeBet:b,
exposureAfterBet:c}};ExposureUtil.genOwTicketArray=function(b){var c=[],d;for(d in b){var a=b[d];a=OwExposureHandler.generatorBetTicketObj(a.eventType,a.eventId,a.marketId,a.selectionId,a.odds,null==a.lastPrice?a.stake:a.lastPrice);c.push(a)}return c};ExposureUtil.calculateBookMakerExposure=function(b,c,d,a,e,f){e=parseInt(e.numberOfActiveRunners);d=ExposureUtil.genBookMakerTicketArray(d,!0);a=ExposureUtil.genBookMakerTicketArray(a,!0);BookMakerExposureHandler.initMarketInfo(b,c,e);c=b=null;0<a.length&&
(BookMakerExposureHandler.calculateExposure(a),b=BookMakerExposureHandler.getMarketExposure(),BookMakerExposureHandler.setMarketExposure(b));0<d.length&&(BookMakerExposureHandler.calculateExposure(d),c=BookMakerExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.genBookMakerTicketArray=function(b){var c=[],d;for(d in b){var a=b[d],e=a.stake;0!=e&&null!=e&&(a=BookMakerExposureHandler.generatorBetTicketObj(a.eventType,a.eventId,a.marketId,a.selectionId,
a.odds,e,a.sideType,a.status,a.result),c.push(a))}return c};ExposureUtil.calculateFinancialExposure=function(b,c,d,a,e,f,g){return ApiSiteType.TS.unique()==b?ExposureUtil.calculateBinaryExposure(c,d,a,e,f,g):null};ExposureUtil.calculateBinaryExposure=function(b,c,d,a,e,f){d=ExposureUtil.genBinaryTicketArray(e);f=ExposureUtil.genBinaryTicketArray(f);BinaryExposureHandler.initMarketInfo(b,c);c=b=null;0<f.length&&(BinaryExposureHandler.calculateExposure(f),b=BinaryExposureHandler.getMarketExposure(),
BinaryExposureHandler.setMarketExposure(b));0<d.length&&(BinaryExposureHandler.calculateExposure(d),c=BinaryExposureHandler.getMarketExposure());return{exposureBeforeBet:b,exposureAfterBet:c}};ExposureUtil.genBinaryTicketArray=function(b){var c=[],d;for(d in b){var a=b[d],e=a.stake;0!=e&&null!=e&&(a=BinaryExposureHandler.generateBetTicketObj(a.eventId,a.marketId,a.price,a.odds,e,a.sideType),c.push(a))}return c}})();

