"undefined"==typeof StreamingUtil&&(StreamingUtil={});
(function(){function m(a,b){a=a.streamingCDNType;return StreamingCDNType.WangSu.value===a.value||StreamingCDNType.LimeLight.value===a.value||StreamingCDNType.Edgecast.value===a.value?"/live/m"+b+"/playlist.m3u8":StreamingCDNType.Akamai.value===a.value?"/live/m"+b+"/playlist.m3u8?hdnts=":"/live/m"+b+".m3u8"}function n(a,b,c){if(a.result)for(var d=0;d<a.result.length;d++){var e=a.result[d];c.jblChannelId==e.name&&(b.playUrlObjList=p(e.resoucres,StreamingUtil.getPlayUrlObjList(c.country)))}}function p(a,
b){let c=[];a.forEach(d=>{b.forEach((e,f)=>{e.url.includes(d)&&(c.push(e),b.splice(f,1),b=b.concat(b.splice(f,b.length-f)))})});Array.prototype.push.apply(c,b);return c}var h=null;StreamingUtil.getPlayUrlObjList=function(a){if(PageConfig.ENABLE_STREAMING_PLAY_LIST_V2){var b=StreamingCDNType.values(),c;for(c in b){var d=b[c];switch(d.name){case "WangSu":d.isActive=PageConfig.ENABLE_STREAMING_WANGSU;break;case "LimeLight":d.isActive=PageConfig.ENABLE_STREAMING_LIMELIGHT;break;case "Akamai":d.isActive=
PageConfig.ENABLE_STREAMING_AKAMAI;break;case "Ali":d.isActive=PageConfig.ENABLE_STREAMING_ALI;break;case "Tencent":d.isActive=PageConfig.ENABLE_STREAMING_TENCENT;break;case "Edgecast":d.isActive=PageConfig.ENABLE_STREAMING_EDGECAST;break;case "CDNetwork":d.isActive=PageConfig.ENABLE_STREAMING_CDNETWORK}}return StreamingUtil.getPlayUrlObjListV2(a)}return StreamingUtil.getPlayUrlObjListV1(a)};StreamingUtil.getPlayUrlObjListV2=function(a){return"IN"==a?StreamingCDNType.values().filter(b=>!0===b.isActive).sort((b,
c)=>b.sortForIN-c.sortForIN):"BD"==a?StreamingCDNType.values().filter(b=>!0===b.isActive).sort((b,c)=>b.sortForBD-c.sortForBD):StreamingCDNType.values().filter(b=>!0===b.isActive).sort((b,c)=>b.sort-c.sort)};StreamingUtil.getPlayUrlObjListV1=function(a){return PageConfig.ENABLE_STREAMING_ALI?"IN"==a||"BD"==a?[StreamingCDNType.LimeLight,StreamingCDNType.WangSu,StreamingCDNType.Ali,StreamingCDNType.Akamai,StreamingCDNType.Tencent]:[StreamingCDNType.WangSu,StreamingCDNType.LimeLight,StreamingCDNType.Ali,
StreamingCDNType.Akamai,StreamingCDNType.Tencent]:"IN"==a||"BD"==a?[StreamingCDNType.LimeLight,StreamingCDNType.WangSu,StreamingCDNType.Akamai,StreamingCDNType.Tencent]:[StreamingCDNType.WangSu,StreamingCDNType.LimeLight,StreamingCDNType.Akamai,StreamingCDNType.Tencent]};StreamingUtil.getPlayUrl=function(a,b,c){return a.streamingCDNType.url+m(a,b)};StreamingUtil.initPlayerObj=function(a,b,c,d,e,f,g,k,l){null==b&&(b="");d={RegId:"Monitor",defaultMuted:!1,maxChkBufferdTimes:10,maxChkReadyStateTimes:10,
maxDelaySec:6,maxChkSeekTimes:6,maxChkCurrentTimes:4,wasmUrl:"",errorCallBack:e};PageConfig.ENABLE_JBL_WEBSOCKET_LISTENING&&JBLWebSocket.connect(k,l.jblChannelId);PageConfig.ENABLE_JBL_INELLIGENT_CHANGE_LINE&&(a.webSocketResourceUrl=JBLWebSocket.getResourceUrl(),n(a.webSocketResourceUrl,a,l),setInterval(function(){n(a.webSocketResourceUrl,a,l)},1E4));a.playerObj=new StreamPlayer(d,!1);a.playerObj.sUID=g;a.playerObj.sChnnalName=b;a.streamingCDNType=a.playUrlObjList[a.urlIndex];a.url=a.streamingCDNType.url;
a.channel=b;a.eventType=c;a.video=null;a.mute=!0;a.playerObj.defaultMuted=!0;a.playerObj.useNativeVolume=!0;StreamingUtil.setPlayerMaxSeekSec(a);f()};StreamingUtil.setPlayerMaxSeekSec=function(a){EventType.HORSE_RACING.unique()==a.eventType?a.playerObj.maxSeekSec=30:a.playerObj.maxSeekSec=12};StreamingUtil.setPlayerChannel=function(a,b,c,d,e,f,g){a.playerObj.Stop();""!=e&&(a.streamingCDNType=a.playUrlObjList[a.urlIndex],a.url=StreamingUtil.getPlayUrl(a,e,f),a.sDomain=(new URL(a.url)).hostname,a.sUri=
m(a,e),a.channel=e,a.eventType=f,a.playerObj.sChnnalName=e,g(),a.streamingCDNType.isGetToken?StreamingUtil.getToken(a,b,c,d,StreamingUtil.startPlayerStream):StreamingUtil.startPlayerStream(a,b,c,d))};StreamingUtil.startPlayerStream=function(a,b,c,d,e){try{var f=a.url;null!=e&&null!=e.token&&(f=e.token);a.playerObj.InitConnect("video",f);StreamingUtil.doStreamA(a.url,a.channel,a.playerObj.sUID);PageConfig.ENABLE_JBL_WEBSOCKET_LISTENING&&JBLWebSocket.upsert(b,c,d.device,a.eventType,a.streamingCDNType.name);
null!=a.playerObj.HLSObj&&PageConfig.ENABLE_JBL_WEBSOCKET_LISTENING&&JBLWebSocket.testHls(a.playerObj.HLSObj,d.jblChannelId)}catch(g){Trace.printStackTrace(g)}};StreamingUtil.changeLine=function(a,b,c,d,e){a.urlIndex++;a.urlIndex>=a.playUrlObjList.length&&(a.urlIndex=0);StreamingUtil.setPlayerChannel(a,b,c,d,a.channel,a.eventType,e)};StreamingUtil.stopVideo=function(a){if(a.playerObj){a.channel="";try{a.playerObj.Stop(),a.playerObj=null,JBLWebSocket.remove()}catch(b){Trace.printStackTrace(b)}}};StreamingUtil.mute=
function(a,b){if(a.playerObj){a.mute=b;try{b?(a.playerObj.Mute(),$j("#mute").attr("class","btn-volume_off")):(a.playerObj.unMute(),$j("#mute").attr("class","btn-volume_on"))}catch(c){Trace.printStackTrace(c)}}};StreamingUtil.doStreamA=function(a,b,c){try{null==h&&(h=new StreamA);var d=a.substr(0,a.lastIndexOf("/")+1);h.send({project:"CRICKET",streamname:b,cdn:d,uid:c})}catch(e){Trace.log(e)}};StreamingUtil.getToken=function(a,b,c,d,e){$j.ajax({type:"POST",url:"/exchange/member/tokenService/getStreamingSecurityKey",
data:{sDomain:a.sDomain,sUri:a.sUri,type:a.streamingCDNType.unique(),sChannel:a.channel},success:function(f){null!=f&&e(a,b,c,d,f)},error:function(f,g,k){Trace.log(f.status);Trace.log(k)}})};StreamingUtil.setJblChannelObj=function(a,b,c){return{device:a,country:b,jblChannelId:c}}})();

