"undefined"==typeof FancyBetMarketUtil&&(FancyBetMarketUtil={});
(function(){FancyBetMarketUtil.isOffline=function(a){return FancyBetMarketStatusType.OFFLINE.unique()==a};FancyBetMarketUtil.isOnline=function(a){return 0<(a&FancyBetMarketStatusType.ONLINE.unique())};FancyBetMarketUtil.isSuspend=function(a){return 0<(a&FancyBetMarketStatusType.SUSPEND.unique())};FancyBetMarketUtil.isBallRun=function(a){return 0<(a&FancyBetMarketStatusType.BALL_RUN.unique())};FancyBetMarketUtil.isClosed=function(a){return 0<(a&FancyBetMarketStatusType.CLOSED.unique())};FancyBetMarketUtil.isSettled=
function(a){return 0<(a&FancyBetMarketStatusType.SETTLED.unique())};FancyBetMarketUtil.isVoided=function(a){return 0<(a&FancyBetMarketStatusType.VOIDED.unique())};FancyBetMarketUtil.isUnderProcessing=function(a){return 0<(a&FancyBetMarketStatusType.SETTLE_PROCESSING.unique())||0<(a&FancyBetMarketStatusType.VOID_PROCESSING.unique())||0<(a&FancyBetMarketStatusType.UNSETTLE_PROCESSING.unique())};FancyBetMarketUtil.isEnableBetting=function(a){return FancyBetMarketStatusType.ONLINE.unique()==a};FancyBetMarketUtil.isAllowUpdateRunsOdds=
function(a){return FancyBetMarketUtil.isOnline(a)&&!FancyBetMarketUtil.isClosed(a)};FancyBetMarketUtil.sortMarkets=function(a,e,c,d){c=FancyBetMarketType.getInstanceOf(c);d=FancyBetMarketType.getInstanceOf(d);c=null!=c?c.sort:99;d=null!=d?d.sort:99;if(c==d)return a>e?1:a<e?-1:0;if(c>d)return 1;if(c<d)return-1};FancyBetMarketUtil.getMarketStatusName=function(a){for(var e,c=Object.keys(FancyBetMarketStatusType).length-2;0<=c;c--)if(e=FancyBetMarketStatusType[Object.keys(FancyBetMarketStatusType)[c]],
0<(a&e.unique()))return e.name;return null};FancyBetMarketUtil.checkForAllClose=function(a){a=$j("#overWrap").find("#fancyBetTable_"+a);var e=a.find("#fancyBetHead"),c=!0,d=!0,h=a.find("#fancyBetMarketList").find("[id^=fancyBetMarket_]"),k=a.find("#bookMakerMarketList").find("[id^=bookMakerMarket_]");h.each(function(){var g=$j(this),b=g.prop("eventId");g=g.prop("marketId");b=DataBase.fancyBetMarkets.get(b,g).status;if(null!=b&&(FancyBetMarketUtil.isOnline(b)||FancyBetMarketUtil.isBallRun(b)||FancyBetMarketUtil.isSuspend(b))&&
!FancyBetMarketUtil.isClosed(b))return c=!1});0==h.length&&(c=!0);k.each(function(){var g=$j(this),b=g.prop("eventId");g=g.prop("marketId");b=DataBase.bookMakerMarkets.get(b,g).status;if(null!=b&&(BookMakerMarketUtil.isOnline(b)||BookMakerMarketUtil.isBallRun(b)||BookMakerMarketUtil.isSuspend(b))&&!BookMakerMarketUtil.isClosed(b))return d=!1});0==k.length&&(d=!0);c&&(a.find("[id^=fancyBetMarketList]").hide(),h.hide());d&&(a.find("[id^=bookMakerMarketList]").hide(),k.hide());c&&d?(e.find("h4").removeClass("in-play"),
a.find("#fancyBetNoBet").show()):(e.find("h4").addClass("in-play"),a.find("#fancyBetNoBet").hide())};FancyBetMarketUtil.checkForAllCloseForMobile=function(a,e){a=$j("#fancyBetTable_"+a);var c=a.find("#fancyBetHead"),d=!0,h=!0,k=a.find("#fancyBetTag").find("[id^=fancyBetMarket_]"),g=a.find("#bookMakerTag").find("[id^=bookMakerMarket_]");k.each(function(){var b=$j(this),f=b.prop("eventId");b=b.prop("marketId");f=DataBase.fancyBetMarkets.get(f,b).status;if(null!=f&&(FancyBetMarketUtil.isOnline(f)||FancyBetMarketUtil.isBallRun(f)||
FancyBetMarketUtil.isSuspend(f))&&!FancyBetMarketUtil.isClosed(f))return d=!1});0==k.length&&(d=!0);g.each(function(){var b=$j(this),f=b.prop("eventId");b=b.prop("marketId");f=DataBase.bookMakerMarkets.get(f,b).status;if(null!=f&&(BookMakerMarketUtil.isOnline(f)||BookMakerMarketUtil.isBallRun(f)||BookMakerMarketUtil.isSuspend(f))&&!BookMakerMarketUtil.isClosed(f))return h=!1});0==g.length&&(h=!0);d&&k.hide();h&&g.hide();d&&h?(c.find(".game-fancy").removeClass("in-play"),c.find("h4").find("span").html(e),
a.find("#noGameWrap").show(),a.find("#fancyBetField").hide()):(c.find(".game-fancy").addClass("in-play"),c.find("h4").find("span").html("<pre>in-play</pre>"+e),a.find("#noGameWrap").hide(),a.find("#fancyBetField").show())};FancyBetMarketUtil.getKhaddaExtendedRuns=function(a,e){return a+e-1};FancyBetMarketUtil.isBelongMarketType=function(a,e){return 0==a.containsType.length?!0:0<=a.containsType.indexOf(e)}})();

