"undefined"==typeof SportsBookMarketUtil&&(SportsBookMarketUtil={});
(function(){SportsBookMarketUtil.isInactive=function(a){return a==SportsBookMarketStatusType.INACTIVE.unique()};SportsBookMarketUtil.isOpen=function(a){return a==SportsBookMarketStatusType.OPEN.unique()};SportsBookMarketUtil.isSuspend=function(a){return a==SportsBookMarketStatusType.SUSPEND.unique()};SportsBookMarketUtil.isClosed=function(a){return a==SportsBookMarketStatusType.CLOSED.unique()};SportsBookMarketUtil.isSettled=function(a){return a==SportsBookMarketStatusType.SETTLED.unique()};SportsBookMarketUtil.isHide=
function(a){return a==SportsBookMarketStatusType.HIDE.unique()};SportsBookMarketUtil.sortMarkets=function(a,b,c,f){var d=a.marketType.sort,e=b.marketType.sort,g=a.marketType.specifierKey,h=b.marketType.specifierKey,k=a.apiSiteSpecifier,l=b.apiSiteSpecifier;a=a.marketType.selectionSpecifierKey;b=b.marketType.selectionSpecifierKey;if(d==e)if("undefined"!=typeof g&&"undefined"!=typeof h&&null!=k&&null!=l)try{var m=$j.parseJSON(k)[g],n=$j.parseJSON(l)[h];if($j.isNumeric(m)&&$j.isNumeric(n)){if(Number(m)>
Number(n))return 1;if(Number(m)==Number(n)&&"undefined"!=typeof a&&"undefined"!=typeof b){var p=$j.parseJSON(k)[a],q=$j.parseJSON(l)[b];return $j.isNumeric(p)&&$j.isNumeric(q)?Number(p)>Number(q)?1:-1:0}return-1}return 0}catch(r){return Trace.printStackTrace(r),0}else return c.localeCompare(f);return d>e?1:-1};SportsBookMarketUtil.sortSelections=function(a,b,c,f){if(ApiSiteType.OW.unique()==c&&OwBetType.getInstanceOf(f).orderById){if(a.id>b.id)return 1;if(a.id<b.id)return-1}else{if(a.apiSiteSelectionId>
b.apiSiteSelectionId)return 1;if(a.apiSiteSelectionId<b.apiSiteSelectionId)return-1}return 0};SportsBookMarketUtil.getMarketStatusName=function(a){for(var b,c=Object.keys(SportsBookMarketStatusType).length-2;0<=c;c--)if(b=SportsBookMarketStatusType[Object.keys(SportsBookMarketStatusType)[c]],a==b)return b.name;return null};SportsBookMarketUtil.isHideMarket=function(a){return SportsBookMarketUtil.isClosed(a)||SportsBookMarketUtil.isSettled(a)||SportsBookMarketUtil.isHide(a)};SportsBookMarketUtil.getFilterMarkets=
function(a,b){var c=[],f;for(f in b){var d=b[f];if(null!=d){var e=SportradarMarketType.getInstanceOf(d.eventType,d.apiSiteMarketId);if(null==e)Trace.printStackTrace(d),Trace.printStackTrace("marketType is null");else if("All"==a||("Popular"==a?e.popular:a==e.group))d.marketType=e,c.push(d)}}c.sort(function(g,h){return SportsBookMarketUtil.sortMarkets(g,h,g.marketName,h.marketName)});return c};SportsBookMarketUtil.getOwFilterMarkets=function(a,b){var c=[],f;for(f in b){var d=b[f];if(null!=d){var e=
OwBetType.getInstanceOf(d.apiSiteMarketType);if(null==e)Trace.printStackTrace(d),Trace.printStackTrace("marketType is null");else if("All"==a||("Popular"==a?e.popular:a==e.group))d.marketType=e,c.push(d)}}c.sort(function(g,h){return SportsBookMarketUtil.sortMarkets(g,h,g.marketName,h.marketName)});return c};SportsBookMarketUtil.getSportsBookMaxStake=function(a,b,c,f,d,e,g,h,k,l){a={apiSiteType:a,eventType:b,eventId:c,marketId:f,selectionId:d,odds:e,stake:g,betfairEventId:h,timestamp:(new Date).getTime()};
$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/getSportsBookMaxStake",data:{sportsBookBets:JSON.stringify([a]),isAcceptAnyOdds:k},success:l,error:function(m,n,p){Trace.log(m.status);Trace.log(p)}})}})();

