"undefined"==typeof ArionPokerHandler&&(ArionPokerHandler={});
(function(){ArionPokerHandler.init=function(){ArionPokerHandler.bindInitEvent()};ArionPokerHandler.bindInitEvent=function(){$j("#pokerLoginBtn").on("click",function(){if(PageConfig.isMobileOrTablet){if(!MobileLoginHandler.userIsLogin())return}else if("undefined"!=typeof LoginHandler&&!LoginHandler.userIsLogin())return;ArionPokerHandler.openDepositPage()});$j("#pokerDeposit").keydown(function(a){var b=a.which;KeyEventUtils.isNumberKey(a)||KeyEventUtils.isBackspaceKey(b)||KeyEventUtils.isDeleteKey(b)||
KeyEventUtils.isArrowKey(b)||KeyEventUtils.isTabKey(b)||KeyEventUtils.isEnterKey(b)||WindowEventUtil.stopEvent(a)});$j("#pokerDeposit").keyup(function(a){$j("#pokerDeposit").val()>PageConfig.pokerMaxDeposit?$j("#pokerErrorMsg").show():($j("#pokerErrorMsg").hide(),$j("#pokerPreCompute").html(MathUtil.decimal.multiply(PageConfig.pokerRate,$j(this).val())))});JsCache.get("#transfer_to_go").find("[id^=selectStake_]").unbind("mousedown").mousedown(function(a){var b=parseInt($j("#pokerDeposit").val())||
0;if(b<PageConfig.pokerMaxDeposit){var c=$j(this);c=parseInt(c.attr("stake"));b+=c;$j("#pokerDeposit").val(b);$j("#pokerPreCompute").html(MathUtil.decimal.multiply(PageConfig.pokerRate,b));b>PageConfig.pokerMaxDeposit&&$j("#pokerErrorMsg").show()}WindowEventUtil.stopEvent(a)})};ArionPokerHandler.bindCloseButtonEvent=function(){$j("#closePoker, #cancelPoker").on("click",function(){ArionPokerHandler.unBindEvent();$j("#transfer_to_go").hide();$j("#pokerErrorMsg").hide()})};ArionPokerHandler.bindLoginButtonEvent=
function(){$j("#pokerDeposit").prop("disabled",!1);$j("#pokerDepositAndLogin, #cancelPoker").removeClass("disable");$j("#pokerDepositAndLogin").on("click",function(){ArionPokerHandler.loginAndDeposit()})};ArionPokerHandler.unBindEvent=function(){$j("#pokerDeposit").prop("disabled",!0);$j("#pokerDepositAndLogin, #cancelPoker").addClass("disable");$j("#closePoker, #cancelPoker, #pokerDepositAndLogin").unbind("click")};ArionPokerHandler.openDepositPage=function(){$j("#cancelPoker").removeClass("disable");
$j("#pokerDepositAndLogin").addClass("disable");ArionPokerHandler.bindCloseButtonEvent();$j("#pokerDeposit").val("");$j("#pokerPreCompute").html("0");$j.ajax({type:"POST",url:"/exchange/member/vendorController/queryVendorCurrencyInfo",data:{vendorSite:VendorSiteType.ARION.value},beforeSend:function(){},complete:function(){},success:function(a){if(null!=a)if(a.error)ArionPokerHandler.showMessage(a.error);else{var b=CurrencyType.getInstanceOf(a.currencyType);$j("#transfer_to_go #vendorBalance").html(ArionPokerHandler.formatCurrency(b,
a.vendorPlayerBalance,0));$j("#pokerBalance").html(b.name+" "+ArionPokerHandler.formatCurrency(b,a.betCredit),2);$j("#pokerRate").html("1"+b.name+" = "+a.rate+" points");PageConfig.pokerRate=a.rate;PageConfig.pokerMaxDeposit=a.betCredit;$j.each(JSON.parse(a.stakeSetting),function(c,d){$j("#selectStake_"+c).attr("stake",d).html(d)});a.isEnableVendorLogin&&ArionPokerHandler.bindLoginButtonEvent()}}});$j("#transfer_to_go").css("display",PageConfig.isMobileOrTablet?"flex":"block")};ArionPokerHandler.deposit=
function(a){var b=!1;0<a?$j.ajax({type:"POST",async:!1,url:"/exchange/member/vendorController/deposit",data:{vendorSite:VendorSiteType.ARION.value,depositBalance:a},beforeSend:function(){JsCache.get("#poker_loading").show()},complete:function(){JsCache.get("#poker_loading").hide()},success:function(c){null!=c&&(c.error?(ArionPokerHandler.showMessage(c.error),ArionPokerHandler.bindCloseButtonEvent(),ArionPokerHandler.bindLoginButtonEvent()):b=!0)}}):b=!0;return b};ArionPokerHandler.loginAndDeposit=
function(){var a=""==$j("#pokerDeposit").val()?0:$j("#pokerDeposit").val();if(a>PageConfig.pokerMaxDeposit)$j("#pokerErrorMsg").show();else{ArionPokerHandler.unBindEvent();var b=null;$j.ajax({type:"POST",url:"/exchange/member/vendorController/login",data:{vendorSite:VendorSiteType.ARION.value},async:!1,beforeSend:function(){JsCache.get("#poker_loading").show()},complete:function(){JsCache.get("#poker_loading").hide()},success:function(d){if(null!=d)if(d.error)ArionPokerHandler.showMessage(d.error),
ArionPokerHandler.bindCloseButtonEvent(),ArionPokerHandler.bindLoginButtonEvent();else if(d.success){var e=!0;0<a&&(e=ArionPokerHandler.deposit(a));e&&(b=d.success,$j("#transfer_to_go").hide())}}});if(null!=b)if(PageCommonConfig.isApp)location=b;else{var c=window.open(b,"_blank");null!=c&&"undefined"!=typeof c||alert("Open new window fail, please confirm your browser")}}};ArionPokerHandler.validatePageNumber=function(a){a.value=a.value.replace(/[\D]|^0[\d]+/,"")};ArionPokerHandler.formatCurrency=
function(a,b,c){return CurrencyUtil.formatter(b,{precision:c,separateSign:",",currencySymbol:a.symbol,formatter:function(d,e){e=0==StringUtil.getlength(StringUtil.trim(e.currencySymbol))?"":e.currencySymbol;return 0==d.indexOf("-")?"("+e+d.replace("-","")+")":e+d},"trailingZeros,":!1})};ArionPokerHandler.withdrawAllFromArionPoker=function(){$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/vendorController/withdraw",data:{vendorSite:VendorSiteType.ARION.value,isWithdrawAll:!0},success:function(a){}})};
ArionPokerHandler.showMessage=function(a){PageConfig.isMobileOrTablet?alert(a):NoticeHandler.error(a)}})();

