var CountDownUtils={};(function(){CountDownUtils.isShowCountDown=!1;CountDownUtils.startCountDown=function(r){CountDownUtils.countDown(5,r)};CountDownUtils.countDown=function(r,n){0<r?(n.html(I18N.get("form.button.placeBets")+I18N.get("form.button.placeBets.forNumberSec",[r])),r--,setTimeout(function(){CountDownUtils.countDown(r,n)},1E3)):n.html(I18N.get("form.button.placeBets")+I18N.get("form.button.placeBets.processing"))}})();"undefined"==typeof BetHandler&&(BetHandler={});
(function(){function r(a,d){if(F){var b=DataBase.unMatchTicket.getByMarketId(null,null),c=DataBase.txn.getByMarketId(null,null);if($j(".slip-wrap").hasClass("full-bet_slip")||0==b.length&&0==c.length)a=$j("#betSlipBoard").height()-d;$j("#betList").attr("style","max-height:"+a+"px")}else $j("#betList").attr("style","max-height:calc(100% - "+d+"px);")}function n(a){var d=[];$j.each(a,function(b,c){if(!(c.sideType&&c.eventId&&c.marketId&&c.selectionId&&c.stake&&c.odds))return!0;b=DataBase.markets.get(c.eventId,
c.marketId.replace("_","."));if(!OddsUtil.isValidOdds(c.odds,b))if(PageConfig.ENABLE_LINE_MARKET){if(!MarketUtil.isLineMarket(b.marketType,b.bettingType))return!0}else return!0;if(1==BetHandler.backOddsIsLessThanLayOdds(c.eventId,c.marketId,c.selectionKey,c.sideType))return!0;b=BetHandler.getMinBet(c.eventId,c.marketId,c.eventType,c.odds);if(c.stake<b||1.01>c.odds)return!0;d.push(c)});return d}function q(){JsCache.get("#placeBets").addClass("disable")}function m(){JsCache.get("#placeBets").removeClass("disable")}
function w(){var a=JsCache.get("#betList"),d=a.find("dl"),b=0,c=0;$j.each(d,function(e,f){e=$j(f);if(e.hasClass("sum")||e.is(":hidden")||BetHandler.isLessThanMinStake(e,a))return!0;b=parseFloat(e.find("#odds").val());if(BetHandler.isLessThanMinOdds(b))return!0;MathUtil.isNumeric(b,!0,!1)&&DataBase.bet.updateOdds(e.attr("eventId"),e.attr("marketId"),e.attr("selectionKey"),e.attr("sideType"),b);c=BetHandler.isAllowNonIntegerStake(PageConfig.playerCurrency)?parseFloat(e.find("#inputStake").val()):parseInt(e.find("#inputStake").val());
MathUtil.isNumeric(c,!1,!1)&&DataBase.bet.updateStake(e.attr("eventId"),e.attr("marketId"),e.attr("selectionKey"),e.attr("sideType"),c);e=DataBase.markets.get(e.attr("eventId"),e.attr("marketId").replace("_","."));null!=e&&1==e.inPlay&&(CountDownUtils.isShowCountDown=!0)})}function y(a){let d=null,b=null,c=null,e=null,f=null,h=null;a.find("#delete").click(function(){var g=$j(this).parent().parent();BetHandler.deleteBet(g);BetHandler.getWinLoss(g.attr("eventId"),g.attr("marketId"))});a.find("#oddsUp").click(function(){var g=
BetHandler.clickOdds(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this,a);BetHandler.eventCalculate(a,g);BetHandler.getDynamicMinBet(a);a.find("#odds").select();1E3<a.find("#odds").val()&&(a.find("#odds").val(1E3),BetHandler.fadeInMsg("#errorMsg",I18N.get("msg.member.editBet.maximumOdds")))});a.find("#oddsDown").click(function(){var g=BetHandler.clickOdds(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this,a);BetHandler.eventCalculate(a,
g);BetHandler.getDynamicMinBet(a);a.find("#odds").select()});PageConfig.TEMP_CTRL_ENABLE_DESKTOP_BETBOARD_KEYDOWN&&(a.find("#oddsUp").mousedown(function(g){null===b&&(b=setTimeout(function(){b=null;null===d&&(d=setInterval(function(){a.find("#oddsUp").click()},50))},1E3))}),a.find("#oddsDown").mousedown(function(g){null===e&&(e=setTimeout(function(){e=null;null===c&&(c=setInterval(function(){a.find("#oddsDown").click()},50))},1E3))}),a.find("#odds").keydown(function(g){g=g.which;KeyEventUtils.isUpArrowKey(g)&&
null===h&&(h=setTimeout(function(){h=null;null===f&&(f=setInterval(function(){a.find("#oddsUp").click()},50))},1E3));KeyEventUtils.isDownArrowKey(g)&&null===h&&(h=setTimeout(function(){h=null;null===f&&(f=setInterval(function(){a.find("#oddsDown").click()},50))},1E3))}));a.find("#oddsUp").mouseup(function(g){clearInterval(d);clearTimeout(b);b=d=null});a.find("#oddsUp").mouseout(function(g){clearInterval(d);clearTimeout(b);b=d=null});a.find("#oddsDown").mouseup(function(g){clearInterval(c);clearTimeout(e);
e=c=null});a.find("#oddsDown").mouseout(function(g){clearInterval(c);clearTimeout(e);e=c=null});a.find("#odds").change(function(){var g=BetHandler.updateKeyupOdds(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this);BetHandler.eventCalculate(a,g);BetHandler.getDynamicMinBet(a)});a.find("#odds").blur(function(){f&&(clearInterval(f),f=null);h&&(clearTimeout(h),h=null);BetHandler.blurCheckOddsValidate(this,null,a.attr("eventId"),a.attr("marketId").replace("_","."));var g=
BetHandler.updateKeyupOdds(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this);BetHandler.eventCalculate(a,g);BetHandler.getDynamicMinBet(a)});a.find("#odds").keyup(function(g){var k=$j(this);TxnHandler.validComma(k);outOfScale(k.val(),2)&&k.val(MathUtil.floorp(k.val(),2));k=BetHandler.updateKeyupOdds(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this);BetHandler.eventCalculate(a,k);BetHandler.getDynamicMinBet(a);g=g.which;KeyEventUtils.isEnterKey(g)&&
$j("#placeBets").click();KeyEventUtils.isTabKey(g)&&a.find("#odds").is(":focus")&&a.find("#odds").select();if(KeyEventUtils.isUpArrowKey(g)||KeyEventUtils.isDownArrowKey(g))f&&(clearInterval(f),f=null),h&&(clearTimeout(h),h=null),k=BetHandler.clickUpDownArrowKey(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),g,a),BetHandler.eventCalculate(a,k),BetHandler.getDynamicMinBet(a),a.find("#odds").select(),KeyEventUtils.isUpArrowKey(g)&&1E3<a.find("#odds").val()&&(a.find("#odds").val(1E3),
BetHandler.fadeInMsg("#errorMsg",I18N.get("msg.member.editBet.maximumOdds")))});a.find("#odds").click(function(){a.find("#odds").select()});a.find("#inputStake").click(function(){a.find("#inputStake").select()});a.find("#inputStake").change(function(){var g=BetHandler.isAllowNonIntegerStake(PageConfig.playerCurrency)?a.find("#inputStake").val():parseInt(a.find("#inputStake").val());isNaN(g)&&(g=0);g=DataBase.bet.updateStake(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),
g);BetHandler.eventCalculate(a,g)});a.find("#inputStake").blur(function(){CoinHandler.hideStakePopupList();var g=BetHandler.isAllowNonIntegerStake(PageConfig.playerCurrency),k=g?a.find("#inputStake").val():parseInt(a.find("#inputStake").val());isNaN(k)&&(g?(g=BetHandler.getMinBet(a.attr("eventId"),a.attr("marketId"),a.attr("eventType"),parseFloat(a.find("#odds").val())),$j(this).val(g),k=g):k=0);k=BetHandler.blurCheckStakeValid($j(this),PageConfig.webSiteType,PageConfig.playerCurrency,k,null,a.attr("eventId"),
a.attr("marketId"),a.attr("selectionId"),a.attr("sideType"),a.attr("eventType"),parseFloat(a.find("#odds").val())||0);g=DataBase.bet.updateStake(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),k);BetHandler.eventCalculate(a,g)});a.find("#inputStake").keydown(function(g){var k=BetHandler.isAllowNonIntegerStake(PageConfig.playerCurrency),l=g.which;KeyEventUtils.isNumberKey(g)||KeyEventUtils.isBackspaceKey(l)||KeyEventUtils.isDeleteKey(l)||KeyEventUtils.isArrowKey(l)||
KeyEventUtils.isTabKey(l)||KeyEventUtils.isEnterKey(l)||k&&KeyEventUtils.isDecimalPointKey(l)||WindowEventUtil.stopEvent(g)});a.find("#inputStake").keyup(function(g){var k=$j(this),l=k.parent().parent(),p=BetHandler.isAllowNonIntegerStake(PageConfig.playerCurrency);p?(TxnHandler.validComma(k),outOfScale(k.val(),1)&&k.val(MathUtil.floorp(k.val(),1))):$j(this).val(function(x,t){return commaSeparateNumber(t)});k=p?l.find("#inputStake").val():parseInt(l.find("#inputStake").val());isNaN(k)&&(k=0);k=DataBase.bet.updateStake(a.attr("eventId"),
a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),k);BetHandler.eventCalculate(a,k);g=g.which;KeyEventUtils.isEnterKey(g)&&$j("#placeBets").click();KeyEventUtils.isTabKey(g)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()})}function v(a){if(0==PageConfig.enableForecastWithCommission||0>=a)return a;let d=MathUtil.decimal.subtract(1,PageConfig.taxRatio);return MathUtil.decimal.multiply(a,d)}function C(a,d,b,c){0==b.length&&(a.find("#withoutBet").hide(),a.find("#lossWithoutBet").hide());
0==d.length&&(a.find("#withBet").hide(),a.find("#lossWithBet").hide());0==b.length&&0==d.length&&(a.find("th").removeClass("predict"),d=EventType.getInstanceOf(c.eventType),null!=d&&d.isRacingEvent()&&a.removeClass("predict"))}function G(a,d,b){0!=a.length&&(0==b.length&&(a.find("#withoutBet").hide(),a.find("#lossWithoutBet").hide()),0==d.length&&(a.find("#withBet").hide(),a.find("#lossWithBet").hide()),0==b.length&&0==d.length&&a.removeClass("predict"))}function A(a,d,b,c,e,f){if(null!=f&&MarketUtil.isLineMarket(f.marketType,
f.bettingType)||null!=f&&MarketUtil.isAsiaHandicapMarket(f)&&f.eventType==EventType.SOCCER.value)return a;f=JsCache.get("#betMsg");null!=e&&(f=e);if(2<=a){e=MathUtil.decimal.subtract(a,d);if(100>a){e=MathUtil.decimal.multiply(e,100);var h=MathUtil.decimal.multiply(c,100);if(0==e%h)return f.hide(),a;f.html(I18N.get("msg.member.odds.increments",[d,b,c]));f.show();return MathUtil.decimal.add(d,MathUtil.decimal.multiply(c,Math.floor(e/h)))}if(0==e%c)return f.hide(),a;f.html(I18N.get("msg.member.odds.increments",
[d,b,c]));f.show();return MathUtil.decimal.add(d,MathUtil.decimal.multiply(c,Math.floor(e/c)))}f.hide();return a}function J(){var a=JsCache.get("#betList").find("dl"),d=[];$j.each(a,function(c,e){c=$j(e);e=c.parent();var f=parseInt(e.attr("count"));if(c.hasClass("sum")||c.is(":hidden"))return!0;BetHandler.removeSelectClass(c.attr("eventId"),c.attr("marketId"),c.attr("selectionKey"),c.attr("sideType"));DataBase.bet.remove(c.attr("eventId"),c.attr("marketId"),c.attr("selectionKey"),c.attr("sideType"));
c.remove();var h=c.attr("eventId")+"_"+c.attr("marketId").replace("_",".");-1==ArrayUtil.indexOf(d,h)&&d.push(h);e.attr("count",--f);0==f&&e.remove();BetHandler.hideStakeTipsPopup(c);BetHandler.hideOddsTips(c)});if(0<d.length)for(a=0;a<d.length;a++){var b=d[a].split("_");BetHandler.getWinLoss(b[0],b[1])}BetHandler.addToCookie();D();JsCache.get("#betMsg").hide();BetHandler.oddsAndStakeCheck()}function D(){var a=JsCache.get("#betList"),d=a.find("[id^=header_]"),b=0;$j.each(d,function(c,e){0!=$j(e).find("[id^=bet_]").length&&
b++});0==b?(JsCache.get("#betSlipBoard").hide(),JsCache.get("#noBetSlipInfo").show()):(JsCache.get("#betSlipBoard").show(),JsCache.get("#noBetSlipInfo").hide());0==a.find('dl[sideType="1"]').length&&a.find("#backSlipHeader").hide();0==a.find('dl[sideType="2"]').length&&a.find("#laySlipHeader").hide()}function H(a){var d=[];if(MultiMarketsHandler.isViewMultiMarket()||1==PageConfig.isPoliticsPage)a.forEach(function(c){d.push($j("[id^=multiMarket_"+c.eventId+"_"+c.marketId.replace(".","_")+"]"))});else if(-1==
PageConfig.selectEventId)a.forEach(function(c){"#InPlay"==location.hash?d.push($j("#event_"+c.eventId)):(d.push($j("#highLightEvent_"+c.eventId)),d.push($j("#"+EventHighlightUtil.getEventPinHighlightId(c.eventId))))});else{var b=$j("#fullMarketBetsWrap:visible");a.forEach(function(c){c.eventId==b.attr("eventid")&&c.marketId==b.attr("marketid")&&d.push(b);0<$j("#popMarketItem_"+c.marketId.replace(".","_")).length&&d.push($j("#popMarketItem_"+c.marketId.replace(".","_")))})}return d}function E(a,d){0<
a.length&&a.forEach(function(b){d?(b.addClass("disabled"),b.addClass("cooldown")):(b.removeClass("cooldown"),b.removeClass("disabled"))})}BetHandler.showSelectionIds=[];BetHandler.isOnBetting=!1;var z=0,B=!1,F=!1;BetHandler.lastBetTime=0;BetHandler.oddsMinBetMap={};BetHandler.ONLY_OFFER_DABBA_EVENT_TYPE=[];var u;BetHandler.init=function(){BetHandler.initCookieBetSlip();BetHandler.checkConfirmBetFromCookie();BetHandler.oddsMinBetMap=JSON.parse(PageConfig.oddsMinBetMap);null!=PageConfig.ONLY_OFFER_DABBA_EVENT_TYPE&&
0<PageConfig.ONLY_OFFER_DABBA_EVENT_TYPE.length&&(BetHandler.ONLY_OFFER_DABBA_EVENT_TYPE=JSON.parse(PageConfig.ONLY_OFFER_DABBA_EVENT_TYPE));var a=WebSiteType.getInstanceOf(PageConfig.webSiteType);u={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};a.isFancyFairGroup()&&(u.precision=0,u.roundingMode="DOWN");JsCache.get("#placeBets").click(function(){("undefined"==typeof LoginHandler||
LoginHandler.userIsLogin())&&1==z&&BetHandler.confirmBets(this)});JsCache.get("#placeBets").keydown(function(d){("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())&&KeyEventUtils.isEnterKey(d.which)&&JsCache.get("#placeBets").click()});JsCache.get("[id^='comfirmBets']").change(function(){0==z?(z=1,BetHandler.oddsAndStakeCheck(),JsCache.get("#placeBets").unbind("click").click(function(){("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())&&BetHandler.confirmBets(this)}),JsCache.get("[id^='comfirmBets']").attr("checked",
!0)):(z=0,BetHandler.oddsAndStakeCheck(),JsCache.get("[id^='comfirmBets']").attr("checked",!1));BetHandler.addConfirmBetToCookie()});JsCache.get("#editBets").click(function(){BetHandler.editBets(this)});JsCache.get("#cancelAll").mousedown(function(){BetHandler.clickCancelAll(this)});JsCache.get("#cancelAll").keydown(function(d){KeyEventUtils.isEnterKey(d.which)&&JsCache.get("#cancelAll").click()});JsCache.get("#betList").scroll(function(){PageConfig.ENABLE_CUSTOMIZE_STAKE||CoinHandler.hideStakePopupList();
for(var d=$j("[id^=bet_]"),b=0;b<d.length;b++){var c=$j(d[b]);BetHandler.hideStakeTipsPopup(c);BetHandler.hideOddsTips(c)}});B=!0;if(BrowserUtil.isIE()||BrowserUtil.isEdge())F=!0};BetHandler.initJob=function(){BetHandler.getPlayerInfoTask.run();PageConfig.enableBetSlipTimeout&&BetHandler.checkBetSlipValidTask.run()};BetHandler.checkBetSlipValidTask=TaskExecuter.createTask(3,0,function(){BetHandler.checkBetSlipValid(this)});BetHandler.checkBetSlipValid=function(a){try{var d=BetHandler.readCookie();
null!=d&&$j.each(d,function(b,c){if(15==c.length){b=c[0];var e=c[1],f=c[2],h=c[3],g=c[4],k=c[5],l=c[6],p=c[7],x=c[10],t=c[12];c=c[13];b&&e&&f&&h&&g&&k&&l&&p&&t&&c&&(k.replace("_","."),1==DateUtil.compare(new Date,x+1E3*PageConfig.playerBetSlipTimeout)&&(c="bet_"+DataBase.bet.generateKey(h,k,t,b),c=$j("#"+c),BetHandler.deleteBet(c),BetHandler.getWinLoss(c.attr("eventId"),c.attr("marketId"))))}})}catch(b){Trace.printStackTrace(b)}finally{a.check(),TaskExecuter.execute()}};BetHandler.getPlayerInfoTask=
TaskExecuter.createTask(5,0,function(){BetHandler.getPlayerInfo(this)});BetHandler.getPlayerInfo=function(a){$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+"/exchange/member/playerService/queryPlayerInfo",data:{queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(d){try{if(null!=d){if(B&&(0<d.accountSuspended||0<d.accountSysSuspended)){var b=!1,c=DataBase.unMatchTicket.queryAll();
$j.each(c,function(e,f){if(UnMatchTicketUtil.isActive(f.status))return b=!0,!1});if(b){NoticeHandler.error(I18N.get("msg.member.suspendedAndCancelUnMatch"));B=!1;return}NoticeHandler.error(I18N.get("msg.member.suspended"));B=!1}if(0==d.accountSuspended||0==d.accountSysSuspended)B=!0}}catch(e){Trace.printStackTrace(e)}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=
null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})};BetHandler.changeBetListHeight=function(){r(169,131)};BetHandler.initBetListHeight=function(){r(189,86)};BetHandler.fadeInMsg=function(a,d){JsCache.get(a).html(d).fadeIn();BetHandler.changeBetListHeight();setTimeout(function(){JsCache.get(a).fadeOut();BetHandler.initBetListHeight()},3E3)};BetHandler.showMsg=function(a,d){JsCache.get(a).html(d).show();BetHandler.changeBetListHeight()};BetHandler.hideMsg=function(a){JsCache.get(a).hide();
BetHandler.initBetListHeight()};BetHandler.checkBetTime=function(){var a=(new Date).getTime();return a&&3E3<a-BetHandler.lastBetTime?(BetHandler.lastBetTime=a,!0):!1};BetHandler.submitBet=function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())if(TxnHandler.clickResetBtn(),BetHandler.checkBetTime()){w();var a=DataBase.bet.queryForBets();if(0!=a.length&&a){var d=n(a);if(0!=d.length&&d){PageConfig.ENABLE_LINE_MARKET&&LineMarketHandler.reverseSideType(d);var b=0,c="",e=$j("#betSlipBoard").find("#placeBets"),
f=H(d);$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/exchange",data:{bets:JSON.stringify(d)},beforeSend:function(){(1<d.length||CountDownUtils.isShowCountDown)&&JsCache.get("#loadingMsg").show();JsCache.get("#betSlipBoard").hide();CountDownUtils.isShowCountDown&&CountDownUtils.startCountDown(JsCache.get("#countDownTime"));BetHandler.isOnBetting=!0;e.attr("disable",!0);e.addClass("disable");E(f,!0)},complete:function(){JsCache.get("#loadingMsg").hide();e.attr("disable",!1);
e.removeClass("disable");E(f,!1)},success:function(h){try{if(h.error)BetHandler.showMsg("#errorMsg",h.error),D(),JsCache.get("#placeBets").unbind("click"),q();else if(0!=h.result.length){JsCache.get("#loadingMsg").hide();BetHandler.isOnBetting=!1;var g=[],k;for(k in h.result){var l=h.result[k];if("SUCCESS"==l.status){var p=JsCache.get("#betList").find("[eventId="+l.eventId+'][marketid="'+l.marketId.replace(".","_")+'"][selectionid='+l.selectionId+"][sidetype="+l.sideType+'][handicap="'+l.handicap+
'"]');BetHandler.deleteBet(p);0==b&&""==c&&(b=l.eventId,c=l.marketId);null!=l.unMatchTicket&&DataBase.unMatchTicket.update([l.unMatchTicket]);null!=l.txn&&DataBase.txn.update([l.txn]);var x=l.eventId+"_"+l.marketId;-1==ArrayUtil.indexOf(g,x)&&g.push(x)}else l.error&&(BetHandler.showMsg("#errorMsg",l.error),D(),JsCache.get("#placeBets").unbind("click"),q())}0!=b&&""!=c&&(TxnHandler.setEventIdAndMarketId(b,c,CategoryType.BETFAIR.unique()),b=0,c="");if(0<g.length)for(h=0;h<g.length;h++)x=g[h].split("_"),
BetHandler.getWinLoss(x[0],x[1]);setTimeout(function(){TxnHandler.getUnMatchTicketsAndTxns()},250);TxnHandler.updateOpenBetSelectionBox();TxnHandler.addBlankSelectOption(PageConfig.selectEventId,PageConfig.selectMarketId);TxnHandler.checkToHideOpenBets();var t=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(t,u))}}catch(I){Trace.printStackTrace(I)}finally{CountDownUtils.isShowCountDown=!1,JsCache.get("#countDownTime").html(I18N.get("form.button.placeBets")),
E(f,!1)}},error:function(h){Trace.printStackTrace(h)}});BetHandler.addToCookie();JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()}}}};BetHandler.clearConfirmBets=()=>{JsCache.get("#betSlipBoard").show();JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide();$j("[id^='confirmBet_']").remove();$j("[id^='confirmHeader_']").remove()};BetHandler.confirmBets=function(a){a=DataBase.bet.queryAll();0!=a.length&&(a=n(a),0!=a.length&&a&&(DataBase.bet.calculatePL(),
BetHandler.clearConfirmBets(),$j.each(a,function(d,b){if(!(b.sideType&&b.eventId&&b.marketId&&b.selectionId&&b.stake&&b.odds&&b.profit&&b.liability&&b.selectionKey&&b.handicap))return!0;JsCache.get("#betSlipBoard").hide();JsCache.get("#confirmBetList").show();JsCache.get("#confirmBetFullBtn").show();var c=b.eventId;d=SideType.getInstanceOf(b.sideType);var e="--",f="--",h=b.marketId.replace("_","."),g=DataBase.events.get(b.eventType,b.eventId);if(null!=g&&0<g.markets.length){for(var k=null,l=null,
p=0;p<g.markets.length;p++)if(g.markets[p].marketId==h){k=g.markets[p];break}if(null!=k){e=k.marketName;for(p=0;p<k.selections.length;p++)if(k.selections[p].selectionKey==b.selectionKey){l=k.selections[p];break}null!=l&&(f=l.runnerName)}}k=JsCache.get("#confirmBetList");h=SideType.Back.unique()==d.value?k.find("#backSlipHeader").show():k.find("#laySlipHeader").show();g=JsCache.get("#confirmHeader_"+d.name+"_"+c);l=b.eventName;if(null==g||void 0==g)g=JsCache.clone("#confirmHeader"),g.attr("id","confirmHeader_"+
d.name+"_"+c).attr("count",0),g.find("h4").html(l),k.prepend(g.show());c=JsCache.clone("#confirmBetTemplate");c.attr("id","confirmBet_"+DataBase.bet.generateKey(b.eventId,b.marketId,b.selectionKey,b.sideType)).attr("eventId",b.eventId).attr("marketId",b.marketId).attr("selectionId",b.selectionId).attr("selectionKey",b.selectionKey).attr("class","slip-"+d.name.toLowerCase()).attr("sideType",d.value);c.attr("class","slip-"+d.name.toLowerCase()).find("#slipType").html(StringUtil.ucfirst(d.name));c.find("#selectionName").html(f);
c.find("#marketName").html(e);c.find("#price").html(b.odds);c.find("#size").html(CurrencyUtil.formatter(Number(b.stake),u));SideType.Back.unique()==d.value?c.find("#profitLiability").html(CurrencyUtil.formatter(b.profit,u)):c.find("#profitLiability").html(CurrencyUtil.formatter(b.liability,u));h.after(g.append(c.show()))}),$j("#submitBets").unbind("click").click(function(){BetHandler.submitBet()}),$j(document).unbind("keydown").keydown(function(d){KeyEventUtils.isEnterKey(d.which)&&(0<$j("#confirmBetList:visible").length?
($j("#submitBets").click(),$j(document).unbind("keydown")):$j("#placeBets").click())}),checkIsNoElement(JsCache.get("#confirmBetList"))))};BetHandler.editBets=function(a){$j("#submitBets").unbind("click");JsCache.get("#betSlipBoard").show();JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()};BetHandler.appendBetObj=(a,d)=>{let b;if("--"!=a.html().replace(/&nbsp;/g,"")){b=parseFloat(a.html());1==d&&(b=parseFloat(a.attr("fullMarketOdds")));isNaN(b)&&(b=1.01);var c=SideType.getInstanceByName(a.attr("side")),
e=a.parent().parent();1==d&&(e=a.parent());d=e.attr("eventType");var f=e.attr("eventId"),h=e.attr("marketId").replace(".","_"),g=parseInt(a.attr("selectionId")),k=a.attr("selectionKey"),l=a.attr("runner"),p=e.attr("eventName"),x=a.attr("marketName"),t=a.attr("inPlay"),I=a.attr("marketType");a=a.attr("handicap");var M=e.attr("sortpriority");e=e.attr("boardType");var K=JsCache.get("#betList").find("[eventId="+f+'][marketid="'+h+'"][selectionKey='+k+"][sidetype="+c.value+"]"),N=K.attr("boardType"),L=
null;0==K.length?L=DataBase.bet.add(c.value,b,d,f,l,h,g,p,x,t,I,k,a,M,e):(BetHandler.deleteBet(K),e!=N&&(L=DataBase.bet.add(c.value,b,d,f,l,h,g,p,x,t,I,k,a,M,e)));return L}};BetHandler.clickBtn=(a,d)=>{if(!JsCache.get("#loadingMsg").is(":visible")){BetHandler.clearConfirmBets();var b=$j(a),c=b.parent().parent();1==d&&(c=b.parent());var e=c.attr("eventType");a=c.attr("eventId");var f=c.attr("marketId").replace(".","_"),h=parseInt(b.attr("selectionId")),g=b.attr("selectionKey"),k=SideType.getInstanceByName(b.attr("side")),
l=DataBase.markets.get(a,f.replace("_","."));null!=l&&(null!=l.disableBettingSite&&WebSiteUtil.isDisableBettingSite(l.disableBettingSite,PageConfig.webSiteType)||null!=l.autoDisableBettingSite&&WebSiteUtil.isDisableBettingSite(l.autoDisableBettingSite,PageConfig.webSiteType))||(l=DataBase.markets.getSelection(a,f.replace("_","."),g),null==l||null!=l&&1==l.isAutoSuspend||BetHandler.isEnableCheckLowLiquidity()&&BetHandler.isLowLiquidity(e,a,f.replace("_","."),!0)||("true"==PageConfig.ENABLE_ONE_CLICK_BET&&
OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&(PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE||d)?OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeBet(b,c,a,f,h,g,k.unique(),d):(d=BetHandler.appendBetObj(b,d),0!=PageConfig.userCoin&&DataBase.bet.updateStake(a,f,g,k.unique(),parseFloat(PageConfig.userCoin)),BetHandler.getWinLoss(a,f),null!=d&&(MarketHandler.checkMarkets(d.eventType,d.eventId,d.marketId),BetHandler.addBets(d),BetHandler.addToCookie(),0!=PageConfig.userCoin&&
(BetHandler.calculateProfitAndLiability(),d=BetHandler.calculateTotalLiability(),JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(d,u)))))))}};BetHandler.isEnableCheckLowLiquidity=function(){return"true"==PageConfig.isEnableLowLiquidity&&!PageConfig.isPoliticsPage};BetHandler.isLowLiquidity=function(a,d,b,c){b=DataBase.markets.get(d,b);if(null==b)return!1;var e=b.marketType;d=b.totalMatchedInUSD;if(null==d)return!1;if(-1==d)return c?!0:!1;if(null!=b.isLowLiquidity)return b.isLowLiquidity;
"true"==PageConfig.ENABLE_MARKET_LIQUIDITY_CACHE?(c="MATCH_ODDS"==e||"WIN"==e?"_MATCH_ODDS":"_OTHERS",a=JSON.parse(PageConfig.marketLiquiditys)[a+c]):a="MATCH_ODDS"==e||"WIN"==e?PageConfig.LOW_LIQUIDITY_FOR_MATCH_ODDS:PageConfig.LOW_LIQUIDITY_FOR_OTHERS;return 0==a?!1:d<a?!0:!1};BetHandler.appendMaxHeightForIE=function(a){var d=86;a&&(d=106);a=BrowserUtil.getBrowserName();if("Mozilla"==a||"Explorer"==a||"Edge"==a)a=$j("#betSlipBoard").height(),JsCache.get("#betList").css("max-height",a-d+"px")};BetHandler.betAll=
function(a,d,b,c,e){if(!BetHandler.isEnableCheckLowLiquidity()||!BetHandler.isLowLiquidity(b,c,e.replace("_",".")))if(b=DataBase.markets.get(c,e),!(null!=b&&null!=b.disableBettingSite&&WebSiteUtil.isDisableBettingSite(b.disableBettingSite,PageConfig.webSiteType)||null!=b.autoDisableBettingSite&&WebSiteUtil.isDisableBettingSite(b.autoDisableBettingSite,PageConfig.webSiteType)||"true"==PageConfig.ENABLE_ONE_CLICK_BET&&1==PageConfig.isOneClickBet||JsCache.get("#loadingMsg").is(":visible"))){b=[];for(var f=
0;f<a.length;f++){var h=$j(a[f]);if(!h.hasClass("sum")&&!h.is(":hidden")&&null!=h.html()){var g=h.attr("selectionKey");g=DataBase.markets.getSelection(c,e.replace("_","."),g);if(null==g||1!=g.isAutoSuspend)h=BetHandler.appendBetObj(h,d),null!=h&&(0!=PageConfig.userCoin&&DataBase.bet.updateStake(h.eventId,h.marketId,h.selectionKey,h.sideType,parseFloat(PageConfig.userCoin)),b.push(h))}}null!=c&&null!=e?BetHandler.getWinLoss(c,e):BetHandler.getWinLoss(PageConfig.selectEventId,PageConfig.selectMarketId);
0!=b.length&&(MarketHandler.checkMarkets(b[0].eventType,b[0].eventId,b[0].marketId),BetHandler.addBetsAll(b),BetHandler.addToCookie(),0!=PageConfig.userCoin&&(BetHandler.calculateProfitAndLiability(),a=BetHandler.calculateTotalLiability(),JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(a,u)),BetHandler.oddsAndStakeCheck()))}};BetHandler.initCookieBetSlip=function(){if(""!=PageConfig.userID){var a=BetHandler.readCookie();null!=a&&$j.each(a,function(d,b){if(15!=b.length)return!0;
var c={sideType:b[0],odds:b[1],eventType:b[2],eventId:b[3],runner:b[4],marketId:b[5],selectionId:b[6],eventName:b[7],marketName:b[8],inPlay:b[9],timestamp:b[10],marketType:b[11],selectionKey:b[12],handicap:b[13],sortpriority:b[14]};if(!(c.sideType&&c.odds&&c.eventType&&c.eventId&&c.runner&&c.marketId&&c.selectionId&&c.eventName&&c.selectionKey&&c.handicap))return!0;d=c.marketId.replace("_",".");$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/querySingleMarket",data:{eventId:c.eventId,
marketId:d},success:function(e){try{e.eventId==c.eventId&&MarketUtil.isOpen(e.status)&&(DataBase.bet.add(c.sideType,c.odds,c.eventType,c.eventId,c.runner,c.marketId,c.selectionId,c.eventName,c.marketName,c.inPlay,c.marketType,c.selectionKey,c.handicap,c.sortpriority),MarketHandler.checkMarkets(c.eventType,c.eventId,c.marketId),BetHandler.addBets(c)),BetHandler.addToCookie()}catch(f){Trace.printStackTrace(f)}finally{}},error:function(e){Trace.printStackTrace(e)}})})}};BetHandler.addToCookie=function(){var a=
DataBase.bet.queryForCookie();null!=a&&(a.length>parseInt(PageConfig.MAX_BET_RECORDS_IN_COOKIE)||CookieUtil.setCookie("betSlips_"+PageConfig.userID,JSON.stringify(a),999))};BetHandler.readCookie=function(){var a=CookieUtil.getCookie("betSlips_"+PageConfig.userID);return JSON.parse(a)};BetHandler.checkConfirmBetFromCookie=function(){1==CookieUtil.getCookie("confirmBets_"+PageConfig.userID)?(z=1,JsCache.get("[id^='comfirmBets']").prop("checked",!0)):(z=0,JsCache.get("[id^='comfirmBets']").prop("checked",
!1))};BetHandler.addConfirmBetToCookie=function(){CookieUtil.setCookie("confirmBets_"+PageConfig.userID,z,999)};BetHandler.appendBetTemplate=function(a){var d=a.eventId,b=SideType.getInstanceOf(a.sideType);JsCache.get("#noBetSlipInfo").hide();JsCache.get("#betSlipBoard").show();var c='<img class="icon-no_play" src="/images/transparent.gif" />';null!=a.inPlay&&1==a.inPlay&&(c='<img class="icon-in_play" src="/images/transparent.gif" />');var e=JsCache.get("#betList"),f=JsCache.get("#betSlipBoard");
f=SideType.Back.unique()==b.value?f.find("#backSlipHeader").show():f.find("#laySlipHeader").show();let h=JsCache.get("#header_"+b.name+"_"+d);var g=a.eventName,k=a.marketName;if(null==h||void 0==h)h=JsCache.clone("#headerTemplate"),h.attr("id","header_"+b.name+"_"+d).attr("count",0),h.find("h4").html(c+" "+g),e.prepend(h.show());d=parseInt(h.attr("count"));c=JsCache.clone("#betTemplate");c.attr("id","bet_"+DataBase.bet.generateKey(a.eventId,a.marketId,a.selectionKey,a.sideType)).attr("eventType",
a.eventType).attr("eventId",a.eventId).attr("marketId",a.marketId).attr("selectionId",a.selectionId).attr("selectionKey",a.selectionKey).attr("class","slip-"+b.name.toLowerCase()).attr("sideType",b.value).attr("marketType",a.marketType).attr("handicap",a.handicap).attr("boardType",a.boardType);null!=a.stake&&0!=a.stake&&c.find("#inputStake").val(a.stake);c.find("#odds").val(a.odds);c.find("#marketName").html(k);c.find("#delete").after('<span class="short-amount">'+a.runner+"</span>");c.find("#profitLiability").html(CurrencyUtil.formatter(0,
u));"INNINGS_RUNS"==a.marketType?(e=DataBase.markets.get(a.eventId,a.marketId.replace("_",".")),b=c.find("#inningsRuns"),PageConfig.ENABLE_LINE_MARKET&&null!=e&&MarketUtil.isLineMarket(e.marketType,e.bettingType)?(b.find("#ifRuns").html("If "+k+"<"+a.odds),b.find("#ifLess").html("If "+k+">"+a.odds)):(k=a.runner.toLowerCase(),b.find("#ifRuns").html("If "+k),b.find("#ifLess").html("If less than "+k.replace("or more",""))),b.find("#runsPL").html(CurrencyUtil.formatter(0,u)),b.find("#lessPL").html(CurrencyUtil.formatter(0,
u)),b.show()):c.find("#inningsRuns").hide();if("ASIAN_HANDICAP"==a.marketType&&PageConfig.ENABLE_ASIANHANDICAP_FORECAST_DESC){{k=a.eventName;b=" v ";0<k.indexOf(" vs ")?b=" vs ":0<k.indexOf(" @ ")&&(b=" @ ");k=k.split(b);e=b="";1<k.length&&(b=k[0],e=k[1]);k=(g=0!=a.sortpriority%2?!0:!1)?b:e;let l=g?e:b;g=e=b="";a=AsianHandicapForecastDescType.getInstanceOf(a.handicap);null!=a&&(b=a.desc1?a.desc1.replace("homeAway",k).replace("anotherTeam",l):"",e=a.desc2?a.desc2.replace("homeAway",k).replace("anotherTeam",
l):"",g=a.desc3?a.desc3.replace("homeAway",k).replace("anotherTeam",l):"");a=c.find("#asianHandicapForecast");a.find("#forecastDesc_1").html(b);a.find("#forecastDesc_2").html(e);a.find("#forecastDesc_3").html(g);a.show()}}f.after(h.append(c.show()).attr("count",++d));c.find("#odds").select();c.find("#odds").attr("tabindex",0);c.find("#inputStake").attr("tabindex",0);JsCache.get("#placeBets").addClass("disable");JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(0,u));return c};
BetHandler.addBets=a=>{a=BetHandler.appendBetTemplate(a);y(a);BetHandler.getDynamicMinBet(a);let d=$j("#betList");CoinHandler.buildStakePopupList(a);CoinHandler.clickStakePopupList(a,d,!1);BetHandler.addSelectClass();BetHandler.oddsAndStakeCheck(a)};BetHandler.addBetsAll=function(a){var d=[],b;for(b in a){var c=BetHandler.appendBetTemplate(a[b]);d.push(c)}BetHandler.addSelectClass();a=$j("#betList");for(var e in d)c=d[e],y(c),BetHandler.getDynamicMinBet(c),CoinHandler.buildStakePopupList(c),CoinHandler.clickStakePopupList(c,
a,!1);d[0].find("#odds").select()};BetHandler.addSelectClass=()=>{(new Date).getTime();let a=0==$j("[id^=popMarketItem_]").length?!1:!0,d=DataBase.bet.queryAll(),b=$j("#overWrap");if("true"==PageConfig.ENABLE_QUICK_BET){let c=DataBase.quickBet.queryAll();for(let e in c)d.push(c[e])}$j.each(d,function(c,e){c=e.eventId;let f=e.marketId,h=e.selectionKey,g=SideType.getInstanceOf(e.sideType);e=e.boardType;1==MultiMarketsHandler.isViewMultiMarket()?(c=$j("#multiMarketsWrap").find("#multiMarket_"+c+"_"+
f.replace(".","_")).find("#fullSelection_"+h).find("#"+g.name.toLowerCase()+"_1"),0!=c.length&&c.addClass("select")):(null==PageConfig.selectMarketId&&(e=("pinHighlight"==e?$j("#eventPinHighlightBoard").find("#"+EventHighlightUtil.getEventPinHighlightId(c)):$j("#eventBoard").find("#highLightEvent_"+c)).find("[selectionKey="+h+"][side="+g.name+"]"),0!=e.length&&e.addClass("select"),e=$j("#event_"+c).find("[selectionKey="+h+"][side="+g.name+"]"),0!=e.length&&e.addClass("select")),null!=PageConfig.selectMarketId&&
(e=$j("#fullMarketBoard").find("#fullSelection_"+h).find("#"+g.name.toLowerCase()+"_1"),0!=e.length&&e.addClass("select"),1==a&&(e=b.find("#popMarketItem_"+f.replace(".","_")).find("#selection_"+h).find("[side="+g.name+"]"),0!=e.length&&e.addClass("select")),PageConfig.ENABLE_LINE_MARKET&&(e=b.find("#lineMarketWrap").find("[eventId="+c+"][marketId="+f+"][selectionKey="+h+"]").find("#"+g.name.toLowerCase()+"_1"),0<e.length&&e.addClass("select"))),1==PageConfig.isPoliticsPage&&(c=$j("#overWrap").find("[eventId="+
c+"][marketId="+f+"][selectionKey="+h+"]").find("#"+g.name.toLowerCase()+"_1"),0!=c.length&&c.addClass("select")))})};BetHandler.removeSelectClass=function(a,d,b,c){c=SideType.getInstanceOf(c);let e=$j("#overWrap");if(1==MultiMarketsHandler.isViewMultiMarket())a=$j("#multiMarketsWrap").find("#multiMarket_"+a+"_"+d.replace(".","_")).find("#fullSelection_"+b).find("#"+c.name.toLowerCase()+"_1"),0!=a.length&&a.removeClass("select");else{if(null==PageConfig.selectMarketId){var f=$j("#eventPinHighlightBoard").find("#"+
EventHighlightUtil.getEventPinHighlightId(a)).find("[selectionKey="+b+"][side="+c.name+"]");0!=f.length&&f.removeClass("select");f=$j("#eventBoard").find("#highLightEvent_"+a).find("[selectionKey="+b+"][side="+c.name+"]");0!=f.length&&f.removeClass("select");f=$j("#event_"+a).find("[selectionKey="+b+"][side="+c.name+"]");0!=f.length&&f.removeClass("select")}null!=PageConfig.selectMarketId&&(f=$j("#fullMarketBoard").find("#fullSelection_"+b).find("#"+c.name.toLowerCase()+"_1"),0!=f.length&&f.removeClass("select"),
f=e.find("#popMarketItem_"+d.replace(".","_")).find("#selection_"+b).find("[side="+c.name+"]"),0!=f.length&&f.removeClass("select"),PageConfig.ENABLE_LINE_MARKET&&(f=e.find("#lineMarketWrap").find("[eventId="+a+"][marketId="+d+"][selectionKey="+b+"]").find("#"+c.name.toLowerCase()+"_1"),0<f.length&&f.removeClass("select")));1==PageConfig.isPoliticsPage&&(a=e.find("[eventId="+a+"][marketId="+d+"][selectionKey="+b+"]").find("#"+c.name.toLowerCase()+"_1"),0!=a.length&&a.removeClass("select"))}};BetHandler.oddsAndStakeCheck=
function(a){JsCache.get("#placeBets").unbind("click");q();var d=DataBase.bet.queryAll(),b=!1,c=!0;$j.each(d,function(e,f){if(!f.odds||!f.stake)return q(),b=!0;if(1==BetHandler.backOddsIsLessThanLayOdds(f.eventId,f.marketId,f.selectionKey,f.sideType))return BetHandler.showMsg("#errorMsg",I18N.get("msg.member.odds.backOddsIsLessThanLayOdds",[f.eventName,f.marketName,f.runner])),q(),b=!0,1==c&&(c=!1),!0;if(1==BetHandler.isLessThanMinOdds(f.odds))return q(),BetHandler.showMsg("#errorMsg",I18N.get("msg.member.odds.minOdds")),
b=!0,1==c&&(c=!1),!0;e=BetHandler.getMinBet(f.eventId,f.marketId,f.eventType,f.odds);if(f.stake<e)return BetHandler.showMsg("#errorMsg",I18N.get("msg.member.minBet")),q(),b=!0,1==c&&(c=!1),!0});1==c&&BetHandler.hideMsg("#errorMsg");if(null!=a){if(1==BetHandler.isLessThanMinStake(a,JsCache.get("#betList"))){q();return}if(1==BetHandler.isLessThanMinOdds(a.find("#odds").val())){q();BetHandler.showOddsTips(a,JsCache.get("#betList"));return}if(1E3<a.find("#odds").val()){a.find("#odds").val(1E3);BetHandler.fadeInMsg("#errorMsg",
I18N.get("msg.member.editBet.maximumOdds"));return}BetHandler.hideOddsTips(a)}1!=b&&(m(),0==z?JsCache.get("#placeBets").unbind("click").click(function(){("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())&&BetHandler.submitBet()}):JsCache.get("#placeBets").unbind("click").click(function(){("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())&&BetHandler.confirmBets(this)}))};BetHandler.eventCalculate=function(a,d){BetHandler.calculateProfitAndLiability();var b=BetHandler.calculateTotalLiability();
JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(b,u));BetHandler.oddsAndStakeCheck(a);1==d&&BetHandler.getWinLoss(a.attr("eventId"),a.attr("marketId"))};BetHandler.getDynamicMinBet=function(a){var d=BetHandler.getMinBet(a.attr("eventId"),a.attr("marketId"),a.attr("eventType"),a.find("#odds").val());a.find("#dynamicMinBet").html(d)};BetHandler.calculateProfitAndLiability=function(){DataBase.bet.calculatePL();var a=DataBase.bet.queryAll(),d;for(d in a){var b=a[d],c=JsCache.get("#betList").find("[eventId="+
b.eventId+'][marketid="'+b.marketId.replace(".","_")+'"][selectionKey='+b.selectionKey+"][sidetype="+b.sideType+"]");var e=SideType.Back.unique()==b.sideType?b.profit:b.liability;isNaN(e)&&(e=0);c.find("#profitLiability").html(CurrencyUtil.formatter(e,u));if("INNINGS_RUNS"==b.marketType){var f=c.find("#runsPL"),h=c.find("#lessPL");if(null==f||null==h)break;if(SideType.Back.unique()==b.sideType){var g=b.profit;var k=-1*b.liability}else g=-1*b.liability,k=b.profit;f.html(CurrencyUtil.formatter(g));
h.html(CurrencyUtil.formatter(k));f.removeClass("green").removeClass("red");h.removeClass("green").removeClass("red");0<=g?f.addClass("green"):f.addClass("red");0<=k?h.addClass("green"):h.addClass("red")}if("ASIAN_HANDICAP"==b.marketType&&PageConfig.ENABLE_ASIANHANDICAP_FORECAST_DESC)switch(f=c.find("#asianHandicapForecast"),SideType.Back.unique()==b.sideType?c=-1*Number(b.liability):(e=-1*Number(e),c=Number(b.profit)),f.find("#winLoss_1").html(CurrencyUtil.formatter(e)),b=AsianHandicapForecastDescType.getInstanceOf(b.handicap).voidType,
!0){case "void"==b:e=0;f.find("#winLoss_2").html(CurrencyUtil.formatter(e));f.find("#winLoss_3").html(CurrencyUtil.formatter(c));break;case "none"==b:f.find("#winLoss_2").html(CurrencyUtil.formatter(c));break;case "halfWin"==b:e*=.5;f.find("#winLoss_2").html(CurrencyUtil.formatter(e));f.find("#winLoss_3").html(CurrencyUtil.formatter(c));break;case "halfLose"==b:e=.5*c,f.find("#winLoss_2").html(CurrencyUtil.formatter(e)),f.find("#winLoss_3").html(CurrencyUtil.formatter(c))}}};BetHandler.calculateTotalLiability=
function(){var a=DataBase.bet.queryAll();return BetHandler.calculateExposure(a)};BetHandler.calculateExposure=function(a){var d=0,b=new HashMap,c;for(c in a){var e=a[c],f=e.eventId+"_"+e.marketId.replace("_","."),h=b.get(f);null==h&&(h=[]);h.push(e);b.put(f,h)}a=[];b=b.entrySet();for(c in b){h=b[c];f=h.key.split("_");h=h.value;e=f[0];f=f[1];var g=DataBase.markets.get(e,f);if(null!=g){var k=g.selections,l=parseInt(g.numberOfWinners),p=parseInt(g.numberOfActiveRunners);parseInt(g.numberOfRunners);g=
ExposureUtil.getNotActiveSelectionIdArr(k);h=ExposureUtil.genTicketArray(h,!1);ExposureHandler.initMarketInfo(e,f,k,l,p,g);ExposureHandler.calculateExposure(h);h=ExposureHandler.getMarketExposure();a.push(h)}}for(c in a)h=a[c],d=MathUtil.decimal.add(d,h.marketExposure);return Math.abs(d)};BetHandler.isOneMoreWinnerMarket=function(a){return null==a?!1:1<parseInt(a.numberOfWinners)||"PLACE"==a.marketType||"OTHER_PLACE"==a.marketType};BetHandler.getWinLoss=function(a,d){BetHandler.showSelectionIds=[];
var b=DataBase.markets.get(a,d.replace("_","."));if(null==b)Trace.log("market "+d+" is null");else{var c=parseInt(b.numberOfWinners),e=b.selections,f=0==$j("[id^=popMarketItem_]").length?!1:!0,h=$j("#overWrap");var g=DataBase.markets.get(a,d.replace("_","."));if(null==g)Trace.error("market "+d+" is null"),g=void 0;else{var k=DataBase.bet.getByMarketId(a,d.replace(".","_")),l=DataBase.unMatchTicket.getByMarketId(a,d.replace("_","."),null,CategoryType.BETFAIR.unique()),p=[MyTransactionStatusType.Active.unique()];
p=DataBase.txn.getByMarketId(a,d.replace("_","."),null,p,CategoryType.BETFAIR.unique());g=ExposureUtil.calculateExposure(k,l,p,a,d,g,BetHandler.showSelectionIds,PageConfig.ENABLE_FORECAST_NOT_INCLUDE_UNMATCHED)}if(null!=g)for(var x in e){p=e[x].selectionKey;k=DataBase.bet.getByMarketId(a,d);l=DataBase.txn.getByMarketId(a,d,null,null,CategoryType.BETFAIR.unique());if(BetHandler.isOneMoreWinnerMarket(b)||0==c)k=DataBase.bet.getBySelectionId(a,d,p),l=DataBase.txn.getBySelectionId(a,d,p,CategoryType.BETFAIR.unique());
(0!=c&&!BetHandler.isOneMoreWinnerMarket(b)||-1!=ArrayUtil.indexOf(BetHandler.showSelectionIds,p)||MarketUtil.isAsiaHandicapMarket(b)&&0<k.length)&&BetHandler.appendSelectionWinLoss(g,b,a,d,p,f,h);if(null!=PageConfig.selectMarketId){var t=$j("#fullMarketBetsWrap").find("[id=fullSelection_"+p+"][marketId="+d.replace(".","_")+"]");0!=t.length&&C(t,k,l,b);1==f&&(t=h.find("#popMarketItem_"+d.replace(".","_")).find("#selection_"+p),G(t,k,l))}null==PageConfig.selectMarketId&&(t="[marketId="+d.replace(".",
"_")+"][selectionItem="+p+"]",t=h.find(t),G(t,k,l));1==MultiMarketsHandler.isViewMultiMarket()&&(t=$j("#multiMarketsWrap").find("#multiMarket_"+a+"_"+d.replace(".","_")).find("#fullSelection_"+p),0!=t.length&&C(t,k,l,b));PageConfig.ENABLE_LINE_MARKET&&(t=h.find("#lineMarketWrap").find("[eventId="+a+"][marketId="+d.replace(".","_")+"][selectionKey="+p+"]"),0<t.length&&C(t,k,l,b));1==PageConfig.isPoliticsPage&&(h=$j("#overWrap"),t=h.find("[id=fullSelection_"+p+"][marketId="+d.replace(".","_")+"]"),
0!=t.length&&C(t,k,l,b))}}};BetHandler.appendSelectionWinLoss=function(a,d,b,c,e,f,h){var g=parseInt(d.numberOfWinners),k=DataBase.bet.getBySelectionId(b,c,e),l=DataBase.unMatchTicket.getBySelectionId(b,c,e,CategoryType.BETFAIR.unique()),p=DataBase.txn.getBySelectionId(b,c,e,CategoryType.BETFAIR.unique());if(null!=PageConfig.selectMarketId){var x=$j("#fullMarketBetsWrap").find("[id=fullSelection_"+e+"][marketId="+c.replace(".","_")+"]");0!=x.length&&BetHandler.appendFullSelectionWinLoss(x,a,d,e,g,
k,l,p,u);1==f&&(f="[marketId="+c.replace(".","_")+"][popSelectionItem="+e+"]",BetHandler.appendSelectionItemWinLoss(f,c,e,a,d,k,l,p,u))}null==PageConfig.selectMarketId&&(f="[marketId="+c.replace(".","_")+"][selectionItem="+e+"]",BetHandler.appendSelectionItemWinLoss(f,c,e,a,d,k,l,p,u));1==MultiMarketsHandler.isViewMultiMarket()&&(x=$j("#multiMarketsWrap").find("[id=fullSelection_"+e+"][marketId="+c.replace(".","_")+"]"),BetHandler.appendFullSelectionWinLoss(x,a,d,e,g,k,l,p,u));PageConfig.ENABLE_LINE_MARKET&&
(b=h.find("#lineMarketWrap").find("[eventId="+b+"][marketId="+c.replace(".","_")+"][selectionKey="+e+"]"),0<b.length&&BetHandler.appendFullSelectionWinLoss(b,a,d,e,g,k,l,p,u));1==PageConfig.isPoliticsPage&&(h=$j("#overWrap"),x=h.find("[id=fullSelection_"+e+"][marketId="+c.replace(".","_")+"]"),BetHandler.appendFullSelectionWinLoss(x,a,d,e,g,k,l,p,u))};BetHandler.appendFullSelectionWinLoss=function(a,d,b,c,e,f,h,g,k){a.find("th").addClass("predict");var l=EventType.getInstanceOf(b.eventType);null!=
l&&l.isRacingEvent()&&a.addClass("predict");d=d.get(c);if(BetHandler.isOneMoreWinnerMarket(b)||0==e){if(0<g.length&&(a.find("#withoutBet").attr("class",0<d.withoutBet?"win":"lose"),b=v(d.withoutBet),a.find("#withoutBet").html(CurrencyUtil.formatter(b,k)+","),a.find("#withoutBet").show(),a.find("#lossWithoutBet").attr("class",0<d.lossWithoutBet?"win":"lose"),a.find("#lossWithoutBet").html(CurrencyUtil.formatter(d.lossWithoutBet,k)),a.find("#lossWithoutBet").show()),0<h.length||0<f.length)a.find("#withBet").attr("class",
0<d.withBet?"to-win":"to-lose"),f=v(d.withBet),a.find("#withBet").html(CurrencyUtil.formatter(f,k)+","),a.find("#withBet").show(),a.find("#lossWithBet").attr("class",0<d.lossWithBet?"win":"lose"),a.find("#lossWithBet").html(CurrencyUtil.formatter(d.lossWithBet,k)),a.find("#lossWithBet").show()}else a.find("#withoutBet").attr("class",0<d.withoutBet?"win":"lose"),f=v(d.withoutBet),a.find("#withoutBet").html(CurrencyUtil.formatter(f,k)),a.find("#withoutBet").show(),a.find("#withBet").attr("class",0<
d.withBet?"to-win":"to-lose"),f=v(d.withBet),a.find("#withBet").html(CurrencyUtil.formatter(f,k)),a.find("#withBet").show()};BetHandler.appendSelectionItemWinLoss=function(a,d,b,c,e,f,h,g,k){if(0!=$j(a).length)if(d=parseInt(e.numberOfWinners),a=$j(a),b=c.get(b),a.addClass("predict"),BetHandler.isOneMoreWinnerMarket(e)||0==d){if(0<g.length&&(a.find("#withoutBet").attr("class",0<b.withoutBet?"win":"lose"),e=v(b.withoutBet),a.find("#withoutBet").html(CurrencyUtil.formatter(e,k)+","),a.find("#withoutBet").show(),
a.find("#lossWithoutBet").attr("class",0<b.lossWithoutBet?"win":"lose"),a.find("#lossWithoutBet").html(CurrencyUtil.formatter(b.lossWithoutBet,k)),a.find("#lossWithoutBet").show()),0<h.length||0<f.length)a.find("#withBet").attr("class",0<b.withBet?"to-win":"to-lose"),f=v(b.withBet),a.find("#withBet").html(CurrencyUtil.formatter(f,k)+","),a.find("#withBet").show(),a.find("#lossWithBet").attr("class",0<b.lossWithBet?"win":"lose"),a.find("#lossWithBet").html(CurrencyUtil.formatter(b.lossWithBet,k)),
a.find("#lossWithBet").show()}else a.find("#withoutBet").attr("class",0<b.withoutBet?"win":"lose"),f=v(b.withoutBet),a.find("#withoutBet").html(CurrencyUtil.formatter(f,k)),a.find("#withoutBet").show(),a.find("#withBet").attr("class",0<b.withBet?"to-win":"to-lose"),f=v(b.withBet),a.find("#withBet").html(CurrencyUtil.formatter(f,k)),a.find("#withBet").show()};BetHandler.clickCancelAll=function(a){J();a=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(a,
u));BetHandler.hideMsg("#errorMsg");m()};BetHandler.clickOdds=function(a,d,b,c,e,f){var h=$j(e).attr("id");f=f.find("#odds");e=parseFloat(f.val())||0;var g=0,k=DataBase.markets.get(a,d.replace("_","."));if("oddsUp"==h){h=OddsUtil.getIncrement(e,"increase",k);var l=h.increment;g=MathUtil.decimal.add(e,l);g=A(g,h.lowerBound,h.upperBound,l,null,k);MarketUtil.isLineMarket(k.marketType,k.bettingType)&&(g=MathUtil.decimal.add(e,1));0==e&&(g=1.01);f.val(g)}else if("oddsDown"==h){h=OddsUtil.getIncrement(e,
"decrease",k);l=h.increment;if(BetHandler.isLessThanMinOdds(e-l))return;g=MathUtil.decimal.subtract(e,l);g=A(g,h.lowerBound,h.upperBound,l,null,k);MarketUtil.isLineMarket(k.marketType,k.bettingType)&&(g=MathUtil.decimal.subtract(e,1));f.val(g)}return DataBase.bet.updateOdds(a,d,b,c,g)};BetHandler.clickUpDownArrowKey=function(a,d,b,c,e,f){f=f.find("#odds");var h=parseFloat(f.val())||0,g=0,k=DataBase.markets.get(a,d.replace("_","."));if(KeyEventUtils.isUpArrowKey(e)){e=OddsUtil.getIncrement(h,"increase",
k);var l=e.increment;g=MathUtil.decimal.add(h,l);g=A(g,e.lowerBound,e.upperBound,l,null,k);MarketUtil.isLineMarket(k.marketType,k.bettingType)&&(g=MathUtil.decimal.add(h,1));0==h&&(g=1.01);f.val(g)}else if(KeyEventUtils.isDownArrowKey(e)){e=OddsUtil.getIncrement(h,"decrease",k);l=e.increment;if(BetHandler.isLessThanMinOdds(h-l))return;g=MathUtil.decimal.subtract(h,l);g=A(g,e.lowerBound,e.upperBound,l,null,k);MarketUtil.isLineMarket(k.marketType,k.bettingType)&&(g=MathUtil.decimal.subtract(h,1));f.val(g)}return DataBase.bet.updateOdds(a,
d,b,c,g)};BetHandler.blurCheckStakeValid=function(a,d,b,c,e,f,h,g,k,l,p){g=JsCache.get("#betMsg");null!=e&&(g=e);if(UnMatchTicketUtil.isValidStake(d,b,c))return g.hide(),c;d=UnMatchTicketUtil.getValidStake(d,b,c);f=BetHandler.getMinBet(f,h,l,p);a.val(d);g.html(I18N.get("msg.member.stake.increments",[f,CurrencyType.getInstanceOf(b).stakeMin]));g.show();return d};BetHandler.blurCheckOddsValidate=function(a,d,b,c){b=DataBase.markets.get(b,c);a=$j(a);c=parseFloat(a.val())||0;var e=OddsUtil.getIncrement(c,
null,b);d=A(c,e.lowerBound,e.upperBound,e.increment,d,b);a.val(d)};BetHandler.updateKeyupOdds=function(a,d,b,c,e){e=$j(e);e=parseFloat(e.val())||0;return DataBase.bet.updateOdds(a,d,b,c,e)};BetHandler.isLessThanMinOdds=function(a){if(void 0==a||null==a||isNaN(a))return!0;a=parseFloat(a);return 1.01>a?!0:!1};BetHandler.backOddsIsLessThanLayOdds=function(a,d,b,c){var e=DataBase.bet.get(a,d,b,c),f=getAnotherSideType(c);a=DataBase.bet.get(a,d,b,f);return null!=a?(a=parseFloat(a.odds),isNaN(a)&&(a=1.01),
SideType.Back.unique()==c?e.odds>a?!1:!0:e.odds<a?!1:!0):!1};BetHandler.getMinBet=function(a,d,b,c){var e=parseFloat(PageConfig.minBet);UnMatchTicketUtil.isExchangeTicket(b,PageConfig.isOfferBetfairExchange,BetHandler.ONLY_OFFER_DABBA_EVENT_TYPE,PageConfig.ONLY_OFFER_DABBA_CURRENCY_TYPE)?(c>PageConfig.BETFAIR_CURRENCY_MAX_ODDS&&(c=PageConfig.BETFAIR_CURRENCY_MAX_ODDS),e=BetHandler.oddsMinBetMap[c]):null!=a&&null!=d&&(d=d.replace("_","."),a=DataBase.markets.get(a,d),null!=a&&null!=a.betLimitSetting&&
a.betLimitSetting.minBet&&(e=parseFloat(a.betLimitSetting.minBet)));return e};BetHandler.isLessThanMinStake=function(a,d){var b=parseInt(a.find("#inputStake").val()),c=BetHandler.getMinBet(a.attr("eventId"),a.attr("marketId"),a.attr("eventType"),a.find("#odds").val());if(b<c)return BetHandler.showLessThanMinBetTips(a,c,d),!0;BetHandler.hideStakeTipsPopup(a);return!1};BetHandler.showLessThanMinBetTips=function(a,d,b){var c=$j("[id=stakeTipsPopup][bet="+a.attr("id")+"]");0==c.length&&(c=JsCache.clone("#stakeTipsPopup"),
b.before(c),c.attr("bet",a.attr("id")),c.attr("stakeTipsPopupType","extended"));b={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};a=PositionUtils.getPosition([a.find("#listPoint"),a.find("#listPoint").parent()]);c.css(a);c.html("Min "+CurrencyUtil.formatter(d,b)).show()};BetHandler.hideStakeTipsPopup=function(a){$j("[id=stakeTipsPopup][bet="+a.attr("id")+"]").remove()};BetHandler.showOddsTips=
function(a,d){var b=$j("[id=oddsTipsPopup][bet="+a.attr("id")+"]");0==b.length&&(b=JsCache.clone("#oddsTipsPopup"),d.before(b),b.attr("bet",a.attr("id")),b.attr("oddsTipsPopupType","extended"));a=PositionUtils.getPosition([a.find("#oddsTipsPoint"),a.find("#oddsTipsPoint").parent()]);b.css(a);b.show()};BetHandler.hideOddsTips=function(a){$j("[id=oddsTipsPopup][bet="+a.attr("id")+"]").remove()};BetHandler.deleteBet=function(a){var d=a.parent(),b=parseInt(d.attr("count"));BetHandler.removeSelectClass(a.attr("eventId"),
a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"));DataBase.bet.remove(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"));a.remove();BetHandler.hideStakeTipsPopup(a);BetHandler.hideOddsTips(a);d.attr("count",--b);0==b&&d.remove();BetHandler.addToCookie();D();JsCache.get("#betMsg").hide();BetHandler.oddsAndStakeCheck();a=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(a,u))};BetHandler.openCallBack=
function(){$j(".slip-wrap").removeClass("full-bet_slip");F&&BetHandler.initBetListHeight()};BetHandler.closeCallBack=function(){$j(".slip-wrap").addClass("full-bet_slip");F&&BetHandler.initBetListHeight()};BetHandler.isAllowNonIntegerStake=function(a){const d=new Set(CurrencyProperty.allowNonIntegerStake);return PageConfig.ENABLE_NON_INTEGER_STAKE&&d.has(CurrencyType.getInstanceOf(a))?!0:!1}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.bet={};let r=new HashMap;DataBase.bet.add=function(n,q,m,w,y,v,C,G,A,J,D,H,E,z,B){q={sideType:n,odds:q,eventType:m,eventId:w,runner:y,marketId:v.replace(".","_"),selectionId:C,eventName:G,marketName:A,inPlay:J,timestamp:(new Date).getTime(),marketType:D,selectionKey:H,handicap:E,sortpriority:z?z:"",boardType:B};r.put(DataBase.bet.generateKey(w,v,H,n),q);return q};DataBase.bet.generateKey=function(n,q,m,w){return n+"_"+q.replace(".","_")+"_"+m+"_"+w};DataBase.bet.updateOdds=function(n,
q,m,w,y){var v=!1;n=DataBase.bet.get(n,q,m,w);if(null!=n){if(null==n.odds||null!=n.odds&&n.odds!=y)v=!0;n.odds=y;return v}};DataBase.bet.updateStake=function(n,q,m,w,y){var v=!1;n=DataBase.bet.get(n,q,m,w);if(null!=n){if(null==n.stake||null!=n.stake&&n.stake!=y)v=!0;n.stake=Number(y);return v}};DataBase.bet.calculatePL=function(){var n=r.values(),q;for(q in n){var m=n[q];if(m.sideType&&m.eventId&&m.marketId&&m.selectionId&&m.odds&&m.timestamp&&m.selectionKey&&m.handicap)if(isNaN(m.stake)||0==m.stake)m.stake=
0,m.profit=0,m.liability=0;else{var w=m.sideType;SideType.Back.unique()==w?(m.profit=UnMatchTicketUtil.getPL(m.odds,m.stake),m.liability=m.stake):SideType.Lay.unique()==w&&(m.profit=m.stake,m.liability=UnMatchTicketUtil.getPL(m.odds,m.stake))}}};DataBase.bet.get=function(n,q,m,w){n=DataBase.bet.generateKey(n,q,m,w);return null==r.get(n)?null:r.get(n)};DataBase.bet.getByMarketId=function(n,q){var m=[];$j.each(r.values(),function(w,y){n==y.eventId&&q.replace(".","_")==y.marketId&&m.push(y)});return m};
DataBase.bet.getBySelectionId=function(n,q,m){var w=[];$j.each(r.values(),function(y,v){n==v.eventId&&q.replace(".","_")==v.marketId&&m==v.selectionKey&&w.push(v)});return w};DataBase.bet.remove=function(n,q,m,w){n=DataBase.bet.generateKey(n,q,m,w);return r.remove(n)};DataBase.bet.queryAll=function(){return r.values()};DataBase.bet.queryForBets=function(){var n=[];$j.each(r.values(),function(q,m){if(!(m.sideType&&m.eventId&&m.marketId&&m.selectionId&&m.stake&&m.odds&&m.timestamp&&m.selectionKey&&
m.handicap))return!0;n.push({sideType:m.sideType,odds:m.odds,stake:m.stake,eventType:m.eventType,eventId:m.eventId,marketId:m.marketId.replace("_","."),selectionId:m.selectionId,handicap:m.handicap,timestamp:m.timestamp})});return n};DataBase.bet.queryForCookie=function(){var n=[];$j.each(r.values(),function(q,m){q=[m.sideType,m.odds,m.eventType,m.eventId,m.runner,m.marketId.replace(".","_"),m.selectionId,m.eventName,m.marketName,m.inPlay,m.timestamp,m.marketType,m.selectionKey,m.handicap,m.sortpriority];
n.push(q)});return n};DataBase.bet.size=function(){return r.length};DataBase.bet.keySet=function(){return r.keySet()};DataBase.bet.entrySet=function(){return r.entrySet()}})();
function checkIsNoElement(r){var n=0;$j.each(r,function(q,m){q=$j(m);if(q.hasClass("sum")||q.is(":hidden"))return!0;n++});if(0==n)return r.find("#backSlipHeader").hide(),r.find("#laySlipHeader").hide(),!0;0==r.find('dl[sideType="1"]').length&&r.find("#backSlipHeader").hide();0==r.find('dl[sideType="2"]').length&&r.find("#laySlipHeader").hide();if(0!=n)return!1}function getAnotherSideType(r){return SideType.Back.unique()==r?SideType.Lay.unique():SideType.Back.unique()}
function commaSeparateNumber(r){return r.toString().replace(/\D/g,"").replace(/\B(?=(\d{3})+(?!\d))/g,"")}
;
