"undefined"==typeof BookMakerMarketHandler&&(BookMakerMarketHandler={});
(function(){function w(a){var c=a.bookMakerEvent.eventId;0!=a.bookMakerMarket.markets.length&&DataBase.bookMakerMarkets.update(c,a.bookMakerMarket.markets);0!=a.bookMakerSelection.selections.length&&DataBase.bookMakerMarkets.updateSelection(c,a.bookMakerSelection.selections)}function h(a,c,b){if(0!==b.bookMakerMarket.markets.length){var d=b.bookMakerEvent.eventId,f=b.bookMakerEvent.eventType;b=b.bookMakerMarket.markets;var g={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,
formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};b.sort(function(t,x){return BookMakerMarketUtil.sortMarkets(t,x)});for(var e=0,l=b.length;e<l;e++){var k=b[e],p=k.marketId,u=k.status;if(!BookMakerMarketUtil.isOffline(u)){var q=a.find("#bookMakerMarket_"+DataBase.bookMakerMarkets.getMarketKey(d,p));if(0===q.length){if(BookMakerMarketUtil.isClosed(u))continue;q=m(a,c,d,k)}r(a,q,k,d,g,f);y(a,q,k,d,p)}}MultiMarketsHandler.appendBookMakerPin(f,d,BookMakerMarketHandler.isViewMultiMarket());
FancyBetMarketUtil.checkForAllClose(d)}}function m(a,c,b,d){c=c.find("#bookMakerMarketTemplate").clone();var f=DataBase.bookMakerMarkets.getMarketKey(b,d.marketId);c.prop("id","bookMakerMarket_"+f);c.prop("eventId",b);c.prop("marketId",d.marketId);c.prop("marketType",d.marketType);c.prop("status",d.status);c.prop("summaryStatus",d.summaryStatus);c.prop("updateDate",d.updateDate);c.prop("marketName",d.marketName);a.append(c.show());return c}function r(a,c,b,d,f,g){c.prop("sort",b.sort);d=CurrencyUtil.formatter(b.min,
f);f=CurrencyUtil.formatter(b.max,f);let e=0==b.rebateRatio?"":MathUtil.decimal.multiply(b.rebateRatio,100)+"%";D(g)?(b.marketName&&c.find("#market-name").text(b.marketName),c.find("#min").html(d),c.find("#max").html(f),0===e.length?c.find("#rebate").hide():(c.find("#rebate").show(),c.find("#rebate-val").text(e))):(a.find("#min").html(d),a.find("#max").html(f),0===e.length?(c.find("#rebateName").hide(),c.find("#rebate").hide()):(c.find("#rebateName").show(),c.find("#rebate").show(),c.find("#rebate").html(e)))}
function y(a,c,b,d,f){let g=a.find("[id^=bookMakerSuspend_][marketId="+f+"]");0!==g.length&&$j.each(g,function(e,l){l=a.find(g[e]);if(null==l||0===l.length)return!0;e=l.prop("selectionId");E(a,c,b,d,f,e,l)})}function v(a,c,b){if(0!==b.bookMakerSelection.selections.length){var d=b.bookMakerEvent,f=b.bookMakerEvent.eventId;b=b.bookMakerSelection.selections;var g=!1;b.sort(function(A,C){return BookMakerSelectionUtil.sort(A.marketId,C.marketId,A.sort,C.sort)});for(var e=0,l=b.length;e<l;e++){var k=b[e],
p=k.marketId,u=k.selectionId,q=DataBase.bookMakerMarkets.get(f,p);if(null!=q&&!BookMakerMarketUtil.isClosed(q.status)){var t=a.find("#bookMakerMarket_"+DataBase.bookMakerMarkets.getMarketKey(f,p));if(0!=t.length){p=DataBase.bookMakerMarkets.getSelectionKey(f,p,u);p=t.find("#bookMakerSelection_"+p);0==p.length&&(p=B(a,t,c,d,q,k),g=!0);BookMakerSelectionUtil.updateSelectionOdds(t,p,k);BookMakerSelectionUtil.updateBetboardOdds(f,k,!1);u=p.find("#back_1");var x=p.find("#lay_1");SparkHandler.addFancyBetSpark(u,
null,u.find("a").text());SparkHandler.addFancyBetSpark(x,null,x.find("a").text());G(a,t,p,f,q,k,g)}}}}}function B(a,c,b,d,f,g){a=g.marketId;var e=g.selectionId,l=DataBase.bookMakerMarkets.getSelectionKey(d.eventId,g.marketId,e),k=b.find("#suspendTemplate").clone();k.prop("id","bookMakerSuspend_"+l);k.prop("selectionId",e);k.attr("marketId",a);c.append(k);b=b.find("#bookMakerSelectionTemplate").clone();b.prop("id","bookMakerSelection_"+l);b.prop("eventId",d.eventId);b.prop("marketId",a);b.prop("selectionId",
e);b.find("#runnerName").html(g.runnerName);F(c,b,b.find("[id^=back_]"),d,f,g,SideType.Back.unique());F(c,b,b.find("[id^=lay_]"),d,f,g,SideType.Lay.unique());c.append(b.show());return b}function G(a,c,b,d,f,g,e){b=DataBase.bookMakerMarkets.getSelectionKey(d,g.marketId,g.selectionId);b=a.find("#bookMakerSuspend_"+b);0!=b.length&&E(a,c,f,d,g.marketId,g.selectionId,b,e)}function E(a,c,b,d,f,g,e,l){a=DataBase.bookMakerMarkets.getMarketKey(d,f);var k={eventId:d,marketId:f};BookMakerMarketUtil.isOnline(b.status)&&
!BookMakerMarketUtil.isClosed(b.status)&&c.show();l&&z.put(a,k);e.find("#suspendClass").removeClass("fancy-suspend");l=DataBase.bookMakerMarkets.getSelection(d,f,g);null!=l&&(BookMakerSelectionUtil.isSuspend(l.status)?(e.find("#suspendClass").addClass("fancy-suspend"),e.find("#info").html("Suspend"),e.fadeIn(),BookMakerBetHandler.hideBetBoardBySelection(d,f,g),BookMakerMarketHandler.removeSelectClass(),z.put(a,k)):BookMakerMarketUtil.isSuspend(b.status)?(e.find("#suspendClass").addClass("fancy-suspend"),
e.find("#info").html("Suspend"),e.fadeIn(),BookMakerBetHandler.hideBetBoardBySelection(d,f,g),BookMakerMarketHandler.removeSelectClass(),z.put(a,k)):BookMakerMarketUtil.isBallRun(b.status)?(e.find("#suspendClass").addClass("fancy-suspend"),e.find("#info").html("Ball Running"),e.fadeIn(),BookMakerBetHandler.hideBetBoardBySelection(d,f,g),BookMakerMarketHandler.removeSelectClass(),z.put(a,k)):BookMakerMarketUtil.isClosed(b.status)||BookMakerMarketUtil.isOffline(b.status)?(e.find("#suspendClass").addClass("fancy-suspend"),
e.find("#info").html("Closed"),e.hide(),BookMakerBetHandler.hideBetBoardBySelection(d,f,g),BookMakerMarketHandler.removeSelectClass(),z.put(a,k),c.hide()):e.hide())}function H(){if(0!=z.size()){var a=z.values(),c;for(c in a){var b=a[c];null!=b&&BookMakerBetHandler.getExposure(b.eventId,b.marketId)}z.clear()}}function F(a,c,b,d,f,g,e){a=function(l,k,p,u,q,t,x,A,C,I){return function(){var n=DataBase.bookMakerMarkets.get(q,t);null==n||BookMakerMarketUtil.isSuspend(n.status)||BookMakerMarketUtil.isClosed(n.status)||
(n=DataBase.bookMakerMarkets.getSelection(q,t,x),null==n||BookMakerSelectionUtil.isSuspend(n.status)||(n=BookMakerSelectionUtil.getOddsInfoJson(A,n),null!=n&&(n=n[0],null==n||isNaN(n)||(n=parseFloat(n),0==n||isNaN(n)||("true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeBookMakerBet(k,u,q,t,x,A,n):(BookMakerMarketHandler.removeSelectClass(),
k.find("#"+SideType.getInstanceOf(A).name.toLowerCase()+"_1").addClass("select"),BookMakerBetHandler.appendBoard(l,k,u,q,t,x,A,n,C,I)))))))}}(a,c,b,d.eventType,d.eventId,g.marketId,g.selectionId,e,d.eventName,f.marketName);b.on("click",a)}function J(a){var c=!1,b;for(b in a){var d=a[b];if(BookMakerMarketUtil.isOnline(d.status)&&!BookMakerMarketUtil.isClosed(d.status)){c=!0;break}}return c}function D(a){return a===EventType.CRICKET.value||a===EventType.ELECTION.value}BookMakerMarketHandler.queryTask=
null;var z=new HashMap;BookMakerMarketHandler.init=function(){BookMakerMarketHandler.isEnableBookMaker()&&BookMakerMarketHandler.initTask()};BookMakerMarketHandler.isEnableBookMaker=function(){return PageConfig.isEnableBookMaker};BookMakerMarketHandler.isShowBookMaker=function(){return BookMakerMarketHandler.isEnableBookMaker()&&PageConfig.hasBookMakerMarkets};BookMakerMarketHandler.isViewMultiMarket=function(){return-1<location.href.indexOf("multiMarkets")};BookMakerMarketHandler.initTask=function(){if(null==
BookMakerMarketHandler.queryTask){var a=TaskExecuter.createTask(PageConfig.getBookMakerMarketsTaskCycleTime,0,function(){BookMakerMarketHandler.queryBookMakerMarkets(this)});a.version=0;a.oddsSettingVersion=0;a.selectionTs=0;BookMakerMarketHandler.queryTask=a}else BookMakerMarketHandler.queryTask.isStop=!1;BookMakerMarketHandler.queryTask.run();TaskExecuter.execute()};BookMakerMarketHandler.abortTask=function(){null!=BookMakerMarketHandler.queryTask&&BookMakerMarketHandler.queryTask.stop()};BookMakerMarketHandler.queryBookMakerMarkets=
function(a){try{$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+"/exchange/member/playerService/queryBookMakerMarkets",data:{eventId:PageConfig.selectEventId,version:a.version,oddsSettingVersion:a.oddsSettingVersion,selectionTs:a.selectionTs,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(c){c&&(c.version>a.version&&(a.version=Math.max(c.version,a.version)),c.oddsSettingVersion>
a.oddsSettingVersion&&(a.oddsSettingVersion=Math.max(c.oddsSettingVersion,a.oddsSettingVersion)),c.selectionTs>a.selectionTs&&(a.selectionTs=Math.max(c.selectionTs,a.selectionTs)),BookMakerMarketHandler.updateBookMakerMarkets(c))},error:function(c,b,d){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.log(c.status);Trace.log(d)}})}catch(c){Trace.printStackTrace(c)}finally{a.check(),
TaskExecuter.execute()}};BookMakerMarketHandler.updateBookMakerMarkets=function(a){if(a.bookMakerEvent&&a.bookMakerMarket&&a.bookMakerSelection){w(a);var c=a.bookMakerEvent.eventType,b=a.bookMakerEvent.eventId,d=a.bookMakerEvent.highlightMarketId,f=a.bookMakerEvent.eventName,g=$j("#overWrap"),e=BookMakerMarketHandler.getBookMakerWrap(g,b,BookMakerMarketHandler.isViewMultiMarket(),c);g=e.find("#bookMakerTempTable");var l=e.find("#bookMakerHead");BookMakerMarketHandler.isViewMultiMarket()&&(e.find(".multi_name").unbind("click").click(function(){location.href=
PageConfig.fullMarketPath+"?eventType="+c+"&eventId="+b+"&marketId="+d}),e.find("#multiMarketRefresh").unbind("click").click(function(){e.find("#multiMarketLoading").show();setTimeout(function(){e.find("#multiMarketLoading").hide()},500)}),0==!a.bookMakerMarket.markets.length&&(e.find("#min").html(CurrencyUtil.formatter(a.bookMakerMarket.markets[0].min,k)),e.find("#max").html(CurrencyUtil.formatter(a.bookMakerMarket.markets[0].max,k)),0==a.bookMakerMarket.markets[0].rebateRatio?(e.find("#rebateName").hide(),
e.find("#rebate").hide()):(k=MathUtil.decimal.multiply(a.bookMakerMarket.markets[0].rebateRatio,100)+"%",e.find("#rebateName").show(),D(c)?(e.find("#rebate").show(),e.find("#rebate-val").html(k)):e.find("#rebate").html(k).show()),l.find("#eventName").text(f)),e.show());f=e.find("#bookMakerMarketList");var k={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};J(DataBase.bookMakerMarkets.queryByEvent(b))?
(f.show(),BookMakerMarketHandler.isViewMultiMarket()&&l.find(".game-bookmaker").addClass("in-play")):(BookMakerMarketHandler.isViewMultiMarket()&&e.hide(),e.hide(),f.hide());h(f,g,a);v(f,g,a);H()}};BookMakerMarketHandler.getDelayBettingElem=function(a,c,b){var d=$j("#overWrap"),f=d.find("#bookMakerTempTable"),g=d.find("#bookMakerMarketList");d=g.find("#bookMakerSelection_"+DataBase.bookMakerMarkets.getSelectionKey(a,c,b));if(0==d.length||!d.is(":visible"))return null;var e=g.find("#bookMakerSuspend_"+
DataBase.bookMakerMarkets.getSelectionKey(a,c,b));if(0==e.length||e.is(":visible"))return null;g=g.find("#delayBetting_"+DataBase.bookMakerMarkets.getSelectionKey(a,c,b));0==g.length&&(g=f.find("#delayTemplate").clone(),g.prop("id","delayBetting_"+DataBase.bookMakerMarkets.getSelectionKey(a,c,b)),d.before(g));return g};BookMakerMarketHandler.showDelayBetting=function(a,c,b){var d=DataBase.bookMakerMarkets.get(a,c);d=d.delayBetting?1E3*parseInt(d.delayBetting):0;if(0!=d){var f=BookMakerMarketHandler.getDelayBettingElem(a,
c,b);null!=f&&0!=f.length&&(f.find("#info").html(""),f.fadeIn(),setTimeout(function(){f.find("#info").html("");f.fadeOut()},d))}};BookMakerMarketHandler.hideDelayBetting=function(a,c,b){a=BookMakerMarketHandler.getDelayBettingElem(a,c,b);null!=a&&0!=a.length&&(a.find("#info").html(""),a.hide())};BookMakerMarketHandler.getBookMakerWrap=function(a,c,b,d){var f=a.find("#bookMakerTable_"+c);b?0===f.length&&(b=D(d)?"#bookMakerEnableMultiCreateMarketTableTemplate":"#bookMakerTableTemplate",f=a.find(b).clone(),
f.prop("id","bookMakerTable_"+c),f.attr("name","multiMarketItem"),a.find("#header").after(f)):f=a.find("#bookMakerWrap").show();return f};BookMakerMarketHandler.removeSelectClass=function(){var a=$j("#overWrap").find("[id^=bookMakerMarket_]");a.find("#lay_1").removeClass("select");a.find("#back_1").removeClass("select")}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.bookMakerMarkets={};var w=new TreeMap;DataBase.bookMakerMarkets.update=function(h,m){var r=w.get(h);null==r&&(r=new TreeMap,w.put(h,r));for(h=0;h<m.length;h++){var y=m[h],v=r.get(y.marketId);null!=v&&null!=v.selectionMap&&(y.selectionMap=v.selectionMap);r.put(y.marketId,y)}};DataBase.bookMakerMarkets.updateSelection=function(h,m){var r=w.get(h);if(null==r)Trace.log("eventId: "+h+" is not exist");else{h=0;for(var y=m.length;h<y;h++){var v=m[h],B=r.get(v.marketId);null==B?Trace.log("marketId: "+
v.marketId+" is not exist"):(null==B.selectionMap&&(B.selectionMap=new TreeMap),B.selectionMap.put(v.selectionId,v))}}};DataBase.bookMakerMarkets.get=function(h,m){h=w.get(h);return null==h?null:h.get(m)};DataBase.bookMakerMarkets.queryByEvent=function(h){var m=w.get(h);null==m&&(m=new TreeMap,w.put(h,m));return m.values()};DataBase.bookMakerMarkets.getSelection=function(h,m,r){h=DataBase.bookMakerMarkets.get(h,m);if(null==h)return null;h=h.selectionMap;return null==h?null:h.get(r)};DataBase.bookMakerMarkets.queryAll=
function(){return w.values()};DataBase.bookMakerMarkets.getMarketKey=function(h,m){return h+"_"+m};DataBase.bookMakerMarkets.getSelectionKey=function(h,m,r){return h+"_"+m+"_"+r}})();

