"undefined"==typeof BookMakerBetHandler&&(BookMakerBetHandler={});
(function(){function w(a,b,c,d,e,g){a.find("#placeBet").unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var k=q(a,b,c);var h=a.find("#inputStake"),m=parseFloat(h.val())||0,l=DataBase.bookMakerBet.get(b,c,d,e),t="",x=f(l);if(!x){var u=DataBase.bookMakerMarkets.get(b,l.marketId);l=u.min;u=u.max;m<l?(h.val(l),DataBase.bookMakerBet.updateStake(b,c,d,e,l),t+=I18N.get("msg.member.minBet")):m>u&&(h.val(u),DataBase.bookMakerBet.updateStake(b,c,d,e,u),t+=I18N.get("msg.member.maxBet"))}""==
t||x||r(k,"warning",t,!0);BookMakerBetHandler.getExposure(b,c);x?(l=DataBase.bookMakerBet.getForBet(b,c,d,e),h=$j("#bookMakerBetBar_"+g),0==h.length&&(h=$j("#bookMakerTempTable").find("#bookMakerBetBarTemplate").clone(),h.prop("id","bookMakerBetBar_"+g),a.after(h)),m=a.find("#bookMakerBetAcceptAnyOdds").is(":checked")?1:0,BookMakerBetHandler.submitBet(l,h,k,null,m),a.hide()):a.find("#placeBet").removeClass("disable")}});a.find("#cancel").unbind("click").click(function(){DataBase.bookMakerBet.clearByEventId(b);
a.hide();BookMakerMarketHandler.removeSelectClass();BookMakerBetHandler.getExposure(b,c)});a.find("#inputStake").click(function(){a.find("#inputStake").select()});a.find("#inputStake").change(function(){var k=parseFloat(a.find("#inputStake").val())||0;q(a,b,c);k=DataBase.bookMakerBet.updateStake(b,c,d,e,k);BookMakerBetHandler.eventCalculate(a,b,c,d,e,k)});a.find("#inputStake").blur(function(){CoinHandler.hideStakePopupList();var k=parseFloat(a.find("#inputStake").val())||0;q(a,b,c);k=DataBase.bookMakerBet.updateStake(b,
c,d,e,k);BookMakerBetHandler.eventCalculate(a,b,c,d,e,k)});a.find("#inputStake").keydown(function(k){var h=k.which;KeyEventUtils.isNumberKey(k)||KeyEventUtils.isBackspaceKey(h)||KeyEventUtils.isDeleteKey(h)||KeyEventUtils.isArrowKey(h)||KeyEventUtils.isTabKey(h)||KeyEventUtils.isEnterKey(h)||WindowEventUtil.stopEvent(k)});a.find("#inputStake").keyup(function(k){$j(this).val(function(m,l){return StringUtil.commaSeparateNumber(l)});var h=parseFloat(a.find("#inputStake").val())||0;q(a,b,c);h=DataBase.bookMakerBet.updateStake(b,
c,d,e,h);BookMakerBetHandler.eventCalculate(a,b,c,d,e,h);k=k.which;KeyEventUtils.isEnterKey(k)&&a.find("#placeBet").click();KeyEventUtils.isTabKey(k)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()})}function f(a){if(null==a)return!1;var b=DataBase.bookMakerMarkets.get(a.eventId,a.marketId);if(null==b)return!1;var c=b.min;b=b.max;if(!c||!b)return!1;a=parseFloat(a.stake||"0");return a<c||a>b?!1:!0}function p(a,b,c){var d=c.find("#progressBar"),e=n(a,b);d.css("width",e);c.find("#secRemain").html(MathUtil.decimal.divide(a,
10)+" sec remaining…");0<a&&(a--,setTimeout(function(){p(a,b,c)},100))}function n(a,b){a=MathUtil.decimal.subtract(b,a);b=MathUtil.decimal.divide(a,b);1<b&&(b=1);b=MathUtil.decimal.multiply(b,100);return Math.round(b)+"%"}function q(a,b,c){var d=$j("#overWrap").find("#bookMakerBetMessage_"+DataBase.bookMakerMarkets.getMarketKey(b,c));0==d.length&&(d=$j("#bookMakerTempTable").find("#bookMakerBetMessageTemplate").clone(),d.prop("id","bookMakerBetMessage_"+DataBase.bookMakerMarkets.getMarketKey(b,c)));
a.after(d);return d}function r(a,b,c,d,e,g){e=a.find("#header");UiUtils.removeContents(a.find("#info"));a.find("#classWrap").removeClass("success").removeClass("error").removeClass("warning").addClass(b);null!=c&&e.html(c);null!=g&&(c=g.stake,b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),c=b.name+b.symbol+c+" at odds "+g.odds,CurrencyUtil.updateSetting({currencySymbol:b.symbol}),c=SideType.Back.unique()==g.sideType?c+" Profit: ":c+" Liability: ",c=BookMakerTransactionUtils.isFancyBetPLEventType(g.eventType)?
c+MyTransactionUtils.getFancyBetPL(g.odds,g.stake):c+UnMatchTicketUtil.getPL(g.odds,g.stake),e.html("Bet Matched"),e.after(c));a.find("#close").unbind("click").click(function(){a.fadeOut()});d&&setTimeout(function(){a.fadeOut()},3E3);a.fadeIn()}function v(a,b){var c=(BookMakerMarketHandler.isViewMultiMarket()?$j("#bookMakerTable_"+a):$j("#bookMakerWrap")).find("#bookMakerMarket_"+DataBase.bookMakerMarkets.getMarketKey(a,b));if(0!=c.length){c=c.find("[id^=bookMakerSelection_]");var d=DataBase.bookMakerBet.getByMarketId(a,
b);a=DataBase.bookMakerTxn.getByMarketId(a,b+"",null,null,CategoryType.BOOK_MAKER.unique());0<d.length?c.find("#after").show():c.find("#after").hide();0<a.length?c.find("#before").show():c.find("#before").hide()}}BookMakerBetHandler.appendBoard=function(a,b,c,d,e,g,k,h,m,l){BookMakerBetHandler.clearBoard(d);a=DataBase.bookMakerBet.generateKey(d,e,g,k);c=DataBase.bookMakerBet.add(c,d,e,g,k,h,m,l);h=!1;m=$j("#overWrap");l=m.find("#bookMakerBetBoard_"+a);if(0==l.length){m=m.find("#bookMakerBetTemplate").clone();
l=m.find("#bookMakerBetHeader");var t=m.find("#oddsHeader"),x=SideType.Back.unique()==k?SideType.Back.name:SideType.Lay.name;m.find("#classWrap").removeClass("slip-back").removeClass("slip-lay").addClass("slip-"+x.toLowerCase());m.prop("id","bookMakerBetBoard_"+a);m.prop("eventId",d);m.prop("marketId",e);m.prop("selectionId",g);m.prop("sideType",k);l.find("#acceptCheck").before(StringUtil.ucfirst(SideType.getInstanceOf(k).name));t.find("#odds").html(c.odds);w(m,d,e,g,k,a);l=m}l.find("#bookMakerBetAcceptAnyOdds").prop("checked",
TopMenuHandler.isAcceptAnyOdds("fancyBet"));a=l;b.after(a.fadeIn());a.find("#odds").html(c.odds);null!=PageConfig.userCoin&&0<PageConfig.userCoin?(b=DataBase.bookMakerMarkets.get(d,e),c=parseFloat(PageConfig.userCoin),b.min&&parseFloat(b.min)>PageConfig.userCoin&&(c=parseFloat(b.min)),a.find("#inputStake").val(c),h=DataBase.bookMakerBet.updateStake(d,e,g,k,c)):a.find("#inputStake").val("");q(a,d,e);BookMakerBetHandler.eventCalculate(a,d,e,g,k,h);a.find("#odds").select();BookMakerBetHandler.updateExposure(d);
CoinHandler.showBookMakerBetCoin(a)};BookMakerBetHandler.clearBoard=function(a){var b=$j("#overWrap"),c=b.find("[id^=bookMakerBetBoard_]");$j.each(c,function(d,e){e=b.find(e);0<e.length&&(e.prop("eventId"),e.prop("marketId"),e.prop("selectionId"),e.prop("sideType"),e.hide())});DataBase.bookMakerBet.clearByEventId(a)};BookMakerBetHandler.hideBetBoardBySelection=function(a,b,c){var d=$j("#bookMakerMarketList"),e;for(e in SideType)if(SideType[e]&&SideType[e].value){var g=DataBase.bookMakerBet.generateKey(a,
b,c,SideType[e].unique());g=d.find("#bookMakerBetBoard_"+g);0!=g.length&&(g.hide(),DataBase.bookMakerBet.remove(a,b,c,SideType[e].unique()))}};BookMakerBetHandler.eventCalculate=function(a,b,c,d,e,g){d=DataBase.bookMakerBet.get(b,c,d,e);d=f(d);a=a.find("#placeBet");d?a.removeClass("disable"):a.addClass("disable");BookMakerBetHandler.getExposure(b,c)};BookMakerBetHandler.submitBet=function(a,b,c,d,e){var g=0,k=0;$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/bookMakerBet",
data:{bookMakerBets:JSON.stringify([a]),isOneClickBet:d,isAcceptAnyOdds:e},beforeSend:function(){if(null!=b){b.show();var h=MathUtil.decimal.multiply(5,10),m=""+MathUtil.decimal.multiply(5,10);0<=h&&p(h,m,b)}BookMakerMarketHandler.showDelayBetting(a.eventId,a.marketId,a.selectionId)},complete:function(){},success:function(h){try{if(h.error)null!=c?r(c,"error",h.error,!0):NoticeHandler.error(h.error),BookMakerMarketHandler.hideDelayBetting(a.eventId,a.marketId,a.selectionId);else if(0==h.result.length)BookMakerMarketHandler.hideDelayBetting(a.eventId,
a.marketId,a.selectionId);else{for(var m in h.result){var l=h.result[m];if("SUCCESS"==l.status){0==g&&0==k&&(g=l.eventId,k=l.marketId);var t=l.bookMakerTxn;null!=t&&(DataBase.bookMakerTxn.update([t]),null!=c&&r(c,"success",null,!0,"txn",t))}else l.error&&(null!=c?r(c,"error",l.error,!0):NoticeHandler.error(l.error),BookMakerMarketHandler.hideDelayBetting(a.eventId,a.marketId))}0!=g&&""!=k&&(TxnHandler.setEventIdAndMarketId(g,k,CategoryType.BOOK_MAKER.unique()),g=0,k="");TxnHandler.updateOpenBetSelectionBox();
TxnHandler.checkToHideOpenBets();var x=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(x))}}catch(u){Trace.printStackTrace(u)}finally{null!=b&&b.hide(),BookMakerMarketHandler.removeSelectClass(),DataBase.bookMakerBet.clearByEventId(a.eventId),BookMakerBetHandler.getExposure(a.eventId,a.marketId)}},error:function(h){Trace.printStackTrace(h);null!=b&&b.hide();BookMakerMarketHandler.hideDelayBetting(a.eventId,a.marketId)}});JsCache.get("#confirmBetList").hide();
JsCache.get("#confirmBetFullBtn").hide()};BookMakerBetHandler.getExposure=function(a,b){try{var c=DataBase.bookMakerMarkets.get(a,b);if(null==c)Trace.log("fancy market "+b+" is null");else{var d=DataBase.bookMakerBet.getByMarketId(a,b),e=DataBase.bookMakerTxn.getByMarketId(a,b+"",null,null,CategoryType.BOOK_MAKER.unique());if(0==d.length&&0==e.length)v(a,b);else if(null!=c.selectionMap){var g=c.selectionMap.values(),k=[MyTransactionStatusType.Active.unique(),MyTransactionStatusType.Void.unique()];
e=DataBase.bookMakerTxn.getByMarketId(a,b+"",null,k,CategoryType.BOOK_MAKER.unique());var h=ExposureUtil.calculateBookMakerExposure(a,b,d,e,c,g);var m=(BookMakerMarketHandler.isViewMultiMarket()?$j("#bookMakerTable_"+a):$j("#bookMakerWrap")).find("#bookMakerMarket_"+DataBase.bookMakerMarkets.getMarketKey(a,b));if(0!=m.length){var l=WebSiteType.getInstanceOf(PageConfig.webSiteType),t={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,
"trailingZeros,":!1};l.isFancyFairGroup()&&(t.precision=0,t.roundingMode="DOWN");c=0;for(var x=g.length;c<x;c++){var u=g[c].selectionId,A=m.find("#bookMakerSelection_"+DataBase.bookMakerMarkets.getSelectionKey(a,b,u));if(0!=A.length){var y=A.find("#before"),z=A.find("#after");if(h.exposureBeforeBet){var B=h.exposureBeforeBet.betSelections;d=0;d=null==B[u]?B[0].minExposure:B[u].minExposure;y.removeClass();0<=parseFloat(d)?y.addClass("win"):y.addClass("lose");y.html(CurrencyUtil.formatter(d,t));y.show()}else y.hide();
if(h.exposureAfterBet){var C=h.exposureAfterBet.betSelections;d=0;d=null==C[u]?C[0].minExposure:C[u].minExposure;z.removeClass();0<=parseFloat(d)?z.addClass("to-win"):z.addClass("to-lose");z.html(CurrencyUtil.formatter(d,t));z.show()}else z.hide()}}}v(a,b)}}}catch(D){Trace.printStackTrace(D)}};BookMakerBetHandler.updateExposure=function(a){a=BookMakerMarketHandler.isViewMultiMarket()?"#bookMakerTable_"+a:"#overWrap";var b=$j(a),c=b.find("[id^=bookMakerMarket_]:visible");if(0!=c.length)for(var d=0,
e=c.length;d<e;d++){var g=b.find(c[d]);a=g.prop("eventId");g=g.prop("marketId");if(null==a||null==g)break;BookMakerBetHandler.getExposure(a,g)}}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.bookMakerBet={};var w=new HashMap;DataBase.bookMakerBet.add=function(f,p,n,q,r,v,a,b){f={eventType:f,eventId:p,marketId:n,selectionId:q,sideType:r,odds:v,eventName:a,marketName:b};p=DataBase.bookMakerBet.generateKey(p,n,q,r);w.put(p,f);return f};DataBase.bookMakerBet.generateKey=function(f,p,n,q){return f+"_"+p+"_"+n+"_"+q};DataBase.bookMakerBet.get=function(f,p,n,q){f=DataBase.bookMakerBet.generateKey(f,p,n,q);return w.get(f)};DataBase.bookMakerBet.remove=function(f,p,n,q){f=
DataBase.bookMakerBet.generateKey(f,p,n,q);return w.remove(f)};DataBase.bookMakerBet.queryAll=function(){return w.values()};DataBase.bookMakerBet.clear=function(){w.clear()};DataBase.bookMakerBet.clearByEventId=function(f){$j.each(w.values(),function(p,n){f==n.eventId&&DataBase.bookMakerBet.remove(n.eventId,n.marketId,n.selectionId,n.sideType)})};DataBase.bookMakerBet.updateStake=function(f,p,n,q,r){var v=!1;f=DataBase.bookMakerBet.get(f,p,n,q);if(null!=f){if(null==f.stake||null!=f.stake&&f.stake!=
r)v=!0;f.stake=r;return v}};DataBase.bookMakerBet.updateOdds=function(f,p,n,q,r){var v=!1;f=DataBase.bookMakerBet.get(f,p,n,q);if(null!=f){if(null==f.odds||null!=f.odds&&f.odds!=r)v=!0;f.odds=r;return v}};DataBase.bookMakerBet.getForBet=function(f,p,n,q){f=DataBase.bookMakerBet.get(f,p,n,q);return{eventType:f.eventType,eventId:f.eventId,marketId:f.marketId,selectionId:f.selectionId,sideType:f.sideType,odds:f.odds,stake:f.stake}};DataBase.bookMakerBet.getByMarketId=function(f,p){var n=[];$j.each(w.values(),
function(q,r){f==r.eventId&&p==r.marketId&&n.push(r)});return n}})();

