"undefined"==typeof CoinHandler&&(CoinHandler={});
(function(){function n(a){var b=a.which;KeyEventUtils.isNumberKey(a)||KeyEventUtils.isBackspaceKey(b)||KeyEventUtils.isDeleteKey(b)||KeyEventUtils.isArrowKey(b)||KeyEventUtils.isTabKey(b)||KeyEventUtils.isEnterKey(b)||WindowEventUtil.stopEvent(a)}function k(){m();if("null"==PageConfig.customizeStake||8!=PageConfig.customizeStake.split(",").length)for(var a=1;8>=a;a++)l.push(CoinType.getInstanceOf(PageConfig.playerCurrency,a).amounts);else l=PageConfig.customizeStake.split(",");CoinHandler.coinClean();
CoinHandler.coinInit()}function r(a){$j.ajax({type:"POST",dataType:"JSON",url:"/member/playerService/setCustomizeStake",data:{newCustomizeStake:a},success:function(b){b?b.error?(NoticeHandler.error(b.error),k()):"SUCCESS"==b.result&&null!=b.customizeStake&&(PageConfig.customizeStake=b.customizeStake,k()):k()},error:function(b){Trace.log(b);k()}})}function t(a){for(var b=a.find("#stakeSet"),c=a.find("#editCustomizeStakeList"),e=c.find("[id^=stakeEdit_]"),d=0;d<e.length;d++)a.find(e[d]).val(l[d]);c.show();
b.hide();a=$j("#coinList");a.find("#closeSet").addClass("disable");a.find("#coinSave").addClass("disable")}function u(a){a.find("#stakeSet");for(var b=a.find("#editCustomizeStakeList").find("[id^=stakeEdit_]"),c=[],e=0;e<b.length;e++){var d=a.find(b[e]).val();7<d.length?NoticeHandler.error("CustomizeStake can not more than 7 bits"):!MathUtil.isNumeric(d,!1,!1)||isNaN(d)?NoticeHandler.error("[ "+d+" ] is illegal"):d<PageConfig.minBet?(d=CurrencyType.getInstanceOf(PageConfig.playerCurrency),NoticeHandler.error("Stake setting can not be less than MinBet "+
PageConfig.minBet+" "+d.name)):c.push(d)}8!=c.length?m():(c.sort(function(g,v){return g>v}),c.toString()==PageConfig.customizeStake?m():r(c.toString()))}function m(){var a=$j("#coinList");a.find("#editCustomizeStakeList").hide();a.find("#stakeSet").show();a=$j("#coinList");a.find("#closeSet").removeClass("disable");a.find("#coinSave").removeClass("disable")}var f=[],h=0,p=[],q=0,l=[];CoinHandler.init=function(){k();JsCache.get("[id^=coin_]").click(function(){CoinHandler.coinListClick(this)});JsCache.get("#slipSet").click(function(b){if("undefined"==
typeof LoginHandler||LoginHandler.userIsLogin())p=f,q=h,JsCache.get("#set_pop").toggle(),$j(document).click(function(){CoinHandler.coinSelectCancel();TopMenuHandler.appendAllAcceptAnyOdds();JsCache.get("#set_pop").hide();$j(document).unbind("click")}),JsCache.get("#set_pop").is(":visible")&&PageConfig.hasAccount&&JsCache.get("#account_pop").hide(),b.stopPropagation()});JsCache.get("#set_pop").click(function(b){b.stopPropagation()});JsCache.get("#closeSet").click(function(){JsCache.get("#closeSet").hasClass("disable")||
(CoinHandler.coinSelectCancel(),JsCache.get("#set_pop").hide())});JsCache.get("#coinSave").click(function(){JsCache.get("#coinSave").hasClass("disable")||CoinHandler.coinSelectSubmit(this)});var a=$j("#coinList");a.find("#edit").unbind("click").click(function(){$j(document).keydown(function(b){KeyEventUtils.isEnterKey(b.which)&&(a.find("#ok").click(),$j(document).unbind("keydown"))});t(a)});a.find("#ok").unbind("click").click(function(){u(a)});a.find("[id^=stakeEdit_]").unbind("click").click(function(){a.find(this).select()});
a.find("[id^=stakeEdit_]").keydown(n);a.find("#userCoin").keydown(n)};CoinHandler.setCoinPreference=function(a,b){$j.ajax({type:"POST",dataType:"JSON",url:"/member/playerService/setCoinPreference",data:{newCoinPreference:a,newUserCoin:b}});PageConfig.coinPreference=a;PageConfig.userCoin=b};CoinHandler.coinClean=function(){for(var a=JsCache.get("#coinList"),b=1;8>=b;b++)a.find("#coin_"+b).removeClass("select");a.find("#userCoin").val("")};CoinHandler.coinInit=function(){f=[];h=0;var a=JsCache.get("#coinList"),
b=PageConfig.coinPreference.split(",");$j.each(b,function(c,e){-1==ArrayUtil.indexOf(f,parseInt(e))&&f.push(parseInt(e))});""!=PageConfig.userCoin&&0!=PageConfig.userCoin?(h=PageConfig.userCoin,a.find("#userCoin").val(h)):a.find("#userCoin").val("");for(b=0;b<f.length;b++)a.find("#coin_"+f[b].toString()).addClass("select");for(b=1;8>=b;b++)a.find("#coin_"+b).html(l[b-1]);CoinHandler.buildStakePopupList()};CoinHandler.buildStakePopupList=function(){for(var a=$j("[id^=stakePopupList]"),b=0;b<f.length;b++){var c=
l[f[b]-1];a.find("#selectStake_"+(b+1)).attr("stake",c).html(c)}5==f.length&&""!=h.toString()&&a.find("#selectStake_6").attr("stake",h).html(h)};CoinHandler.clickStakePopupList=function(a,b,c){var e="[id=stakePopupList][bet="+(a.attr("id")+"]");e=b.find(e);0==e.length&&(e=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),e.attr("bet",a.attr("id")),e.attr("stakePopupListType","extended"),e.show(),e.find("[id^=selectStake_]").mousedown(function(){if(!a.find("#inputStake").hasClass("disable")){var d=
CoinHandler.clickSelectStake(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this,a),g=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(g));1==d&&BetHandler.getWinLoss(a.attr("eventId"),a.attr("marketId"));c?TxnHandler.commonEvent(a):BetHandler.oddsAndStakeCheck(a)}}));a.find("#profitLiability").after(e);e.fadeIn();BetHandler.hideStakeTipsPopup(a)};CoinHandler.showQuickBetCoin=function(a){var b=$j("#betList"),
c=a.find("[id=stakePopupList][quickBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),c.attr("quickBetBoard",a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){1==CoinHandler.clickSelectStake(a.attr("eventId"),a.attr("marketId"),a.attr("selectionKey"),a.attr("sideType"),this,a)&&BetHandler.getWinLoss(a.attr("eventId"),a.attr("marketId"));(BrowserUtil.isEdge()||BrowserUtil.isIE())&&BetHandler.oddsAndStakeCheck(a)}));
a.find("#placeBet").after(c);c.fadeIn()};CoinHandler.showFancyBetCoin=function(a){var b=$j("#betList"),c=a.find("[id=stakePopupList][fancyBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),c.attr("fancyBetBoard",a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){var e=$j(this),d=a.find("#inputStake");parseInt(d.val());e=parseInt(e.attr("stake"));d.val(e);d=DataBase.fancyBet.updateStake(a.prop("eventId"),
a.prop("marketId"),a.prop("sideType"),e);CoinHandler.hideStakePopupList();1==d&&FancyBetHandler.getExposure(a.prop("eventId"),a.prop("marketId"));FancyBetHandler.eventCalculate(a,a.prop("eventId"),a.prop("marketId"),a.prop("sideType"),d)}));a.find("#placeBet").parent().after(c);c.fadeIn()};CoinHandler.showFeedingSiteBetCoin=function(a){var b=$j("#betList"),c=a.find("[id=stakePopupList][feedingSiteBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),
c.attr("feedingSiteBetBoard",a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){var e=$j(this),d=a.find("#inputStake");parseInt(d.val());e=parseInt(e.attr("stake"));d.val(e);d=DataBase.feedingSiteBet.updateStake(a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),e);CoinHandler.hideStakePopupList();FeedingSiteBetHandler.eventCalculate(a,a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),d)}));a.find("#placeBet").parent().after(c);
c.fadeIn()};CoinHandler.showSportsBookBetCoin=function(a){var b=$j("#betList"),c=a.find("[id=stakePopupList][sportsBookBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),c.attr("sportsBookBetBoard",a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){var e=$j(this),d=a.find("#inputStake");parseInt(d.val());e=parseInt(e.attr("stake"));d.val(e);d=DataBase.sportsBookBet.updateStake(a.prop("apiSiteType"),
a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),e);CoinHandler.hideStakePopupList();SportsBookBetHandler.eventCalculate(a,a.prop("apiSiteType"),a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),d)}));a.find("#placeBet").parent().after(c);c.fadeIn()};CoinHandler.showBookMakerBetCoin=function(a){var b=$j("#betList"),c=a.find("[id=stakePopupList][bookMakerBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),c.attr("bookMakerBetBoard",
a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){var e=$j(this),d=a.find("#inputStake");parseInt(d.val());e=parseInt(e.attr("stake"));d.val(e);d=DataBase.bookMakerBet.updateStake(a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),a.prop("sideType"),e);CoinHandler.hideStakePopupList();BookMakerBetHandler.eventCalculate(a,a.prop("eventId"),a.prop("marketId"),a.prop("selectionId"),a.prop("sideType"),d)}));a.find("#placeBet").parent().after(c);
c.fadeIn()};CoinHandler.showFinancialBetCoin=function(a){var b=$j("#betList"),c=a.find("[id=stakePopupList][financialBetBoard="+a.attr("id")+"]");0==c.length&&(c=b.find("[id=stakePopupList][stakePopupListType=template]").clone(),c.attr("financialBetBoard",a.attr("id")),c.attr("stakePopupListType","extended"),c.find("[id^=selectStake_]").mousedown(function(){var e=$j(this),d=a.find("#inputStake");parseInt(d.val());e=parseInt(e.attr("stake"));d.val(e);d=DataBase.financialBet.updateStake(a.prop("apiSite"),
a.prop("eventId"),a.prop("marketId"),a.prop("sideType"),e);CoinHandler.hideStakePopupList();FinancialBetHandler.eventCalculate(a,a.prop("apiSite"),a.prop("eventId"),a.prop("marketId"),a.prop("sideType"),d)}));a.find("#placeBet").parent().after(c);c.fadeIn()};CoinHandler.hideStakePopupList=function(){};CoinHandler.clickSelectStake=function(a,b,c,e,d,g){d=$j(d);g=g.find("#inputStake");parseInt(g.val());d=parseInt(d.attr("stake"));g.val(d);a=DataBase.bet.updateStake(a,b,c,e,d);CoinHandler.hideStakePopupList();
BetHandler.calculateProfitAndLiability();return a};CoinHandler.coinListClick=function(a){var b=a.id;a=$j(a);var c=parseInt(b.replace("coin_","")),e=JsCache.get("#coinList");a.hasClass("select")?(e.find("#"+b).removeClass("select"),f=$j.grep(f,function(d){return d!=c})):(6<=f.length&&(b=f[0],f=f.slice(1,6),e.find("#coin_"+b).removeClass("select")),-1==ArrayUtil.indexOf(f,c)&&(a.addClass("select"),f.push(c),f.sort(function(d,g){return d-g})))};CoinHandler.coinSelectSubmit=function(a){var b=JsCache.get("#userCoin");
a=0;if(6==parseInt(f.length)||5==parseInt(f.length)&&0!=b.val()){b=b.val();if(""!=b.toString()&&0!=b){a=parseFloat(PageConfig.minBet);if(0>b){NoticeHandler.error("DefaultStake can not less than 0");return}if(9999999<b){NoticeHandler.error("DefaultStake can not more than 7 bits");return}if(!MathUtil.isNumeric(b,!1,!1)||!MathUtil.isPositive(b)){NoticeHandler.error("DefaultStake is illegal");return}b>a&&(a=b)}CoinHandler.setCoinPreference(f.toString(),a);JsCache.get("#set_pop").hide();k()}else NoticeHandler.error(I18N.get("msg.member.coin.amoutsLess"))};
CoinHandler.coinSelectCancel=function(a){f=p;h=q;k();1==a&&JsCache.get("#coinList").hide()}})();

