"undefined"==typeof EventHandler&&(EventHandler={});
(function(){function t(a){try{var b=JsCache.get("#eventBoard").find("[id^=highLightEvent_]");0<b.length&&b.each(function(){var e=$j(this),f=DataBase.events.get(e.attr("eventType"),e.attr("eventId"));if(null!=f&&null!=f.isInPlay&&1==f.isInPlay){for(var g=null,h=0;h<f.markets.length;h++)if(1==f.markets[h].isHighLight){g=f.markets[h];break}null!=g&&1==g.inPlay&&EventHandler.updateEventCountdown(f,g,e)}});var c=$j("#centerColumn");c.hasClass("inplay")&&c.find("[id^=inPlayEventType_]").each(function(){$j(this).find("#inplayGameList").find("dl").each(function(){var e=
$j(this),f=DataBase.events.get(e.attr("eventType"),e.attr("eventId"));if(null!=f&&null!=f.isInPlay&&1==f.isInPlay){for(var g=null,h=0;h<f.markets.length;h++)if(1==f.markets[h].isHighLight){g=f.markets[h];break}null!=g&&EventHandler.updateEventCountdown(f,g,e)}})})}catch(e){Trace.printStackTrace(e)}finally{a.check(),TaskExecuter.execute()}}function n(a){if("#Home"!=location.hash&&-1==PageConfig.highlightEventType||-1!=location.href.indexOf("#eventId#")||-1!=location.href.indexOf("#marketId#"))a.check(),
TaskExecuter.execute();else{var b=PageConfig.highlightEventType,c=EventHandler.eventTsMap.get(b);null==c&&(c=-1,EventHandler.eventTsMap.put(b,c));var e=EventHandler.marketTsMap.get(b);null==e&&(e=-1,EventHandler.marketTsMap.put(b,e));var f=EventHandler.selectionTsMap.get(b);null==f&&(f=-1,EventHandler.selectionTsMap.put(b,f));var g="";JsCache.get("#eventBoard").find("[id^=highLightEvent_]").each(function(){g=0==g.length?g+this.id.replace("highLightEvent_",""):g+(","+this.id.replace("highLightEvent_",
""))});""!=g&&JsCache.get("#noDataDiv").hide();b=(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsWithMarketPath;var h=PageConfig.highlightCurrentPage,m=$j("#viewType").val();$j.ajax({type:"POST",dataType:"JSON",url:b,data:{eventType:PageConfig.highlightEventType,competitionId:-1,eventTs:c,marketTs:e,selectionTs:f,collectEventIds:g,pageNumber:h,viewType:m,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},
success:function(k){try{JsCache.get("#loading").hide(),k.eventTs>c&&EventHandler.eventTsMap.put(k.eventType,k.eventTs),k.marketTs>e&&EventHandler.marketTsMap.put(k.eventType,k.marketTs),k.selectionTs>f&&EventHandler.selectionTsMap.put(k.eventType,k.selectionTs),0<k.events.length&&JsCache.get("#noDataDiv").hide(),DataBase.events.update(k.events),EventHandler.updateEvents(k.gameProductStatus,!1)}catch(d){Trace.printStackTrace(d)}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&
null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);JsCache.get("#loading").hide();a.check();TaskExecuter.execute()}})}}EventHandler.getEventsTask=null;EventHandler.initGetEventsTask=function(){EventHandler.getEventsTask=TaskExecuter.createTask(PageConfig.getEventsTaskCycleTime,0,function(){n(this)});EventHandler.getEventsTask.run();TaskExecuter.execute()};EventHandler.updateCountdownTask=null;EventHandler.initUpdateCountdownTask=
function(){EventHandler.updateCountdownTask=TaskExecuter.createTask(PageConfig.updateCountdownCycleTime,0,function(){t(this)});EventHandler.updateCountdownTask.run();TaskExecuter.execute()};EventHandler.eventTsMap=new TreeMap;EventHandler.marketTsMap=new TreeMap;EventHandler.selectionTsMap=new TreeMap;EventHandler.checkEvents=function(a,b,c,e){if(!isNaN(a)&&!isNaN(b)&&(null==DataBase.events.get(a,b)||c)){var f=this;$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=
QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsWithMarketPath,data:{eventType:a,eventTs:-1,marketTs:-1,selectionTs:-1,eventId:b,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(g){try{0<g.events.length&&DataBase.events.update(g.events)}catch(h){Trace.printStackTrace(h)}finally{null!=e&&"function"===typeof e&&e.call(f)}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&
(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}})}};EventHandler.updateDateTimeInfo=function(a,b){var c=new Date,e=DateUtil.format(c,"yyyy-MM-dd");c.setDate(c.getDate()+1);c=DateUtil.format(c,"yyyy-MM-dd");a=a.marketTime.split("+")[0];a=a.replace("T"," ");a=a.replace(":00.000","");0<=a.indexOf(e)?a=a.replace(e," "):0<=a.indexOf(c)&&(a=a.replace(c,"Tomorrow "));b.find("#dateTimeInfo").html(a)};EventHandler.updateEvents=function(a,b){if(-1==PageConfig.selectEventId&&(-1!=
PageConfig.highlightEventType||-1!=PageConfig.selectEventType)){var c=null,e=null,f=-1;-1==PageConfig.selectEventType||-1!=PageConfig.highlightEventType?(f=PageConfig.highlightEventType,c=DataBase.events.queryAll(PageConfig.highlightEventType)):(f=PageConfig.selectEventType,c=DataBase.events.queryAll(PageConfig.selectEventType));if(null!=c){var g=0;$j("#moreEventLink").hide();if(PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW){var h=$j("#viewType").val();PageConfig.ENABLE_OCER_NAVIGATION||c.sort(EventHandler.sortEventsByViewType)}else PageConfig.highlightEventType==
EventType.SOCCER.unique()&&PageConfig.highlightEventType==EventType.E_SOCCER.unique()||c.sort(EventHandler.sortEvents);var m=b||!PageConfig.ENABLE_DESKTOP_HIGHLIGHT_PAGINATION;b=[];for(var k=0;k<c.length;k++){var d=c[k];if(d.isManualEvent&&d.isManualEventClosed)$j("#highLightEvent_"+d.id).remove(),b.push(k);else if(0<(d.status&16)||0<(d.status&48))b.push(k);else if(CompetitionUtils.isCloseSite(d.competitionCloseSite,PageConfig.webSiteType)||EventUtils.isCloseSite(d.closeSite,PageConfig.webSiteType))d=
$j("#highLightEvent_"+d.id),1==d.length&&d.remove(),b.push(k);else if(0<d.markets.length&&3==d.markets[0].status)1==$j("#highLightEvent_"+d.id).length&&$j("#highLightEvent_"+d.id).remove(),b.push(k);else if(0==d.markets.length)b.push(k);else if(0!=d.markets[0].selections.length||d.isManualEvent){for(var p=null,l=0;l<d.markets.length;l++)if(1==d.markets[l].isHighLight||("EXTRA_TIME"==d.markets[l].marketType||"SUPER_OVER"==d.markets[l].marketType)&&!MarketUtil.isCloseSite(d.markets[l].closeSite,PageConfig.webSiteType)){p=
d.markets[l];break}if(null==p)b.push(k);else if(MarketUtil.isClosed(p.status)||MarketUtil.isCloseSite(p.closeSite,PageConfig.webSiteType))$j("#highLightEvent_"+d.id).remove(),b.push(k);else{PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&"competitionName"===h&&(e=EventHandler.getCompetitionName(d.competitionName),0==$j("#eventBoard").find("#"+e).length?(l=StringUtil.isEmpty(d.competitionName)?"Others":d.competitionName,m&&($j("#eventBoard").append('<h3 id="'+e+'" class="leagueTitle competition-expand" priority="'+
d.priority+'" ><a>'+l+"</a></h3>"),$j("#eventBoard #"+e).after('<div id="'+e+'Board" class="leagueBoard"></div>'))):parseInt($j("#eventBoard #"+e).attr("priority"))!=d.priority&&$j("#eventBoard #"+e).attr("priority",d.priority));l=null;if(0==$j("#highLightEvent_"+d.id).length){l=$j("#eventTemplate").clone();l.attr("competitionName",e);(function(x,z){return function(){NavigationHandler.navigationIds=[];location.href=PageConfig.fullMarketPath+"?eventType="+x.eventType+"&eventId="+x.id+"&marketId="+
z.marketId}})(d,p);var q=PageConfig.fullMarketPath+"?eventType="+d.eventType+"&eventId="+d.id+"&marketId="+p.marketId;l.find("#eventInfo").find("#vsName").attr("href",q);l.attr("id","highLightEvent_"+d.id);MultiMarketsHandler.bindPinEvent(l,d.eventType,d.id,p.marketId);MultiMarketsHandler.checkIsMultiMarket(l.find("#multiMarketPin"),d.eventType,d.id,p.marketId)}else l=$j("#highLightEvent_"+d.id);PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&EventHighlightUtil.displayAllBoardTotalMatched(d,p);HeadToHeadHandler.displayH2HIconButton(d,
l,"hightLight");FancyBetMarketHandler.isEnableFancyBet()&&d.hasFancyBetMarkets?(l.find("#fancyBetIcon").show().css("display","inline-flex"),d.hasInPlayFancyBetMarkets?l.find(".game-fancy").addClass("in-play"):l.find(".game-fancy").removeClass("in-play")):l.find("#fancyBetIcon").hide();PageConfig.isEnableBookMaker&&d.hasBookMakerMarkets?(q=l.find("#bookMakerIcon"),q.show().css("display","inline-flex"),d.hasInPlayBookMakerMarkets?q.addClass("in-play"):q.removeClass("in-play")):l.find("#bookMakerIcon").hide();
SportsBookEventHandler.isEnableSportsBookBet()&&d.hasSportsBookMarkets?l.find("#sportsBookIcon_"+ApiSiteType.SPORTRADAR.unique()).show().css("display","inline-flex"):l.find("#sportsBookIcon_"+ApiSiteType.SPORTRADAR.unique()).hide();1==d.isElectronic&&l.find("#sportsBookEIcon_"+d.eventType).show().css("display","inline-flex");null!=d.streamingChannel&&0!=d.streamingChannel.length&&0!=d.streamingChannel?l.find("#streamingIcon").show().css("display","inline-flex"):l.find("#streamingIcon").hide();var r=
d.name;if(EventType.getInstanceOf(d.eventType).isTwoTeamsEvent()){r=" v ";0<d.name.indexOf(" vs ")?r=" vs ":0<d.name.indexOf(" @ ")&&(r=" @ ");var w=d.name.split(r);if(1==w.length){b.push(k);continue}for(var v=q="",u=0;u<p.selections.length;u++){var y=p.selections[u];1==y.sortPriority?q=y.runnerName:2==y.sortPriority&&(v=y.runnerName);if(""!=q&&""!=v)break}""!=q&&""!=v?r=q+"<span>"+r.trim()+"</span>"+v:(q=w[0],v=w[1],r=w[0]+"<span>"+r.trim()+"</span>"+w[1]);1==p.inPlay&&(r=EventHandler.getScoreInfo(d,
q,v),r=q+r+v)}l.attr("eventType",d.eventType);l.attr("eventId",d.id);l.attr("marketId",p.marketId);l.attr("eventName",d.name);l.attr("openDate",d.openDate);l.attr("openDateTime",d.openDateTime);l.attr("totalMatched",p.totalMatched);l.attr("elapsedTime",d.elapsedTime);l.attr("inPlay",p.inPlay);l.attr("priority",d.priority);l.attr("boardType","highlight");l.find("#vsName").html(r);null!=p.inPlay&&1==p.inPlay&&(l.find("#playIcon").removeClass("icon-no_play"),l.find("#playIcon").addClass("icon-in_play"));
null!=p.inPlay&&1==p.inPlay?EventHandler.updateEventCountdown(d,p,l):EventHandler.updateDateTimeInfo(p,l);0==$j("#highLightEvent_"+d.id).length&&EventHandler.bindEvent(l);EventHighlightUtil.displayAllBoardSelections(d,p,a);0==$j("#highLightEvent_"+d.id).length&&(PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&"competitionName"===h?(e=EventHandler.getCompetitionName(d.competitionName),m&&$j("#eventBoard #"+e+"Board").append(l.css("display","flex"))):m&&$j("#eventBoard").append(l.css("display","flex")),
EventType.getInstanceOf(d.eventType).hasDraw()?($j("#gameHighlightWrap").addClass("col3"),l.find(".col-draw").show(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?$j("#gameHighlightWrap .col-game").css("width",""):($j("#eventBoard dt").css("width","calc(64.1% - 41px)"),$j("#gameHighlightWrap .col-game").css("width","calc(64.1% - 41px)"))):($j("#gameHighlightWrap").removeClass("col3"),l.find(".col-draw").hide(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?($j("#eventBoard dt").css("width","calc(64.1% - 41px)"),
$j("#gameHighlightWrap .col-game").css("width","calc(64.1% - 41px)")):$j("#gameHighlightWrap .col-game").css("width","")));g++;EventHighlightUtil.displayAllBoardMarketShowDisabled(d,p)}}else b.push(k)}EventHandler.bindToExpand($j("#eventBoard"));k=$j("#gameHighlightWrap");-1==f||EventType.getInstanceOf(f).hasDraw()?(k.addClass("col3"),k.find(".col-draw").show(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?$j("#gameHighlightWrap .col-game").css("width",""):($j("#eventBoard dt").css("width","calc(64.1% - 41px)"),
$j("#gameHighlightWrap .col-game").css("width","calc(64.1% - 41px)"))):(k.removeClass("col3"),k.find(".col-draw").hide(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?($j("#eventBoard dt").css("width","calc(64.1% - 41px)"),$j("#gameHighlightWrap .col-game").css("width","calc(64.1% - 41px)")):$j("#gameHighlightWrap .col-game").css("width",""));BetHandler.addSelectClass();f=$j("#eventBoard");a=f.find("[id^=highLightEvent_]");k=$j("#noDataDiv");0==a.length?k.show():k.hide();if(PageConfig.highlightEventType!=
EventType.SOCCER.unique()&&PageConfig.highlightEventType!=EventType.E_SOCCER.unique()){for(u in b)k=b[u],c.splice(k,1);PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW||(c=c.map(function(x){return x.id}),u=a.length-1,b=f.find(a[u]),c.length==a.length&&ArrayUtil.indexOf(c,parseInt(b.attr("eventId")))!=u&&(a.sort(EventHandler.sortEventsOnUI),f.append(a)))}PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&EventHandler.reSortEventBoard()}}};EventHandler.bindEvent=a=>{a.find("#btnBack").click(function(){"true"==PageConfig.ENABLE_QUICK_BET&&
0==PageConfig.isOneClickBet?QuickBetUtil.appendBoard(this,a,SideType.Back.unique()):BetHandler.clickBtn(this,!1)});a.find("#btnLay").click(function(){"true"==PageConfig.ENABLE_QUICK_BET&&0==PageConfig.isOneClickBet?QuickBetUtil.appendBoard(this,a,SideType.Lay.unique()):BetHandler.clickBtn(this,!1)})};EventHandler.getScoreInfo=function(a,b,c){var e="<span>v</span>";0<a.name.indexOf(" vs ")?e="<span>vs</span>":0<a.name.indexOf(" @ ")&&(e="<span>@</span>");if(null!=a.scores){var f=JSON.parse(a.scores),
g=f.home;f=f.away;if(a.eventType==EventType.TENNIS.value){if(0<g.sets||0<g.games||0<f.games||0<f.sets)e='<span class="in_play">('+g.sets+") "+g.games+" - "+f.games+" ("+f.sets+")</span>"}else if(a.eventType==EventType.SOCCER.value||a.eventType==EventType.E_SOCCER.value||a.eventType==EventType.BASKETBALL.value){var h=0,m=0;if(a.eventType==EventType.BASKETBALL.value)null!=b&&null!=c&&b.trim()==g.name.trim()&&c.trim()==f.name.trim()?(h=g.score,m=f.score):(h=f.score,m=g.score);else if(a.eventType==EventType.SOCCER.value||
a.eventType==EventType.E_SOCCER.value)null!=b&&null!=c&&b.trim()==f.name.trim()&&c.trim()==g.name.trim()?(h=f.score,m=g.score):(h=g.score,m=f.score);if(0<=g.score||0<=f.score)e='<span class="in_play">'+h+" - "+m+"</span>"}}return e};EventHandler.getEventDisplayName=function(a,b,c){var e=a.name,f=" v ";0<e.indexOf(" vs ")?f=" vs ":0<e.indexOf(" @ ")&&(f=" @ ");e=e.split(f);if(1==e.length)return a.name.trim();var g="",h="";f="<span>"+f.trim()+"</span>";if(EventType.getInstanceOf(a.eventType).isTwoTeamsEvent()){for(var m=
0;m<b.selections.length;m++){var k=b.selections[m];1==k.sortPriority?g=k.runnerName:2==k.sortPriority&&(h=k.runnerName)}1==b.inPlay&&(f=EventHandler.getScoreInfo(a))}""==g&&(g=e[0]);""==h&&(h=e[1]);c.attr("firstTeam",g);c.attr("secondTeam",h);return g+f+h};EventHandler.sortEventsOnUI=function(a,b){a=$j(a);b=$j(b);var c=a.attr("eventName"),e=b.attr("eventName"),f=a.attr("elapsedTime"),g=b.attr("elapsedTime");f=f>g?-1:f<g?1:0;g=a.attr("openDateTime");var h=b.attr("openDateTime");g=g>h?1:g<h?-1:0;if(1!=
a.attr("inPlay")||1!=b.attr("inPlay")){if(1==a.attr("inPlay"))return-1;if(1==b.attr("inPlay"))return 1}a=c.localeCompare(e);return 0==f?0==g?a:g:f};EventHandler.sortEvents=function(a,b){var c=a.name,e=b.name,f=a.elapsedTime,g=b.elapsedTime;f=f>g?-1:f<g?1:0;g=a.openDateTime;var h=b.openDateTime;g=g>h?1:g<h?-1:0;a=0==a.markets.length?0:a.markets[0].inPlay;b=0==b.markets.length?0:b.markets[0].inPlay;if(1!=a||1!=b){if(1==a)return-1;if(1==b)return 1}c=c.localeCompare(e);return 0==f?0==g?c:g:f};EventHandler.updateEventCountdown=
function(a,b,c){var e=(new Date).getTime();0<=a.secondsToStart||null!=b.inPlay&&1==b.inPlay?null==b.inPlay||0==b.inPlay?a="Starting soon":EventUtils.isClose(a.status)&&EventUtils.isEnd(a.status)?(null==a.inPlayStatus&&(a.inPlayStatus="FT"),a='<span class="in_play">'+a.inPlayStatus+"</span>"):(null==a.inPlayStatus&&(a.inPlayStatus="In-Play"),a=0<a.elapsedTime?"HT"==a.inPlayStatus?'<span class="in_play">'+a.inPlayStatus+"'</span>":'<span class="in_play">'+a.inPlayStatus+" "+a.elapsedTime+"'</span>":
'<span class="in_play">'+a.inPlayStatus+"</span>"):(b=0,null==a.secondsPassed?(a.secondsPassed=0,a.uiTs=e):(b=(e-a.uiTs)/1E3,a.secondsPassed=b),a=(1+(b+a.secondsToStart)/60*-1+"").split(".")[0],a="0"==a?"Starting soon":"Starting in "+a+"' ");c.find("#dateTimeInfo").html(a);"Starting soon"==a?c.find("#dateTimeInfo").addClass("game-list-soon").removeClass("game-list-time"):c.find("#dateTimeInfo").addClass("game-list-time").removeClass("game-list-soon")};EventHandler.bindToExpand=function(a){PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&
a.find(".leagueTitle").unbind("click").click(function(){$j(this).hasClass("competition-expand")?($j(this).removeClass("competition-expand").addClass("competition-collapse"),$j('dl[competitionname="'+this.id).hide()):($j(this).removeClass("competition-collapse").addClass("competition-expand"),$j('dl[competitionname="'+this.id).show())})};EventHandler.sortEventsByViewType=function(a,b){let c=$j("#viewType").val(),e="asc"===$j("#viewType").find(":selected").attr("orderby")?1:-1;if("openDateTime"===c)return("asc"===
$j("#viewType").find(":selected").attr("inplay")?1:-1)*((0==a.markets.length?0:a.markets[0].inPlay)-(0==b.markets.length?0:b.markets[0].inPlay))||e*(a.openDateTime-b.openDateTime);if("totalMatched"===c){if(null!=a.markets[0]&&null!=b.markets[0])return e*(a.markets[0].totalMatched-b.markets[0].totalMatched)}else if("competitionName"===c)return("asc"===$j("#viewType").find(":selected").attr("priority")?1:-1)*(a.priority-b.priority)||e*a.competitionName.localeCompare(b.competitionName);return 0};EventHandler.reSortEventBoard=
function(){if(!PageConfig.ENABLE_OCER_NAVIGATION){let c=$j("#viewType").val(),e="asc"===$j("#viewType").find(":selected").attr("orderby")?1:-1,f="asc"===$j("#viewType").find(":selected").attr("inplay")?1:-1,g="asc"===$j("#viewType").find(":selected").attr("priority")?1:-1;var a=$j("#eventBoard").toArray().map(function(h,m){return h}).reduce(function(h,m){"competitionName"===c&&$j(m).find(".leagueTitle").toArray().forEach(function(k,d){h.leagueTitleAttr.push($j(k).attr("id"));h.priorityAttr.push(parseInt($j(k).attr("priority")))});
"openDateTime"===c&&$j(m).find("[id^=highLightEvent_]").toArray().forEach(function(k,d){h.openDateTimeAttr.push(parseInt($j(k).attr("openDateTime")));h.inPlayAttr.push(parseInt($j(k).attr("inPlay")))});"totalMatched"===c&&$j(m).find("[id^=highLightEvent_]").toArray().forEach(function(k,d){h.totalMatchedAttr.push(parseInt($j(k).attr("totalMatched")))});return h},{leagueTitleAttr:[],priorityAttr:[],openDateTimeAttr:[],totalMatchedAttr:[],inPlayAttr:[]});if("competitionName"==c){var b=EventHandler.isSorted(a.leagueTitleAttr,
$j("#viewType").find(":selected").attr("orderby"));EventHandler.isSorted(a.priorityAttr,$j("#viewType").find(":selected").attr("priority"))&&b||(a=$j("#eventBoard").find(".leagueTitle").sort(function(h,m){let k=parseInt($j(h).attr("priority")),d=parseInt($j(m).attr("priority"));return g*(k-d)||e*h.id.localeCompare(m.id)}),$j("#eventBoard").find(".leagueTitle").detach(),$j("#eventBoard").append(a),$j("#eventBoard").find(".leagueBoard").toArray().forEach(function(h,m){m=$j(h).attr("id").replace("Board",
"");$j("#eventBoard").find(h).detach().insertAfter("#"+m)}))}else"openDateTime"===c?(b=EventHandler.isSorted(a.inPlayAttr,$j("#viewType").find(":selected").attr("inplay")),a=EventHandler.isSorted(a.openDateTimeAttr,$j("#viewType").find(":selected").attr("orderby")),b&&a||(a=$j("#eventBoard").find("[id^=highLightEvent_]").sort(function(h,m){let k=parseInt($j(h).attr(c)),d=parseInt($j(m).attr(c));h=parseInt($j(h).attr("inplay"));m=parseInt($j(m).attr("inplay"));return f*(h-m)||e*(k-d)}),$j("#eventBoard").find("[id^=highLightEvent_]").detach(),
$j("#eventBoard").append(a))):"totalMatched"!==c||EventHandler.isSorted(a.totalMatchedAttr,$j("#viewType").find(":selected").attr("orderby"))||(a=$j("#eventBoard").find("[id^=highLightEvent_]").sort(function(h,m){h=parseInt($j(h).attr(c));m=parseInt($j(m).attr(c));return e*(h-m)}),$j("#eventBoard").find("[id^=highLightEvent_]").detach(),$j("#eventBoard").append(a))}$j("#eventBoard").find(".leagueBoard").toArray().forEach(function(c,e){$j("#"+c.id+":empty").length&&(c=c.id.replaceAll("Board",""),$j("#"+
c).remove())})};EventHandler.getCompetitionName=function(a){return(StringUtil.isEmpty(a)?"zzz":StringUtil.trim(a).replace("'","").replace(/\s*/g,"")).replace(".","").replace(/,/g,"")};EventHandler.isSorted=function(a,b){for(let c=0;c<a.length-1;++c)if("asc"===b?a[c]>a[c+1]:a[c]<a[c+1])return!1;return!0}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.events={};var t=new TreeMap;DataBase.events.update=function(n){for(var a,b=0;b<n.length;b++){var c=n[b];a=t.get(c.eventType);null==a&&(a=new TreeMap,t.put(c.eventType,a));a.put(c.id,c);DataBase.markets.update(c.id,c.markets)}};DataBase.events.remove=function(n){t.remove(n)};DataBase.events.get=function(n,a){n=t.get(n);return null==n?null:n.get(a)};DataBase.events.queryAll=function(n){var a=t.get(n);null==a&&(a=new TreeMap,t.put(n,a));return a.values()};DataBase.events.queryByCompetition=
function(n,a){n=DataBase.events.queryAll(n);for(var b=[],c=0;c<n.length;c++){var e=n[c];e.competitionId==a&&(b[b.length]=e)}return b};DataBase.events.queryByCountryCode=function(n,a){n=DataBase.events.queryAll(n);for(var b=[],c=0;c<n.length;c++){var e=n[c];e.countryCode==a&&(b[b.length]=e)}return b};DataBase.events.sort=function(n){n=t.get(n);null!=n&&n.sort(function(a,b){return a.value.openDateTime-b.value.openDateTime})}})();

