"undefined"==typeof PageConfig&&(PageConfig={});"undefined"==typeof EventResultHandler&&(EventResultHandler={});
(function(){function m(b){b.find("#fancyBetEvent").unbind("click").click(function(){b.hasClass("open")?b.removeClass("open"):(b.addClass("open"),EventResultHandler.queryFancyBetMarketList(b.attr("eventId"),b.attr("marketGroup")))})}EventResultHandler.init=function(){""==location.hash&&(location.hash="#Today");$j(window).bind("hashchange",function(){""==location.hash?(location.hash="#Today",location.reload()):EventResultHandler.query()});$j("#sports").change(function(){EventResultHandler.query()});
"true"==PageConfig.ENABLE_ONE_CLICK_BET?OneClickBetHandler.show():UiUtils.appendHeight();EventResultHandler.query()};EventResultHandler.query=function(){if("#Today"==location.hash){var b="today";TabMenuHandler.updateSelect("resultTab","today")}else"#Yesterday"==location.hash&&(b="yesterday",TabMenuHandler.updateSelect("resultTab","yesterday"));var f=JsCache.get("#sports").val();try{$j.ajax({type:"POST",url:"/member/reportController/queryEventResults",data:{type:b,sport:f},beforeSend:function(){JsCache.get("#loading").show()},
complete:function(){JsCache.get("#loading").hide()},success:function(d){if(d&&d.error)NoticeHandler.error(d.error);else{var e=$j("#Result_Table"),g=$j("#Fancybet_Result_Table");f==EventType.FANCYBET.value?(e.hide(),g.show()):(e.show(),g.hide());if(f==EventType.FANCYBET.value)g.html(""),$j.isEmptyObject(d)||$j.each(d,function(c,a){c=JsCache.get("#fancyBetTr").clone().show();c.find("#eventOpenDate").html(a.eventOpenDate);c.find("#eventName").html(a.eventName);c.attr("id","fancyBetTr_"+a.eventId+"_"+
a.marketGroup);c.attr("eventId",a.eventId);c.attr("marketGroup",a.marketGroup);c.find("#filter_tags").attr("id","filter_tags_"+a.eventId+"_"+a.marketGroup);c.find("#marketContent").attr("id","marketContent_"+a.eventId+"_"+a.marketGroup);m(c);g.append(c)});else{if(f==EventType.CRICKET.value)e.find("#Result_Title_1").html("Home"),e.find("#Result_Title_2").html("Away");else if(f==EventType.SOCCER.value||f==EventType.E_SOCCER.value)e.find("#Result_Title_1").html("HT"),e.find("#Result_Title_2").html("FT");
var h=e.find("#Result_Content");h.html("");$j.isEmptyObject(d)?(d=JsCache.clone("#noDataTemplate"),h.append(d.show())):$j.each(d,function(c,a){c=JsCache.get("#tempTr").clone();c.find("#eventDate").html(a.eventDate);c.find("#eventName").html(a.eventName);c.find("#resultItem1").html(a.resultItem1);c.find("#resultItem2").html(a.resultItem2);h.append(c)})}}}})}catch(d){NoticeHandler.error(d.message)}};EventResultHandler.queryFancyBetMarketList=function(b,f){$j.ajax({type:"POST",url:"/member/reportController/queryMarketListForResultPage",
data:{eventId:b,marketGroup:f},beforeSend:function(){JsCache.get("#loading").show()},complete:function(){JsCache.get("#loading").hide();$j("#filter_tags_"+b+"_"+f).find("#filter_1").click()},success:function(d){if(d)if(d.error)alert(d.error);else{var e=$j("#fancyBetTr_"+b+"_"+f),g=$j("#marketHead").clone().show().css("display","flex"),h=$j("#noDataHr").clone(),c=$j("#noDataTr").clone(),a=e.find("#marketContent_"+b+"_"+f);a.empty();a.append(g);a.append(h);a.append(c);$j.each(d,function(k,l){k=$j("#marketTempTr").clone();
k.find("#marketName").html(l.marketName);k.find("#resultRuns").html(l.resultRuns);k.find("#resultSource").html(null==l.resultSource||0==l.resultSource.length?"-":l.resultSource);k.attr("id","market_"+l.marketId);k.attr("marketType",l.marketType);a.append(k.show().css("display","flex"))})}},error:function(d,e,g){Trace.log(d.status);Trace.log(g)}})};EventResultHandler.getFilterMarkets=function(b){b=$j(b);var f=b.parent();f.find("[id^=filter_]").removeClass("select");b.addClass("select");var d=b.attr("id").split("_")[1];
b=f.attr("id").replace("filter_tags_","");var e=$j("#marketContent_"+b);b=e.find("[id^=market_]");f=e.find("#marketHead").show().css("display","flex");var g=e.find("#noDataHr").hide();e=e.find("#noDataTr").hide();var h=!0;b.each(function(c,a){c=$j(a);a=c.attr("marketType");"ALL"!=d&&a!=d?c.hide():(c.show().css("display","flex"),h=!1)});h&&(f.hide(),g.show().css("display","flex"),e.show().css("display","flex"))}})();

