"undefined"==typeof EventPinHighlightHandler&&(EventPinHighlightHandler={});
(function(){EventPinHighlightHandler.eventTsMap=new TreeMap;EventPinHighlightHandler.marketTsMap=new TreeMap;EventPinHighlightHandler.selectionTsMap=new TreeMap;EventPinHighlightHandler.init=()=>{PageConfig.ENABLE_PIN_HIGHLIGHT_EVNET_BOARD&&EventHighlightUtil.isViewHighlightPage()&&EventPinHighlightHandler.initEventPinHighlight(PageConfig.pinHighlightCurrentPage)};EventPinHighlightHandler.selectPinHighlights=c=>{c!=PageConfig.highlightEventType&&(PageConfig.pinHighlightCurrentPage=1);EventPinHighlightHandler.init()};
EventPinHighlightHandler.getEventPinHighlightTask=null;EventPinHighlightHandler.initGetPinHighlightEventsTask=function(){PageConfig.ENABLE_PIN_HIGHLIGHT_EVNET_BOARD&&(null==EventPinHighlightHandler.getEventPinHighlightTask?EventPinHighlightHandler.getEventPinHighlightTask=TaskExecuterV2.createTask(PageConfig.getEventsTaskCycleTime,0,function(){k(this)}):EventPinHighlightHandler.getEventPinHighlightTask.isStop=!1,EventPinHighlightHandler.getEventPinHighlightTask.run(),TaskExecuterV2.execute())};EventPinHighlightHandler.abortTask=
()=>{null!=EventPinHighlightHandler.getEventPinHighlightTask&&EventPinHighlightHandler.getEventPinHighlightTask.stop()};EventPinHighlightHandler.initTsMap=async()=>{EventPinHighlightHandler.eventTsMap.put(PageConfig.highlightEventType,-1);EventPinHighlightHandler.marketTsMap.put(PageConfig.highlightEventType,-1);EventPinHighlightHandler.selectionTsMap.put(PageConfig.highlightEventType,-1)};EventPinHighlightHandler.PreviousPage=c=>{c--&&1>=c&&(c=1);let b=$j("#eventPinHighlightWrap");b.find("#eventPinHighlightBoard").empty();
b.find("#pinPreviousPage").addClass("disabled");b.find("#pinNextPage").addClass("disabled");EventPinHighlightHandler.initTsMap().then(()=>{EventPinHighlightHandler.initEventPinHighlight(c)})};EventPinHighlightHandler.NextPage=c=>{let b=$j("#eventPinHighlightWrap");b.find("#eventPinHighlightBoard").empty();b.find("#pinPreviousPage").addClass("disabled");b.find("#pinNextPage").addClass("disabled");EventPinHighlightHandler.initTsMap().then(()=>{EventPinHighlightHandler.initEventPinHighlight(++c)})};
EventHighlightUtil.PageNavigation=c=>{let b=$j("#eventPinHighlightWrap");1==c.lastPage?(b.find("#pinPreviousPage").hide(),b.find("#pinNextPage").hide()):(b.find("#pinPreviousPage").unbind("click").bind("click",()=>{EventPinHighlightHandler.PreviousPage(PageConfig.pinHighlightCurrentPage)}),b.find("#pinNextPage").unbind("click").bind("click",()=>{EventPinHighlightHandler.NextPage(PageConfig.pinHighlightCurrentPage)}),b.find("#pinPreviousPage").show(),b.find("#pinNextPage").show());1==PageConfig.pinHighlightCurrentPage?
b.find("#pinPreviousPage").unbind("click").addClass("disabled"):b.find("#pinPreviousPage").removeClass("disabled");c.lastPage==PageConfig.pinHighlightCurrentPage?b.find("#pinNextPage").unbind("click").addClass("disabled"):b.find("#pinNextPage").removeClass("disabled")};EventPinHighlightHandler.clearPinHighlightBoard=()=>{let c=$j("#eventPinHighlightWrap");c.hide();c.find("#eventPinHighlightBoard").empty()};EventPinHighlightHandler.initEventPinHighlight=c=>{let b=h(PageConfig.highlightEventType);if(null==
b||0==b.length)EventPinHighlightHandler.clearPinHighlightBoard();else{var d=PageConfig.highlightEventType;if(-1!=d){var e=EventPinHighlightHandler.eventTsMap.get(d);null==e&&(e=-1,EventPinHighlightHandler.eventTsMap.put(d,e));var f=EventPinHighlightHandler.marketTsMap.get(d);null==f&&(f=-1,EventPinHighlightHandler.marketTsMap.put(d,f));var g=EventPinHighlightHandler.selectionTsMap.get(d);null==g&&(g=-1,EventPinHighlightHandler.selectionTsMap.put(d,g));$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&
null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsPinHighlightWithMarketPath,data:{eventIds:b,eventType:d,eventTs:-1,marketTs:-1,selectionTs:-1,pageNumber:c,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(a){try{a.eventTs>e&&EventPinHighlightHandler.eventTsMap.put(a.eventType,a.eventTs),a.marketTs>f&&EventPinHighlightHandler.marketTsMap.put(a.eventType,a.marketTs),a.selectionTs>g&&EventPinHighlightHandler.selectionTsMap.put(a.eventType,
a.selectionTs),PageConfig.pinHighlightCurrentPage=a.currentPage>a.lastPage?a.lastPage:a.currentPage,DataBase.pinHighlightEvents.push(a.events),EventHighlightUtil.updateEvents(a),EventHighlightUtil.PageNavigation(a)}catch(l){Trace.printStackTrace(l)}},error:function(a){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(a)}})}}};const k=c=>
{let b=h(PageConfig.highlightEventType);if(null==b||0==b.length)c.check(),TaskExecuterV2.execute(),EventPinHighlightHandler.clearPinHighlightBoard();else{var d=PageConfig.highlightEventType;if(-1!=d){var e=EventPinHighlightHandler.eventTsMap.get(d);null==e&&(e=-1,EventPinHighlightHandler.eventTsMap.put(d,e));var f=EventPinHighlightHandler.marketTsMap.get(d);null==f&&(f=-1,EventPinHighlightHandler.marketTsMap.put(d,f));var g=EventPinHighlightHandler.selectionTsMap.get(d);null==g&&(g=-1,EventPinHighlightHandler.selectionTsMap.put(d,
g));$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsPinHighlightWithMarketPath,data:{eventIds:b,eventType:d,eventTs:-1,marketTs:-1,selectionTs:-1,pageNumber:PageConfig.pinHighlightCurrentPage,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(a){try{PageConfig.pinHighlightCurrentPage==a.currentPage&&(a.eventTs>e&&EventPinHighlightHandler.eventTsMap.put(a.eventType,
a.eventTs),a.marketTs>f&&EventPinHighlightHandler.marketTsMap.put(a.eventType,a.marketTs),a.selectionTs>g&&EventPinHighlightHandler.selectionTsMap.put(a.eventType,a.selectionTs),DataBase.pinHighlightEvents.push(a.events),EventHighlightUtil.updateEvents(a),EventHighlightUtil.PageNavigation(a))}catch(l){Trace.printStackTrace(l)}finally{c.check(),TaskExecuterV2.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&
(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);c.check();TaskExecuterV2.execute()}})}}},h=c=>{c=DataBase.multiMarkets.queryAllMarketPkByEventType(c);return EventHighlightUtil.collectEventId(c)}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.pinHighlightEvents={};let k=[];DataBase.pinHighlightEvents.push=h=>{let c=[];for(let b=0;b<h.length;b++){let d=h[b];c.push(d);DataBase.markets.update(d.id,d.markets)}k=c};DataBase.pinHighlightEvents.clear=()=>{k=[]};DataBase.pinHighlightEvents.queryAll=()=>k.map(h=>h)})();

