"undefined"==typeof FancyBetMarketHandler&&(FancyBetMarketHandler={});
(function(){function r(a){var b=$j("#fancyBetTabWrap");b.show();b.delegate("a","click",function(){var c=$j(this);A=FancyBetTabType.getInstanceOf(c.attr("fancyBetTabType")).unique();b.find("li").removeClass("select");c.parent().addClass("select");e();DataBase.fancyBet.clearByEventId(a);FancyBetHandler.clearBoard(a);FancyBetMarketHandler.removeSelectClass(a);FancyBetHandler.updateExposure(a)})}function e(){var a=$j("#fancyBetMarketList"),b=a.find("[id^=fancyBetMarket_]");$j.each(b,function(c,d){d=a.find(b[c]);
if(0==d.length)return!0;c=DataBase.fancyBetMarkets.get(d.prop("eventId"),d.prop("marketId"));if(null==c)return!0;FancyBetMarketHandler.updateMarketStatus(a,d,c)})}function m(a,b){if(b.fancyBetMarkets&&0!=b.fancyBetMarkets.length){var c=b.eventId;b=b.fancyBetMarkets;for(var d={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1},h=0,k=b.length;h<k;h++){var g=b[h],f=g.marketId,n=g.status;
if(!FancyBetMarketUtil.isOffline(n)){f=a.find("#fancyBetMarket_"+f);if(0==f.length){if(FancyBetMarketUtil.isClosed(n))continue;f=t(a,g)}n=a;var l=g,u=c;g=d;var v=l.marketType;FancyBetMarketType.LOTTERY.unique()==v?FancyBetLotteryMarketHandler.updateFancyBetMarket(n,f,l,u,g):FancyBetMarketType.KHADDA.unique()==v?FancyBetKhaddaMarketHandler.updateFancyBetMarket(n,f,l,u,g):FancyBetMarketType.THREE_SELECTIONS.unique()==v?FancyBetThreeSelectionsMarketHandler.updateFancyBetMarket(n,f,l,u,g):(f.prop("sort",
l.sort),u=f.find("#lay_1"),v=f.find("#back_1"),UiUtils.removeContents(u.find("#runsInfo")),UiUtils.removeContents(v.find("#runsInfo")),q(u,l.runsNo,l.oddsNo),q(v,l.runsYes,l.oddsYes),w(FancySideType.NO.unique(),l),w(FancySideType.YES.unique(),l),f.find("#minMax").html(CurrencyUtil.formatter(l.min,g)+" / "+CurrencyUtil.formatter(l.max,g)),0==l.rebateRatio?(f.find("#rebateName").hide(),f.find("#rebate").hide()):(f.find("#rebateName").show(),f.find("#rebate").show(),f.find("#rebate").html(MathUtil.decimal.multiply(l.rebateRatio,
100)+"%")),FancyBetMarketHandler.updateMarketStatus(n,f,l),FancyBetMarketHandler.updateMarketRemark(f,l))}}}}function p(a,b){if(b.fancyBetSelection&&0!=b.fancyBetSelection.selections.length){var c=b.eventId;b=b.fancyBetSelection.selections;for(var d=0,h=b.length;d<h;d++){var k=b[d],g=k.marketId,f=k.selectionId;g=a.find("#fancyBetMarket_"+g).find("#fancyBetSelection_"+g+"_"+f);if(0!=g.length){f=g.find("#lay_1");var n=g.find("#back_1");UiUtils.removeContents(f.find("#runsInfo"));UiUtils.removeContents(n.find("#runsInfo"));
q(f,k.runsNo,k.oddsNo);q(n,k.runsYes,k.oddsYes);B(FancySideType.NO.unique(),c,k);B(FancySideType.YES.unique(),c,k)}FancyBetSelectionUtil.isActive(k.status)||k.isFirstInit?g.show():g.hide()}}}function t(a,b){var c=b.marketType;if(FancyBetMarketType.LOTTERY.unique()==c)return FancyBetLotteryMarketHandler.genFancyBetMarket(a,b);if(FancyBetMarketType.KHADDA.unique()==c)return FancyBetKhaddaMarketHandler.genFancyBetMarket(a,b);if(FancyBetMarketType.THREE_SELECTIONS.unique()==c)return FancyBetThreeSelectionsMarketHandler.genFancyBetMarket(a,
b);c=a.find("#fancyBetMarketTemplate").clone();var d=a.find("#suspendTemplate").clone();c.prop("id","fancyBetMarket_"+b.marketId);c.prop("eventId",b.eventId);c.prop("marketId",b.marketId);c.prop("marketType",b.marketType);c.prop("status",b.status);c.prop("summaryStatus",b.summaryStatus);c.prop("updateDate",b.updateDate);c.prop("marketName",b.marketName);c.prop("sort",b.sort);c.find("#marketName").html(b.marketName);null!=b.remarkFirstRow&&0<b.remarkFirstRow.length&&(c.find("#remarkFirstRow").show(),
c.find("#remarkFirstRow").html(b.remarkFirstRow));null!=b.remarkSecondRow&&0<b.remarkSecondRow.length&&(c.find("#remarkSecondRow").show(),c.find("#remarkSecondRow").html(b.remarkSecondRow));C(c,c.find("#lay_1"),b,FancySideType.NO.unique());C(c,c.find("#back_1"),b,FancySideType.YES.unique());FancyBetMarketHandler.bindFancyBetBookClickFunc(c,b.eventId,b.marketId);d.prop("id","suspend_"+b.marketId);a.append(d);a.append(c);0<DataBase.fancyBetTxn.getByMarketId(b.eventId,b.marketId+"",null,null,CategoryType.FANCY_BET.unique()).length&&
(c.find("#fancyBetBookBtn").show(),FancyBetHandler.getExposure(b.eventId,b.marketId));return c}function q(a,b,c){var d=a.find("#runsInfo");d.find("span").before(0==b?"":b);d.find("span").html(0==c?"":c);d.prop("runs",b);d.prop("odds",c);SparkHandler.addFancyBetSpark(a,b,c)}function w(a,b){if(PageConfig.enableBetboardSyncRunsOdds&&null!=b){var c=DataBase.fancyBet.generateKey(b.eventId,b.marketId,a),d=$j("#fancyBetTable_"+b.eventId).find("#fancyBetBoard_"+c);c=a==FancySideType.NO.unique()?b.oddsNo:
b.oddsYes;var h=a==FancySideType.NO.unique()?b.runsNo:b.runsYes;d&&(d=d.find("#oddsHeader"),d.find("#runs").text()!=h||d.find("#odds").text()!=c)&&(d.find("#runs").html(h),d.find("#odds").html(c),DataBase.fancyBet.updateRunsOdds(b.eventId,b.marketId,a,h,c))}}function B(a,b,c){if(PageConfig.enableBetboardSyncRunsOdds&&null!=c){var d=DataBase.fancyBet.generateKey(b,c.marketId,a),h=$j("#fancyBetTable_"+b).find("#fancyBetBoard_"+d+"_"+c.selectionId);d=a==FancySideType.NO.unique()?c.oddsNo:c.oddsYes;var k=
a==FancySideType.NO.unique()?c.runsNo:c.runsYes;h&&(h=h.find("#oddsHeader"),h.find("#runs").text()!=k||h.find("#odds").text()!=d)&&(h.find("#runs").html(k),h.find("#odds").html(d),DataBase.fancyBet.updateThreeSelectionsRunsOdds(b,c.marketId,c.selectionId,a,k,d))}}function x(a,b){FancyBetHandler.hideBetBoardByMarket(a,b);FancyBetHandler.getExposure(a,b);FancyBetMarketHandler.removeSelectClass(a)}function C(a,b,c,d){a=function(h,k,g,f,n,l,u,v){return function(){var y=k.find("#runsInfo").prop("runs")||
0,z=k.find("#runsInfo").prop("odds")||0;0!=y&&0!=z&&("true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeFancyBet(h,g,f,n,l,y,z):(FancyBetMarketHandler.addSelectClass(k,f),FancyBetHandler.appendBoard(h,g,f,n,l,y,z,u,v)))}}(a,b,c.eventType,c.eventId,c.marketId,d,c.eventName,c.marketName);b.on("click",a)}function D(a){var b=!1,c;for(c in a){var d=
a[c];if(FancyBetMarketUtil.isOnline(d.status)&&!FancyBetMarketUtil.isClosed(d.status)){b=!0;break}}return b}function E(a){var b=a.find("[id^=fancyBetMarket_]:visible");if(!(2>b.length)){for(var c=!1,d=0;d<b.length&&!(d+1>=b.length);d++){var h=a.find(b[d]),k=a.find(b[d+1]);if(!(0==h.length||0>h.prop("id").indexOf("fancyBetMarket_")||0==k.length||0>k.prop("id").indexOf("fancyBetMarket_"))&&h.prop("marketType")==k.prop("marketType")&&h.prop("sort")>k.prop("sort")){c=!0;break}}c&&(b=b.sort(function(g,
f){g=a.find(g);f=a.find(f);return FancyBetMarketUtil.sortMarkets(g.prop("sort"),f.prop("sort"),g.prop("marketType"),f.prop("marketType"))}),a.append(b),$j.each(b,function(g,f){f=a.find(f);g=f.prop("marketId");var n=a.find("#suspend_"+g);0<n.length&&a.find("#fancyBetMarket_"+g).before(n);f=a.find("[id^=fancyBetBoard_"+f.prop("eventId")+"_"+f.prop("marketId")+"_]");0<f.length&&a.find("#fancyBetMarket_"+g).after(f)}))}}var A=FancyBetTabType.ALL.unique();FancyBetMarketHandler.queryTask=null;FancyBetMarketHandler.init=
function(){FancyBetMarketHandler.isEnableFancyBet()&&FancyBetMarketHandler.initTask()};FancyBetMarketHandler.isEnableFancyBet=function(){return PageConfig.isEnableFancyBet};FancyBetMarketHandler.isShowFancyBet=function(){return FancyBetMarketHandler.isEnableFancyBet()&&PageConfig.hasFancyBetMarkets};FancyBetMarketHandler.isViewMultiMarket=function(){return-1<location.href.indexOf("multiMarkets")};FancyBetMarketHandler.initTask=function(){if(null==FancyBetMarketHandler.queryTask){var a=TaskExecuterV2.createTask(PageConfig.getFancyBetMarketsTaskCycleTime,
0,function(){FancyBetMarketHandler.queryFancyBetMarkets(this)});a.version=0;a.oddsSettingVersion=0;a.selectionTs=0;FancyBetMarketHandler.queryTask=a}else FancyBetMarketHandler.queryTask.isStop=!1;FancyBetMarketHandler.queryTask.run();TaskExecuterV2.execute()};FancyBetMarketHandler.abortTask=function(){null!=FancyBetMarketHandler.queryTask&&FancyBetMarketHandler.queryTask.stop()};FancyBetMarketHandler.queryFancyBetMarkets=function(a){try{$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&
null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:PageConfig.landingPath)+"/member/playerService/queryFancyBetMarkets",data:{eventId:PageConfig.selectEventId,version:a.version,oddsSettingVersion:a.oddsSettingVersion,queryPass:PageConfig.queryPass,selectionTs:a.selectionTs},xhrFields:{withCredentials:!0},success:function(b){b&&(b.version>a.version&&(a.version=Math.max(b.version,a.version)),b.oddsSettingVersion>a.oddsSettingVersion&&(a.oddsSettingVersion=Math.max(b.oddsSettingVersion,
a.oddsSettingVersion)),b.selectionTs>a.selectionTs&&(a.selectionTs=Math.max(b.selectionTs,a.selectionTs)),FancyBetMarketHandler.updateFancyBetMarkets(b),FancyBetMarketHandler.updateFancyBetSelections(b))},error:function(b,c,d){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.log(b.status);Trace.log(d)}})}catch(b){Trace.printStackTrace(b)}finally{a.check(),
TaskExecuterV2.execute()}};FancyBetMarketHandler.getFancyBetTable=function(a,b,c,d){var h=(c=c&&d)?a.find("#bookMakerTable_"+b):a.find("#fancyBetTable_"+b);0==h.length&&(h=c?a.find("#bookMakerTableTemplate").clone():a.find("#fancyBetTableTemplate").clone(),c?h.prop("id","bookMakerTable_"+b):h.prop("id","fancyBetTable_"+b),d?a.find("#header").after(h):(a.find("#fancyBetPosition").after(h),FullMarketUtil.view("fancyBet"),EventType.ELECTION.unique()!=PageConfig.selectEventType&&EventType.FANCYBET.unique()!=
PageConfig.selectEventType&&r(b)));h.attr("name","multiMarketItem");return h};FancyBetMarketHandler.updateFancyBetMarkets=function(a){if(a.fancyBetMarkets&&0!=a.fancyBetMarkets.length){var b=a.fancyBetMarkets[0].eventType,c=a.eventId,d=a.highlightMarketId,h=a.fancyBetMarkets;DataBase.fancyBetMarkets.update(c,a.fancyBetMarkets);a.fancyBetSelection&&DataBase.fancyBetMarkets.updateSelection(c,a.fancyBetSelection.selections);var k=$j("#overWrap"),g=FancyBetMarketHandler.getFancyBetTable(k,c,!1,FancyBetMarketHandler.isViewMultiMarket());
k=g.find("#fancyBetHead");var f=g.find("#fancyBetMarketList");MultiMarketsHandler.appendFancyBetPin(b,c,FancyBetMarketHandler.isViewMultiMarket());FancyBetMarketHandler.isViewMultiMarket()&&(g.find(".multi_name").unbind("click").click(function(){location.href=PageConfig.fullMarketPath+"?eventType="+b+"&eventId="+c+"&marketId="+d}),g.find("#multiMarketRefresh").unbind("click").click(function(){g.find("#multiMarketLoading").show();setTimeout(function(){g.find("#multiMarketLoading").hide()},500)}),k.find("#eventName").text(a.fancyBetMarkets[0].eventName),
g.show());EventType.ELECTION.unique()==b&&k.find("#headerName").html("Election Fancy Bet");D(DataBase.fancyBetMarkets.queryByEvent(c))?(f.show(),FancyBetMarketHandler.isViewMultiMarket()&&k.find(".game-fancy").addClass("in-play")):(FancyBetMarketHandler.isViewMultiMarket()&&g.hide(),f.hide());h.sort(function(n,l){return FancyBetMarketUtil.sortMarkets(n.sort,l.sort,n.marketType,l.marketType)});m(f,a);p(f,a);FancyBetMarketUtil.checkForAllClose(c);E(f)}};FancyBetMarketHandler.updateFancyBetSelections=
function(a){if(a.fancyBetSelection&&0!=a.fancyBetSelection.selections){var b=a.eventId,c=$j("#overWrap");c=FancyBetMarketHandler.getFancyBetTable(c,b,!1,FancyBetMarketHandler.isViewMultiMarket()).find("#fancyBetMarketList");DataBase.fancyBetMarkets.updateSelection(b,a.fancyBetSelection.selections);p(c,a)}};FancyBetMarketHandler.updateMarketStatus=function(a,b,c){var d=c.status,h=c.marketType;a=a.find("#suspend_"+c.marketId);b.prop("status",d);var k=FancyBetMarketUtil.isOnline(d)&&!FancyBetMarketUtil.isClosed(d);
k&&(b.show(),b.prop("timeout",!1));var g=FancyBetMarketUtil.isBelongMarketType(FancyBetTabType.getInstanceOf(A),h);g?b.show():(b.hide(),a.hide());a.find("#suspendClass").removeClass("fancy-suspend").removeClass("fancy-suspend-white");FancyBetMarketUtil.isSuspend(d)?(a.find("#suspendClass").addClass("fancy-suspend"),a.find("#info").html("Suspend"),k&&g&&a.fadeIn(),FancyBetMarketType.THREE_SELECTIONS.unique()==h&&(b.find("#multi_select").addClass("multi_suspend"),b.find("#multi_select").prop("style",
'--table-tip-content: "Suspend"')),x(c.eventId,c.marketId)):FancyBetMarketUtil.isBallRun(d)?(a.find("#suspendClass").addClass("fancy-suspend"),a.find("#info").html("Ball Running"),k&&g&&a.fadeIn(),FancyBetMarketType.THREE_SELECTIONS.unique()==h&&(b.find("#multi_select").addClass("multi_suspend"),b.find("#multi_select").prop("style",'--table-tip-content: "Ball Running"')),x(c.eventId,c.marketId)):FancyBetMarketUtil.isClosed(d)?(a.find("#suspendClass").addClass("fancy-suspend-white"),a.find("#info").html("Closed"),
k&&g&&a.fadeIn(),x(c.eventId,c.marketId),b.hide(),a.hide(),b.prop("timeout",!0)):(a.hide(),b.find("#multi_select").removeClass("multi_suspend"))};FancyBetMarketHandler.getDelayBettingElem=function(a,b){a=$j("#overWrap").find("#fancyBetTable_"+a).find("#fancyBetMarketList");var c=a.find("#fancyBetMarket_"+b);if(0==c.length||!c.is(":visible"))return null;var d=a.find("#suspend_"+b);if(0==d.length||d.is(":visible"))return null;d=a.find("#delayBetting_"+b);0==d.length&&(d=a.find("#delayTemplate").clone(),
d.prop("id","delayBetting_"+b),c.before(d));return d};FancyBetMarketHandler.showDelayBetting=function(a,b){var c=DataBase.fancyBetMarkets.get(a,b);c=c.delayBetting?1E3*parseInt(c.delayBetting):0;if(0!=c){var d=FancyBetMarketHandler.getDelayBettingElem(a,b);null!=d&&0!=d.length&&(d.find("#info").html(""),d.fadeIn(),setTimeout(function(){d.find("#info").html("");d.fadeOut()},c))}};FancyBetMarketHandler.hideDelayBetting=function(a,b){a=FancyBetMarketHandler.getDelayBettingElem(a,b);null!=a&&0!=a.length&&
(a.find("#info").html(""),a.hide())};FancyBetMarketHandler.bindFancyBetBookClickFunc=function(a,b,c){a.find("#fancyBetBookBtn").off("click").on("click",function(){window.open("/exchange/member/market/fancyBetBook.jsp?eventId="+b+"&marketId="+c,"_blank","resizable=no,width=600,height=650")})};FancyBetMarketHandler.showFancyBetBookBtn=function(a,b){if(a&&b){var c=$j("#overWrap").find("#fancyBetTable_"+a).find("#fancyBetMarketList").find("#fancyBetMarket_"+b+":visible");0!=c.length&&(0==DataBase.fancyBetTxn.getByMarketId(a,
b,null,null,CategoryType.FANCY_BET.unique()).length?c.find("#fancyBetBookBtn").hide():c.find("#fancyBetBookBtn").show())}};FancyBetMarketHandler.addSelectClass=function(a,b){FancyBetMarketHandler.removeSelectClass(b);a.addClass("select")};FancyBetMarketHandler.removeSelectClass=function(a){a=$j("#overWrap").find("#fancyBetTable_"+a).find("[id^=fancyBetMarket_]");a.find("#lay_1").removeClass("select");a.find("#back_1").removeClass("select");a.find("#clickToBet").removeClass("select")};FancyBetMarketHandler.updateMarketRemark=
function(a,b){null!=b.remarkFirstRow&&0<b.remarkFirstRow.length?(a.find("#remarkFirstRow").show(),a.find("#remarkFirstRow").html(b.remarkFirstRow)):(a.find("#remarkFirstRow").hide(),a.find("#remarkFirstRow").html(""));null!=b.remarkSecondRow&&0<b.remarkSecondRow.length?(a.find("#remarkSecondRow").show(),a.find("#remarkSecondRow").html(b.remarkSecondRow)):(a.find("#remarkSecondRow").hide(),a.find("#remarkSecondRow").html(""))}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.fancyBetMarkets={};var r=new TreeMap;DataBase.fancyBetMarkets.update=function(e,m){var p=r.get(e);null==p&&(p=new TreeMap,r.put(e,p));for(e=0;e<m.length;e++){var t=m[e],q=p.get(t.marketId);null!=q&&null!=q.selectionMap&&(t.selectionMap=q.selectionMap);p.put(t.marketId,t)}};DataBase.fancyBetMarkets.get=function(e,m){e=r.get(e);return null==e?null:e.get(m)};DataBase.fancyBetMarkets.queryByEvent=function(e){var m=r.get(e);null==m&&(m=new TreeMap,r.put(e,m));return m.values()};DataBase.fancyBetMarkets.updateSelection=
function(e,m){var p=r.get(e);if(null==p)Trace.log("eventId: "+e+" is not exist");else{e=0;for(var t=m.length;e<t;e++){var q=m[e],w=p.get(q.marketId);null==w?Trace.log("marketId: "+q.marketId+" is not exist"):(null==w.selectionMap&&(w.selectionMap=new TreeMap),w.selectionMap.put(q.selectionId,q))}}};DataBase.fancyBetMarkets.getSelection=function(e,m,p){e=DataBase.fancyBetMarkets.get(e,m);if(null==e)return null;e=e.selectionMap;return null==e?null:e.get(p)};DataBase.fancyBetMarkets.getSelections=function(e,
m){e=DataBase.fancyBetMarkets.get(e,m);if(null==e)return null;e=e.selectionMap;return null==e?null:e.values()};DataBase.fancyBetMarkets.getSelectionByIndex=function(e,m,p){if(2<p)return null;e=DataBase.fancyBetMarkets.get(e,m);if(null==e)return null;e=e.selectionMap;return null==e?null:e.values()[p]}})();

