"undefined"==typeof FancyBetKhaddaHandler&&(FancyBetKhaddaHandler={});
(function(){function r(b,c,d,g,e){b.find("#inputRuns").off("change").on("change",function(){n(b,c,d,g,e)});b.find("#inputRuns").off("blur").on("blur",function(){n(b,c,d,g,e)});b.find("#inputRuns").keydown(function(f){var a=f.which;KeyEventUtils.isNumberKey(f)||KeyEventUtils.isBackspaceKey(a)||KeyEventUtils.isDeleteKey(a)||KeyEventUtils.isArrowKey(a)||KeyEventUtils.isTabKey(a)||KeyEventUtils.isEnterKey(a)||WindowEventUtil.stopEvent(f)});b.find("#inputRuns").keyup(function(f){$j(this).val(function(a,
h){return StringUtil.commaSeparateNumber(h)});n(b,c,d,g,e);KeyEventUtils.isTabKey(f.which)&&b.find("#inputRuns").is(":focus")&&b.find("#inputRuns").select()})}function n(b,c,d,g,e){var f=parseFloat(b.find("#inputRuns").val())||0,a=FancyBetMarketUtil.getKhaddaExtendedRuns(f,e);f<PageConfig.fancybetKhaddaMinRuns&&(f=PageConfig.fancybetKhaddaMinRuns,a=FancyBetMarketUtil.getKhaddaExtendedRuns(f,e),b.find("#inputRuns").val(f));a>PageConfig.fancybetKhaddaMaxRuns&&(f=PageConfig.fancybetKhaddaMaxRuns-e+1,
a=FancyBetMarketUtil.getKhaddaExtendedRuns(f,e),b.find("#inputRuns").val(f));b.find("#extendedRuns").html(a);e=parseFloat(b.find("#inputRuns").val())||0;DataBase.fancyBet.updateRuns(c,d,g,e);FancyBetHandler.eventCalculate(b,c,d,g)}function t(b,c,d,g,e){b.find("#placeBet").off("click").on("click",function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var f=FancyBetHandler.getfancyBetMessage(b,d);var a=b.find("#inputStake"),h=parseFloat(a.val())||0,l=DataBase.fancyBet.get(c,d,g),
k="",p=FancyBetHandler.checkBetStake(l);if(!p){var m=DataBase.fancyBetMarkets.get(c,l.marketId),q=m.min;m=m.max;h<q?(a.val(q),DataBase.fancyBet.updateStake(c,d,g,q),k+=I18N.get("msg.member.minBet")):h>m&&(a.val(m),DataBase.fancyBet.updateStake(c,d,g,m),k+=I18N.get("msg.member.maxBet"))}(l=FancyBetHandler.checkRuns(l))||(k+=I18N.get("msg.member.runs.empty"));(""==k||p)&&l||FancyBetHandler.showfancyBetMessage(f,"warning",k,!0);FancyBetHandler.getExposure(c,d);p&&l?(l=DataBase.fancyBet.getForBet(c,d,
g),k=$j("#fancyBetBar_"+e),0==k.length&&(k=FancyBetHandler.genfancyBetBar(e),b.after(k)),FancyBetHandler.submitBet(l,k,f,null,!1),b.hide()):l&&b.find("#placeBet").removeClass("disable")}})}FancyBetKhaddaHandler.appendBoard=function(b,c,d,g,e,f,a){var h=DataBase.fancyBetMarkets.get(c,d);if(null!=h){FancyBetHandler.clearBoard(c);var l=DataBase.fancyBet.generateKey(c,d,e);f=DataBase.fancyBet.add(h.eventType,c,d,e,f,a,h.eventName,h.marketName,h.marketType);h=!1;a=$j("#overWrap");var k=a.find("#fancyBetBoard_"+
l);0==k.length&&(a=a.find("#fancyBetKhaddaTemplate").clone(),k=FancySideType.YES.unique()==e?SideType.Back.name:SideType.Lay.name,a.find("#classWrap").removeClass("slip-back").removeClass("slip-lay").addClass("slip-"+k.toLowerCase()),a.prop("id","fancyBetBoard_"+l),a.prop("eventId",c),a.prop("marketId",d),a.prop("sideType",e),a.prop("marketType",f.marketType),t(a,c,d,e,l),r(a,c,d,e,g),FancyBetHandler.bindClickEvent(a,c,d,e,l),k=a);g=k;b.after(g.fadeIn());null!=PageConfig.userCoin&&0<PageConfig.userCoin?
(h=DataBase.fancyBetMarkets.get(c,d),b=parseFloat(PageConfig.userCoin),h.min&&parseFloat(h.min)>PageConfig.userCoin&&(b=parseFloat(h.min)),g.find("#inputStake").val(b),h=DataBase.fancyBet.updateStake(c,d,e,b)):g.find("#inputStake").val("");FancyBetHandler.getfancyBetMessage(g,d);FancyBetHandler.eventCalculate(g,c,d,e,h);FancyBetHandler.updateExposure(c);CoinHandler.showFancyBetCoin(g)}}})();

