"undefined"==typeof FancyBetHandler&&(FancyBetHandler={});
(function(){function t(a,b,c,f,e){a.find("#placeBet").off("click").on("click",function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var g=FancyBetHandler.getfancyBetMessage(a,c);var l=a.find("#inputStake"),p=parseFloat(l.val())||0,m=DataBase.fancyBet.get(b,c,f),r="",q=FancyBetHandler.checkBetStake(m);if(!q){var u=DataBase.fancyBetMarkets.get(b,m.marketId);m=u.min;u=u.max;p<m?(l.val(m),DataBase.fancyBet.updateStake(b,c,f,m),r+=I18N.get("msg.member.minBet")):p>u&&(l.val(u),DataBase.fancyBet.updateStake(b,
c,f,u),r+=I18N.get("msg.member.maxBet"))}""==r||q||FancyBetHandler.showfancyBetMessage(g,"warning",r,!0);FancyBetHandler.getExposure(b,c);q?(m=DataBase.fancyBet.getForBet(b,c,f),l=$j("#fancyBetBar_"+e),0==l.length&&(l=FancyBetHandler.genfancyBetBar(e),a.after(l)),p=a.find("#fancyBetAcceptAnyOdds").is(":checked")?1:0,FancyBetHandler.submitBet(m,l,g,null,p),a.hide()):a.find("#placeBet").removeClass("disable")}})}function d(a,b,c,f=!1){null!=a&&a.hide();f?FancyBetMarketHandler.hideDelayBetting(b,c):
(FancyBetMarketHandler.removeSelectClass(b),DataBase.fancyBet.clearByEventId(b),FancyBetHandler.getExposure(b,c))}function h(a,b,c){var f=c.find("#progressBar"),e=k(a,b);f.css("width",e);c.find("#secRemain").html(MathUtil.decimal.divide(a,10)+" sec remaining…");0<a&&(a--,setTimeout(function(){h(a,b,c)},100))}function k(a,b){a=MathUtil.decimal.subtract(b,a);b=MathUtil.decimal.divide(a,b);1<b&&(b=1);b=MathUtil.decimal.multiply(b,100);return Math.round(b)+"%"}var n;FancyBetHandler.appendBoard=function(a,
b,c,f,e,g,l,p,m){var r=DataBase.fancyBetMarkets.get(c,f);if(null!=r){FancyBetHandler.clearBoard(c);var q=DataBase.fancyBet.generateKey(c,f,e);r=DataBase.fancyBet.add(b,c,f,e,g,l,p,m,r.marketType);b=!1;g=$j("#overWrap");l=g.find("#fancyBetBoard_"+q);0==l.length&&(g=g.find("#fancyBetTemplate").clone(),l=g.find("#fancyBetHeader"),p=g.find("#oddsHeader"),m=FancySideType.YES.unique()==e?SideType.Back.name:SideType.Lay.name,g.find("#classWrap").removeClass("slip-back").removeClass("slip-lay").addClass("slip-"+
m.toLowerCase()),g.prop("id","fancyBetBoard_"+q),g.prop("eventId",c),g.prop("marketId",f),g.prop("sideType",e),g.prop("marketType",r.marketType),l.find("#acceptCheck").before(StringUtil.ucfirst(FancySideType.getInstanceOf(e).name)),p.find("#runs").html(r.runs),p.find("#odds").html(r.odds),t(g,c,f,e,q),FancyBetHandler.bindClickEvent(g,c,f,e,q),l=g);l.find("#fancyBetAcceptAnyOdds").prop("checked",TopMenuHandler.isAcceptAnyOdds("fancyBet"));q=l;a.after(q.fadeIn());q.find("#runs").html(r.runs);q.find("#odds").html(r.odds);
null!=PageConfig.userCoin&&0<PageConfig.userCoin?(r=DataBase.fancyBetMarkets.get(c,f),a=parseFloat(PageConfig.userCoin),r.min&&parseFloat(r.min)>PageConfig.userCoin&&(a=parseFloat(r.min)),q.find("#inputStake").val(a),b=DataBase.fancyBet.updateStake(c,f,e,a)):q.find("#inputStake").val("");FancyBetHandler.getfancyBetMessage(q,f);FancyBetHandler.eventCalculate(q,c,f,e,b);q.find("#odds").select();FancyBetHandler.updateExposure(c);CoinHandler.showFancyBetCoin(q)}};FancyBetHandler.clearBoard=function(a){var b=
$j("#fancyBetTable_"+a),c=b.find("[id^=fancyBetBoard_]");$j.each(c,function(f,e){e=b.find(e);0<e.length&&(e.prop("eventId"),e.prop("marketId"),e.prop("sideType"),f=e.prop("marketType"),FancyBetMarketType.LOTTERY.unique()==f?e.find("*").removeClass("select"):FancyBetMarketType.KHADDA.unique()==f&&(e.find("#inputRuns").val(""),e.find("#extendedRuns").html("")),e.hide())});DataBase.fancyBet.clearByEventId(a)};FancyBetHandler.hideBetBoardByMarket=function(a,b){var c=$j("#fancyBetTable_"+a),f;for(f in FancySideType)if(FancySideType[f]&&
FancySideType[f].value){var e=DataBase.fancyBet.generateKey(a,b,FancySideType[f].unique());e=c.find("[id^=fancyBetBoard_"+e+"]");0!=e.length&&(e.hide(),DataBase.fancyBet.remove(a,b,FancySideType[f].unique()))}};FancyBetHandler.bindClickEvent=function(a,b,c,f,e){a.find("#cancel").off("click").on("click",function(){DataBase.fancyBet.clearByEventId(b);a.hide();FancyBetMarketHandler.removeSelectClass(b);FancyBetHandler.getExposure(b,c)});a.find("#inputStake").off("click").on("click",function(){a.find("#inputStake").select()});
a.find("#inputStake").off("change").on("change",function(){var g=parseFloat(a.find("#inputStake").val())||0;FancyBetHandler.getfancyBetMessage(a,c);g=DataBase.fancyBet.updateStake(b,c,f,g);FancyBetHandler.eventCalculate(a,b,c,f,g)});a.find("#inputStake").off("blur").on("blur",function(){CoinHandler.hideStakePopupList();var g=parseFloat(a.find("#inputStake").val())||0;FancyBetHandler.getfancyBetMessage(a,c);g=DataBase.fancyBet.updateStake(b,c,f,g);FancyBetHandler.eventCalculate(a,b,c,f,g)});a.find("#inputStake").keydown(function(g){var l=
g.which;KeyEventUtils.isNumberKey(g)||KeyEventUtils.isBackspaceKey(l)||KeyEventUtils.isDeleteKey(l)||KeyEventUtils.isArrowKey(l)||KeyEventUtils.isTabKey(l)||KeyEventUtils.isEnterKey(l)||WindowEventUtil.stopEvent(g)});a.find("#inputStake").keyup(function(g){$j(this).val(function(p,m){return StringUtil.commaSeparateNumber(m)});var l=parseFloat(a.find("#inputStake").val())||0;FancyBetHandler.getfancyBetMessage(a,c);l=DataBase.fancyBet.updateStake(b,c,f,l);FancyBetHandler.eventCalculate(a,b,c,f,l);g=
g.which;KeyEventUtils.isEnterKey(g)&&a.find("#placeBet").click();KeyEventUtils.isTabKey(g)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()})};FancyBetHandler.eventCalculate=function(a,b,c,f,e){e=DataBase.fancyBet.get(b,c,f);var g=FancyBetHandler.checkBetStake(e);f=a.find("#placeBet");e.marketType==FancyBetMarketType.LOTTERY.value?(g=g&&FancyBetHandler.checkLotteryNo(e),e=e.stake*e.lotteryBall.length,a.find("#totalStakeP").show(),a.find("#totalStake").html(e)):g=e.marketType==FancyBetMarketType.KHADDA.value?
g&&FancyBetHandler.checkRuns(e):g;g?f.removeClass("disable"):f.addClass("disable");FancyBetHandler.getExposure(b,c)};FancyBetHandler.checkLotteryNo=function(a){if(null==a||null==DataBase.fancyBetMarkets.get(a.eventId,a.marketId))return!1;if(a.marketType!=FancyBetMarketType.LOTTERY.value)return!0;a=a.lotteryBall;return null!=a&&0<a.length};FancyBetHandler.checkRuns=function(a){return null==a||null==DataBase.fancyBetMarkets.get(a.eventId,a.marketId)?!1:""!=a.runs&&0<a.runs};FancyBetHandler.checkBetStake=
function(a){if(null==a)return!1;var b=DataBase.fancyBetMarkets.get(a.eventId,a.marketId);if(null==b)return!1;var c=b.min;b=b.max;if(!c||!b)return!1;a=parseFloat(a.stake||"0");return a<c||a>b?!1:!0};FancyBetHandler.submitBet=function(a,b,c,f,e){var g=0,l=0;let p=!1;$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/fancyBet",data:{fancyBets:JSON.stringify([a]),isOneClickBet:f,isAcceptAnyOdds:e},beforeSend:function(){if(null!=b){b.show();var m=MathUtil.decimal.multiply(5,
10),r=""+MathUtil.decimal.multiply(5,10);0<=m&&h(m,r,b)}FancyBetMarketHandler.showDelayBetting(a.eventId,a.marketId)},complete:function(){},success:function(m){try{if(m.error)null!=c?FancyBetHandler.showfancyBetMessage(c,"error",m.error,!0):NoticeHandler.error(m.error),FancyBetMarketHandler.hideDelayBetting(a.eventId,a.marketId);else if(0==m.result.length)FancyBetMarketHandler.hideDelayBetting(a.eventId,a.marketId);else if(void 0!==m.result[0].tempId){p=!0;const v=(new Date).getTime();n=setInterval(function(){FancyBetHandler.queryFancyBetTempTxn(m.result[0].tempId,
a,b,c,v)},1E3)}else{for(var r in m.result){var q=m.result[r];"SUCCESS"==q.status?(0==g&&0==l&&(g=q.eventId,l=q.marketId),null!=q.txn&&(DataBase.fancyBetTxn.update([q.txn]),null!=c&&FancyBetHandler.showfancyBetMessage(c,"success",null,!0,"txn",q.txn))):q.error&&(null!=c?FancyBetHandler.showfancyBetMessage(c,"error",q.error,!0):NoticeHandler.error(q.error),FancyBetMarketHandler.hideDelayBetting(a.eventId,a.marketId))}0!=g&&""!=l&&(TxnHandler.setEventIdAndMarketId(g,l,CategoryType.FANCY_BET.unique()),
g=0,l="");TxnHandler.updateOpenBetSelectionBox();TxnHandler.checkToHideOpenBets();var u=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(u))}}catch(v){Trace.printStackTrace(v)}finally{p||d(b,a.eventId,a.marketId)}},error:function(m){Trace.printStackTrace(m);d(b,a.eventId,a.marketId)}});JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()};FancyBetHandler.queryFancyBetTempTxn=function(a,b,c,f,e){var g=0,l=0;$j.ajax({type:"POST",
dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/queryFancyBetTempTxn",data:{tempId:a,isOverTime:4E4<=(new Date).getTime()-e},beforeSend:function(){},complete:function(){},success:function(p){try{if(p.error)null!=f?FancyBetHandler.showfancyBetMessage(f,"error",p.error,!0):NoticeHandler.error(p.error),FancyBetMarketHandler.hideDelayBetting(b.eventId,b.marketId);else{if("PROCESSING"===p.status||"WAITING"===p.status)return;if("SUCCESS"===p.status){0===g&&0===l&&(g=p.eventId,l=p.marketId);
null!=p.txn&&(DataBase.fancyBetTxn.update([p.txn]),null!=f&&FancyBetHandler.showfancyBetMessage(f,"success",null,!0,"txn",p.txn));0!==g&&""!==l&&(TxnHandler.setEventIdAndMarketId(g,l,CategoryType.FANCY_BET.unique()),g=0,l="");TxnHandler.updateOpenBetSelectionBox();TxnHandler.checkToHideOpenBets();const m=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(m))}}d(c,b.eventId,b.marketId);clearInterval(n)}catch(m){clearInterval(n),Trace.printStackTrace(m)}},
error:function(p){Trace.printStackTrace(p);d(c,b.eventId,b.marketId,!0);clearInterval(n)}})};FancyBetHandler.genfancyBetBar=function(a){var b=$j("#tempTable").find("#fancyBetBarTemplate").clone();b.prop("id","fancyBetBar_"+a);return b};FancyBetHandler.getfancyBetMessage=function(a,b){var c=$j("#overWrap").find("#fancyBetMessage_"+b);0==c.length&&(c=$j("#tempTable").find("#fancyBetMessageTemplate").clone(),c.prop("id","fancyBetMessage_"+b));a.after(c);return c};FancyBetHandler.showfancyBetMessage=
function(a,b,c,f,e,g){e=a.find("#header");a.find("#info").contents().filter(function(){return 3==this.nodeType}).remove();a.find("#classWrap").removeClass("success").removeClass("error").removeClass("warning").addClass(b);null!=c&&e.html(c);null!=g&&(c=g.stake,b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),c=b.name+b.symbol+c+" at runs/odds "+g.runs+"/"+g.odds,CurrencyUtil.updateSetting({currencySymbol:b.symbol}),c=FancySideType.YES.unique()==g.sideType?c+" Profit: ":c+" Liability: ",c+=
MyTransactionUtils.getFancyBetPL(g.odds,g.stake),e.html("Bet Matched"),e.after(c));a.find("#close").unbind("click").click(function(){a.fadeOut()});f&&setTimeout(function(){a.fadeOut()},3E3);a.fadeIn()};FancyBetHandler.getExposure=function(a,b){try{var c=DataBase.fancyBetMarkets.get(a,b);if(null==c)Trace.log("fancy market "+b+" is null");else{var f=DataBase.fancyBet.getByMarketId(a,b),e=DataBase.fancyBetTxn.getByMarketId(a,b+"",null,null,CategoryType.FANCY_BET.unique());if(0!=f.length||0!=e.length){var g=
[MyTransactionStatusType.Active.unique(),MyTransactionStatusType.Void.unique()];e=DataBase.fancyBetTxn.getByMarketId(a,b+"",null,g,CategoryType.FANCY_BET.unique());var l=FancyBetMarketType.LOTTERY.unique()==c.marketType?ExposureUtil.calculateFancyBetLotteryExposure(a,b,f,e):FancyBetMarketType.KHADDA.unique()==c.marketType?ExposureUtil.calculateFancyBetKhaddaExposure(a,b,c.runsRange,f,e):ExposureUtil.calculateFancyBetExposure(a,b,f,e);FancyBetHandler.appendExposure(a,b,f,e,l)}FancyBetHandler.removeExposure(a,
b)}}catch(p){Trace.printStackTrace(p)}};FancyBetHandler.appendExposure=function(a,b,c,f,e){b=$j("#fancyBetTable_"+a).find("#fancyBetMarketList").find("#fancyBetMarket_"+b);0!=b.length&&(c=WebSiteType.getInstanceOf(PageConfig.webSiteType),a={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1},c.isFancyFairGroup()&&(a.precision=0,a.roundingMode="DOWN"),c=b.find("#before"),e.exposureBeforeBet?
(f=e.exposureBeforeBet.marketExposure,c.removeClass(),0<=parseFloat(f)?c.addClass("win"):c.addClass("lose"),c.html(CurrencyUtil.formatter(f,a)),c.show()):c.hide(),b=b.find("#after"),e.exposureAfterBet?(e=e.exposureAfterBet.marketExposure,b.removeClass(),0<=parseFloat(e)?b.addClass("to-win"):b.addClass("to-lose"),b.html(CurrencyUtil.formatter(e,a)),b.show()):b.hide())};FancyBetHandler.removeExposure=function(a,b){var c=$j("#fancyBetTable_"+a).find("#fancyBetMarketList").find("#fancyBetMarket_"+b);
if(0!=c.length){var f=DataBase.fancyBet.getByMarketId(a,b);a=DataBase.fancyBetTxn.getByMarketId(a,b+"",null,null,CategoryType.FANCY_BET.unique());0<f.length?c.find("#after").show():c.find("#after").hide();0<a.length?c.find("#before").show():c.find("#before").hide()}};FancyBetHandler.updateExposure=function(a){a=$j("#fancyBetTable_"+a).find("#fancyBetMarketList");if(0!=a.length&&a.is(":visible")){var b=a.find("[id^=fancyBetMarket_]:visible");if(0!=b.length)for(var c in b){var f=a.find(b[c]),e=f.prop("eventId");
f=f.prop("marketId");if(null==e||null==f)break;FancyBetHandler.getExposure(e,f)}}}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.fancyBet={};var t=new HashMap;DataBase.fancyBet.add=function(d,h,k,n,a,b,c,f,e){d=DataBase.fancyBet.commonFancyBetObj(d,h,k,n,a,b,c,f,e);h=DataBase.fancyBet.generateKey(h,k,n);t.put(h,d);return d};DataBase.fancyBet.commonFancyBetObj=function(d,h,k,n,a,b,c,f,e){return{eventType:d,eventId:h,marketId:k,sideType:n,runs:a,odds:b,eventName:c,marketName:f,marketType:e}};DataBase.fancyBet.generateKey=function(d,h,k){return d+"_"+h+"_"+k};DataBase.fancyBet.get=function(d,h,k){d=DataBase.fancyBet.generateKey(d,
h,k);return t.get(d)};DataBase.fancyBet.remove=function(d,h,k){d=DataBase.fancyBet.generateKey(d,h,k);return t.remove(d)};DataBase.fancyBet.queryAll=function(){return t.values()};DataBase.fancyBet.clear=function(){t.clear()};DataBase.fancyBet.clearByEventId=function(d){$j.each(t.values(),function(h,k){d==k.eventId&&DataBase.fancyBet.remove(k.eventId,k.marketId,k.sideType)})};DataBase.fancyBet.updateStake=function(d,h,k,n){var a=!1;d=DataBase.fancyBet.get(d,h,k);if(null!=d){if(null==d.stake||null!=
d.stake&&d.stake!=n)a=!0;d.stake=n;return a}};DataBase.fancyBet.getForBet=function(d,h,k){d=DataBase.fancyBet.get(d,h,k);return{eventType:d.eventType,eventId:d.eventId,marketId:d.marketId,sideType:d.sideType,runs:d.runs,odds:d.odds,stake:d.stake,marketType:d.marketType}};DataBase.fancyBet.getByMarketId=function(d,h){var k=[];$j.each(t.values(),function(n,a){d==a.eventId&&h==a.marketId&&k.push(a)});return k};DataBase.fancyBet.updateLotteryBall=function(d,h,k,n){var a=DataBase.fancyBet.get(d,h,k);if(null!=
a)return a.lotteryBall=n,d=DataBase.fancyBet.generateKey(d,h,k),t.put(d,a),a};DataBase.fancyBet.addLotteryBet=function(d,h,k,n,a,b,c,f,e){d=DataBase.fancyBet.commonFancyBetObj(d,h,k,n,a,b,c,f,e);d.lotteryBall=[];h=DataBase.fancyBet.generateKey(h,k,n);t.put(h,d);return d};DataBase.fancyBet.getForLotteryBet=function(d,h,k){d=DataBase.fancyBet.get(d,h,k);return{eventType:d.eventType,eventId:d.eventId,marketId:d.marketId,sideType:d.sideType,runs:d.runs,odds:d.odds,stake:d.stake,marketType:d.marketType,
lotteryBall:d.lotteryBall}};DataBase.fancyBet.updateRuns=function(d,h,k,n){var a=DataBase.fancyBet.get(d,h,k);if(null!=a)return a.runs=n,d=DataBase.fancyBet.generateKey(d,h,k),t.put(d,a),a};DataBase.fancyBet.updateOdds=function(d,h,k,n){var a=DataBase.fancyBet.get(d,h,k);if(null!=a)return a.odds=n,d=DataBase.fancyBet.generateKey(d,h,k),t.put(d,a),a};DataBase.fancyBet.updateRunsOdds=function(d,h,k,n,a){var b=DataBase.fancyBet.get(d,h,k);if(null!=b)return b.runs=n,b.odds=a,d=DataBase.fancyBet.generateKey(d,
h,k),t.put(d,b),b};DataBase.fancyBet.updateThreeSelectionsRunsOdds=function(d,h,k,n,a,b){var c=DataBase.fancyBet.get(d,h,n);if(null!=c&&c.selectionId==k)return c.runs=a,c.odds=b,d=DataBase.fancyBet.generateKey(d,h,n),t.put(d,c),c};DataBase.fancyBet.addThreeSelectionsBet=function(d,h,k,n,a,b,c,f,e,g){d=DataBase.fancyBet.commonFancyBetObj(d,h,k,n,a,b,c,f,e);d.selectionId=g;h=DataBase.fancyBet.generateKey(h,k,n);t.put(h,d);return d};DataBase.fancyBet.getForThreeSelectionsBet=function(d,h,k){d=DataBase.fancyBet.get(d,
h,k);return{eventType:d.eventType,eventId:d.eventId,marketId:d.marketId,selectionId:d.selectionId,sideType:d.sideType,runs:d.runs,odds:d.odds,stake:d.stake,marketType:d.marketType}}})();

