"undefined"==typeof FeedingSiteMarketHandler&&(FeedingSiteMarketHandler={});
(function(){function n(a,d,b,c,g){var h=a.find("#feedingSiteHead");a=c.feedingSiteSelections;h.show();h.find("#minMaxWrap").show();a.sort(function(m,f){return FeedingSiteMarketUtil.sortSelections(m.sortPriority,f.sortPriority)});h.find("#minMaxInfo").html(CurrencyUtil.formatter(c.min,g)+" / "+CurrencyUtil.formatter(c.max,g));null==c.rebateRatio||0==c.rebateRatio?(h.find("#rebateRatio").hide(),h.find("#rebateName").hide()):(h.find("#rebateRatio").html(MathUtil.decimal.multiply(c.rebateRatio,100)+"%"),
h.find("#rebateRatio").show(),h.find("#rebateName").show());for(var t in a)g=a[t],h=b.find("#feedingSiteSelection_"+FeedingSiteMarketHandler.getSelectionKey(g)),0==h.length&&(h=k(d,b,g)),r(b,g,c);e(b,c)}function e(a,d){var b=d.status,c=MarketUtil.isCloseSite(d.closeSite,PageConfig.webSiteType);if(FeedingSiteMarketUtil.isInternal(b)||FeedingSiteMarketUtil.isClosed(b)||c)a.hide();else if(a.show(),FeedingSiteMarketUtil.isSuspend(b)||FeedingSiteMarketUtil.isClosePrice(b))FeedingSiteBetHandler.getExposure(d.eventId,
d.id),FeedingSiteMarketHandler.removeSelectClass()}function k(a,d,b){var c=a.find("#feedingSiteSelectionTemplate").clone();c.prop("id","feedingSiteSelection_"+FeedingSiteMarketHandler.getSelectionKey(b));c.prop("betfairEventId",b.betfairEventId);c.prop("eventType",b.eventType);c.prop("eventId",b.eventId);c.prop("marketId",b.marketId);c.prop("selectionName",b.selectionName);c.prop("gameType",b.gameType);c.prop("handicap",b.handicap);c.prop("updateDate",b.updateDate);c.find("#selectionName").html(b.selectionName);
c.show();p(c,c.find("#back_1"),b);a=a.find("#feedingSiteSuspendTemplate").clone();a.prop("id","feedingSiteSuspend_"+FeedingSiteMarketHandler.getSelectionKey(b));a.prop("eventId",b.eventId);a.prop("marketId",b.marketId);a.prop("selectionId",b.id);d.find("tbody").append(a);d.find("tbody").append(c);return c}function r(a,d,b){var c=a.find("#feedingSiteSelection_"+FeedingSiteMarketHandler.getSelectionKey(d));a=a.find("#feedingSiteSuspend_"+FeedingSiteMarketHandler.getSelectionKey(d));b=b.status;0!=a.length&&
(FeedingSiteMarketUtil.isInternal(b)?(a.find("span").html("Internal"),a.show()):FeedingSiteMarketUtil.isSuspend(b)?(a.find("span").html("Suspend"),a.show()):FeedingSiteMarketUtil.isClosePrice(b)?(a.find("span").html("Close Price"),a.show()):FeedingSiteMarketUtil.isClosed(b)?(a.find("span").html("Closed"),a.show()):a.hide(),0!=c.length&&(c.find("#info").prop("odds",d.exOdds),c.find("#info").html(0==d.exOdds?"":d.exOdds),SparkHandler.addSparkClass(c.find("#back_1"),d.exOdds)))}function p(a,d,b){a=function(c,
g,h,t,m,f,v){return function(){var q=g.find("#info").prop("odds")||0;0!=q&&("true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeFeedingSiteBet(c,h,t,m,f,q):(FeedingSiteMarketHandler.removeSelectClass(),g.addClass("select"),FeedingSiteBetHandler.appendBoard(c,h,t,m,f,q)))}}(a,d,b.eventType,b.eventId,b.marketId,b.id);d.on("click",a)}FeedingSiteMarketHandler.queryTask=
null;FeedingSiteMarketHandler.init=function(){if(FeedingSiteMarketHandler.isEnableFeedingSiteBet()){var a=$j("#overWrap");a.find("#feedingSiteWrap").show();a.find("#feedingSiteHead").show();a.find("#feedingSiteNoBet").show();FeedingSiteMarketHandler.initTask()}};FeedingSiteMarketHandler.isEnableFeedingSiteBet=function(){return PageConfig.isEnableFeedingSiteBet};FeedingSiteMarketHandler.initTask=function(){if(null==FeedingSiteMarketHandler.queryTask){var a=TaskExecuter.createTask(PageConfig.getFeedingSiteMarketsTaskCycleTime,
0,function(){FeedingSiteMarketHandler.queryFeedingSiteMarkets(this)});a.version=0;FeedingSiteMarketHandler.queryTask=a}else FeedingSiteMarketHandler.queryTask.isStop=!1;FeedingSiteMarketHandler.queryTask.run();TaskExecuter.execute()};FeedingSiteMarketHandler.abortTask=function(){null!=FeedingSiteMarketHandler.queryTask&&FeedingSiteMarketHandler.queryTask.stop()};FeedingSiteMarketHandler.queryFeedingSiteMarkets=function(a){$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/queryFeedingSiteMarkets",
data:{eventId:PageConfig.selectEventId,version:a.version},success:function(d){try{if(d&&(d.version>a.version&&(a.version=Math.max(d.version,a.version)),d.feedingSiteMarkets&&0!=d.feedingSiteMarkets.length)){DataBase.feedingSiteMarkets.update(d.feedingSiteMarkets);var b=d.feedingSiteMarkets,c=$j("#overWrap"),g=c.find("#feedingSiteWrap"),h=c.find("#feedingSiteTempTable"),t={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,
"trailingZeros,":!1};g.show();d=!1;for(var m in b){var f=b[m].status;if(FeedingSiteMarketUtil.isRunning(f)||FeedingSiteMarketUtil.isSuspend(f)||FeedingSiteMarketUtil.isClosePrice(f)){d=!0;break}}d?g.find("#feedingSiteNoBet").hide():g.find("#feedingSiteNoBet").show();for(var v in b){var q=b[v],w=q.status,u=g.find("#feedingSiteMarket_"+q.id);if(0==u.length){if(FeedingSiteMarketUtil.isClosed(w))continue;m=g;f=q;var l=m.find("#feedingSiteMarketTemplate").clone();l.prop("id","feedingSiteMarket_"+f.id);
l.prop("eventType",f.eventType);l.prop("betfairEventId",f.betfairEventId);l.prop("eventId",f.eventId);l.prop("marketId",f.id);l.prop("feedingEventName",f.feedingEventName);l.prop("feedingMarketName",f.feedingMarketName);l.prop("status",f.status);l.prop("isLive",f.isLive);l.prop("updateDate",f.updateDate);l.find("#marketName").html(f.feedingMarketName);m.append(l);u=l}n(g,h,u,q,t)}}}catch(x){Trace.printStackTrace(x)}finally{a.check(),TaskExecuter.execute()}},error:function(d,b,c){Trace.log(d.status);
Trace.log(c)}})};FeedingSiteMarketHandler.getSelectionKey=function(a){return a.eventId+"_"+a.marketId+"_"+a.id};FeedingSiteMarketHandler.removeSelectClass=function(){$j("#overWrap").find("#feedingSiteWrap").find("[id^=feedingSiteSelection_]").find("#back_1").removeClass("select")}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.feedingSiteMarkets={};var n=new TreeMap;DataBase.feedingSiteMarkets.update=function(e){for(var k=0;k<e.length;k++){var r=e[k],p=r.eventId,a=n.get(p);null==a&&(a=new TreeMap,n.put(p,a));a.put(r.id,r)}};DataBase.feedingSiteMarkets.get=function(e,k){e=n.get(e);return null==e?null:e.get(k)};DataBase.feedingSiteMarkets.queryByEvent=function(e){var k=n.get(e);null==k&&(k=new TreeMap,n.put(e,k));return k.values()};DataBase.feedingSiteMarkets.getSelection=function(e,k,r){e=DataBase.feedingSiteMarkets.get(e,
k);if(null==e)return null;e=e.feedingSiteSelections;if(null==e||0==e.length)return null;for(var p in e)if(null!=e[p]&&e[p].id==r)return e[p];return null};DataBase.feedingSiteMarkets.queryAll=function(){return n.values()}})();

