"undefined"==typeof FeedingSiteBetHandler&&(FeedingSiteBetHandler={});
(function(){function u(a,b,c,d,k){a.find("#placeBet").unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var f=q(a,c);var e=a.find("#inputStake"),l=parseFloat(e.val())||0,h=DataBase.feedingSiteBet.get(b,c,d),r="",t=g(h);if(!t){var v=DataBase.feedingSiteMarkets.get(h.eventId,h.marketId);h=v.min;v=v.max;l<h?(e.val(h),DataBase.feedingSiteBet.updateStake(b,c,d,h),r+=I18N.get("msg.member.minBet")):l>v&&(e.val(v),DataBase.feedingSiteBet.updateStake(b,c,d,v),
r+=I18N.get("msg.member.maxBet"))}""==r||t||p(f,"warning",r,!0);FeedingSiteBetHandler.getExposure(b,c);t?(h=DataBase.feedingSiteBet.getForBet(b,c,d),e=$j("#feedingSiteBetBar_"+k),0==e.length&&(e=$j("#overWrap").find("#feedingSiteTempTable").find("#feedingSiteBetBarTemplate").clone(),e.prop("id","feedingSiteBetBar_"+k),a.after(e)),FeedingSiteBetHandler.submitBet(h,e,f),a.hide()):a.find("#placeBet").removeClass("disable")}});a.find("#cancel").unbind("click").click(function(){DataBase.feedingSiteBet.clear();
a.hide();FeedingSiteMarketHandler.removeSelectClass();FeedingSiteBetHandler.getExposure(b,c)});a.find("#inputStake").click(function(){a.find("#inputStake").select()});a.find("#inputStake").change(function(){var f=parseFloat(a.find("#inputStake").val())||0;q(a,c);f=DataBase.feedingSiteBet.updateStake(b,c,d,f);FeedingSiteBetHandler.eventCalculate(a,b,c,d,f)});a.find("#inputStake").blur(function(){CoinHandler.hideStakePopupList();var f=parseFloat(a.find("#inputStake").val())||0;q(a,c);f=DataBase.feedingSiteBet.updateStake(b,
c,d,f);FeedingSiteBetHandler.eventCalculate(a,b,c,d,f)});a.find("#inputStake").keydown(function(f){var e=f.which;KeyEventUtils.isNumberKey(f)||KeyEventUtils.isBackspaceKey(e)||KeyEventUtils.isDeleteKey(e)||KeyEventUtils.isArrowKey(e)||KeyEventUtils.isTabKey(e)||KeyEventUtils.isEnterKey(e)||WindowEventUtil.stopEvent(f)});a.find("#inputStake").keyup(function(f){$j(this).val(function(l,h){return StringUtil.commaSeparateNumber(h)});var e=parseFloat(a.find("#inputStake").val())||0;q(a,c);e=DataBase.feedingSiteBet.updateStake(b,
c,d,e);FeedingSiteBetHandler.eventCalculate(a,b,c,d,e);f=f.which;KeyEventUtils.isEnterKey(f)&&a.find("#placeBet").click();KeyEventUtils.isTabKey(f)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()})}function g(a){if(null==a)return!1;var b=DataBase.feedingSiteMarkets.get(a.eventId,a.marketId);if(null==b)return!1;var c=b.min;b=b.max;if(!c||!b)return!1;a=parseFloat(a.stake||"0");return a<c||a>b?!1:!0}function m(a,b,c){var d=c.find("#progressBar"),k=n(a,b);d.css("width",k);c.find("#secRemain").html(MathUtil.decimal.divide(a,
10)+" sec remaining…");0<a&&(a--,setTimeout(function(){m(a,b,c)},100))}function n(a,b){a=MathUtil.decimal.subtract(b,a);b=MathUtil.decimal.divide(a,b);1<b&&(b=1);b=MathUtil.decimal.multiply(b,100);return Math.round(b)+"%"}function q(a,b){var c=$j("#overWrap").find("#feedingSiteBetMessage_"+b);0==c.length&&(c=$j("#overWrap").find("#feedingSiteTempTable").find("#feedingSiteBetMessageTemplate").clone(),c.prop("id","feedingSiteBetMessage_"+b));a.after(c);return c}function p(a,b,c,d,k,f){k=a.find("#header");
a.find("#info").contents().filter(function(){return 3==this.nodeType}).remove();a.find("#classWrap").removeClass("success").removeClass("error").removeClass("warning").addClass(b);null!=c&&k.html(c);null!=f&&(c=f.stake,b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),c=b.name+b.symbol+c+" at odds "+f.odds,CurrencyUtil.updateSetting({currencySymbol:b.symbol}),c=c+" Profit: "+UnMatchTicketUtil.getPL(f.odds,f.stake),k.html("Bet Matched"),k.after(c));a.find("#close").unbind("click").click(function(){a.fadeOut()});
d&&setTimeout(function(){a.fadeOut()},3E3);a.fadeIn()}FeedingSiteBetHandler.appendBoard=function(a,b,c,d,k,f){FeedingSiteBetHandler.clearBoard();var e=DataBase.feedingSiteBet.generateKey(c,d,k),l=DataBase.feedingSiteMarkets.getSelection(c,d,k);if(null!=l){b=DataBase.feedingSiteBet.add(b,c,d,k,f,l.selectionName,GameType.getInstanceOf(l.gameType).displayName,l.betfairEventId);f=!1;l=$j("#overWrap");var h=l.find("#feedingSiteBetBoard_"+e);if(0==h.length){l=l.find("#feedingSiteTempTable").find("#feedingSiteBetTemplate").clone();
h=l.find("#feedingSiteBetHeader");var r=l.find("#oddsHeader");l.prop("id","feedingSiteBetBoard_"+e);l.prop("eventId",c);l.prop("marketId",d);l.prop("selectionId",k);h.find("#gameTypeName").before(" "+b.selectionName+" ");h.find("#gameTypeName").html(b.gameTypeName);r.find("#odds").html(b.odds);u(l,c,d,k,e);h=l}e=h;a.after(e.fadeIn());e.find("#odds").html(b.odds);null!=PageConfig.userCoin&&0<PageConfig.userCoin?(a=DataBase.feedingSiteMarkets.get(c,d),b=parseFloat(PageConfig.userCoin),a.min&&parseFloat(a.min)>
PageConfig.userCoin&&(b=parseFloat(a.min)),e.find("#inputStake").val(b),f=DataBase.feedingSiteBet.updateStake(c,d,k,b)):e.find("#inputStake").val("");q(e,d);FeedingSiteBetHandler.eventCalculate(e,c,d,k,f);e.find("#odds").select();FeedingSiteBetHandler.updateExposure();CoinHandler.showFeedingSiteBetCoin(e)}};FeedingSiteBetHandler.clearBoard=function(){var a=$j("#feedingSiteWrap"),b=a.find("[id^=feedingSiteBetBoard_]");$j.each(b,function(c,d){d=a.find(d);0<d.length&&(d.prop("eventId"),d.prop("marketId"),
d.prop("selectionId"),d.hide())});DataBase.feedingSiteBet.clear()};FeedingSiteBetHandler.eventCalculate=function(a,b,c,d,k){d=DataBase.feedingSiteBet.get(b,c,d);d=g(d);a=a.find("#placeBet");d?a.removeClass("disable"):a.addClass("disable");FeedingSiteBetHandler.getExposure(b,c)};FeedingSiteBetHandler.submitBet=function(a,b,c,d){var k=0,f=0;$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/feedingSiteBet",data:{feedingSiteBets:JSON.stringify([a]),isOneClickBet:d},
beforeSend:function(){if(null!=b){b.show();var e=MathUtil.decimal.multiply(5,10),l=""+MathUtil.decimal.multiply(5,10);0<=e&&m(e,l,b)}},complete:function(){},success:function(e){try{if(e.error)null!=c?p(c,"error",e.error,!0):NoticeHandler.error(e.error);else if(0!=e.result.length){for(var l in e.result){var h=e.result[l];"SUCCESS"==h.status?(0==k&&0==f&&(k=h.eventId,f=h.marketId),null!=h.unMatchTicket&&DataBase.unMatchTicket.update([h.unMatchTicket]),null!=h.txn&&(DataBase.txn.update([h.txn]),null!=
c&&p(c,"success",null,!0,"txn",h.txn))):h.error&&(null!=c?p(c,"error",h.error,!0):NoticeHandler.error(h.error))}0!=k&&""!=f&&(TxnHandler.setEventIdAndMarketId(k,f,CategoryType.OW_SPORTSBOOK.unique()),k=0,f="");TxnHandler.updateOpenBetSelectionBox();TxnHandler.checkToHideOpenBets();var r=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(r))}}catch(t){Trace.printStackTrace(t)}finally{null!=b&&b.hide(),FeedingSiteMarketHandler.removeSelectClass(),
DataBase.feedingSiteBet.clear(),FeedingSiteBetHandler.getExposure(a.eventId,a.marketId)}},error:function(e){Trace.printStackTrace(e);null!=b&&b.hide()}});JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()};FeedingSiteBetHandler.getExposure=function(a,b){try{var c=DataBase.feedingSiteMarkets.get(a,b);if(null==c)Trace.log("FeedingSite market "+b+" is null");else{var d=c.feedingSiteSelections;if(null==d)Trace.log("feedingSiteSelections "+b+" is null");else{var k=DataBase.feedingSiteBet.getByMarketId(a,
b),f=DataBase.unMatchTicket.getByMarketId(a,b,null,CategoryType.OW_SPORTSBOOK.unique()),e=DataBase.txn.getByMarketId(a,b+"",null,null,CategoryType.OW_SPORTSBOOK.unique());if(0!=k.length||0!=f.length||0!=e.length){var l=ExposureUtil.calculateFeedingSiteBetExposure(a,b,c.numberOfWinner,c.numberOfActiveRunners,k,f,e);var h=$j("#feedingSiteWrap").find("#feedingSiteMarket_"+b);if(0!=h.length){var r=WebSiteType.getInstanceOf(PageConfig.webSiteType),t={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,
formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};r.isFancyFairGroup()&&(t.precision=0,t.roundingMode="DOWN");for(var v in d){var y=d[v],A=h.find("#feedingSiteSelection_"+FeedingSiteMarketHandler.getSelectionKey(y));if(0!=A.length){var w=A.find("#before"),x=A.find("#after");if(l.exposureBeforeBet){var B=l.exposureBeforeBet.betSelections;c=0;c=null==B[y.id]?B[0].minExposure:B[y.id].minExposure;w.removeClass();0<=parseFloat(c)?w.addClass("win"):w.addClass("lose");w.html(CurrencyUtil.formatter(c,
t));w.show()}else w.hide();if(l.exposureAfterBet){var C=l.exposureAfterBet.betSelections;c=0;c=null==C[y.id]?C[0].minExposure:C[y.id].minExposure;x.removeClass();0<=parseFloat(c)?x.addClass("to-win"):x.addClass("to-lose");x.html(CurrencyUtil.formatter(c,t));x.show()}else x.hide()}}}}var D=$j("#feedingSiteWrap").find("#feedingSiteMarket_"+b);if(0!=D.length){var z=D.find("[id^=feedingSiteSelection_]"),E=DataBase.feedingSiteBet.getByMarketId(a,b),F=DataBase.txn.getByMarketId(a,b+"",null,null,CategoryType.OW_SPORTSBOOK.unique());
0<E.length?z.find("#after").show():z.find("#after").hide();0<F.length?z.find("#before").show():z.find("#before").hide()}}}}catch(G){Trace.printStackTrace(G)}};FeedingSiteBetHandler.updateExposure=function(){var a=$j("#feedingSiteWrap");if(0!=a.length&&a.is(":visible")){var b=a.find("[id^=feedingSiteMarket_]:visible");if(0!=b.length)for(var c in b){var d=a.find(b[c]),k=d.prop("eventId"),f=d.prop("marketId");if(0==d.length||null==k||null==f)break;FeedingSiteBetHandler.getExposure(k,f)}}}})();
"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.feedingSiteBet={};var u=new HashMap;DataBase.feedingSiteBet.add=function(g,m,n,q,p,a,b,c){g={eventType:g,eventId:m,marketId:n,selectionId:q,odds:p,selectionName:a,gameTypeName:b,betfairEventId:c};m=DataBase.feedingSiteBet.generateKey(m,n,q);u.put(m,g);return g};DataBase.feedingSiteBet.generateKey=function(g,m,n){return g+"_"+m+"_"+n};DataBase.feedingSiteBet.get=function(g,m,n){g=DataBase.feedingSiteBet.generateKey(g,m,n);return u.get(g)};DataBase.feedingSiteBet.remove=function(g,
m,n){g=DataBase.feedingSiteBet.generateKey(g,m,n);return u.remove(g)};DataBase.feedingSiteBet.queryAll=function(){return u.values()};DataBase.feedingSiteBet.clear=function(){u.clear()};DataBase.feedingSiteBet.updateStake=function(g,m,n,q){var p=!1;g=DataBase.feedingSiteBet.get(g,m,n);if(null!=g){if(null==g.stake||null!=g.stake&&g.stake!=q)p=!0;g.stake=q;return p}};DataBase.feedingSiteBet.getForBet=function(g,m,n){g=DataBase.feedingSiteBet.get(g,m,n);return{eventType:g.eventType,eventId:g.eventId,
marketId:g.marketId,selectionId:g.selectionId,odds:g.odds,stake:g.stake,betfairEventId:g.betfairEventId,timestamp:(new Date).getTime()}};DataBase.feedingSiteBet.getByMarketId=function(g,m){var n=[];$j.each(u.values(),function(q,p){g==p.eventId&&m==p.marketId&&n.push(p)});return n}})();

