"undefined"==typeof FinancialBetHandler&&(FinancialBetHandler={});
(function(){function w(a,b,c,d,e,k,t){a.find("#placeBet").unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var g=m(a,b,c,d);var f=a.find("#inputStake"),n=parseFloat(f.val())||0,l=DataBase.financialBet.get(b,c,d,e),u="",x=h(l);if(!x){var v=DataBase.financialMarkets.get(l.apiSite,l.eventId,l.marketId);l=v.min;v=v.max;l&&v||Trace.log(I18N.get("msg.error.validation.minMaxBetIsNotValid"));n<l?(f.val(l),DataBase.financialBet.updateStake(b,c,d,e,l),u+=I18N.get("msg.member.minBet")):
n>v&&(f.val(v),DataBase.financialBet.updateStake(b,c,d,e,v),u+=I18N.get("msg.member.maxBet"))}""==u||x||r(g,"warning",u,!0);FinancialBetHandler.getExposure(b,c,d);x?(l=DataBase.financialBet.getForBet(b,c,d,e),f=$j("#financialBetBar_"+k),0==f.length&&(f=$j("#overWrap").find("#financialBarTemplate").clone(),f.prop("id","financialBetBar_"+k),a.after(f)),n=a.find("#financialAcceptAnyOdds").is(":checked")?1:0,FinancialBetHandler.submitBet(l,b,n,f,g),a.hide()):a.find("#placeBet").removeClass("disable")}});
a.find("#cancel").unbind("click").click(function(){DataBase.financialBet.clear();a.hide();FinancialMarketHandler.removeSelectClass();FinancialBetHandler.getExposure(b,c,d)});a.find("#inputStake").unbind("click").click(function(){a.find("#inputStake").select()});a.find("#inputStake").change(function(){var g=parseFloat(a.find("#inputStake").val())||0;m(a,b,c,d);g=DataBase.financialBet.updateStake(b,c,d,e,g);FinancialBetHandler.eventCalculate(a,b,c,d,e,g)});a.find("#inputStake").blur(function(){CoinHandler.hideStakePopupList();
var g=parseFloat(a.find("#inputStake").val())||0;m(a,b,c,d);g=DataBase.financialBet.updateStake(b,c,d,e,g);FinancialBetHandler.eventCalculate(a,b,c,d,e,g)});a.find("#inputStake").keydown(function(g){var f=g.which;KeyEventUtils.isNumberKey(g)||KeyEventUtils.isBackspaceKey(f)||KeyEventUtils.isDeleteKey(f)||KeyEventUtils.isArrowKey(f)||KeyEventUtils.isTabKey(f)||KeyEventUtils.isEnterKey(f)||WindowEventUtil.stopEvent(g)});a.find("#inputStake").keyup(function(g){$j(this).val(function(n,l){return StringUtil.commaSeparateNumber(l)});
var f=parseFloat(a.find("#inputStake").val())||0;m(a,b,c,d);f=DataBase.financialBet.updateStake(b,c,d,e,f);FinancialBetHandler.eventCalculate(a,b,c,d,e,f);g=g.which;KeyEventUtils.isEnterKey(g)&&a.find("#placeBet").click();KeyEventUtils.isTabKey(g)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()})}function h(a){if(null==a)return!1;var b=DataBase.financialMarkets.get(a.apiSite,a.eventId,a.marketId);if(null==b)return!1;var c=b.min;b=b.max;if(!c||!b)return!1;a=parseFloat(a.stake||
"0");return a<c||a>b?!1:!0}function p(a,b,c){var d=c.find("#progressBar"),e=q(a,b);d.css("width",e);c.find("#secRemain").html(MathUtil.decimal.divide(a,10)+" sec remaining…");0<a&&(a--,setTimeout(function(){p(a,b,c)},100))}function q(a,b){a=MathUtil.decimal.subtract(b,a);b=MathUtil.decimal.divide(a,b);1<b&&(b=1);b=MathUtil.decimal.multiply(b,100);return Math.round(b)+"%"}function m(a,b,c,d){var e=$j("#overWrap").find("#financialBetMessage_"+(b+"_"+c+"_"+d));0==e.length&&(e=$j("#overWrap").find("#financialBetMessageTemplate").clone(),
e.prop("id","financialBetMessage_"+(b+"_"+c+"_"+d)));a.after(e);return e}function r(a,b,c,d,e,k){e=a.find("#header");UiUtils.removeContents(a.find("#info"));a.find("#classWrap").removeClass("success").removeClass("error").removeClass("warning").addClass(b);null!=c&&e.html(c);null!=k&&(c=k.stake,b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),c=b.name+b.symbol+c+" at odds "+k.odds,CurrencyUtil.updateSetting({currencySymbol:b.symbol}),c=FancySideType.YES.unique()==k.sideType?c+" Profit: ":c+
" Liability: ",c+=MyTransactionUtils.getFancyBetPL(k.odds,k.stake),e.html("Bet Matched"),e.after(c));a.find("#close").unbind("click").click(function(){a.fadeOut()});d&&setTimeout(function(){a.fadeOut()},3E3);a.fadeIn()}FinancialBetHandler.appendBoard=function(a,b,c,d,e,k,t,g){FinancialBetHandler.clearBoard(b);k=DataBase.financialBet.generateKey(d,b,c,e);var f=DataBase.financialMarkets.get(d,b,c);if(null!=f){f=DataBase.financialBet.add(d,b,c,e,t,g,f.marketName);t=!1;g=$j("#overWrap");var n=g.find("#financialBetBoard_"+
k);if(0==n.length){g=g.find("#financialBetTemplate").clone();g.find("#financialBetHeader");n=g.find("#oddsHeader");var l=FancySideType.YES.unique()==e?SideType.Back.name:SideType.Lay.name;g.find("#classWrap").removeClass("slip-back").removeClass("slip-lay").addClass("slip-"+l.toLowerCase());g.prop("id","financialBetBoard_"+k);g.prop("eventId",b);g.prop("marketId",c);g.prop("sideType",e);g.prop("apiSite",d);g.attr("marketPk",DataBase.financialMarkets.getEventMarketKey(d,b,c));n.find("#odds").html(f.odds);
w(g,d,b,c,e,k,f);n=g}n.find("#financialAcceptAnyOdds").prop("checked",TopMenuHandler.isAcceptAnyOdds("financial"));k=n;a.after(k.fadeIn());k.find("#price").html(f.price);k.find("#odds").html(f.odds);null!=PageConfig.userCoin&&0<PageConfig.userCoin?(f=DataBase.financialMarkets.get(d,b,c),a=parseFloat(PageConfig.userCoin),f.min&&parseFloat(f.min)>PageConfig.userCoin&&(a=parseFloat(f.min)),k.find("#inputStake").val(a),t=DataBase.financialBet.updateStake(d,b,c,e,a)):k.find("#inputStake").val("");m(k,
d,b,c);FinancialBetHandler.eventCalculate(k,d,b,c,e,t);k.find("#odds").select();FinancialBetHandler.updateExposure();CoinHandler.showFinancialBetCoin(k)}};FinancialBetHandler.clearBoard=function(a){var b=$j("#overWrap").find("#financialTable_"+a);a=b.find("[id^=financialBetBoard_]");$j.each(a,function(c,d){d=b.find(d);0<d.length&&(d.prop("eventId"),d.prop("marketId"),d.hide())});DataBase.financialBet.clear()};FinancialBetHandler.removeBoardByMarket=function(a,b,c){var d=$j("#overWrap"),e=DataBase.financialMarkets.getEventMarketKey(a,
b,c);d.find("[id^=financialBetBoard_][marketPk="+e+"]").hide();DataBase.financialBet.removeByMarket(a,b,c);FinancialBetHandler.getExposure(a,b,c)};FinancialBetHandler.resetAllBetBoard=function(){$j("#overWrap").find("[id^=financialBetBoard_]").hide();FinancialMarketHandler.removeSelectClass();FinancialBetHandler.updateExposure()};FinancialBetHandler.eventCalculate=function(a,b,c,d,e,k){e=DataBase.financialBet.get(b,c,d,e);e=h(e);a=a.find("#placeBet");e?a.removeClass("disable"):a.addClass("disable");
FinancialBetHandler.getExposure(b,c,d)};FinancialBetHandler.showDelayBetting=function(a,b,c){var d=DataBase.financialMarkets.get(a,b,c);d=d.delayBetting?1E3*parseInt(d.delayBetting):0;if(0!=d){var e=FinancialBetHandler.getDelayBettingElem(a,b,c);null!=e&&0!=e.length&&(e.find("#info").html(""),e.fadeIn(),setTimeout(function(){e.find("#info").html("");e.fadeOut()},d))}};FinancialBetHandler.getDelayBettingElem=function(a,b,c){var d=$j("#overWrap").find("#financialTable_"+b).find("#financialMarketList");
a=DataBase.financialMarkets.getEventMarketKey(a,b,c);a=d.find("#financialMarket_"+a);if(0==a.length||!a.is(":visible"))return null;b=d.find("#suspend_"+c);if(0==b.length||b.is(":visible"))return null;b=d.find("#delayBetting_"+c);0==b.length&&(b=d.find("#delayTemplate").clone(),b.prop("id","delayBetting_"+c),b.find("#info").html(""),a.before(b));return b};FinancialBetHandler.hideDelayBetting=function(a,b,c){a=FinancialBetHandler.getDelayBettingElem(a,b,c);null!=a&&0!=a.length&&(a.find("#info").html(""),
a.hide())};FinancialBetHandler.submitBet=function(a,b,c,d,e,k){var t=0,g=0;$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/financialBet",data:{financialBets:JSON.stringify([a]),isOneClickBet:k,isAcceptAnyOdds:c,apiSite:b},beforeSend:function(){if(null!=d){d.show();var f=MathUtil.decimal.multiply(5,10),n=""+MathUtil.decimal.multiply(5,10);0<=f&&p(f,n,d)}FinancialBetHandler.showDelayBetting(a.apiSite,a.eventId,a.marketId)},complete:function(){},success:function(f){try{if(f.error)null!=
e?r(e,"error",f.error,!0):NoticeHandler.error(f.error),FinancialBetHandler.hideDelayBetting(a.apiSite,a.eventId,a.marketId);else if(0==f.result.length)FinancialBetHandler.hideDelayBetting(a.apiSite,a.eventId,a.marketId);else{for(var n in f.result){var l=f.result[n];"SUCCESS"==l.status?(0==t&&0==g&&(t=l.eventId,g=l.marketId),null!=l.financialTxn&&(DataBase.financialTxn.update([l.financialTxn]),null!=e&&r(e,"success",null,!0,"financialTxn",l.financialTxn))):l.error&&(null!=e?r(e,"error",l.error,!0):
NoticeHandler.error(l.error),FinancialBetHandler.hideDelayBetting(a.apiSite,a.eventId,a.marketId))}0!=t&&""!=g&&(f="",ApiSiteType.TS.unique()==b&&(f=CategoryType.TS_BINARY.unique()),TxnHandler.setEventIdAndMarketId(t,g,f),t=0,g="");TxnHandler.updateOpenBetSelectionBox();TxnHandler.checkToHideOpenBets();var u=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(u))}}catch(x){Trace.printStackTrace(x)}finally{null!=d&&d.hide(),FinancialMarketHandler.removeSelectClass(),
DataBase.financialBet.clear(),FinancialBetHandler.getExposure(a.apiSite,a.eventId,a.marketId)}},error:function(f){Trace.printStackTrace(f);null!=d&&d.hide();FinancialBetHandler.hideDelayBetting(a.apiSite,a.eventId,a.marketId)}});JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()};FinancialBetHandler.getExposure=function(a,b,c){try{var d=DataBase.financialMarkets.get(a,b,c);if(null==d)Trace.printStackTrace("financialMarkets "+c+" is null");else{var e=DataBase.financialBet.getByMarketId(a,
b,c),k=DataBase.financialTxn.getByMarketId(b,c,null,null,CategoryType.TS_BINARY.unique());if(0!=e.length||0!=k.length){var t=ExposureUtil.calculateFinancialExposure(a,b,c,d.numberOfWinner,d.numberOfActiveRunners,e,k);var g=$j("#overWrap").find("#financialMarket_"+DataBase.financialMarkets.getEventMarketKey(a,b,c));if(0!=g.length){var f=WebSiteType.getInstanceOf(PageConfig.webSiteType),n={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,
"trailingZeros,":!1};f.isFancyFairGroup()&&(n.precision=0,n.roundingMode="DOWN");var l=g.find("#before"),u=g.find("#after");if(t.exposureBeforeBet){var x=t.exposureBeforeBet.marketExposure;l.removeClass();0<=parseFloat(x)?l.addClass("win"):l.addClass("lose");l.html(CurrencyUtil.formatter(x,n));l.show()}else l.hide();if(t.exposureAfterBet){var v=t.exposureAfterBet.marketExposure;u.removeClass();0<=parseFloat(v)?u.addClass("to-win"):u.addClass("to-lose");u.html(CurrencyUtil.formatter(v,n));u.show()}else u.hide()}}var y=
$j("#overWrap").find("#financialMarket_"+DataBase.financialMarkets.getEventMarketKey(a,b,c));if(0!=y.length){var z=DataBase.financialBet.getByMarketId(a,b,c),A=DataBase.financialTxn.getByMarketId(b,c,null,null,CategoryType.TS_BINARY.unique());0<z.length?y.find("#after").show():y.find("#after").hide();0<A.length?y.find("#before").show():y.find("#before").hide()}}}catch(B){Trace.printStackTrace(B)}};FinancialBetHandler.updateExposure=function(){var a=$j("#overWrap");if(0!=a.length&&a.is(":visible")){var b=
a.find("[id^=financialMarket_]:visible");if(0!=b.length)for(var c in b){var d=a.find(b[c]),e=d.prop("eventId"),k=d.prop("marketId"),t=d.prop("apiSite");if(0==d.length||null==e||null==k)break;FinancialBetHandler.getExposure(t,e,k)}}}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.financialBet={};var w=new HashMap;DataBase.financialBet.add=function(h,p,q,m,r,a,b){r={apiSite:h,eventId:p,marketId:q,price:r,odds:a,sideType:m,marketName:b};h=DataBase.financialBet.generateKey(h,p,q,m);w.put(h,r);return r};DataBase.financialBet.generateKey=function(h,p,q,m){return h+"_"+p+"_"+q+"_"+m};DataBase.financialBet.get=function(h,p,q,m){h=DataBase.financialBet.generateKey(h,p,q,m);return w.get(h)};DataBase.financialBet.remove=function(h,p,q,m){h=DataBase.financialBet.generateKey(h,
p,q,m);return w.remove(h)};DataBase.financialBet.removeByMarket=function(h,p,q){var m=DataBase.financialBet.getByMarketId(h,p,q);$j.each(m,function(r){var a=m[r];if(null==a)return!0;for(r in SideType)DataBase.financialBet.remove(a.apiSite,a.eventId,a.marketId,SideType[r].value)})};DataBase.financialBet.queryAll=function(){return w.values()};DataBase.financialBet.clear=function(){w.clear()};DataBase.financialBet.updateStake=function(h,p,q,m,r){var a=!1;h=DataBase.financialBet.get(h,p,q,m);if(null!=
h){if(null==h.stake||null!=h.stake&&h.stake!=r)a=!0;h.stake=r;return a}};DataBase.financialBet.updatePriceOdds=function(h,p,q,m,r,a){h=DataBase.financialBet.get(h,p,q,m);null!=h&&(h.price=r,h.odds=a)};DataBase.financialBet.getForBet=function(h,p,q,m){h=DataBase.financialBet.get(h,p,q,m);return{apiSite:h.apiSite,eventId:h.eventId,marketId:h.marketId,sideType:h.sideType,odds:h.odds,price:h.price,stake:h.stake}};DataBase.financialBet.getByMarketId=function(h,p,q){var m=[];$j.each(w.values(),function(r,
a){p==a.eventId&&q==a.marketId&&h==a.apiSite&&m.push(a)});return m}})();

