"undefined"==typeof FinancialMarketHandler&&(FinancialMarketHandler={});
(function(){function n(a,c,b){var d=new Date;$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/queryFinancialMarkets",data:c,success:function(e){try{if(e){null!=a&&(a.isInit=!1,e.version>a.version&&(a.version=Math.max(e.version,a.version)));var f=new Date,g=f.getTime()-d.getTime();Trace.info("UPDATE start:"+d.toString()+" end:"+f.toString()+" ms:"+g+" market num: "+(null==e.financialMarket?0:e.financialMarket.length));FinancialMarketHandler.updateFinancialEvent(b,e,c)}}catch(h){Trace.printStackTrace(h)}},
error:function(e,f,g){Trace.log(e.status);Trace.log(g)}})}function k(a,c){var b=r.get(a);null==b&&(b=new HashMap,r.put(a,b));b.put(c,-1)}function l(a,c,b){if(null!=b){var d=r.get(a);null==d&&(d=new HashMap,r.put(a,d));a=d.get(c);null==a||b<a||d.put(c,b)}}function p(a,c,b){a=r.get(a);null!=a&&null!=a.get(c)&&a.remove(c)}function v(a,c){var b=c.eventId,d=a.find("#financialTable_"+b);0==d.length&&(d=a.find("#financialTableTemplate").clone(),d.prop("id","financialTable_"+b),a.find("#financialTableTemplate").after(d),
d.show(),c.periodType==FinancialPeriodType.Daily.unique()&&(d.find("#dailyTabHead").addClass("select"),d.find("#dailyTabHead").find("strong").html(c.eventName),a=function(){return function(){location.href="/exchange/member/financialMarket.jsp?periodType="+FinancialPeriodType.Daily.unique()}}(),d.find("#dailyTabHead").unbind("click").click(a)));return d}function B(a,c,b,d,e,f){a=c.find("#financialMarketList");c={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,
formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};f.sort(function(t,u){return FinancialMarketUtil.sortMarkets(t.sort,u.sort)});for(var g in f){var h=f[g],m=h.id;d=h.eventId;var q=h.marketStatus;d=DataBase.financialMarkets.getEventMarketKey(b,d,m);d=a.find("#financialMarket_"+d);if(0==d.length){if(FinancialMarketUtil.isClosed(q)){p(b,m);continue}d=C(a,b,h);k(b,m)}else l(b,m,h.version);D(a,d,h,c,e)}E(a)}function C(a,c,b){var d=a.find("#financialMarketTemplate").clone(),e=a.find("#suspendTemplate").clone(),
f=DataBase.financialMarkets.getEventMarketKey(c,b.eventId,b.id);d.prop("id","financialMarket_"+f);d.prop("marketId",b.id);d.prop("eventId",b.eventId);d.prop("marketName",b.marketName);d.prop("marketStatus",b.marketStatus);d.prop("apiSite",c);d.find("#marketName").find("a").after(b.marketName);d.prop("sort",b.sort);y(d,d.find("#lay_1"),b,FancySideType.NO.unique());y(d,d.find("#back_1"),b,FancySideType.YES.unique());e.prop("id","suspend_"+b.id);a.append(e);a.append(d);d.find("#financialBookBtn").off("click").on("click",
function(){window.open("/exchange/member/market/financialMarketBook.jsp?apiSite="+c+"&eventId="+b.eventId+"&marketId="+b.id,"_blank","resizable=no,width=600,height=650")});return d}function D(a,c,b,d,e){c.prop("sort",b.sort);var f=c.find("#lay_1"),g=c.find("#back_1");UiUtils.removeContents(f.find("#priceInfo"));UiUtils.removeContents(g.find("#priceInfo"));z(f,b.layPrice,b.layOdds);z(g,b.backPrice,b.backOdds);A(FancySideType.NO.unique(),b);A(FancySideType.YES.unique(),b);c.find("#minMax").html(CurrencyUtil.formatter(b.min,
d)+" / "+CurrencyUtil.formatter(b.max,d));0==b.rebateRatio?(c.find("#rebateName").hide(),c.find("#rebate").hide()):(c.find("#rebateName").show(),c.find("#rebate").show(),c.find("#rebate").html(MathUtil.decimal.multiply(b.rebateRatio,100)+"%"));null!=b.marketCloseDate&&c.find("#remarkFirstRow").html(b.marketCloseDate).show();d=FinancialEventUtil.isSuspend(e.eventStatus);e=b.marketStatus;a=a.find("#suspend_"+b.id);a.find("#suspendClass").removeClass("fancy-suspend").removeClass("fancy-suspend-white");
c.attr("status",e);a.attr("status",e);FinancialMarketUtil.isOnline(e)&&(c.show(),a.hide());FinancialMarketUtil.isSuspend(e)||d?(a.find("#suspendClass").addClass("fancy-suspend"),a.find("#info").html("Suspend"),c.show(),a.show(),w(b.apiSite,b.eventId,b.id)):FinancialMarketUtil.isClosed(e)?(c.hide(),a.hide(),w(b.apiSite,b.eventId,b.id)):FinancialMarketUtil.isReady(e)?(a.find("#suspendClass").addClass("fancy-suspend"),a.find("#info").html("Starting Soon"),c.show(),a.show(),w(b.apiSite,b.eventId,b.id)):
a.hide();null!=b.marketInfo?(b=JSON.parse(b.marketInfo),null!=b.remark&&""!=$j.trim(b.remark)?c.find("#remarkSecondRow").html(b.remark).show():c.find("#remarkSecondRow").html("").hide()):c.find("#remarkSecondRow").html("").hide()}function y(a,c,b,d){a=function(e,f,g,h,m,q,t){return function(){var u=f.find("#priceInfo").prop("price")||0,x=f.find("#priceInfo").prop("odds")||0;0!=u&&0!=x&&("true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?
OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeFinancialBet(e,m,g,h,q,u,x):(FinancialMarketHandler.removeSelectClass(),f.addClass("select"),FinancialBetHandler.appendBoard(e,g,h,m,q,t,u,x)))}}(a,c,b.eventId,b.id,b.apiSite,d,b.marketName);c.on("click",a)}function z(a,c,b){var d=a.find("#priceInfo");d.find("span").before(0==c?"":c);d.find("span").html(0==b?"":b);d.prop("price",c);d.prop("odds",b);SparkHandler.addFancyBetSpark(a,c,b)}function A(a,c){if(PageConfig.enableBetboardSyncRunsOdds){var b=
$j("#overWrap"),d=DataBase.financialBet.generateKey(c.apiSite,c.eventId,c.id,a);b=b.find("#financialBetBoard_"+d);d=a==FancySideType.NO.unique()?c.layPrice:c.backPrice;var e=a==FancySideType.NO.unique()?c.layOdds:c.backOdds;!b||b.find("#price").text()==d&&b.find("#odds").text()==e||(b.find("#price").html(d),b.find("#odds").html(e),DataBase.financialBet.updatePriceOdds(c.apiSite,c.eventId,c.id,a,d,e))}}function w(a,c,b){FinancialBetHandler.removeBoardByMarket(a,c,b);FinancialBetHandler.getExposure(a,
c,b);FinancialMarketHandler.removeSelectClass()}function E(a){var c=a.find("[id^=financialMarket_]:visible");if(!(2>c.length)){for(var b=!1,d=0;d<c.length&&!(d+1>=c.length);d++){var e=a.find(c[d]),f=a.find(c[d+1]);if(!(0==e.length||0>e.prop("id").indexOf("financialMarket_")||0==f.length||0>f.prop("id").indexOf("financialMarket_"))&&e.prop("sort")>f.prop("sort")){b=!0;break}}b&&(c=c.sort(function(g,h){g=a.find(g);h=a.find(h);return FinancialMarketUtil.sortMarkets(g.prop("sort"),h.prop("sort"))}),a.append(c),
$j.each(c,function(g,h){h=a.find(h);g=h.prop("apiSite");var m=h.prop("eventId"),q=h.prop("marketId");h=DataBase.financialMarkets.getEventMarketKey(g,m,q);var t=a.find("#suspend_"+q);0<t.length&&a.find("#financialMarket_"+h).before(t);g=a.find("[id^=financialBetBoard_"+g+"_"+m+"_"+q+"_]");0<g.length&&a.find("#financialMarket_"+h).after(g)}))}}FinancialMarketHandler.queryTasks=[];var r=new HashMap;FinancialMarketHandler.init=function(a){FinancialMarketHandler.isEnableTsFinancial()&&FinancialMarketHandler.initTask(a)};
FinancialMarketHandler.isEnableTsFinancial=function(){return PageConfig.isEnableTsFinancial};FinancialMarketHandler.isShowTsFinancial=function(){return FinancialMarketHandler.isEnableTsFinancial()&&PageConfig.hasTsBinaryMarkets};FinancialMarketHandler.initTask=function(a){if(null==FinancialMarketHandler.queryTasks[a]){var c=TaskExecuterV2.createTask(PageConfig.getFinancialEventTaskCycleTime,0,function(){FinancialMarketHandler.queryFinancialMarkets(this,a)});c.apiSite=a;FinancialMarketHandler.queryTasks[a]=
c}else FinancialMarketHandler.queryTasks[a].isStop=!1;FinancialMarketHandler.queryTasks[a].isInit=!0;FinancialMarketHandler.queryTasks[a].version=0;FinancialMarketHandler.queryTasks[a].run();TaskExecuterV2.execute()};FinancialMarketHandler.abortTask=function(a){null!=FinancialMarketHandler.queryTasks[a]&&FinancialMarketHandler.queryTasks[a].stop()};FinancialMarketHandler.queryFinancialMarkets=function(a,c){try{var b={eventId:PageConfig.selectEventId,apiSite:a.apiSite,version:a.version};if(!a.isInit){var d=
"",e=r.get(c);if(null!=e&&0!=e.size()){var f=e.keySet();for(e=0;e<f.length;e++)d+=f[e].toString()+",";b.marketIds=d}}n(a,b,c)}catch(g){Trace.printStackTrace(g)}finally{a.check(),TaskExecuterV2.execute()}};FinancialMarketHandler.updateFinancialEvent=function(a,c,b){if(null!=c)if(b=c.eventId,FinancialEventUtil.isClosed(c.eventStatus))MessageUtils.showThenGoToIndex("event is closed");else{var d=$j("#overWrap"),e=v(d,c);var f=c.eventUpdateDate,g=c.gameProductUpdateDate;if(e.prop("eventUpdateDate")!=f||
e.prop("gameProductUpdateDate")!=g)e.prop("eventUpdateDate",f),e.prop("gameProductUpdateDate",g),GameProductUtils.isClose(c.gameProductStatus)?e.hide():e.show(),f=FinancialEventUtil.isSuspend(c.eventStatus),g=e.find("[id^=suspend_][status="+FinancialMarketStatusType.ONLINE.unique()+"]"),g.find("#suspendClass").removeClass("fancy-suspend").removeClass("fancy-suspend-white"),f?(g.find("#suspendClass").addClass("fancy-suspend"),g.find("#info").html("Suspend"),g.show()):g.hide();f=c.financialMarket;null!=
f&&0!=f.length&&(DataBase.financialMarkets.update(a,b,f),B(d,e,a,b,c,f))}};FinancialMarketHandler.removeSelectClass=function(){var a=$j("#overWrap").find("[id^=financialMarket_]");a.find("#lay_1").removeClass("select");a.find("#back_1").removeClass("select")}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.financialMarkets={};var n=new HashMap;DataBase.financialMarkets.update=function(k,l,p){l=DataBase.financialMarkets.getEventKey(k,l);k=n.get(l);null==k&&(k=new HashMap,n.put(l,k));for(l=0;l<p.length;l++){var v=p[l];k.put(v.id,v)}};DataBase.financialMarkets.getEventKey=function(k,l){return l};DataBase.financialMarkets.getEventMarketKey=function(k,l,p){return k+"_"+l+"_"+p};DataBase.financialMarkets.queryAll=function(){return n.values()};DataBase.financialMarkets.get=function(k,
l,p){k=DataBase.financialMarkets.getEventKey(k,l);k=n.get(k);return null==k?null:k.get(p)};DataBase.financialMarkets.queryMarkets=function(k,l){k=DataBase.financialMarkets.getEventKey(k,l);l=n.get(k);null==l&&(l=new HashMap,n.put(k,l));return l.values()}})();

