"undefined"==typeof FullMarketViewHandler&&(FullMarketViewHandler={});
(function(){function p(a){if(0==location.hash.indexOf("#marketId#")){var c=location.hash.split("#");if(4==c.length){var g=c[2];PageConfig.selectEventId=c[3];PageConfig.selectMarketId=g}}if(-1==PageConfig.selectEventId||null==PageConfig.selectMarketId)a.check(),TaskExecuterV2.execute();else{PageConfig.selectEventType==EventType.ELECTION.unique()&&$j("#noTeam .game-name").css({padding:"5px 10px 5px 10px"});try{$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?
QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryFullMarketsPath,data:{eventId:PageConfig.selectEventId,marketId:PageConfig.selectMarketId,selectionTs:-1,isGetRunnerMetadata:a.isGetRunnerMetadata,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(d){JsCache.get("#loading").hide();if(d&&(-1==PageConfig.selectEventType&&PageConfig.selectEventId==d.eventId&&PageConfig.selectMarketId==d.marketId&&(PageConfig.selectEventType=d.eventType),null!=d.market&&null!=d.market.eventId&&
DataBase.markets.update(d.market.eventId,[d.market]),FullMarketViewHandler.updateFullMarkets(d),"true"==PageConfig.ENABLE_CASH_OUT&&CashOutHandler.updateCashOutInfo(d.cash),null!=d.market&&EventType.ELECTION.unique()!=d.eventType&&EventType.FANCYBET.unique()!=d.eventType)){d=d.market;var b=$j("#gameHead");PageConfig.hasLiveMatchTracker&&(b=$j("#liveMatchGameHead"));b=b.find("#minMaxBox");null==d.betLimitSetting||0==d.betLimitSetting.length?b.hide():(d=d.betLimitSetting,d.minBet?(b.find("#minMaxDt").show(),
b.find("#maxDt").hide(),b.find("#minMaxInfo").html(MathUtil.roundp(d.minBet,2)+" / "+MathUtil.roundp(d.maxBet,2))):(b.find("#maxDt").show(),b.find("#minMaxDt").hide(),b.find("#minMaxInfo").html(MathUtil.roundp(d.maxBet,2))),b.show())}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}})}catch(d){Trace.printStackTrace(d)}finally{a.check(),TaskExecuterV2.execute()}}}
function l(a,c){a.find("#scoresEvent").html(c.marketName+'<img src="/images/transparent.gif">')}function q(a){a=a.sort(function(c,g){return MarketUtil.isClosed(c.status)?1:MarketUtil.isClosed(g.status)?-1:"WIN"==c.marketType&&"WIN"==g.marketType?c.marketTime.localeCompare(g.marketTime):"WIN"==c.marketType?-1:"WIN"==g.marketType?1:c.marketTime.localeCompare(g.marketTime)})[0];return MarketUtil.isOpen(a.status)?a:null}FullMarketViewHandler.getFullMarketsTask=null;FullMarketViewHandler.initTask=function(){if(null==
FullMarketViewHandler.getFullMarketsTask){var a=TaskExecuterV2.createTask(PageConfig.getFullMarketsTaskCycleTime,0,function(){p(this)});FullMarketViewHandler.getFullMarketsTask=a}else FullMarketViewHandler.getFullMarketsTask.isStop=!1;a.isGetRunnerMetadata=!0;FullMarketViewHandler.getFullMarketsTask.run();TaskExecuterV2.execute()};FullMarketViewHandler.abortTask=function(){null!=FullMarketViewHandler.getFullMarketsTask&&FullMarketViewHandler.getFullMarketsTask.stop()};FullMarketViewHandler.updateFullMarkets=
function(a){var c=a.eventType,g=a.eventId,d=a.marketId,b=a.market,r=a.gameProductStatus;if(PageConfig.selectMarketId!=d)Trace.info("selectMarketId: "+PageConfig.selectMarketId+" marketId: "+d);else{var f=EventType.getInstanceOf(c),h=0<=PageConfig.isTodaysCard?!0:!1;if(null==b||null==b.marketId)null!=f&&f.isRacingEvent()&&h&&(MemberPage.view("marketClose"),UiUtils.appendHeight());else{var k=$j("#fullMarketBetsWrap"),t=$j("#fullMarketBoard"),e=$j("[id^='fullSelection_']");k.attr("eventType",c);k.attr("eventId",
g);k.attr("marketId",d);if(null!=e&&0<e.length)for(var m=0;m<e.length;m++){var n=e[m];$j(n).attr("marketId")!=d.replace(".","_")&&$j(n).remove()}e=MarketUtil.isCloseSite(b.closeSite,PageConfig.webSiteType)||EventUtils.isCloseSite(a.eventCloseSite,PageConfig.webSiteType)||CompetitionUtils.isCloseSite(a.competitionCloseSite,PageConfig.webSiteType);if(f.isRacingEvent()&&(MarketUtil.isClosed(b.status)||e)&&!h)FullMarketViewHandler.changeToNextOpenRacingMarket();else if(f.isRacingEvent()||!MarketUtil.isClosed(b.status)&&
!e)if(f.isRacingEvent()&&MarketUtil.isClosed(b.status)&&h)MemberPage.view("marketClose"),UiUtils.appendHeight();else{if(JsCache.get("#refreshButton").unbind("click").click(function(){JsCache.get("#loading").show();FullMarketViewHandler.getFullMarketsTask.refresh()}),null!=DataBase.events.get(c,g)){h='<img class="icon-time" src="/images/transparent.gif" />';1!=b.inPlay||MarketUtil.isClosed(b.status)||(h='<img class="icon-irun" src="/images/transparent.gif" />');f=$j("#gameHead");PageConfig.hasLiveMatchTracker&&
(f=$j("#liveMatchGameHead"));e=f.find("#gameInfoDate");0!=e.length&&(1==b.inPlay?(e.addClass("green"),e.removeClass("red"),e.html(h+" In-Play")):(e.removeClass("green"),e.removeClass("red"),e.html(h+" "+b.openDateDayOfWeek+" "+b.marketTimeStr)),MarketUtil.isClosed(b.status)&&(e.removeClass("green"),e.addClass("red"),e.html(h+I18N.get("form.text.market.closed"))));PageConfig.lmtMatchId!=a.lmtMatchId&&null!=a.lmtMatchId&&"0"!=a.lmtMatchId&&(LiveMatchTrackerHandler.init(PageConfig.selectEventType,PageConfig.selectEventId,
PageConfig.selectMarketId,a.lmtMatchId),PageConfig.lmtMatchId=a.lmtMatchId);PageConfig.hasLiveMatchTracker?(MemberPage.view("liveMatchTracker"),l(f,b)):(1==b.inPlay&&!MarketUtil.isClosed(b.status)&&null!=a.scores&&LiveScoreHandler.isEnableLiveScore()?(l(f,b),MemberPage.view("marketLiveScore"),PageConfig.useBetfairScores=!0,LiveScoreHandler.appendInfo(a.scores,a.matchInfo,a.scoresDetail,a.timeElapsed,c,g,d)):PageConfig.useSportradarScorecard||PageConfig.useSportsBookScorecard?(l(f,b),h=PageConfig.useSportradarScorecard?
SportradarScorecardHandler.getBoardByEventType(PageConfig.selectEventType):OwScorecardHandler.getBoardByEventType(PageConfig.selectEventType),null!=c&&null!=g&&null!=d&&MultiMarketsHandler.appendGameHeadPin(c,g,d,h)):null!=a.livescores?(l(f,b),MemberPage.view("marketLiveScore"),h=JSON.parse(a.livescores),TraderInputLiveScoreHandler.appendInfo(h,a)):(MemberPage.view("market"),MultiMarketsHandler.appendGameHeadPin(c,g,d)),UiUtils.appendHeight());h=CurrencyUtil.formatter(0<b.totalMatched?b.totalMatched:
0,{precision:0,separateSign:",",currencySymbol:null==PageConfig.currencySymbol?"$":PageConfig.currencySymbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1});e=f.find("#gameMatched");if(PageConfig.hasLiveMatchTracker||PageConfig.hasCricketLiveMatchTracker)e=f.find("#liveGameMatched");e.html(PageConfig.playerCurrencyType+" "+h);BetHandler.isEnableCheckLowLiquidity()&&(BetHandler.isLowLiquidity(c,g,d.replace("_","."))?FullMarketUtil.showLowLiquidityTag(f.find("#lowLiquidityTag"),!0):FullMarketUtil.showLowLiquidityTag(f.find("#lowLiquidityTag"),
!1));PageConfig.ENABLE_LINE_MARKET&&MarketUtil.isLineMarket(b.marketType,b.bettingType)&&(f=k.find("#lineMarketName"),f.find("span").html(b.marketName),f.show());1==b.isStreamingOpenTime&&PageConfig.hasAccount&&null!=a.streamingChannel&&"0"!=a.streamingChannel&&!PageConfig.userCloseStreaming?(PageConfig.ENABLE_GLIVE_STREAMING?b.isStreamingBoxOff&&!$j("#tv-wrap").is(":visible")?($j("#openStreaming").show(),$j("#lmtOpenStreaming").show()):a.streamingChannel!=PageConfig.streamingChannel&&GLiveStreamingHandler.openStreamingBox(a.streamingChannel):
b.isStreamingBoxOff?($j("#openStreaming").show(),$j("#lmtOpenStreaming").show()):a.streamingChannel!=PageConfig.streamingChannel&&StreamingHandler.openStreamingBox(a.streamingChannel,a.eventType),PageConfig.streamingChannel=a.streamingChannel):(PageConfig.ENABLE_GLIVE_STREAMING?GLiveStreamingHandler.closeStreamingBox():StreamingHandler.closeStreamingBox(),PageConfig.userCloseStreaming||(PageConfig.streamingChannel="0",$j("#openStreaming").hide(),$j("#lmtOpenStreaming").hide()));FullMarketUtil.updateFullMarket(k,
t,c,g,d,b,r,a.isOfferBetfairExchange);if(EventType.ELECTION.unique()==c||EventType.FANCYBET.unique()==c)a=$j("#centerColumn"),a.find("#fullMarketBetsWrap").hide(),a.find("#gameMatchedName").hide(),a.find("#gameMatched").hide(),a.find("#gameHead").find("#multiMarketPin").hide();EventType.GREYHOUND_RACING.unique()==c&&k.find("#fullMarketBoard").removeClass("bets").addClass("bets-GH");c=b.selections;if(null!=c&&0!=c.length&&null!=c[0]&&null!=c[0].runnerMetadata){FullMarketViewHandler.getFullMarketsTask.isGetRunnerMetadata=
!1;try{null!=JSON.parse(c[0].runnerMetadata)&&k.find("#fullMarketBoard").removeClass("bets").addClass("bets-HS")}catch(u){Trace.log(u)}}}}else MessageUtils.showThenGoToIndex("market is closed")}}};FullMarketViewHandler.changeToNextOpenRacingMarket=function(){$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,
eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(a){try{DataBase.markets.update(a.eventId,a.markets);var c=q(a.markets);null!=c&&null!=c.marketId?(PageConfig.selectMarketId=c.marketId,location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+PageConfig.selectEventId+"&marketId="+c.marketId,NavigationHandler.clickNextOpenRacingEvent(PageConfig.selectEventId,c.marketId,c.marketDateTime)):MessageUtils.showThenGoToIndex("event is closed")}catch(g){Trace.printStackTrace(g)}finally{}},
error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}})}})();

