var HorseRacingPage={};
(function(){function c(a){RacingSportUtil.initQueryRacingByDay(a,EventType.HORSE_RACING.value,function(b){try{b.marketTs>HorseRacingPage.marketTs&&(HorseRacingPage.marketTs=b.marketTs),RacingSportUtil.initRenderRacing(b.events),0==$j("#contentBox").find("div").length?$j("#noDataDiv").show():$j("#noDataDiv").hide()}catch(d){Trace.printStackTrace(d)}finally{setTimeout(function(){$j("#loading").hide()},250)}})}function e(a){$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=
QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryRacingByDayPath,data:{dayType:HorseRacingPage.selectDayType,eventType:EventType.HORSE_RACING.value,marketTs:HorseRacingPage.marketTs,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{HorseRacingPage.tabChanged?(HorseRacingPage.marketTs=-1,HorseRacingPage.tabChanged=!1):(b.marketTs>HorseRacingPage.marketTs&&(HorseRacingPage.marketTs=b.marketTs),0<b.events.length&&RacingSportUtil.updateMarkets(b.events))}catch(d){Trace.printStackTrace(d)}finally{a.check(),
TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}HorseRacingPage.marketTs=-1;HorseRacingPage.tabChanged=!1;HorseRacingPage.selectDayType="today";HorseRacingPage.init=function(){"#Today"!=location.hash&&"#Tomorrow"!=location.hash&&"#AftTomorrow"!=location.hash&&(location.hash="#Today");
$j(window).bind("hashchange",function(){var a=location.hash;""==a&&(location.hash="#Today");HorseRacingPage.route(a)});HorseRacingPage.route(location.hash);PageConfig.isHideUpcomingHorseRace||UpcomingHandler.init();UiUtils.appendHeight(!0)};HorseRacingPage.initMenu=function(){NavigationBar.addNode({id:EventType.HORSE_RACING.value,type:"EVENT_TYPE",name:"Horse Racing"});NavigationHandler.getMenu([EventType.HORSE_RACING.value])};HorseRacingPage.route=function(a){"#Today"==a?(TabMenuHandler.updateSelect("daySelectTab",
a.substring(1).toLowerCase()),HorseRacingPage.viewToday()):"#Tomorrow"==a?(TabMenuHandler.updateSelect("daySelectTab",a.substring(1).toLowerCase()),HorseRacingPage.viewTomorrow()):"#AftTomorrow"==a?(TabMenuHandler.updateSelect("daySelectTab",a.substring(1).toLowerCase()),HorseRacingPage.viewAftTomorrow()):$j("#loading").hide()};HorseRacingPage.viewToday=function(){HorseRacingPage.tabChanged=!0;HorseRacingPage.selectDayType="today";$j("#contentBox").children().remove();c("today")};HorseRacingPage.viewTomorrow=
function(){HorseRacingPage.tabChanged=!0;HorseRacingPage.selectDayType="tomorrow";$j("#contentBox").children().remove();c("tomorrow")};HorseRacingPage.viewAftTomorrow=function(){HorseRacingPage.tabChanged=!0;HorseRacingPage.selectDayType="aftTomorrow";$j("#contentBox").children().remove();c("aftTomorrow")};HorseRacingPage.updateHorseRacingMarkets=null;HorseRacingPage.initUpdateHorseRacingMarkets=function(){HorseRacingPage.updateHorseRacingMarkets=TaskExecuter.createTask(PageConfig.updateHorseRacingMarketsCycleTime,
2,function(){e(this)});HorseRacingPage.updateHorseRacingMarkets.run();TaskExecuter.execute()}})();

