"undefined"==typeof PageConfig&&(PageConfig={});var InPlayPage={};
(function(){function p(){null==C?C=TaskExecuter.createTask(PageConfig.getInPlayEventsTaskCycleTime,1,function(){k(this)}):C.isStop=!1;C.run();TaskExecuter.execute()}function h(){null==D?D=TaskExecuter.createTask(PageConfig.getTodayEventsTaskCycleTime,1,function(){u(this)}):D.isStop=!1;D.run();TaskExecuter.execute()}function f(){null==E?E=TaskExecuter.createTask(PageConfig.getTomorrowEventsTaskCycleTime,1,function(){K(this)}):E.isStop=!1;E.run();TaskExecuter.execute()}function k(a){if("#InPlay"!=location.hash)a.check(),
TaskExecuter.execute();else{var g="",d=[];JsCache.get("#centerColumn").find("[id^=inPlayEventType_]").each(function(){d[d.length]=$j(this)});for(var l=0;l<d.length;l++)d[l].find("#inplayGameList").find("[id^=event_]:visible").each(function(){g=""==g?g+this.id.replace("event_",""):g+(","+this.id.replace("event_",""))});$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsPath,
data:{type:"inplay",eventTs:inPlayEventTs,marketTs:-1,selectionTs:inPlaySelectionTs,collectEventIds:g,eventType:-1,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(n){try{setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),250),n.eventTs>inPlayEventTs&&(inPlayEventTs=n.eventTs),n.selectionTs>inPlaySelectionTs&&(inPlaySelectionTs=n.selectionTs),0<O(n.events).length||0<$j("#centerColumn").find("[id^=inPlayEventType_] :visible").length?JsCache.get("#noDataDiv").hide():
JsCache.get("#noDataDiv").show(),DataBase.events.update(n.events),V(n.events,n.gameProductStatus)}catch(b){Trace.printStackTrace(b)}finally{a.check(),TaskExecuter.execute()}},error:function(n){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}}function m(){for(var a=$j("input[name=sportsFilter]:checked"),g=[],d=0;d<a.length;d++){var l=
a.get(d).value;g.push(l);if(-1==l)break}return g.join()}function u(a){m();"#Today"!=location.hash?(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsPath,data:{type:"today",eventTs:todayEventTs,marketTs:-1,eventType:m(),selectionTs:inPlaySelectionTs,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(g){try{g.eventTs>
todayEventTs&&(todayEventTs=g.eventTs),0<O(g.events).length||0<$j("#centerColumn").find("[id^=todayEvent_] :visible").length?JsCache.get("#noDataDiv").hide():JsCache.get("#noDataDiv").show(),DataBase.events.update(g.events),DataBase.todayEvents.update(g.events),DataBase.todayEvents.queryAll(),setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),2E3),g.events.sort(N),L(g.events,"todayEvent_")}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&
null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}function K(a){"#Tomorrow"!=location.hash?(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsPath,data:{type:"tomorrow",eventTs:tomorrowEventTs,marketTs:-1,
eventType:m(),selectionTs:inPlaySelectionTs,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(g){try{g.eventTs>tomorrowEventTs&&(tomorrowEventTs=g.eventTs),0<O(g.events).length||0<$j("#centerColumn").find("[id^=tomorrowEvent_] :visible").length?JsCache.get("#noDataDiv").hide():JsCache.get("#noDataDiv").show(),DataBase.events.update(g.events),DataBase.tomorrowEvents.update(g.events),DataBase.tomorrowEvents.queryAll(),setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),
2E3),g.events.sort(N),L(g.events,"tomorrowEvent_")}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}function N(a,g){var d=a.openDateTime.toString(),l=g.openDateTime.toString();if(0==d.localeCompare(l)){if(a.eventType==g.eventType)return 0==a.competitionName.localeCompare(g.competitionName)?
a.name.localeCompare(g.name):a.competitionName.localeCompare(g.competitionName);a=I18N.get("eventType.name."+EventType.getInstanceOf(a.eventType).name);g=I18N.get("eventType.name."+EventType.getInstanceOf(g.eventType).name);return a.localeCompare(g)}return d.localeCompare(l)}function V(a,g){if("#InPlay"==location.hash){a.sort(function(e,y){return EventType.getInstanceOf(e.eventType).inplaySort-EventType.getInstanceOf(y.eventType).inplaySort});for(var d=-1,l=null,n=0,b=0,c=null,w=0;w<a.length;w++){var r=
a[w];if(null!=r.markets&&0!=r.markets.length&&0!=r.markets.length&&(0!=r.markets[0].selections.length||r.isManualEvent)){DataBase.markets.update(r.id,r.markets);b++;if(d!=r.eventType){if(-1!=d&&0<c.length){c.sort(function(e,y){return e.name.localeCompare(y.name)});b=c;var x={groupOfEvents:b,gameWrap:l,run:function(){P(this,g)}};setTimeout(function(e,y){return function(){e.run()}}(x,n),100+100*n)}n++;b=0;c=[];l=$j("#inPlayEventType_"+r.eventType);1!=l.length&&(l=JsCache.clone("#gameWrapTemplate"),
UiUtils.bindToExpand(l.find(".to-expand")),$j("#contentBox").before(l));l.attr("id","inPlayEventType_"+r.eventType);l.find("#eventType").html(I18N.get("eventType.name."+EventType.getInstanceOf(r.eventType).name));d=r.eventType}null!=l&&(c[c.length]=r)}}if(null!=c&&0<c.length&&null!=l)try{c.sort(EventHandler.sortEvents),x={groupOfEvents:c,gameWrap:l,run:function(){P(this,g)}},setTimeout(function(e,y){return function(){e.run();JsCache.get("#loading").hide()}}(x,n),2E3)}catch(e){Trace.error(e)}}}function O(a){for(var g=
[],d=0;d<a.length;d++){var l=a[d].markets[0];null!=l&&(MarketUtil.isOpen(l.status)||MarketUtil.isSuspend(l.status))&&g.push(l)}return g}InPlayPage.init=function(){""==location.hash&&(location.hash="#InPlay");$j(window).bind("hashchange",function(){JsCache.get("#sportFilterContainer").hide();var a=location.hash;""==a?(location.hash="#InPlay",location.reload()):InPlayPage.route(a)});CompetitionsFilterHandler.init();SportFilterHandler.init();InPlayPage.route(location.hash)};InPlayPage.route=function(a){JsCache.get("#noDataDiv").hide();
"#InPlay"==location.hash?InPlayPage.viewInPlay():"#Today"==location.hash?InPlayPage.viewToday():"#Tomorrow"==location.hash&&InPlayPage.viewTomorrow();"true"==PageConfig.ENABLE_ONE_CLICK_BET?OneClickBetHandler.show():UiUtils.appendHeight()};InPlayPage.viewInPlay=function(){location.hash="#InPlay";TabMenuHandler.updateSelect("tabMenu","menu_InPlay");TabMenuHandler.updateSelect("inPlayTab","inPlay");0<JsCache.get("#centerColumn").find("[id^=inPlayEventType_]").length&&JsCache.get("#noDataDiv").hide();
var a=$j("#centerColumn").find("[id^=inPlayEventType_]");0<a.length&&$j.each(a,function(g,d){d=$j(d);0<d.length&&0<d.find("[id^=event_]").length&&d.show()});JsCache.get("#centerColumn").find('[id^="todayEvent_"]').hide();JsCache.get("#centerColumn").find('[id^="tomorrowEvent_"]').hide();JsCache.get("#loading").css("top","100px").show();setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),2E3);PageConfig.highlightEventType=-1;PageConfig.prefix="inPlayEvent_";$j("#sportFilter").hide();
inPlaySelectionTs=inPlayEventTs=-1;p();null!=D&&D.stop();null!=E&&E.stop()};InPlayPage.viewToday=function(){$j("#noDataDiv").nextAll().remove();TabMenuHandler.updateSelect("tabMenu","menu_InPlay");TabMenuHandler.updateSelect("inPlayTab","today");0<JsCache.get("#centerColumn").find("[id^=todayEvent_]").length&&JsCache.get("#noDataDiv").hide();JsCache.get("#centerColumn").find("[id^=inPlayEventType_]").hide();JsCache.get("#centerColumn").find("[id^=todayEvent_]").show();JsCache.get("#centerColumn").find("[id^=tomorrowEvent_]").hide();
PageConfig.highlightEventType=-1;PageConfig.prefix="todayEvent_";$j("#sportFilter").show();var a=DataBase.todayEvents.queryAll();0==a.length&&(JsCache.get("#loading").css("top","100px").show(),setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),2E3));a.sort(N);L(a,"todayEvent_");h();null!=C&&C.stop();null!=E&&E.stop();location.hash="#Today"};InPlayPage.viewTomorrow=function(){$j("#noDataDiv").nextAll().remove();TabMenuHandler.updateSelect("tabMenu","menu_InPlay");TabMenuHandler.updateSelect("inPlayTab",
"tomorrow");0<JsCache.get("#centerColumn").find("[id^=tomorrowEvent_]").length&&JsCache.get("#noDataDiv").hide();JsCache.get("#centerColumn").find("[id^=inPlayEventType_]").hide();JsCache.get("#centerColumn").find("[id^=todayEvent_]").hide();JsCache.get("#centerColumn").find("[id^=tomorrowEvent_]").show();PageConfig.highlightEventType=-1;PageConfig.prefix="tomorrowEvent_";$j("#sportFilter").show();var a=DataBase.tomorrowEvents.queryAll();0==a.length&&(JsCache.get("#loading").css("top","100px").show(),
setTimeout(function(){return function(){JsCache.get("#loading").hide()}}(),2E3));a.sort(N);L(a,"tomorrowEvent_");f();null!=C&&C.stop();null!=D&&D.stop();location.hash="#Tomorrow"};tomorrowEventTs=todayEventTs=inPlaySelectionTs=inPlayEventTs=-1;var C=null,D=null,E=null,L=function(a,g,d){if(!("#Today"==location.hash&&"todayEvent_"!=g||"#Tomorrow"==location.hash&&"tomorrowEvent_"!=g)){null==d&&(d=0);for(var l=(new Date).getTime(),n=null,b=d;b<a.length;b++){if(50<(new Date).getTime()-l){setTimeout(function(){L(a,
g,b)},0);break}d=a[b];var c=((d.openDateTime-l)/6E4+"").split(".")[0],w=d.markets[0];if(null!=w&&"QuickBets"!=d.name&&!(15>parseInt(c))){c=EventUtils.isCloseSite(d.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(w.closeSite,PageConfig.webSiteType)||CompetitionUtils.isCloseSite(d.competitionCloseSite,PageConfig.webSiteType);n=$j("#"+g+d.id+w.marketDateTime);if(0==n.length){if(c)continue;n=JsCache.clone("#gameListTemplate");n.attr("id",g+d.id+w.marketDateTime);n.attr("eventType",d.eventType);
n.attr("openDateTime",w.marketTime);JsCache.get("#sportListWrap").append(n)}else if(c){n.remove();continue}c=w.marketTime.split(" ")[1];n.find("#openTime").html(c);c="--";-1!=d.competitionId?null!=d.competitionName&&""!=d.competitionName&&"null"!=d.competitionName&&(c=d.competitionName):null!=d.countryCode&&""!=d.countryCode&&"null"!=d.countryCode&&(c=d.countryCode);var r=d.name,x="";0<r.indexOf(" @ ")?x=" @ ":0<r.indexOf(" v ")?x=" v ":0<r.indexOf(" vs ")&&(x=" vs ");""!=x&&(r=r.split(x),r=r[0].trim()+
"</strong>"+x+"<strong>"+r[1].trim());x='<a id="vsNameClick"><strong>'+r+"</strong></a>";c=I18N.get("eventType.name."+EventType.getInstanceOf(d.eventType).name)+'<img class="fromto" src="/images/transparent.gif" />'+c+'<img class="fromto" src="/images/transparent.gif" />'+x;n.find("#eventDetail").html(c);d=PageConfig.fullMarketPath+"?eventType="+d.eventType+"&eventId="+d.id+"&marketId="+w.marketId;n.find("#vsNameClick").attr("href",d);if("#Today"!=location.hash&&"#Tomorrow"!=location.hash){n.hide();
break}}}0<a.length&&null==n&&JsCache.get("#noDataDiv").show();JsCache.get("#sportListWrap").find("dl").each(function(){var e=$j(this),y=((e.attr("openDateTime")-l)/6E4+"").split(".")[0];15>parseInt(y)&&e.remove()});SportFilterHandler.filter()}},P=function(a,g){if("#InPlay"==location.hash)try{var d=(new Date).getTime();try{var l=0;null!=a.startIdx&&(l=a.startIdx);for(;l<a.groupOfEvents.length;l++){var n=(new Date).getTime();if(100<n-d){a.startIdx=l;setTimeout(function(t){return function(){P(t,g)}}(a),
100);return}var b=a.groupOfEvents[l];if(0<b.markets.length&&3==b.markets[0].status)1==$j("#event_"+b.id).length&&$j("#event_"+b.id).remove();else if(null!=b.markets&&0!=b.markets.length){var c=b.markets[0];if(!(c.marketDateTime>n+9E5||!(b.isManualEvent||null!=c.selections&&0!=c.selections.length)||(b.eventType==EventType.TENNIS.value||b.eventType==EventType.CRICKET.value||b.eventType==EventType.RUGBY_UNION.value||b.eventType==EventType.BASEBALL.value||b.eventType==EventType.BASKETBALL.value)&&"MATCH_ODDS"!=
c.marketType&&"SUPER_OVER"!=c.marketType||EventType.getInstanceOf(b.eventType).isRacingEvent()&&"WIN"!=c.marketType&&"PLACE"!=c.marketType)){var w=EventUtils.isCloseSite(b.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(c.closeSite,PageConfig.webSiteType)||CompetitionUtils.isCloseSite(b.competitionCloseSite,PageConfig.webSiteType),r=b.name,x=EventType.getInstanceOf(b.eventType),e=null,y=a.gameWrap.find("#event_"+b.id);if(1==y.length){if(w){y.remove();continue}e=y;var v="";if(x.isTwoTeamsEvent()&&
1==c.inPlay){var F=" v ";0<b.name.indexOf(" vs ")?F=" vs ":0<b.name.indexOf(" @ ")&&(F=" @ ");var M=b.name.split(F);if(1==M.length)continue;for(var G="",H="",I=0;I<c.selections.length;I++){var q=c.selections[I];1==q.sortPriority?G=q.runnerName:2==q.sortPriority&&(H=q.runnerName);if(""!=G&&""!=H)break}""!=G&&""!=H?r=G+"<span>"+F.trim()+"</span>"+H:(G=M[0],H=M[1],r=M[0]+"<span>"+F.trim()+"</span>"+M[1]);v=EventHandler.getScoreInfo(b,G,H);r=G+v+H;e.find("#vsName").html(r)}}else{if(w)continue;e=JsCache.clone("#eventTemplate");
e.attr("id","event_"+b.id);if(b.eventType==EventType.SOCCER.value||b.eventType==EventType.E_SOCCER.value)if(null==PageConfig.checkedFilterCompetitions)a.gameWrap.find("#inplayGameList").append(e.css("display","flex"));else{v=!1;for(atr in PageConfig.checkedFilterCompetitions)if(PageConfig.checkedFilterCompetitions[atr]==b.competitionId){v=!0;break}v?a.gameWrap.find("#inplayGameList").append(e.css("display","flex")):a.gameWrap.find("#inplayGameList").append(e.hide())}else a.gameWrap.find("#inplayGameList").append(e.css("display",
"flex"));EventType.getInstanceOf(b.eventType).hasDraw()?(a.gameWrap.addClass("col3"),a.gameWrap.find(".col-draw").show(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?a.gameWrap.find(".col-game").css("width",""):(a.gameWrap.find(".col-game").css("width","calc(63.8% - 41px)"),a.gameWrap.find("dt").css("width","calc(63.8% - 41px)"))):(a.gameWrap.removeClass("col3"),a.gameWrap.find(".col-draw").hide(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?(a.gameWrap.find(".col-game").css("width","calc(63.8% - 41px)"),
a.gameWrap.find("dt").css("width","calc(63.8% - 41px)")):a.gameWrap.find(".col-game").css("width",""));e.attr("eventType",b.eventType);e.attr("competitionId",b.competitionId);e.attr("eventId",b.id);e.attr("marketId",c.marketId);e.attr("openDate",b.openDate);e.attr("openDateTime",b.openDateTime);e.attr("elapsedTime",b.elapsedTime);e.attr("inPlay",c.inPlay);var W=EventHandler.getEventDisplayName(b,c,e),X=function(t,z){return function(){location.href=PageConfig.fullMarketPath+"?eventType="+t.eventType+
"&eventId="+t.id+"&marketId="+z.marketId}}(b,c);e.attr("eventName",b.name);e.find("#vsName").html(W);var Y=PageConfig.fullMarketPath+"?eventType="+b.eventType+"&eventId="+b.id+"&marketId="+c.marketId;e.find("#vsName").click(X).attr("href",Y);MultiMarketsHandler.bindPinEvent(e,b.eventType,b.id,c.marketId);MultiMarketsHandler.checkIsMultiMarket(e.find("#multiMarketPin"),b.eventType,b.id,c.marketId);if(PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW){var Z=CurrencyUtil.formatNumberToKM(0<c.totalMatched?c.totalMatched:
0,{precision:0,separateSign:",",currencySymbol:PageConfig.playerCurrencyType,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1});e.find("#matched").html(Z).show()}}F=v=!1;BetHandler.isEnableCheckLowLiquidity()&&BetHandler.isLowLiquidity(b.eventType,b.id,c.marketId.replace("_","."))&&(F=!0);WebSiteUtil.isDisableBettingSite(c.disableBettingSite,PageConfig.webSiteType)&&(v=!0);WebSiteUtil.isDisableBettingSite(c.autoDisableBettingSite,PageConfig.webSiteType)&&(v=!0);v||F?e.addClass("disabled"):
e.hasClass("cooldown")||e.removeClass("disabled");if(FancyBetMarketHandler.isEnableFancyBet()&&b.hasFancyBetMarkets){var Q=e.find("#fancyBetIcon");Q.show().css("display","inline-flex");b.hasInPlayFancyBetMarkets?Q.addClass("in-play"):Q.removeClass("in-play")}else e.find("#fancyBetIcon").hide();if(PageConfig.isEnableBookMaker&&b.hasBookMakerMarkets){var R=e.find("#bookMakerIcon");R.show().css("display","inline-flex");b.hasInPlayBookMakerMarkets?R.addClass("in-play"):R.removeClass("in-play")}else e.find("#bookMakerIcon").hide();
SportsBookEventHandler.isEnableSportsBookBet()&&b.hasSportsBookMarkets?e.find("#sportsBookIcon_"+ApiSiteType.SPORTRADAR.unique()).show().css("display","inline-flex"):e.find("#sportsBookIcon_"+ApiSiteType.OW.unique()).hide();1==b.isElectronic&&e.find("#sportsBookEIcon_"+b.eventType).show().css("display","inline-flex");null!=b.streamingChannel&&0!=b.streamingChannel.length&&0!=b.streamingChannel?e.find("#streamingIcon").show().css("display","inline-flex"):e.find("#streamingIcon").hide();HeadToHeadHandler.displayH2HIconButton(b,
e,"inPlay");a.gameWrap.show();null!=c.inPlay&&1==c.inPlay&&(e.find("#playIcon").removeClass("icon-no_play"),e.find("#playIcon").addClass("icon-in_play"));null!=b.isInPlay&&1==b.isInPlay&&EventHandler.updateEventCountdown(b,c,e);if(MarketUtil.isSuspend(c.status))e.find(".suspend").show();else{e.find(".suspend").hide();0==y.length&&EventHandler.bindEvent(e);var S=c.marketType;null==S&&(S=c.marketName);c.selections.sort(function(t,z){return t.sortPriority-z.sortPriority});for(I=0;I<c.selections.length;I++){q=
c.selections[I];var aa=SelectionUtil.isShowSelection(q.closeSite,q.bookMode,PageConfig.webSiteType),ba=GameProductUtils.isClose(g)||SelectionUtil.isShowSuspend(q.suspendSite,q.bookSuspend,PageConfig.webSiteType),ca=1==q.isAutoSuspend;v="";if(1==q.sortPriority)v=".col-visit";else if(2==q.sortPriority)v=".col-home";else if(3==q.sortPriority)v=".col-draw";else continue;var J=e.find(v+" > a");if(0!=J.length)if(aa)if(J.show(),ba)J.parent().find(".suspend").show();else{J.parent().find(".suspend").hide();
ca?e.find(v).addClass("disabled"):e.find(v).removeClass("disabled");var A=$j(J[0]),B=$j(J[1]);A.attr("selectionId",q.selectionId);A.attr("selectionKey",q.selectionKey);A.attr("runner",q.runnerName);A.attr("marketName",c.marketName);A.attr("inPlay",c.inPlay);A.attr("handicap",q.handicap);B.attr("selectionId",q.selectionId);B.attr("selectionKey",q.selectionKey);B.attr("runner",q.runnerName);B.attr("marketName",c.marketName);B.attr("inPlay",c.inPlay);B.attr("handicap",q.handicap);0<q.availableToBack.length?
(A.html(q.availableToBack[0].price),SparkHandler.addSparkClass(A,q.availableToBack[0].price,q.availableToBack[0].size)):A.html("&nbsp;");0<q.availableToLay.length?(B.html(q.availableToLay[0].price),SparkHandler.addSparkClass(B,q.availableToLay[0].price,q.availableToLay[0].size)):B.html("&nbsp;")}else J.hide()}}}}}0<a.gameWrap.find("#inplayGameList").find("[id^=event_]:visible").length||a.gameWrap.hide();d=-1;0<a.groupOfEvents.length&&(d=a.groupOfEvents[0].eventType);-1==d||EventType.getInstanceOf(d).hasDraw()?
(a.gameWrap.addClass("col3"),a.gameWrap.find(".col-draw").show(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?a.gameWrap.find(".col-game").css("width",""):(a.gameWrap.find(".col-game").css("width","calc(63.8% - 41px)"),a.gameWrap.find("dt").css("width","calc(63.8% - 41px)"))):(a.gameWrap.removeClass("col3"),a.gameWrap.find(".col-draw").hide(),PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW?(a.gameWrap.find(".col-game").css("width","calc(63.8% - 41px)"),a.gameWrap.find("dt").css("width","calc(63.8% - 41px)")):
a.gameWrap.find(".col-game").css("width",""));if(EventType.SOCCER.value==a.groupOfEvents[0].eventType||EventType.E_SOCCER.value==a.groupOfEvents[0].eventType){CompetitionsFilterHandler.sortFilterContent();var T=a.gameWrap.find("#soccerCompetitionFilter").find("#filterCheckBoxList"),U=T.find("li");U.sort(function(t,z){t=$j(t);z=$j(z);if("btn"==t.attr("id"))return 1;if("btn"==z.attr("id")||"filter-all"==t.find("input").attr("id"))return-1;if("filter-all"==z.find("input").attr("id"))return 1;t=t.find("label").html();
z=z.find("label").html();return t.localeCompare(z)});T.find("ul").append(U);CompetitionsFilterHandler.filter()}}catch(t){Trace.error(t)}(new Date).getTime();BetHandler.addSelectClass()}catch(t){Trace.error(t)}}})();var CompetitionsFilterHandler={};
(function(){CompetitionsFilterHandler.init=function(){PageConfig.checkedFilterCompetitions=null;var p=CookieUtil.getCookie("filterCompetitions_"+PageConfig.userID);if(null!=p)try{PageConfig.checkedFilterCompetitions=JSON.parse(p)}catch(h){Trace.error(h),CookieUtil.deleteCookie(CookieUtil.getCookie("filterCompetitions_"+PageConfig.userID))}};CompetitionsFilterHandler.sortFilterContent=function(){var p=$j("#soccerCompetitionFilter").find(".filter-content"),h=p.find("span");h.sort(function(f,k){f=$j(f);
k=$j(k);f.removeClass("filter-first");k.removeClass("filter-first");var m=f.html().localeCompare(k.html());return"none"===f.css("display")&&"none"===k.css("display")?m:"none"===f.css("display")?1:"none"===k.css("display")?-1:m});$j(h[0]).addClass("filter-first");p.append(h)};CompetitionsFilterHandler.filterPopup=function(){JsCache.get("#filterCheckBoxList").toggle()};CompetitionsFilterHandler.checkAll=function(p){var h=$j("#soccerCompetitionFilter").find("#filter-all").prop("checked");p&&(h=h?!1:
!0);$j("#soccerCompetitionFilter").find('[name="competitionsFilter"]').each(function(){$j(this).prop("checked",h)})};CompetitionsFilterHandler.filter=function(){if(null!=PageConfig.checkedFilterCompetitions){$j("#inPlayEventType_1").find("[id^=event_]").hide();$j(PageConfig.checkedFilterCompetitions).each(function(k,m){$j("[id^=event_][competitionId="+m+"]").show()});var p=$j("#soccerCompetitionFilter"),h=p.find('[name="competitionsFilter"]').length,f=p.find("input:checked").length;h==f+1&&(p=p.find('[id="filter-all"]'),
p.prop("checked")?p.prop("checked",!1):p.prop("checked",!0))}};CompetitionsFilterHandler.revertCheckedSports=function(){try{if(null!=PageConfig.checkedFilterCompetitions){var p=JsCache.get("#filterCheckBoxList");p.find("input").prop("checked",!1);$j(PageConfig.checkedFilterCompetitions).each(function(h,f){p.find("#filter-"+f).prop("checked",!0)})}}catch(h){Trace.error(h)}};CompetitionsFilterHandler.updateFilter=function(){var p=JsCache.get("#soccerCompetitionFilter").find(".filter-content"),h=[];
$j("#soccerCompetitionFilter").find('[name="competitionsFilter"]').each(function(){var f=$j(this),k=f.val();f.prop("checked")?(h[h.length]=k,p.find("#comp_"+k).show()):p.find("#comp_"+k).hide()});CompetitionsFilterHandler.sortFilterContent();CookieUtil.setCookie("filterCompetitions_"+PageConfig.userID,JSON.stringify(h),-1);PageConfig.checkedFilterCompetitions=h;CompetitionsFilterHandler.filter()}})();var SportFilterHandler={};
(function(){function p(){var h=JsCache.get("#sportFilter").find(".filter-content"),f=h.find("span");f.sort(function(k,m){k=$j(k);m=$j(m);k.removeClass("filter-first");m.removeClass("filter-first");var u=k.html().localeCompare(m.html());return"none"===k.css("display")&&"none"===m.css("display")?u:"none"===k.css("display")?1:"none"===m.css("display")?-1:u});$j(f[0]).addClass("filter-first");h.append(f)}SportFilterHandler.init=function(){JsCache.get("#sportFilterPopup").click(function(u){SportFilterHandler.filterPopup(this);
u.stopPropagation()});JsCache.get("#sportFilterSave").click(function(u){SportFilterHandler.updateFilter();JsCache.get("#sportFilterContainer").hide();$j("#noDataDiv").nextAll().remove();"#Today"==location.hash?todayEventTs=-1:"#Tomorrow"==location.hash&&(tomorrowEventTs=-1);u.stopPropagation()});JsCache.get("#sportFilterCancel").click(function(u){SportFilterHandler.revertCheckedSports();JsCache.get("#sportFilterContainer").hide();u.stopPropagation()});var h=JsCache.get("#sportFilter").find(".filter-content");
PageConfig.checkedFilterSports=null;var f=CookieUtil.getCookie("filterSports_"+PageConfig.userID),k=JsCache.get("#sportFilterContainer");if(null!=f)try{PageConfig.checkedFilterSports=JSON.parse(f),null!=PageConfig.checkedFilterSports&&$j(PageConfig.checkedFilterSports).each(function(u,K){k.find("#filter-"+K).prop("checked",!0);h.find("#sport_"+K).show()})}catch(u){Trace.error(u),CookieUtil.deleteCookie(CookieUtil.getCookie("filterSports_"+PageConfig.userID))}else{f=[0];k.find("#filter-all").prop("checked",
!0);for(atr in EventType){var m=EventType[atr];void 0!=m.value&&(f[f.length]=m.value,k.find("#filter-"+m.value).prop("checked",!0),h.find("#sport_"+m.value).show())}CookieUtil.setCookie("filterSports_"+PageConfig.userID,JSON.stringify(f),999);PageConfig.checkedFilterSports=f}p()};SportFilterHandler.filterPopup=function(){JsCache.get("#sportFilterContainer").toggle()};SportFilterHandler.checkAll=function(){var h=JsCache.get("#sportFilterContainer"),f=h.find('[name="sportsFilter"][id="filter-all"]').prop("checked");
h.find('[name="sportsFilter"]').each(function(){$j(this).prop("checked",f)})};SportFilterHandler.filter=function(){var h=0;if(null!=PageConfig.checkedFilterSports){JsCache.get("#sportListWrap").find("[id^="+PageConfig.prefix+"]").hide();$j(PageConfig.checkedFilterSports).each(function(u,K){u=JsCache.get("#sportListWrap").find("[id^="+PageConfig.prefix+"][eventType="+K+"]");u.show();h+=u.length;0<h&&JsCache.get("#noDataDiv").hide()});var f=JsCache.get("#sportFilterContainer"),k=f.find('[name="sportsFilter"]').length,
m=f.find("input:checked").length;k==m+1&&(f=f.find('[name="sportsFilter"][id="filter-all"]'),f.prop("checked")?f.prop("checked",!1):f.prop("checked",!0))}};SportFilterHandler.revertCheckedSports=function(){try{if(null!=PageConfig.checkedFilterSports){var h=JsCache.get("#sportFilterContainer");h.find("input").prop("checked",!1);$j(PageConfig.checkedFilterSports).each(function(f,k){h.find("#filter-"+k).prop("checked",!0)})}}catch(f){Trace.error(f)}};SportFilterHandler.updateFilter=function(){var h=
JsCache.get("#sportFilter").find(".filter-content"),f=[];JsCache.get("#sportFilterContainer").find('[name="sportsFilter"]').each(function(){var k=$j(this),m=k.val();k.prop("checked")?(f[f.length]=m,h.find("#sport_"+m).show()):h.find("#sport_"+m).hide()});p();CookieUtil.setCookie("filterSports_"+PageConfig.userID,JSON.stringify(f),999);PageConfig.checkedFilterSports=f;SportFilterHandler.filter();0==JsCache.get("#centerColumn").find("[id^="+PageConfig.prefix+"]:visible").length&&JsCache.get("#noDataDiv").show()}})();
"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.todayEvents={};var p=new TreeMap;DataBase.todayEvents.update=function(f){for(var k=0;k<f.length;k++){var m=f[k];p.put(m.id,m)}};DataBase.todayEvents.get=function(f){return p.get(f)};DataBase.todayEvents.queryAll=function(){return p.values()};DataBase.tomorrowEvents={};var h=new TreeMap;DataBase.tomorrowEvents.update=function(f){for(var k=0;k<f.length;k++){var m=f[k];h.put(m.id,m)}};DataBase.tomorrowEvents.get=function(f){return h.get(f)};DataBase.tomorrowEvents.queryAll=function(){return h.values()}})();

