"undefined"==typeof LiveScoreHandler&&(LiveScoreHandler={});
(function(){function x(a,b,d){for(var c=1;c<=d;c++){var e=$j("#inningsBox"+c);if(0==e.length){var f=c,h=JsCache.clone("#inningsBoxTemplate");h.attr("id","inningsBox"+f).attr("eventId",PageConfig.selectEventId).attr("name","extended");h.find("#inningsIndex").html(I18N.get("liveScore.cricket.innings")+" "+f);JsCache.get("#inningsBox"+(parseInt(f)-1)).after(h.show());e=h}f=e.find(b);var k=a["inning"+c];h=a.highlight;f.removeClass("scores-now");if(null!=k){e.show();e=k.overs;var g=k.runs;k=k.wickets;
"ALL_OUT"==k?f.html(g+"&nbsp<span>("+e+")</span>"):(f.html(g+"/"+k+"&nbsp<span>("+e+")</span>"),1==h&&f.addClass("scores-now"))}else f.html(I18N.get("liveScore.cricket.yetToBat"))}}function y(a){var b=JsCache.clone("#setBoxTemplate");b.attr("id","setBox"+a).attr("eventId",PageConfig.selectEventId).attr("name","extended").addClass("last-box");b.find("#setIndex").html(a);JsCache.get("#setBox"+(parseInt(a)-1)).removeClass("last-box").after(b.show());return b}function z(a,b){for(var d in a){var c=parseInt(d)+
1,e=$j("#setBox"+c);0==e.length&&(e=y(c));c=e.find(b);c.html(a[d]);c.removeClass("scores-now")}}function C(a,b,d,c,e,f,h,k){a.addClass(c);a.addClass(e);u(a,f);a.show();b.find("img").addClass(c);b.find("img").addClass(e);b.find("img").after(d);null!=k?b.find("#matchTime").html(h+"+"+k+"'"):b.find("#matchTime").html(h+"'");u(b,f);"team-b"==e&&b.addClass(e);a.hover(function(){b.show()});a.mouseleave(function(){b.hide()})}function D(a,b,d,c,e){d=a.find("#sumTemplate").clone();d.attr("id","sum_"+b);d.addClass(e);
u(d,c);d.show();var f=a.find("#sumPopupTemplate").clone();f.attr("id","sumPopup_"+b);u(f,c);"team-b"==e&&f.addClass(e);a.find("#progressPercent").after(d);a.find("#progressPercent").after(f);d.hover(function(){f.show()});d.mouseleave(function(){f.hide()});return d}function A(a){if("Goal"==a)return"icon-soccer";if("YellowCard"==a)return"icon-card-yellow";if("RedCard"==a)return"icon-card-red"}function v(a){a=MathUtil.decimal.divide(a,90);1<a&&(a=1);a=MathUtil.decimal.multiply(a,100);return Math.round(a)+
"%"}function u(a,b){"100%"==b?(a.css("left",""),a.css("right","0%")):(a.css("left",b),a.css("right",""))}LiveScoreHandler.isEnableLiveScore=function(){return EventType.CRICKET.unique()==PageConfig.selectEventType||EventType.TENNIS.unique()==PageConfig.selectEventType||EventType.SOCCER.unique()==PageConfig.selectEventType||EventType.E_SOCCER.unique()==PageConfig.selectEventType||EventType.BASKETBALL.unique()==PageConfig.selectEventType};LiveScoreHandler.getBoardByEventType=function(a){$j(".game-scores").hide();
if(EventType.CRICKET.unique()==a)return JsCache.get("#cricketScoreBoard").show();if(EventType.TENNIS.unique()==a)return JsCache.get("#tennisScoreBoard").show();if(EventType.SOCCER.unique()==a||EventType.E_SOCCER.unique()==a)return JsCache.get("#soccerScoreBoard").show();if(EventType.BASKETBALL.unique()==a)return JsCache.get("#basketballScoreBoard").show()};LiveScoreHandler.appendInfo=function(a,b,d,c,e,f,h){var k=LiveScoreHandler.getBoardByEventType(PageConfig.selectEventType);a=JSON.parse(a);var g=
null,l=null;null!=b&&(g=JSON.parse(b));null!=d&&(l=JSON.parse(d));null!=e&&null!=f&&null!=h&&MultiMarketsHandler.appendGameHeadPin(e,f,h,k);LiveScoreHandler.appendScoresByEventType(k,a,g,l,c)};LiveScoreHandler.appendScoresByEventType=function(a,b,d,c,e){EventType.CRICKET.unique()==PageConfig.selectEventType?LiveScoreHandler.appendCricketScores(a,b):EventType.TENNIS.unique()==PageConfig.selectEventType?LiveScoreHandler.appendTennisScores(a,b,d):EventType.SOCCER.unique()==PageConfig.selectEventType||
EventType.E_SOCCER.unique()==PageConfig.selectEventType?LiveScoreHandler.appendSoccerScores(a,b,d,c,e):EventType.BASKETBALL.unique()==PageConfig.selectEventType&&LiveScoreHandler.appendBasketballScores(a,b,e)};LiveScoreHandler.cleanBox=function(a){a=a.find("[name=extended]");if(null!=a&&0!=a.length)for(var b=0;b<a.length;b++){var d=$j(a[b]);null!=d.attr("eventId")&&d.attr("eventId")!=PageConfig.selectEventId&&d.remove()}};LiveScoreHandler.appendCricketScores=function(a,b){if(a.attr("eventId")!=PageConfig.selectEventId){LiveScoreHandler.cleanBox($j("#cricketScoreBoard"));
for(var d=a.find("[id^=inningsBox]"),c=0;c<d.length;c++){var e=$j(d[c]);e.find("#runsHome").html("");e.find("#runsAway").html("")}a.attr("eventId",PageConfig.selectEventId)}d=b.currentSet;c=b.home;e=b.away;var f=a.find("#teamHome"),h=a.find("#teamAway");null!=c.name&&null!=e.name&&("HOME"!=c.name&&f.html(c.name),"AWAY"!=e.name&&h.html(e.name));f=b.description;b=b.currentDay;a.find("#description").html(f);a.find("#currentDay").html(I18N.get("liveScore.cricket.day")+" "+b);x(c,"#runsHome",d);x(e,"#runsAway",
d)};LiveScoreHandler.appendTennisScores=function(a,b,d){if(a.attr("eventId")!=PageConfig.selectEventId){LiveScoreHandler.cleanBox($j("#tennisScoreBoard"));for(var c=a.find("[id^=setBox]"),e=0;e<c.length;e++){var f=$j(c[e]);f.find("#setHome").html("").removeClass("scores-now");f.find("#setAway").html("").removeClass("scores-now")}a.find("#court").html("");c=a.find("#points");c.find("#pointsHome").html(0);c.find("#pointsAway").html(0);c=a.find("#aces");c.find("#acesHome").html(0);c.find("#acesAway").html(0);
c=a.find("#faults");c.find("#faultsHome").html(0);c.find("#faultsAway").html(0);c=a.find("#breaks");c.find("#breaksHome").html(0);c.find("#breaksAway").html(0);a.attr("eventId",PageConfig.selectEventId)}c=b.home;e=b.away;f=a.find("#teamHome");var h=a.find("#teamAway"),k=c.playerSeed,g=e.playerSeed,l="",t="";null!=k&&(l='<span class="rank">('+k+")</span>");null!=g&&(t='<span class="rank">('+g+")</span>");null!=c.name&&null!=e.name&&(f.html(c.name+l),h.html(e.name+t),1==c.isServing?f.html(c.name+l+
'&nbsp<img class="its_turn" src="/images/transparent.gif">'):1==e.isServing&&h.html(e.name+t+'&nbsp<img class="its_turn" src="/images/transparent.gif">'));h=b.matchStatus;f=b.currentSet;null==f&&(f=1);k=a.find("#currentSet");"Suspended"==h?k.html(I18N.get("liveScore.tennis.stopped")):"Oncourt"==h?k.html(I18N.get("liveScore.tennis.oncourt")):k.html(I18N.get("liveScore.tennis.set")+" "+f);h=a.find("#fullTimeElapsed");b=b.fullTimeElapsed;h.html(b.hour+"h"+b.min);null!=d&&null!=d.surface&&""!=d.surface&&
a.find("#court").html(d.surface+" court");d=e.gameSequence;z(c.gameSequence,"#setHome");z(d,"#setAway");d=$j("#setBox"+f);0==d.length&&(d=y(f));d.find("#setHome").html(c.games).addClass("scores-now");d.find("#setAway").html(e.games).addClass("scores-now");d=a.find("#points");d.find("#pointsHome").html(c.score);d.find("#pointsAway").html(e.score);d=a.find("#aces");d.find("#acesHome").html(c.aces);d.find("#acesAway").html(e.aces);d=a.find("#faults");d.find("#faultsHome").html(c.doubleFaults);d.find("#faultsAway").html(e.doubleFaults);
a=a.find("#breaks");a.find("#breaksHome").html(c.serviceBreaks);a.find("#breaksAway").html(e.serviceBreaks)};LiveScoreHandler.appendSoccerScores=function(a,b,d,c,e){a.attr("eventId")!=PageConfig.selectEventId&&(a.find("[id^=soccerEvent_]").remove(),a.find("[id^=popup_]").remove(),a.find("#progressPercent").css("width","0%"),a.attr("eventId",PageConfig.selectEventId));var f=b.home,h=b.away;b=a.find("#teamHome");d=a.find("#teamAway");b.html(f.name);d.html(h.name);var k=a.find("#vsScores");b=a.find("#timeElapsed");
d=a.find("#progressPercent");var g=v(e);k.html(f.score+" - "+h.score);b.html(e+"'");d.css("width",g);e=0;f=new HashMap;for(h=0;h<c.length;h++){k=c[h];g=k.type;var l=k.elapsedRegularTime;if("Goal"==g||"YellowCard"==g||"RedCard"==g||"FirstHalfEnd"==g)"FirstHalfEnd"==g?null!=l&&h==c.length-1&&(e=l):(g=k.team+"_"+l,l=f.get(g),null==l&&(l=[]),l.push(k),f.put(g,l))}c=f.values();for(var t in c){g=c[t];f=g[0];k=f.elapsedRegularTime;l=f.elapsedAddedTime;var m=f.team,n=f.type,w=f.teamName;f="home"==m?"team-a":
"team-b";h=v(k);if(1<g.length)for(h in l=m+"_"+k,n=a.find("#sum_"+l),k=a.find("#sumPopup_"+l),0==n.length&&(n=D(a,l,g,h,f)),n.html(g.length),h=void 0,l=k.find("#list"),g){var p=g[h],q=p.team;m=p.elapsedRegularTime;var r=p.elapsedAddedTime,B=p.type;n=p.teamName;w=A(B);p=q+"_"+B+"_"+p.updateId;q=k.find("#matchTime_"+p);0==q.length&&(q=k.find("#matchTimeTemplate").clone(),q.attr("id","matchTime_"+p),null!=r?q.html(m+"+"+r+"'"):q.html(m+"'"),q.show(),m=k.find("#iconTemplate").clone(),m.attr("id","icon_"+
p),m.find("img").addClass(w),m.find("img").addClass(f),m.find("img").after(n),m.show(),l.append(q),l.append(m))}else if(r=m+"_"+n+"_"+k,g=a.find("#soccerEvent_"+r),m=a.find("#popup_"+r),0==g.length||0==m.length)g=a.find("#soccerEventTemplate").clone(),g.attr("id","soccerEvent_"+r),m=a.find("#popupTemplate").clone(),m.attr("id","popup_"+r),n=A(n),C(g,m,w,n,f,h,k,l),a.find("#progressPercent").after(g),a.find("#progressPercent").after(m)}a=e;0!=a&&(g=v(a),b.html("Half-time"),d.css("width",g))};LiveScoreHandler.appendBasketballScores=
function(a,b,d){if(a.attr("eventId")!=PageConfig.selectEventId){for(var c=a.find(".scores-box"),e=0;e<c.length;e++){var f=$j(c[e]);f.find("#homeScore").html("-").removeClass("scores-now");f.find("#awayScore").html("-").removeClass("scores-now")}a.attr("eventId",PageConfig.selectEventId)}c=b.home;e=b.away;var h=a.find("#teamHome"),k=a.find("#teamAway"),g=a.find("#matchStatus"),l=a.find("#timeElapsed");f=a.find("#totalScore");a=f.find("#homeScore");f=f.find("#awayScore");h.html(c.name);k.html(e.name);
b=BaseketBallLiveScoreMatchStatusType.getInstanceOf(b.matchStatus);null!=b&&g.html(b.alias);b!=BaseketBallLiveScoreMatchStatusType.Finished&&b!=BaseketBallLiveScoreMatchStatusType.FirstHalfEnd&&b!=BaseketBallLiveScoreMatchStatusType.StopQuarter?l.html(d):l.html("");g=c.quarterByQuarter;d=e.quarterByQuarter;for(b=0;b<g.length;b++)l=parseInt(b)+1,h=$j("#period"+l),l==g.length?h.find("#homeScore").html(g[b]).addClass("scores-now"):h.find("#homeScore").html(g[b]);for(b=0;b<d.length;b++)g=parseInt(b)+
1,l=$j("#period"+g),g==d.length?l.find("#awayScore").html(d[b]).addClass("scores-now"):l.find("#awayScore").html(d[b]);a.html(c.score).addClass("scores-now");f.html(e.score).addClass("scores-now")}})();

