"undefined"==typeof LoginHandler&&(LoginHandler={});
(function(){function f(){e("#loginBtn");JsCache.get("#authenticateImage").bind("click",function(){LoginHandler.refreshImgTask.refresh()})}function e(b){$j(document).off("keydown").on("keydown",function(a){KeyEventUtils.isEnterKey(a.keyCode)&&(a.preventDefault(),$j(b).click())})}function g(){$j("#loginBoxAuthenticateImage").on("click",function(){LoginHandler.refreshImgTask.refresh()})}LoginHandler.init=function(){f();g();JsCache.get("#loginName").focus();PageConfig.fingerprint=(new TrafficStatistics).get();
PageConfig.fingerprint2="";(new TrafficStatistics2).get(function(b){PageConfig.fingerprint2=b});PageConfig.fingerprintCanvas=(new TrafficStatistics({canvas:!0})).get();PageConfig.fingerprintActiveX=(new TrafficStatistics({ie_activex:!0})).get();PageConfig.fingerprintResolution=(new TrafficStatistics({screen_resolution:!0})).get();LoginHandler.refreshImgTask.run();TaskExecuter.execute()};LoginHandler.hideUrgentNotice=function(){$j("#urgentNotice").hide()};LoginHandler.check=function(b){WindowEventUtil.stopEvent(b);
PageConfig.loginName=$j("#loginName").val();PageConfig.password=$j("#password").val();PageConfig.validCode=$j("#validCode").val();PageConfig.valid=$j("#valid").val();FraudProtectionSystemHandler.collectFpsParams();b=!0;var a="";!PageConfig.isValidationCodeEnable||null!=PageConfig.validCode&&0!=PageConfig.validCode.length||(b=!1,a="msg.error.account.verifyCodeEmpty");if(null==PageConfig.password||0==PageConfig.password.length)b=!1,a="msg.error.account.passwordEmpty";if(null==PageConfig.loginName||
0==PageConfig.loginName.length)b=!1,a="msg.error.account.accountEmpty";b?LoginHandler.submit():JsCache.get("#errorMsg").html(I18N.get(a)).show()};LoginHandler.loginBoxCheck=function(b){WindowEventUtil.stopEvent(b);PageConfig.loginName=$j("#loginBoxLoginName").val();PageConfig.password=$j("#loginBoxPassword").val();PageConfig.validCode=$j("#loginBoxValidCode").val();PageConfig.valid=$j("#loginBoxValid").val();FraudProtectionSystemHandler.collectFpsParams();b=!0;var a="";!PageConfig.isValidationCodeEnable||
null!=PageConfig.validCode&&0!=PageConfig.validCode.length||(b=!1,a="msg.error.account.verifyCodeEmpty");if(null==PageConfig.password||0==PageConfig.password.length)b=!1,a="msg.error.account.passwordEmpty";if(null==PageConfig.loginName||0==PageConfig.loginName.length)b=!1,a="msg.error.account.accountEmpty";b?LoginHandler.submit():$j("#loginBoxErrorMsg").html(I18N.get(a)).show()};LoginHandler.submit=function(b){$j.ajax({type:"POST",url:"/login/memberAuthController/login",data:{loginName:PageConfig.loginName,
valid:PageConfig.valid,password:EncryptUtil.mask(EncryptUtil.mask(PageConfig.password)+PageConfig.valid),validCode:PageConfig.validCode,fingerprint:PageConfig.fingerprint,fingerprint2:PageConfig.fingerprint2,fingerprintCanvas:PageConfig.fingerprintCanvas,fingerprintActiveX:PageConfig.fingerprintActiveX,fingerprintResolution:PageConfig.fingerprintResolution,tk:PageConfig.tk,di:PageConfig.di,"detecas-analysis":PageConfig.detecasAnalysis,bi:PageConfig.bi,__fdi:PageConfig.fdi,isDemoLogin:b},success:function(a){if(a&&
a.error){a.new_valid&&($j("#valid").val(a.new_valid),$j("#loginBoxValid").val(a.new_valid));if("["==a.error[0]){var c="";a=JSON.parse(a.error);for(var d in a)c=a[d]}else c=a.error;JsCache.get("#errorMsg").html(c).show();$j("#loginBoxErrorMsg").html(c).show();LoginHandler.refreshImgTask.refresh()}else if(a&&"string"==typeof a&&a.includes("banCountry"))document.write(a);else if("true"==a.resetPW)window.location.replace("/login/members/passwordOnSignIn.jsp");else if(c=PageConfig.ENABLE_LOGIN_CHANGE_LINE?
a.goTo:a.redirect,"undefined"==typeof GoogleAnalyticsHandler||!GoogleAnalyticsHandler.isEnable(PageConfig.webSiteType)||PageConfig.ENABLE_TERMS_CONDITIONS_PAGE&&-1!=c.indexOf("termsconditions.jsp")||GoogleAnalyticsHandler.loginSuccess(PageConfig.loginName,PageConfig.webSiteType),PageConfig.ENABLE_LOGIN_CHANGE_LINE)if(a.z&&a.e)if(0==window.location.hostname.indexOf("aws."))window.top.location=a.goTo;else for(PageConfig.goTo=a.goTo,PageConfig.z=a.z,PageConfig.e=a.e,PageConfig.eDefault=a.eDefault,PageConfig.port=
a.port,a=0;a<PageConfig.eDefault.length;a++)ImagePreload.loadImage(PageConfig.eDefault[a].host);else window.top.location=a.goTo;else a.redirect&&(location.href=a.redirect)},error:function(a,c,d){Trace.log(a.status);Trace.log(d);LoginHandler.refreshImgTask.refresh()}})};LoginHandler.refreshImgTask=TaskExecuter.createTask(60,0,function(){LoginHandler.refreshImg(this)});LoginHandler.refreshImg=function(b){if(null!=b){reloadImg("authenticateImage");var a=document.getElementById("authenticateImage"),c=
document.getElementById("loginBoxAuthenticateImage");if(null!=c&&0!=c.length)try{c.src=a.src}catch(d){Trace.log(d)}b.check();TaskExecuter.execute()}};LoginHandler.userIsLogin=function(){if(!PageConfig.hasAccount){var b=PageConfig.isFromAPI?$j("#loginToGoApi"):$j("#loginBox");b.fadeIn();b.find("#loginBoxErrorMsg").html("");e("#loginBoxLoginBtn");return!1}return!0};LoginHandler.hideLoginBox=function(b){$j("#"+b).fadeOut();e("#loginBtn")};LoginHandler.demoLogin=function(){LoginHandler.submit(!0)}})();

