"undefined"==typeof MarketHandler&&(MarketHandler={});
(function(){function f(a){-1==PageConfig.selectEventId||null!=PageConfig.selectMarketId?(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{b&&(JsCache.get("#listBoardLoading").hide(),
JsCache.get("#loading").hide(),null!=b.eventId&&0!=b.markets.length&&(DataBase.markets.update(b.eventId,b.markets),MarketHandler.updateMarkets(b.eventId,b.markets)))}catch(e){Trace.printStackTrace(e)}finally{a.check(),TaskExecuter.execute()}},error:function(){a.check();TaskExecuter.execute()}})}MarketHandler.getMarketsTask=null;MarketHandler.initGetMarketsTask=function(){MarketHandler.getMarketsTask=TaskExecuter.createTask(PageConfig.queryMarketsWithoutSelectionCycleTimes,0,function(){f(this)});MarketHandler.getMarketsTask.run();
TaskExecuter.execute()};MarketHandler.updateMarkets=function(a,b){var e=$j("#listBoard");if(null!=DataBase.events.get(PageConfig.selectEventType,a))for(a=0;a<b.length;a++){var c=b[a];if(null!=c&&null!=c.marketId){var d=e.find("#naviMenu_"+c.marketId.replace(".","_"));(MarketUtil.isClosed(c.status)||MarketUtil.isCloseSite(c.closeSite,PageConfig.webSiteType))&&0<d.length&&d.remove();1==c.inPlay?0<d.length&&(c=d.find("#name").find("img"),c.removeClass("icon-no_play"),c.addClass("icon-in_play")):0<d.length&&
(c=d.find("#name").find("img"),c.removeClass("icon-in_play"),c.addClass("icon-no_play"))}}};MarketHandler.checkMarkets=function(a,b,e,c){1!=c&&(0<=e.indexOf("_")&&(e=e.replace("_",".")),null==DataBase.markets.get(b,e)&&-1!=b&&$j.ajax({type:"POST",dataType:"JSON",url:"/member/playerService/queryMarkets",data:{eventType:a,eventId:b,selectionTs:-1},success:function(d){try{0<d.markets.length&&DataBase.markets.update(d.eventId,d.markets)}catch(g){Trace.printStackTrace(g)}},error:function(d){Trace.error("eventId: "+
b+" marketId: "+e+d)}}))};MarketHandler.sortRule=function(a,b,e,c,d,g){var h=a.localeCompare(b);if("Match Odds"==a)return-1;if("Match Odds"==b)return 1;if("Moneyline"==a)return-1;if("Moneyline"==b)return 1;if(e!=c)return c-e;if(EventType.SOCCER.unique()==EventType.getInstanceOf(PageConfig.selectEventType).unique()||EventType.E_SOCCER.unique()==EventType.getInstanceOf(PageConfig.selectEventType).unique()){if("Correct Score"==a)return-1;if("Correct Score"==b)return 1;if("Over/Under 2.5 Goals"==a)return-1;
if("Over/Under 2.5 Goals"==b)return 1;if(0<=a.indexOf("Over/Under")&&0<=b.indexOf("Over/Under"))return h;if(0<=a.indexOf("Over/Under"))return-1;if(0<=b.indexOf("Over/Under"))return 1}return d.localeCompare(g)}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.markets={};var f=new TreeMap;DataBase.markets.update=function(a,b){var e=f.get(a);null==e&&(e=new TreeMap,f.put(a,e));for(a=0;a<b.length;a++){var c=b[a],d=e.get(c.marketId);if(null!=d)if(0==c.selections.length)c.selections=d.selections;else{for(var g=0;g<c.selections.length;g++){let k=c.selections[g],l=k.selectionKey;for(var h=0;h<d.selections.length;h++)l==d.selections[h].selectionKey&&(d.selections[h]=k)}0==d.selections?d.selections=c.selections:c.selections=d.selections}e.put(c.marketId,
c)}};DataBase.markets.get=function(a,b){a=f.get(a);return null==a?null:a.get(b)};DataBase.markets.queryByEvent=function(a){var b=f.get(a);null==b&&(b=new TreeMap,f.put(a,b));return b.values()};DataBase.markets.getSelection=function(a,b,e){a=f.get(a);if(null==a)return null;b=a.get(b).selections;a=0;for(var c=b.length;a<c;a++){var d=b[a];if(d.selectionKey==e)return d}return null};DataBase.markets.getFirstSelection=function(a,b,e){a=f.get(a);if(null==a)return null;b=a.get(b).selections;a=0;for(var c=
b.length;a<c;a++){var d=b[a];if(d.selectionId==e)return d}return null}})();

