var MessageUtils={};(function(){MessageUtils.showThenGoToIndex=function(g){NoticeHandler.info(g);setTimeout(function(){var d=EventType.getInstanceOf(PageConfig.selectEventType);location=null!=d?d.isRacingEvent()?"/exchange/member/"+d.name.replace("_","-").toLowerCase():PageConfig.sportsPath+"?eventType="+d.value:PageConfig.sportsPath},3E3)}})();var HighlightsHandler={},selectHighlightsAjaxInProgress=!1;
(function(){HighlightsHandler.init=function(){$j("#previousPage").off("click").on("click",function(){$j(this).hasClass("disabled")||HighlightsHandler.PreviousPage()});$j("#nextPage").off("click").on("click",function(){$j(this).hasClass("disabled")||HighlightsHandler.NextPage()})};HighlightsHandler.viewType=function(){PageConfig.ENABLE_EXPAND_HIGHT_LIGHT_VIEW&&$j("#highlightLabel .select").click()};HighlightsHandler.selectHighlightTab=(g,d,f)=>{d!=PageConfig.highlightEventType&&(PageConfig.pinHighlightCurrentPage=
1);HighlightsHandler.selectHighlights(g,d,f);EventPinHighlightHandler.selectPinHighlights(d)};HighlightsHandler.selectHighlights=function(g,d,f){$j("#previousPage").addClass("disabled");$j("#nextPage").addClass("disabled");if(!selectHighlightsAjaxInProgress||f){selectHighlightsAjaxInProgress=!0;$j("#eventBoard").empty();d!=PageConfig.highlightEventType&&(PageConfig.highlightEventType=d,PageConfig.highlightCurrentPage=1);JsCache.get("#loading").css("top","260px").show();d=(PageConfig.enableQueryDataSubdomain&&
null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryEventsWithMarketPath;var a=PageConfig.highlightCurrentPage;f=$j("#viewType").val();$j.ajax({type:"POST",dataType:"JSON",url:d,data:{eventType:PageConfig.highlightEventType,competitionId:-1,eventTs:-1,marketTs:-1,selectionTs:-1,pageNumber:a,viewType:f,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){JsCache.get("#loading").hide();try{DataBase.events.remove(PageConfig.highlightEventType),
DataBase.events.update(b.events),EventHandler.updateEvents(null,!0),selectHighlightsAjaxInProgress=!1,PageConfig.ENABLE_DESKTOP_HIGHLIGHT_PAGINATION&&0<b.events.length?(1==b.lastPage?($j("#previousPage").hide(),$j("#nextPage").hide()):($j("#previousPage").show(),$j("#nextPage").show()),1==PageConfig.highlightCurrentPage?$j("#previousPage").addClass("disabled"):$j("#previousPage").removeClass("disabled"),b.lastPage==PageConfig.highlightCurrentPage?$j("#nextPage").addClass("disabled"):$j("#nextPage").removeClass("disabled")):
PageConfig.ENABLE_DESKTOP_HIGHLIGHT_PAGINATION&&1<a&&0==b.events.length?HighlightsHandler.PreviousPage():($j("#previousPage").hide(),$j("#nextPage").hide())}catch(c){Trace.printStackTrace(c)}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);JsCache.get("#loading").hide();selectHighlightsAjaxInProgress=!1},complete:function(){JsCache.get("#loading").hide();
selectHighlightsAjaxInProgress=!1}}).then(()=>{$j("#highlightLabel").find("a").removeClass("select");g?$j(g).addClass("select"):$j("#highlightTab"+PageConfig.highlightEventType).addClass("select")})}};HighlightsHandler.PreviousPage=function(){selectHighlightsAjaxInProgress||(--PageConfig.highlightCurrentPage,1>=PageConfig.highlightCurrentPage&&(PageConfig.highlightCurrentPage=1),DataBase.events.remove(PageConfig.highlightEventType),$j("#eventBoard").empty(),$j("#previousPage").addClass("disabled"),
$j("#nextPage").addClass("disabled"),HighlightsHandler.selectHighlights(null,PageConfig.highlightEventType,!1))};HighlightsHandler.NextPage=function(){selectHighlightsAjaxInProgress||(PageConfig.highlightCurrentPage+=1,DataBase.events.remove(PageConfig.highlightEventType),$j("#eventBoard").empty(),$j("#previousPage").addClass("disabled"),$j("#nextPage").addClass("disabled"),HighlightsHandler.selectHighlights(null,PageConfig.highlightEventType,!1))}})();var MemberPage={};
(function(){function g(a){a=EventType.getInstanceOf(a);return null!=a&&null!=a.webSiteType&&null!=a.webSiteType[PageConfig.webSiteType]&&null!=a.webSiteType[PageConfig.webSiteType].images?PageConfig.mediaURL+a.webSiteType[PageConfig.webSiteType].images:null!=a&&null!=a.images?PageConfig.mediaURL+a.images:null}MemberPage.init=function(){1==PageConfig.isTodaysCard?NavigationHandler.getMenu(PageConfig.selectEventType,!0,1):-1==PageConfig.selectEventType?MemberPage.viewHome():MemberPage.selectSport(PageConfig.selectEventType)};
MemberPage.viewHome=function(){TabMenuHandler.updateSelect("tabMenu","menu_Home");$j(".kv-wrap").find("img").attr("src",g("-1")).show();$j("[id^=sport_]").remove();$j("[id^=competition_]").remove();$j("[id^=countryCode_]").remove();$j("[id^=leftside_event_]").remove();$j("[id^=leftside_market_]").remove();NavigationBar.init();PageConfig.ENABLE_OCER_NAVIGATION?NavigationOcerMenuHandler.init():NavigationHandler.init();PageConfig.highlightEventType!=EventType.CRICKET.value&&PageConfig.webSiteType!=WebSiteType.FAIRENTER.unique()&&
PageConfig.webSiteType!=WebSiteType.KINGFAIR24.unique()&&PageConfig.webSiteType!=WebSiteType.ENTERFAIR.unique()&&PageConfig.webSiteType!=WebSiteType.EAGLEFAIR24.unique()&&PageConfig.webSiteType!=WebSiteType.SAFAIR24.unique()&&PageConfig.webSiteType!=WebSiteType.WEBPOINT7.unique()&&(PageConfig.highlightEventType=EventType.CRICKET.value);$j("[id^='highLightEvent_']").remove();PageConfig.selectEventType=-1;PageConfig.selectEventId=-1;PageConfig.selectMarketId=null;MemberPage.view("list");$j("#highlightLabel li a").removeClass("select");
$j("#highlightTab"+PageConfig.highlightEventType).addClass("select");$j("#highlightLabel").show();EventHandler.eventTsMap.put(PageConfig.highlightEventType,-1);EventHandler.marketTsMap.put(PageConfig.highlightEventType,-1);EventHandler.selectionTsMap.put(PageConfig.highlightEventType,-1);TxnHandler.updateOpenBetSelectionBox();TxnHandler.addBlankSelectOption(PageConfig.selectEventId,PageConfig.selectMarketId);PageConfig.isHideUpcomingHorseRace||UpcomingHandler.init();UiUtils.appendHeight(!0);"true"==
PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.show()};MemberPage.selectSport=function(a){if(PageConfig.selectMarketId||MultiMarketsHandler.isViewMultiMarket())location.href="/exchange/member/index.jsp?eventType="+a;$j(".kv-wrap").find("img").attr("src",g(a));$j("[id^=sport_]").remove();$j("[id^=competition_]").remove();$j("[id^=countryCode_]").remove();$j("[id^=leftside_event_]").remove();$j("[id^=leftside_market_]").remove();PageConfig.selectEventType=a;PageConfig.selectEventId=-1;PageConfig.selectMarketId=
null;PageConfig.highlightEventType!=a&&(PageConfig.highlightEventType=a);$j("#eventBoard").empty();$j("#highlightTab"+PageConfig.selectEventType).addClass("select");TabMenuHandler.updateSelect("tabMenu","menu_"+EventType.getInstanceOf(a).name);var b=I18N.get("eventType.name."+EventType.getInstanceOf(a).name);NavigationBar.init();let c=EventType.getInstanceOf(PageConfig.selectEventType);PageConfig.ENABLE_OCER_NAVIGATION&&!c.isRacingEvent()?NavigationOcerMenuHandler.getMenu(PageConfig.selectEventType,
"",-2,-1):(NavigationBar.addNode({id:a,type:"EVENT_TYPE",name:b}),NavigationHandler.getMenu([a]));MemberPage.view("list");$j("#highlightLabel").hide();b=DataBase.events.queryAll(a);null!=b&&0!=b.length&&EventHandler.updateEvents(null,!0);EventHandler.eventTsMap.put(a,-1);EventHandler.marketTsMap.put(a,-1);EventHandler.selectionTsMap.put(a,-1);TxnHandler.updateOpenBetSelectionBox();TxnHandler.addBlankSelectOption(PageConfig.selectEventId,PageConfig.selectMarketId);PageConfig.isHideUpcomingHorseRace||
UpcomingHandler.init();UiUtils.appendHeight(!0);"true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.show()};MemberPage.selectMarket=function(a,b,c){var e=1==PageConfig.isTodaysCard?!0:!1;if(PageConfig.selectMarketId!=c)MessageUtils.showThenGoToIndex("marketId not match");else{var n=EventType.getInstanceOf(a),h=DataBase.events.get(a,b),l=DataBase.markets.get(b,c);if(null!=l&&null!=h||1!=e||null==n||!n.isRacingEvent())if(null==h&&0==e)MessageUtils.showThenGoToIndex("event is not available");
else if(null==l&&0==e)MessageUtils.showThenGoToIndex("market is not available");else{PageConfig.uiSelect={};PageConfig.uiSelect.act="selectMarket";PageConfig.uiSelect.competitionName=PageConfig.selectCompetitionName;PageConfig.uiSelect.eventType=a;PageConfig.uiSelect.eventId=b;PageConfig.uiSelect.marketId=c;CookieUtil.setCookie(PageConfig.uiCookie,JSON.stringify(PageConfig.uiSelect),-1);$j("[id^='highLightEvent_']").remove();$j("[id^=fullSelection_]").remove();PageConfig.ENABLE_OCER_NAVIGATION&&!n.isRacingEvent()?
NavigationOcerMenuHandler.getMenu(PageConfig.selectEventType,"",-2,b):(1<=NavigationHandler.navigationIds.length&&(NavigationHandler.navigationIds[0]!=PageConfig.selectEventType||NavigationHandler.navigationIds[NavigationHandler.navigationIds.length-1]!=b)&&0==e&&(NavigationHandler.navigationIds=[]),0==NavigationHandler.navigationIds.length&&0==e?null!=PageConfig.fcId?NavigationHandler.getNavigationPathFully(PageConfig.selectEventType,PageConfig.fcId):EventType.ELECTION.unique()==PageConfig.selectEventType?
NavigationHandler.getMenu([PageConfig.selectEventType],!0):NavigationHandler.getNavigationPathFully(PageConfig.selectEventType,b):(JsCache.get("#listBoard").find("li").removeClass("select"),$j("#naviMenu_"+c.replace(".","_")).addClass("select")),1==e&&(NavigationBar.addTodaysCardNode(PageConfig.selectEventType),NavigationHandler.getMenu([PageConfig.selectEventType],!1,1,b,c)));e=b+"_"+c.replace(".","_");TabMenuHandler.updateSelect("tabMenu","menu_"+EventType.getInstanceOf(a).name+"_"+e);LiveMatchTrackerHandler.isEnableLiveMatchTracker(a)?
MemberPage.view("liveMatchTracker"):null!=h.scores&&LiveScoreHandler.isEnableLiveScore()?(MemberPage.view("marketLiveScore"),JsCache.get("#scoresEvent").html(l.marketName+'<img src="/images/transparent.gif">'),LiveScoreHandler.appendInfo(h.scores,h.matchInfo,h.scoresDetail,h.timeElapsed,a,b,c)):(MemberPage.view("market"),MultiMarketsHandler.appendGameHeadPin(a,b,c));e=$j("#gameHead");var k=JsCache.get("#gameTeam");k.find("#noTeam").hide();k.find("#twoTeam").hide();h=h.name;var p=l.marketName,m=" v ";
0<=h.indexOf(" vs ")?m=" vs ":0<=h.indexOf(" @ ")&&(m=" @ ");1<h.split(m).length?(k.find("#gameVisit").html(h.split(m)[0]+"<span></span>"),k.find("#gameVs").html("<div>"+p+"<span>"+m.trim()+"</span></div>"),k.find("#gameHome").html(h.split(m)[1]+"<span></span>"),k.find("#noTeam").hide(),k.find("#twoTeam").show()):(k.find(".game-name").html(h+"<span>"+p+"</span>"),k.find("#noTeam").show(),k.find("#twoTeam").hide());PageConfig.ENABLE_LINE_MARKET&&(MarketUtil.isLineMarket(l.marketType,l.bettingType)?
(k.addClass("line_markets-team"),e.find("#lineMarketRulesBtn").show()):(k.removeClass("line_markets-team"),e.find("#lineMarketRulesBtn").hide()));PageConfig.selectEventType=a;PageConfig.selectEventId=b;PageConfig.selectMarketId=c;TxnHandler.updateOpenBetSelectionBox();TxnHandler.addBlankSelectOption(PageConfig.selectEventId,PageConfig.selectMarketId);PopularMarketHandler.init();PopularMarketHandler.appendAllTab();null!=n&&n.isRacingEvent()&&NavigationHandler.updateTabMarket();UiUtils.appendHeight();
"true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.show();PageConfig.ENABLE_LINE_MARKET&&(a=$j("#betSlipBoard").find("[name=slipHeader]"),MarketUtil.isLineMarket(l.marketType,l.bettingType)?(a.find("#oddsHeader").hide(),a.find("#runsHeader").show()):(a.find("#oddsHeader").show(),a.find("#runsHeader").hide()))}else MemberPage.view("marketClose"),NavigationBar.addTodaysCardNode(a),NavigationHandler.getMenu([a],!1,1,b,c)}};MemberPage.multiMarkets=function(){0==MultiMarketsHandler.isHasMultiMarket()?
$j("#noMultiMarkets").show():$j("#noMultiMarkets").hide();TabMenuHandler.updateSelect("tabMenu","menu_MultiMarkets");PageConfig.highlightEventType=-1;PageConfig.selectEventType=-1;PageConfig.selectEventId=-1;PageConfig.selectMarketId=null;$j("[name=multiMarketItem]").remove();MemberPage.view("multiMarkets");NavigationBar.init();PageConfig.ENABLE_OCER_NAVIGATION?NavigationOcerMenuHandler.init():NavigationHandler.init();MultiMarketsHandler.getMultiMarket();var a=JsCache.get("#upcomingHorseRace");a&&
a.is(":visible")&&a.hide();UiUtils.appendHeight(!0);"true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.show()};var d=[{name:"list",elem:[".kv-wrap","#gameHighlightWrap"]},{name:"today",elem:[".function-wrap","#sportListWrap"]},{name:"market",elem:[]},{name:"marketClose",elem:["#marketClosedWrap"]},{name:"marketLiveScore",elem:[".game-scores","#scoresEvent"]},{name:"multiMarkets",elem:["#multiMarketsWrap"]},{name:"liveMatchTracker",elem:["#liveMatchGameHead"]}],f=[{elem:".col-left",views:"list market marketClose marketLiveScore multiMarkets liveMatchTracker".split(" ")},
{elem:"#gameHead",views:["market","marketLiveScore"]},{elem:"#gameTeam",views:["market"]},{elem:".game-info",views:["market","marketLiveScore","liveMatchTracker"]},{elem:".game-matched",views:["market","marketLiveScore","liveMatchTracker"]},{elem:"#fullMarketEventLeft",views:["market","marketLiveScore","liveMatchTracker"]},{elem:"#fullMarketEventRight",views:["market","marketLiveScore","liveMatchTracker"]}];MemberPage.view=function(a){"inPlay"==a?($j(".col-center").addClass("inplay"),$j("[id^='inPlayEventType_']").show()):
"today"==a?($j(".col-center").addClass("inplay"),$j("[id^='inPlayEventType_']").hide()):"market"==a||"marketClose"==a||"marketLiveScore"==a||"liveMatchTracker"==a?$j(".col-center").addClass("markets"):($j("[id^='inPlayEventType_']").hide(),$j(".col-center").removeClass("inplay"),$j(".col-center").removeClass("markets"));for(var b=0;b<d.length;b++)for(var c=0;c<d[b].elem.length;c++){var e=d[b].elem[c];a==d[b].name?null!=$j(e)?$j(e).show():Trace.error(e+" not found"):null!=$j(e)?$j(e).hide():Trace.error(e+
" not found")}for(b=0;b<f.length;b++)for(e=f[b].elem,c=0;c<f[b].views.length;c++){if(a==f[b].views[c]){$j(e).show();break}$j(e).hide()}}})();var isEqual=function(g,d){return JSON.stringify(g)===JSON.stringify(d)};"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.sports={};var g=new TreeMap;DataBase.sports.update=function(a){for(var b=0;b<a.length;b++){var c=a[b];c.name=I18N.get("eventType.name."+EventType.getInstanceOf(c.id).name);g.put(c.id,c)}};DataBase.sports.get=function(a){return g.get(a)};DataBase.sports.queryAll=function(){return g.values()};DataBase.sports.sort=function(){g.sort(function(a,b){return a.value.name.localeCompare(b.value.name)})};DataBase.competitions={};var d=new TreeMap;DataBase.competitions.update=function(a,b){var c=
d.get(a);null==c&&(c=new TreeMap,d.put(a,c));for(a=0;a<b.length;a++){var e=b[a];c.put(e.id,e)}};DataBase.competitions.get=function(a,b){var c=d.get(a);null==c&&(c=new TreeMap,d.put(a,c));return c.get(b)};DataBase.competitions.queryAll=function(a){var b=d.get(a);null==b&&(b=new TreeMap,d.put(a,b));return b.values()};DataBase.competitions.size=function(a){return d.get(a).length};DataBase.competitions.sort=function(a){var b=d.get(a);null==b?(b=new TreeMap,d.put(a,b)):b.sort(function(c,e){return c.value.name.localeCompare(e.value.name)})};
DataBase.countryCodes={};var f=new TreeMap;DataBase.countryCodes.update=function(a,b){var c=f.get(a);null==c&&(c=new TreeMap,f.put(a,c));for(a=0;a<b.length;a++){var e=b[a];c.put(e.code,e)}};DataBase.countryCodes.get=function(a,b){return null==f.get(a)?null:f.get(a).get(b)};DataBase.countryCodes.queryAll=function(a){var b=f.get(a);null==b&&(b=new TreeMap,f.put(a,b));return b.values()};DataBase.countryCodes.sort=function(){f.sort(function(a,b){return a.value.code.localeCompare(b.value.code)})}})();

