"undefined"==typeof TopMenuHandler&&(TopMenuHandler={});
(function(){function d(a){c[a]=CookieUtil.getCookie(a+"AcceptAnyOdds_"+PageConfig.userID);if(PageConfig.isEnableAcceptOdds){null==c[a]&&(c[a]=0,"sportsBook"==a||"fancyBet"==a||"financial"==a)&&(c[a]=1);TopMenuHandler.appendAcceptAnyOdds(a);var b=$j("#set_pop");b.find("#coinSave").on("click",function(g){TopMenuHandler.getAcceptAnyOdds(a);TopMenuHandler.setCookie(a);TopMenuHandler.appendAcceptAnyOdds(a)});b.find("#closeSet").on("click",function(){TopMenuHandler.appendAcceptAnyOdds(a)})}else c[a]=0}
var c={};TopMenuHandler.init=function(){if(PageConfig.hasAccount){LogoutUtilHandler.init();var a=$j("#logout");0<a.length&&a.click(function(){try{PageConfig.isFromAPI?LogoutUtilHandler.logoutAPI():LogoutUtilHandler.logout()}catch(b){}});JsCache.get("#accountPopup").click(function(b){TopMenuHandler.accountPopup(this);$j(document).click(function(){JsCache.get("#account_pop").hide();$j(document).unbind("click")});JsCache.get("#set_pop").is(":visible")&&(CoinHandler.coinSelectCancel(),SparkHandler.setEnableCheckBox(),
TopMenuHandler.appendAllAcceptAnyOdds(),JsCache.get("#set_pop").hide());b.stopPropagation()});JsCache.get("#menuRefresh").click(function(b){JsCache.get("#accountCredit").hide();JsCache.get("#menuRefreshLoading").show();TopMenuHandler.getPlayerInfoTask.refresh();setTimeout(function(){JsCache.get("#accountCredit").show();JsCache.get("#menuRefreshLoading").hide()},1E3)});JsCache.get("#accountCredit").click(function(b){PageConfig.isFromApi||TopMenuHandler.queryBalanceDetail()})}d("fancyBet");d("sportsBook");
d("financial")};TopMenuHandler.accountPopup=function(a){JsCache.get("#account_pop").toggle()};TopMenuHandler.getPlayerInfoTask=TaskExecuter.createTask(5,0,function(){TopMenuHandler.getPlayerInfo(this)});TopMenuHandler.getPlayerInfo=function(a){null!=a&&$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+"/member/playerService/queryPlayerInfo",data:{queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},
success:function(b){try{if(null!=b){var g=$j("#accountCredit"),f=JsCache.get("#betCredit"),k=JsCache.get("#totalExposure"),p=JsCache.get("#mainBalance"),m=JsCache.get("#mainExposure"),n=CurrencyType.getInstanceOf(PageConfig.playerCurrency),h={precision:2,separateSign:",",currencySymbol:n.symbol,formatter:function(e,l){l=0==StringUtil.getlength(StringUtil.trim(l.currencySymbol))?"":l.currencySymbol;return 0==e.indexOf("-")?"("+l+e.replace("-","")+")":l+e},"trailingZeros,":!1};f.removeClass("red");
k.removeClass("red");p.removeClass("red");m.removeClass("red");f.html(n.name+" "+CurrencyUtil.formatter(b.betCredit,h));k.html(CurrencyUtil.formatter(b.totalExposure,h));p.html(CurrencyUtil.formatter(b.betCredit,h));m.html(CurrencyUtil.formatter(b.totalExposure,h));0>b.betCredit&&(f.addClass("red"),p.addClass("red"));0>b.totalExposure&&(k.addClass("red"),m.addClass("red"));null!=b.minBet&&(PageConfig.minBet=b.minBet);g.find("#vendorQuantity").html(b.vendorQuantity)}}catch(e){Trace.printStackTrace(e)}finally{a.check(),
TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})};TopMenuHandler.appendAcceptAnyOdds=function(a){var b=$j("#"+a+"AcceptAnyOddsCheckBox"),g=$j("[id^="+a+"AcceptAnyOdds]");1==c[a]?(b.prop("checked",!0),g.prop("checked",!0)):(b.prop("checked",!1),g.prop("checked",!1))};TopMenuHandler.appendAllAcceptAnyOdds=
function(){TopMenuHandler.appendAcceptAnyOdds("fancyBet");TopMenuHandler.appendAcceptAnyOdds("sportsBook");TopMenuHandler.appendAcceptAnyOdds("financial")};TopMenuHandler.getAcceptAnyOdds=function(a){1==$j("#"+a+"AcceptAnyOddsCheckBox").prop("checked")?c[a]=1:c[a]=0};TopMenuHandler.setCookie=function(a){CookieUtil.setCookie(a+"AcceptAnyOdds_"+PageConfig.userID,c[a],999)};TopMenuHandler.isAcceptAnyOdds=function(a){return 1==c[a]};TopMenuHandler.queryBalanceDetail=function(){$j.ajax({type:"POST",dataType:"JSON",
url:"/member/playerService/queryPlayerBalanceDetail",data:{},success:function(a){try{if(null!=a){var b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),g={precision:2,separateSign:",",currencySymbol:b.symbol,formatter:function(h,e){e=0==StringUtil.getlength(StringUtil.trim(e.currencySymbol))?"":e.currencySymbol;return 0==h.indexOf("-")?"("+e+h.replace("-","")+")":e+h},"trailingZeros,":!1},f=$j("#multiBalancePop");f.find("#mainBalance").removeClass("red");f.find("#mainExposure").removeClass("red");
$j.each(a.mainBalanceList,function(h,e){f.find("#currency").html(b.name);f.find("#mainBalance").html(CurrencyUtil.formatter(e.mainBalance,g));f.find("#mainExposure").html(CurrencyUtil.formatter(e.exposure,g));0>e.mainBalance&&f.find("#mainBalance").addClass("red");0>e.exposure&&f.find("#mainExposure").addClass("red")});if(null!=a.vendorBalanceList&&0!==a.vendorBalanceList.length){var k=f.find("#walletContent"),p=f.find("#walletTemp");k.html("");var m="";$j.each(a.vendorBalanceList,function(h,e){VendorSiteType.MT5.value!=
e.vendorSite&&(m+=e.vendorSite+",");h=p.find("#tempDl").clone();h.find("#vendorCurrency").attr("id","vendorCurrency_"+e.vendorSite).text(b.name);h.find("#vendorTitle").attr("id","vendorTitle_"+e.vendorSite).text(e.vendorName+" Balance");var l=e.vendorBalance;VendorSiteType.ARION.value==VendorSiteType.getInstanceOf(e.vendorSite).value&&(l+=" Points");h.find("#vendorBalance").attr("id","vendorBalance_"+e.vendorSite).text(l);h.find("#recall").attr("id","recall_"+e.vendorSite).attr("onclick","TopMenuHandler.recall('"+
e.vendorSite+"')");k.append(h)});var n=f.find("#recallAllDl").clone();n.find("#recallAll").attr("onclick","TopMenuHandler.recall('"+m.substr(0,m.length-1)+"')");n.find("#recallAll").prop("disabled",!1);k.append(n)}}}catch(h){NoticeHandler.error(h.message)}},error:function(a,b,g){Trace.log(a.status);Trace.log(g)}})};TopMenuHandler.recall=function(a){var b=a.split(",");$j.each(b,function(g){$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/vendorController/withdraw",data:{vendorSite:b[g],isWithdrawAll:!0},
beforeSend:function(){$j("#multiBalancePop #recall_"+b[g]).prop("disabled",!0);$j("#multiBalancePop #recallAll").prop("disabled",!0)},complete:function(){$j("#multiBalancePop #recallAll").prop("disabled",!1)},success:function(f){null!=f&&(f.error&&NoticeHandler.error(f.error),f.success&&b.length-1==g&&TopMenuHandler.queryBalanceDetail())}})})}})();var TabMenuHandler={};
(function(){TabMenuHandler.updateSelect=function(d,c){JsCache.get("#"+d).find("a").removeClass("select");JsCache.get("#"+d).find("#"+c).addClass("select")}})();"undefined"==typeof SparkHandler&&(SparkHandler={});
(function(){var d=1;SparkHandler.init=function(){var c=JsCache.get("#enableSparkCheck");d=CookieUtil.getCookie("enableSpark_"+PageConfig.userID);null==d&&(d=1);1==d?c.prop("checked",!0):c.prop("checked",!1);JsCache.get("#slipSet").click(function(a){$j(document).click(function(){SparkHandler.setEnableCheckBox();$j(document).unbind("click")})});JsCache.get("#coinSave").click(function(a){SparkHandler.getEnableSpark();SparkHandler.setCookie();SparkHandler.setEnableCheckBox();a.stopPropagation()});JsCache.get("#closeSet").click(function(a){SparkHandler.setEnableCheckBox()})};
SparkHandler.setCookie=function(){CookieUtil.setCookie("enableSpark_"+PageConfig.userID,d,999)};SparkHandler.setEnableCheckBox=function(){var c=JsCache.get("#enableSparkCheck");1==d?c.prop("checked",!0):c.prop("checked",!1)};SparkHandler.getEnableSpark=function(){d=1==JsCache.get("#enableSparkCheck").prop("checked")?1:0};SparkHandler.addSparkClass=function(c,a,b){if(1==d&&(null!=a||null!=b)){var g=c.prop("sparkOdds"),f=c.prop("sparkStake");null!=g&&g!=a||null!=f&&f!=b?c.addClass("spark"):c.removeClass("spark");
null!=a&&c.prop("sparkOdds",a);null!=b&&c.prop("sparkStake",b)}};SparkHandler.addFancyBetSpark=function(c,a,b){if(1==d&&(null!=a||null!=b)){var g=c.prop("sparkRuns"),f=c.prop("sparkOdds");if(g!=a||f!=b){c.addClass("spark");var k=setTimeout(function(){c.removeClass("spark");null!=k&&clearTimeout(k)},1E3)}g!=a&&c.prop("sparkRuns",a);f!=b&&c.prop("sparkOdds",b)}}})();"undefined"==typeof ZoomHandler&&(ZoomHandler={});
(function(){ZoomHandler.zoomLevel=1;ZoomHandler.init=function(){var d=null;ZoomHandler.zoomLevel=ZoomHandler.readCookie();1==ZoomHandler.zoomLevel?d=JsCache.get("#zoom_S"):1.2==ZoomHandler.zoomLevel?d=JsCache.get("#zoom_M"):1.35==ZoomHandler.zoomLevel&&(d=JsCache.get("#zoom_L"));ZoomHandler.updateZoom(d,ZoomHandler.zoomLevel);JsCache.get("#zoom_S").click(function(){ZoomHandler.updateZoom(JsCache.get("#zoom_S"),1)});JsCache.get("#zoom_M").click(function(){ZoomHandler.updateZoom(JsCache.get("#zoom_M"),
1.2)});JsCache.get("#zoom_L").click(function(){ZoomHandler.updateZoom(JsCache.get("#zoom_L"),1.35)})};ZoomHandler.updateZoom=function(d,c){ZoomHandler.zoomLevel=c;$j("body").css({zoom:ZoomHandler.zoomLevel,"-moz-transform":"scale("+ZoomHandler.zoomLevel+")","-moz-transform-origin":"left top"});$j("#zoomBoard").find("[id^=zoom_]").removeClass("select");d.addClass("select");ZoomHandler.saveCookie(c)};ZoomHandler.readCookie=function(){var d=CookieUtil.getCookie("zoomSize_"+PageConfig.userID);return null==
d||0==ZoomHandler.isValid(d)?1:d};ZoomHandler.saveCookie=function(d){0==ZoomHandler.isValid(d)?CookieUtil.setCookie("zoomSize_"+PageConfig.userID,1,999):CookieUtil.setCookie("zoomSize_"+PageConfig.userID,d,999)};ZoomHandler.isValid=function(d){return 1==d||1.2==d||1.35==d}})();

