"undefined"==typeof MultiMarketsHandler&&(MultiMarketsHandler={});
(function(){function t(a,c){return m.BTNPIN==c?!a.hasClass("select"):a.hasClass("add-pin")}function k(a,c){m.BTNPIN==c?a.addClass("select"):a.attr("class","delete-pin")}function n(a,c){m.BTNPIN==c?a.removeClass("select"):a.attr("class","add-pin")}function l(a){var c=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BETFAIR.unique());-1!=PageConfig.highlightEventType||-1!=PageConfig.selectEventId||null!=PageConfig.selectMarketId||null==c||0==c.length?(a.check(),TaskExecuterV2.execute()):$j.ajax({type:"POST",
dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMultiMarketsPath,data:{marketPks:JSON.stringify(c),queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(e){try{for(var b=e.multiMarkets,d=0;d<b.length;d++){var g=b[d],f=g.market;null!=f&&DataBase.markets.update(g.eventId,[f])}MultiMarketsHandler.updateMultiMarketList(e,!1)}catch(h){Trace.printStackTrace(h)}finally{a.check(),
TaskExecuterV2.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuterV2.execute()}})}var m={ADDPIN:"ADDPIN",BTNPIN:"BTNPIN"};MultiMarketsHandler.init=async function(){await MultiMarketsHandler.initFromCookie()};MultiMarketsHandler.bindPinEvent=function(a,c,e,b){let d=a.find("#multiMarketPin");c===EventType.ELECTION.unique()&&
d.hide();MultiMarketsHandler.clickEvent(d,c,CategoryType.BETFAIR.unique(),e,b,a)};MultiMarketsHandler.clickEvent=function(a,c,e,b,d,g,f){a.unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())t(a,f)?(DataBase.multiMarkets.addMarketPk(c,e,b,d),MultiMarketsHandler.addToCookie().then(h=>{h?(k(a,f),a.attr("title",I18N.get("msg.member.multiMarkets.removeFrom")),EventPinHighlightHandler.init()):DataBase.multiMarkets.removeMarketPk(c,e,b,d)})):(n(a,f),a.attr("title",
I18N.get("msg.member.multiMarkets.addTo")),DataBase.multiMarkets.removeMarketPk(c,e,b,d),MultiMarketsHandler.addToCookie(),1==MultiMarketsHandler.isViewMultiMarket()&&null!=g&&MultiMarketsHandler.removeMarketElemFromMultiMarket(g),EventPinHighlightHandler.init())})};MultiMarketsHandler.removeMarketElemFromMultiMarket=function(a){if("multiMarketItem"==a.attr("name")){a.fadeOut();setTimeout(function(){a.remove()},1E3);var c=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BETFAIR.unique()),
e=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.FANCY_BET.unique()),b=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.SPORTRADAR_SPORTSBOOK.unique()),d=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.OW_SPORTSBOOK.unique()),g=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BOOK_MAKER.unique());0==c.length&&0==e.length&&0==b.length&&0==d.length&&0==g.length&&MemberPage.multiMarkets()}};MultiMarketsHandler.checkIsMultiMarket=function(a,c,e,b,d,g){"undefined"==
typeof g&&(g=CategoryType.BETFAIR.unique());g=DataBase.multiMarkets.queryAllByCategoryType(g);for(var f=0;f<g.length;f++){var h=g[f];if(c==h.eventType&&e==h.eventId&&b==h.marketId){k(a,d);a.attr("title",I18N.get("msg.member.multiMarkets.removeFrom"));break}n(a,d);a.attr("title",I18N.get("msg.member.multiMarkets.addTo"))}};MultiMarketsHandler.appendGameHeadPin=function(a,c,e,b){var d=$j("#gameHead").find("#multiMarketPin");MultiMarketsHandler.bindHeadPinEvent(d,a,c,e);a==EventType.ELECTION.unique()?
d.hide():d.show();null!=b&&b.find("#gameHeadPinSpace").show()};MultiMarketsHandler.appendLiveMatchTrackerPin=function(a,c,e){var b=$j("#overWrap").find("#liveMultiMarketPin");MultiMarketsHandler.bindHeadPinEvent(b,a,c,e,m.BTNPIN);b.show()};MultiMarketsHandler.appendFancyBetPin=function(a,c,e){var b=$j("#fancyBetTable_"+c);e=(e?b.find("#fancyBetHead"):b.find("#fancyBetSpecialBet")).find("#multiMarketPin");MultiMarketsHandler.clickEvent(e,a,CategoryType.FANCY_BET.unique(),c,CategoryType.FANCY_BET.name,
b);MultiMarketsHandler.checkIsMultiMarket(e,a,c,CategoryType.FANCY_BET.name,null,CategoryType.FANCY_BET.unique())};MultiMarketsHandler.appendSportsBookPin=function(a,c,e,b,d,g){d?(c=$j("#sportsBookTable_"+c),d=c.find("#sportsBookHead")):(c=$j("#sportsBookMarket_"+c),d=c.find("#marketHeader"));d=d.find("#multiMarketPin");g=ApiSiteType.SPORTRADAR.unique()==g?CategoryType.SPORTRADAR_SPORTSBOOK.unique():CategoryType.OW_SPORTSBOOK.unique();MultiMarketsHandler.clickEvent(d,a,g,e,b,c);MultiMarketsHandler.checkIsMultiMarket(d,
a,e,b,null,g)};MultiMarketsHandler.appendBookMakerPin=function(a,c,e){let b;e?(e=$j("#bookMakerTable_"+c),b=e.find("#bookMakerHead").find("#multiMarketPin")):(e=$j("#bookMakerWrap"),b=e.find("#bookMakerSpecialBet").find("#multiMarketPin"));MultiMarketsHandler.clickEvent(b,a,CategoryType.BOOK_MAKER.unique(),c,CategoryType.BOOK_MAKER.name,e);MultiMarketsHandler.checkIsMultiMarket(b,a,c,CategoryType.BOOK_MAKER.name,null,CategoryType.BOOK_MAKER.unique())};MultiMarketsHandler.bindHeadPinEvent=function(a,
c,e,b,d){MultiMarketsHandler.clickEvent(a,c,CategoryType.BETFAIR.unique(),e,b,null,d);MultiMarketsHandler.checkIsMultiMarket(a,c,e,b,d);a.attr("eventType",c);a.attr("eventId",e);a.attr("marketId",b)};MultiMarketsHandler.isHasMultiMarket=function(){var a=MultiMarketsHandler.readCookie();if(null==a)return!1;var c=a[CategoryType.BETFAIR.unique()],e=a[CategoryType.FANCY_BET.unique()],b=a[CategoryType.SPORTRADAR_SPORTSBOOK.unique()],d=a[CategoryType.OW_SPORTSBOOK.unique()];a=a[CategoryType.BOOK_MAKER.unique()];
return null!=c&&0!=c.length||null!=e&&0!=e.length||null!=b&&0!=b.length||null!=d&&0!=d.length||null!=a&&0!=a.length?!0:!1};MultiMarketsHandler.isHasFancybetMultiMarket=function(){var a=MultiMarketsHandler.readCookie();if(null==a)return!1;a=a[CategoryType.FANCY_BET.unique()];return null!=a&&0<a.length?!0:!1};MultiMarketsHandler.isHasSportsBookMultiMarket=function(){var a=MultiMarketsHandler.readCookie();if(null==a)return!1;a=a[CategoryType.SPORTRADAR_SPORTSBOOK.unique()];return null!=a&&0<a.length?
!0:!1};MultiMarketsHandler.isHasOwSportsBookMultiMarket=function(){var a=MultiMarketsHandler.readCookie();if(null==a)return!1;a=a[CategoryType.OW_SPORTSBOOK.unique()];return null!=a&&0<a.length?!0:!1};MultiMarketsHandler.isHasBookMakerMultiMarket=function(){var a=MultiMarketsHandler.readCookie();if(null==a)return!1;a=a[CategoryType.BOOK_MAKER.unique()];return null!=a&&0<a.length?!0:!1};MultiMarketsHandler.isViewMultiMarket=function(){return-1<location.href.indexOf("multiMarkets")};MultiMarketsHandler.addToCookie=
async()=>{let a=DataBase.multiMarkets.queryForCookie();if(50<a[CategoryType.BETFAIR.unique()].length+a[CategoryType.FANCY_BET.unique()].length+a[CategoryType.SPORTRADAR_SPORTSBOOK.unique()].length+a[CategoryType.OW_SPORTSBOOK.unique()].length+a[CategoryType.BOOK_MAKER.unique()].length)return NoticeHandler.error(I18N.get("msg.popup.cookieOverLimit",[50])),!1;let c=CookieUtil.getCookieDomainFormat(window.location.hostname);CookieUtil.setCookie("multiMarket_"+PageConfig.userID,JSON.stringify(a),999,
null,c);return!0};MultiMarketsHandler.readCookie=function(){var a=CookieUtil.getCookie("multiMarket_"+PageConfig.userID);return JSON.parse(a)};MultiMarketsHandler.initDataBase=function(){if(MultiMarketsHandler.isHasMultiMarket()){var a=MultiMarketsHandler.readCookie(),c=a[CategoryType.BETFAIR.unique()],e=a[CategoryType.FANCY_BET.unique()],b=a[CategoryType.SPORTRADAR_SPORTSBOOK.unique()],d=a[CategoryType.OW_SPORTSBOOK.unique()];a=a[CategoryType.BOOK_MAKER.unique()];null!=c&&0<c.length&&$j.each(c,function(g,
f){if(3!=f.length)return!0;DataBase.multiMarkets.addMarketPk(f[0],CategoryType.BETFAIR.unique(),f[1],f[2])});null!=e&&0<e.length&&$j.each(e,function(g,f){if(2!=f.length)return!0;DataBase.multiMarkets.addMarketPk(f[0],CategoryType.FANCY_BET.unique(),f[1],CategoryType.FANCY_BET.name)});null!=b&&0<b.length&&$j.each(b,function(g,f){if(3!=f.length)return!0;DataBase.multiMarkets.addMarketPk(f[0],CategoryType.SPORTRADAR_SPORTSBOOK.unique(),f[1],f[2])});null!=d&&0<d.length&&$j.each(d,function(g,f){if(3!=
f.length)return!0;DataBase.multiMarkets.addMarketPk(f[0],CategoryType.OW_SPORTSBOOK.unique(),f[1],f[2])});null!=a&&0<a.length&&$j.each(a,function(g,f){if(2!==f.length)return!0;DataBase.multiMarkets.addMarketPk(f[0],CategoryType.BOOK_MAKER.unique(),f[1],CategoryType.BOOK_MAKER.name)})}};MultiMarketsHandler.checkAndAddBetfairDataBase=function(a,c){if(null!=a&&0<a.length){var e=[];$j.each(a,function(b,d){if(3!=d.length)return!0;e.push({eventType:d[0],eventId:d[1],marketId:d[2],selectionTs:-1})});return $j.ajax({type:"POST",
dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMultiMarketsPath,data:{marketPks:JSON.stringify(e),queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{var d=b.multiMarkets;d.length!=e.length&&DataBase.multiMarkets.removeAllByCategoryType(CategoryType.BETFAIR.unique());for(b=0;b<d.length;b++){var g=d[b],f=g.eventType,h=g.eventId,r=g.marketId,q=g.market;null!=q&&(DataBase.markets.update(h,
[q]),DataBase.multiMarkets.addMarketPk(f,CategoryType.BETFAIR.unique(),h,r),EventHandler.checkEvents(f,h,!0,null))}MultiMarketsHandler.addToCookie()}catch(p){Trace.printStackTrace(p)}},error:function(b){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(b)}})}};MultiMarketsHandler.checkAndAddFancybetDataBase=function(a,c){if(null!=a&&0<a.length){var e=
[];$j.each(a,function(b,d){if(2!=d.length)return!0;e.push({eventType:d[0],eventId:d[1],version:-1,oddsSettingVersion:-1})});return $j.ajax({type:"POST",dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/queryFancyBetMultiMarkets",data:{marketPks:JSON.stringify(e)},success:function(b){try{var d=b.fancyBets;d.length!=e.length&&DataBase.multiMarkets.removeAllByCategoryType(CategoryType.FANCY_BET.unique());for(b=0;b<d.length;b++){var g=d[b],f=g.fancyBetMarkets[0].eventType,h=g.fancyBetMarkets[0].eventId,
r=CategoryType.FANCY_BET.name;DataBase.fancyBetMarkets.update(h,g.fancyBetMarkets);DataBase.multiMarkets.addMarketPk(f,CategoryType.FANCY_BET.unique(),h,r);EventHandler.checkEvents(f,h,!0,null)}MultiMarketsHandler.addToCookie()}catch(q){Trace.printStackTrace(q)}},error:function(b){Trace.printStackTrace(b)}})}};MultiMarketsHandler.checkAndAddSportsBookDataBase=function(a,c,e){if(null!=a&&0<a.length){var b=[];$j.each(a,function(d,g){if(3!=g.length)return!0;b.push({eventType:g[0],betfairEventId:g[1],
marketId:g[2],selectionTs:-1,apiSiteType:e})});return $j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.landingPath+"/member/playerService/querySportsBookMultiMarkets",data:{marketPks:JSON.stringify(b),queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(d){try{var g=d.sportsBookEvents,f=ApiSiteType.SPORTRADAR.unique()==e?CategoryType.SPORTRADAR_SPORTSBOOK.unique():
CategoryType.OW_SPORTSBOOK.unique();b.length!=g.length&&DataBase.multiMarkets.removeAllByCategoryType(f);for(d=0;d<g.length;d++){var h=g[d],r=h.eventId,q=h.sportsBookMarket;DataBase.sportsBookMarkets.update(e,r,q);for(var p in q){var u=q[p],v=u.eventType;DataBase.multiMarkets.addMarketPk(v,f,u.betfairEventId,u.id)}EventHandler.checkEvents(v,r,!0,null)}MultiMarketsHandler.addToCookie()}catch(w){Trace.printStackTrace(w)}},error:function(d){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&
!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(d)}})}};MultiMarketsHandler.checkAndAddBookMakerDataBase=function(a,c){if(null!=a&&0<a.length){let e=[];$j.each(a,function(b,d){if(2!==d.length)return!0;e.push({eventType:d[0],eventId:d[1],version:-1,oddsSettingVersion:-1})});return $j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:
"")+PageConfig.landingPath+"/member/playerService/queryBookMakerMultiMarkets",data:{marketPks:JSON.stringify(e),queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{let d=b.bookMakerInfos;const g=CategoryType.BOOK_MAKER.unique();e.length!==d.length&&DataBase.multiMarkets.removeAllByCategoryType(g);for(b=0;b<d.length;b++){let f=d[b],h=f.bookMakerEvent,r=h.eventType,q=h.eventId;DataBase.bookMakerMarkets.update(q,f.bookMakerMarket.markets);DataBase.multiMarkets.addMarketPk(r,
g,q,CategoryType.BOOK_MAKER.name);EventHandler.checkEvents(r,q,!0,null)}MultiMarketsHandler.addToCookie()}catch(d){Trace.printStackTrace(d)}},error:function(b){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(b)}})}};MultiMarketsHandler.initFromCookie=async function(a){if(MultiMarketsHandler.isHasMultiMarket()){var c=MultiMarketsHandler.readCookie(),
e=c[CategoryType.BETFAIR.unique()],b=c[CategoryType.FANCY_BET.unique()],d=c[CategoryType.SPORTRADAR_SPORTSBOOK.unique()],g=c[CategoryType.OW_SPORTSBOOK.unique()];c=c[CategoryType.BOOK_MAKER.unique()];var f=[];f.push(MultiMarketsHandler.checkAndAddBetfairDataBase(e,a));f.push(MultiMarketsHandler.checkAndAddFancybetDataBase(b,a));f.push(MultiMarketsHandler.checkAndAddSportsBookDataBase(d,a,ApiSiteType.SPORTRADAR.unique()));f.push(MultiMarketsHandler.checkAndAddSportsBookDataBase(g,a,ApiSiteType.OW.unique()));
f.push(MultiMarketsHandler.checkAndAddBookMakerDataBase(c,a));await Promise.all(f)}1==a&&MemberPage.multiMarkets()};MultiMarketsHandler.getMultiMarketsTask=null;MultiMarketsHandler.initTask=function(){if(null==MultiMarketsHandler.getMultiMarketsTask){var a=TaskExecuterV2.createTask(PageConfig.getMultiMarketsTaskCycleTime,0,function(){l(this)});MultiMarketsHandler.getMultiMarketsTask=a}else MultiMarketsHandler.getMultiMarketsTask.isStop=!1;MultiMarketsHandler.getMultiMarketsTask.run();TaskExecuterV2.execute()};
MultiMarketsHandler.abortTask=function(){null!=MultiMarketsHandler.getMultiMarketsTask&&MultiMarketsHandler.getMultiMarketsTask.stop()};MultiMarketsHandler.updateMultiMarketList=function(a,c){var e=$j("#multiMarketsWrap");a=a.multiMarkets;for(var b=0;b<a.length;b++){var d=a[b];c?MultiMarketsHandler.updateMultiMarketByWebSocket(e,d):MultiMarketsHandler.updateMultiMarket(e,d)}};MultiMarketsHandler.updateMultiMarket=function(a,c){var e=c.eventType,b=c.eventId,d=c.marketId,g=b+"_"+d.replace(".","_"),
f=c.eventName,h=c.market,r=c.gameProductStatus,q=MarketUtil.isCloseSite(h.closeSite,PageConfig.webSiteType)||EventUtils.isCloseSite(c.eventCloseSite,PageConfig.webSiteType)||CompetitionUtils.isCloseSite(c.competitionCloseSite,PageConfig.webSiteType);if(null!=DataBase.multiMarkets.getMarketPk(e,CategoryType.BETFAIR.unique(),b,d)){var p=a.find("#multiMarket_"+g);if(0==p.length){if(MarketUtil.isClosed(h.status)||q){DataBase.multiMarkets.removeMarketPk(e,CategoryType.BETFAIR.unique(),b,d);MultiMarketsHandler.addToCookie();
return}p=a.find("#multiMarketsTemplate").clone();p.attr("id","multiMarket_"+g);p.attr("eventType",e);p.attr("eventId",b);p.attr("marketId",d);p.attr("name","multiMarketItem");p.find("#multiMarketPin").attr("class","delete-pin");p.find("#multiMarketPin").attr("title",I18N.get("msg.member.multiMarkets.removeFrom"));MultiMarketsHandler.bindPinEvent(p,e,b,d);BetHandler.addSelectClass();a.find("#header").after(p.show())}else{if(MarketUtil.isClosed(h.status)||q){DataBase.multiMarkets.removeMarketPk(e,CategoryType.BETFAIR.unique(),
b,d);MultiMarketsHandler.addToCookie();p.hide();return}p.show()}MultiMarketsHandler.appendMultiMarketInfo(p,b,f,h,e);a=c.isOfferBetfairExchange;FullMarketUtil.updateFullMarket(p,p.find("#multiMarketBoard"),e,b,d,h,r,a);EventType.GREYHOUND_RACING.unique()==e&&p.find("#multiMarketBoard").removeClass("bets").addClass("bets-GH");h=h.selections;if(null!=h&&0!=h.length&&null!=h[0]&&null!=h[0].runnerMetadata){DataBase.multiMarkets.getMarketPk(e,CategoryType.BETFAIR.unique(),b,d).isGetRunnerMetadata=!1;try{var u=
JSON.parse(h[0].runnerMetadata);null!=u&&null!=u.COLOURS_FILENAME&&p.find("#multiMarketBoard").removeClass("bets").addClass("bets-HS")}catch(v){Trace.log(v)}}}};MultiMarketsHandler.updateMultiMarketByWebSocket=function(a,c){var e=c.eventType,b=c.eventId,d=c.marketId,g=b+"_"+d.replace(".","_");a=a.find("#multiMarket_"+g);0<a.length&&FullMarketUtil.updateSelection(a,a.find("#multiMarketBoard"),e,b,d,c.selections,!0,c.gameProductStatus)};MultiMarketsHandler.appendMultiMarketInfo=function(a,c,e,b,d){var g=
a.find("#eventHeader"),f="",h="";h="";var r=b.marketId;1!=b.inPlay||MarketUtil.isClosed(b.status)||(h='<img class="icon-irun" src="/images/transparent.gif" />');f=e;h='<span id="marketName" class="multi-event_type">'+b.marketName+"</span>"+h;e=function(q,p){return function(){location.href=PageConfig.fullMarketPath+"?eventType="+d+"&eventId="+c+"&marketId="+r}}(c,r,d);g.html(f+h);g.click(e);BetHandler.isEnableCheckLowLiquidity()&&(BetHandler.isLowLiquidity(d,c,b.marketId.replace("_","."))?FullMarketUtil.showLowLiquidityTag(a.find("#lowLiquidityTag"),
!0):FullMarketUtil.showLowLiquidityTag(a.find("#lowLiquidityTag"),!1))};MultiMarketsHandler.getMultiMarket=function(){var a=DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BETFAIR.unique());-1==PageConfig.highlightEventType&&-1==PageConfig.selectEventId&&null==PageConfig.selectMarketId&&null!=a&&0!=a.length&&$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMultiMarketsPath,
data:{marketPks:JSON.stringify(a),queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(c){try{MultiMarketsHandler.updateMultiMarketList(c,!1)}catch(e){Trace.printStackTrace(e)}},error:function(c){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(c)}})}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.multiMarkets={};var t=new HashMap;t.put(CategoryType.BETFAIR.unique(),new HashMap);t.put(CategoryType.FANCY_BET.unique(),new HashMap);t.put(CategoryType.SPORTRADAR_SPORTSBOOK.unique(),new HashMap);t.put(CategoryType.OW_SPORTSBOOK.unique(),new HashMap);t.put(CategoryType.BOOK_MAKER.unique(),new HashMap);DataBase.multiMarkets.addMarketPk=function(k,n,l,m){var a=t.get(n),c=a.keySet(),e=DataBase.multiMarkets.generateKey(l,m);l={eventType:k,eventId:l,marketId:m,selectionTs:-1};CategoryType.BETFAIR.unique()==
n&&EventType.HORSE_RACING.unique()==k&&(l.isGetRunnerMetadata=!0);-1==ArrayUtil.indexOf(c,e)&&a.put(e,l)};DataBase.multiMarkets.getMarketPk=function(k,n,l,m){k=DataBase.multiMarkets.generateKey(l,m);return t.get(n).get(k)};DataBase.multiMarkets.removeMarketPk=function(k,n,l,m){k=DataBase.multiMarkets.generateKey(l,m);t.get(n).remove(k)};DataBase.multiMarkets.queryAllByCategoryType=function(k){return t.get(k).values()};DataBase.multiMarkets.queryMarketPks=function(k){var n=[],l=t.get(CategoryType.BETFAIR.unique()).values(),
m;for(m in l){var a=l[m],c=DataBase.markets.get(a.eventId,a.marketId);null!=c&&(k?1==c.inPlay&&"MATCH_ODDS"==c.marketType&&n.push(a):(1!=c.inPlay||"MATCH_ODDS"!=c.marketType)&&n.push(a))}return n};DataBase.multiMarkets.queryForCookie=function(){var k={},n=[],l=[],m=[],a=[],c=[];$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BETFAIR.unique()),function(e,b){n.push([b.eventType,b.eventId,b.marketId])});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.FANCY_BET.unique()),
function(e,b){l.push([b.eventType,b.eventId])});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.SPORTRADAR_SPORTSBOOK.unique()),function(e,b){m.push([b.eventType,b.eventId,b.marketId])});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.OW_SPORTSBOOK.unique()),function(e,b){a.push([b.eventType,b.eventId,b.marketId])});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BOOK_MAKER.unique()),function(e,b){c.push([b.eventType,b.eventId])});k[CategoryType.BETFAIR.unique()]=
n;k[CategoryType.FANCY_BET.unique()]=l;k[CategoryType.SPORTRADAR_SPORTSBOOK.unique()]=m;k[CategoryType.OW_SPORTSBOOK.unique()]=a;k[CategoryType.BOOK_MAKER.unique()]=c;return k};DataBase.multiMarkets.generateKey=function(k,n){return k+"_"+n.replace(".","_")};DataBase.multiMarkets.updateSelectionTs=function(k,n,l,m){DataBase.multiMarkets.getMarketPk(k,CategoryType.BETFAIR.unique(),n,l).selectionTs=m};DataBase.multiMarkets.removeAllByCategoryType=function(k){t.put(k,new HashMap)};DataBase.multiMarkets.queryAllMarketPk=
function(){let k=[];$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BETFAIR.unique()),function(n,l){k.push(l)});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.FANCY_BET.unique()),function(n,l){0!=DataBase.fancyBetMarkets.queryByEvent(l.eventId).filter(m=>FancyBetMarketUtil.isOnline(m.status)&&!FancyBetMarketUtil.isClosed(m.status)).length&&k.push(l)});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.SPORTRADAR_SPORTSBOOK.unique()),function(n,l){n=
l.eventId;0!=DataBase.sportsBookMarkets.queryMarketsByBetfairEventId(ApiSiteType.SPORTRADAR.unique(),n).filter(m=>SportsBookMarketUtil.isOpen(m.marketStatus)||SportsBookMarketUtil.isSuspend(m.marketStatus)).length&&k.push(l)});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.OW_SPORTSBOOK.unique()),function(n,l){n=l.eventId;0!=DataBase.sportsBookMarkets.queryMarketsByBetfairEventId(ApiSiteType.OW.unique(),n).filter(m=>SportsBookMarketUtil.isOpen(m.marketStatus)||SportsBookMarketUtil.isSuspend(m.marketStatus)).length&&
k.push(l)});$j.each(DataBase.multiMarkets.queryAllByCategoryType(CategoryType.BOOK_MAKER.unique()),function(n,l){0!=DataBase.bookMakerMarkets.queryByEvent(l.eventId).filter(m=>BookMakerMarketUtil.isOnline(m.status)&&!BookMakerMarketUtil.isClosed(m.status)).length&&k.push(l)});return k};DataBase.multiMarkets.queryAllMarketPkByEventType=function(k){return DataBase.multiMarkets.queryAllMarketPk().filter(n=>n.eventType==k)}})();

