var NavigationBar={};
(function(){var B=[];NavigationBar.init=function(){};NavigationBar.togglePathPop=function(h){};NavigationBar.addNode=function(h){if("MARKET"!=h.type){var p=(h.id+"").replace(".","_"),q=$j("#listBoard");if(!(0<q.find("#navi_"+p).length)){B[B.length]=h.id;for(var v=[],x=B.length,u=0;u<x;u++)v[v.length]=B[u];x=EventType.getInstanceOf(v[0]);u="";"EVENT_TYPE"==h.type?h.id==EventType.HORSE_RACING.unique()?u=PageConfig.landingPath+"/member/horse-racing/#Today":h.id==EventType.GREYHOUND_RACING.unique()?u=
PageConfig.landingPath+"/member/greyhound-racing/#Today":h.id!=EventType.ELECTION.unique()&&h.id!=EventType.FANCYBET.unique()&&(u=PageConfig.sportsPath+"?eventType="+h.id):"MARKET"==h.type&&(u=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+PageConfig.naviEventId+"&marketId="+h.id);var D=RacingSportUtil.getCountryNameWithType(h.type,h.name);u=0<u.length?'<a href="'+u+'" id="navi_'+p+'" menuObjType="'+h.type+'" >'+h.name+"</a>":'<a id="navi_'+p+'" menuObjType="'+h.type+
'" >'+D+"</a>";"EVENT"==h.type&&x.isRacingEvent()&&(u='<a style="cursor: default;" id="navi_'+p+'" menuObjType="'+h.type+'" >'+h.name+"</a>");v=function(G,K,y){return function(){"EVENT"==y.type&&(PageConfig.naviEventId=y.id,PageConfig.selectMarketId=null);for(var a=[],b=0;b<G.length;b++)a[b]=G[b];b=$j(this).parent().hasClass("menu-select-head");NavigationBar.update(a,b);NavigationHandler.getMenu(a);"EVENT_TYPE"==y.type?y.id!=EventType.ELECTION.unique()&&y.id!=EventType.FANCYBET.unique()&&MemberPage.selectSport(y.id):
"MARKET"==y.type&&(location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+PageConfig.naviEventId+"&marketId="+y.id)}}(v,v[0],h);D=$j("li.menu-select-head")[0];q.find(D).removeClass("menu-select-head");q.append('<li class="menu-select-head">'+u+"</li>");"EVENT_TYPE"==h.type?(PageConfig.ENABLE_OCER_NAVIGATION?x.isRacingEvent()||q.append($j("#topCompetitions").show()):(PageConfig.isEnterFairGroup||PageConfig.isSkyFairGroup)&&q.append($j("#topCompetitions")),q.append($j("#commonGroup").show())):
($j("#topCompetitions").hide(),$j("#commonGroup").hide());"EVENT"==h.type&&x.isRacingEvent()||q.find("#navi_"+p).click(v)}}};NavigationBar.update=function(h,p){if(null!=h&&0!=h.length&&!p){p=$j("#listBoard");var q=$j("li.menu-select-head")[0];p.find(q).remove();p.find("#navi_"+h[h.length-1]).parent().addClass("menu-select-head")}};NavigationBar.restoreFullBar=function(h,p){for(var q=0;q<h.length;q++){if(0!=q){for(var v=null,x=0;x<p.children.length;x++)if(p.children[x].id==h[q]){v=p.children[x];break}null!=
v&&(p=v)}p.id==h[q]&&NavigationBar.addNode(p)}};NavigationBar.addTodaysCardNode=function(h){NavigationBar.init();var p=EventType.getInstanceOf(h),q=null;null!=p&&EventType.HORSE_RACING.unique()==p.unique()?q={id:h,name:"Horse Racing - Today's Card",type:"EVENT_TYPE",isTodaysCard:1}:null!=p&&EventType.GREYHOUND_RACING.unique()==p.unique()&&(q={id:h,name:"Greyhounds Racing - Today's Card",type:"EVENT_TYPE",isTodaysCard:1});NavigationBar.addNode(q)}})();
"undefined"==typeof NavigationHandler&&(NavigationHandler={});
(function(){function B(a){var b=[];if(null!=a&&0<a.length)for(var c in a)b.push(a[c]);return b}function h(a,b,c){if(0!=a.children.length){var d=b.find("#listBoardTemplate").clone(),e=a.children[0],f=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+e.eventId+"&marketId="+e.id;-1<e.marketType.indexOf("FORECAST")&&(PageConfig.fcId=menuNode.id.split(".")[0],f+="&fcId="+PageConfig.fcId);d.prop("id",("naviMenu_"+a.id).replace(".","_"));d.attr("fcGroup",c);d.attr("type",a.type);
d.find("#name").html(a.name);d.find("#name").attr("href",f);d.find("#arrow").hide();b.append(d.show());d=!1;e=a.children;e.sort(NaviMenuUtil.sortFcMarket);for(var l in e)f=a.children[l],null!=f&&(p(f,b,c,a.id),PageConfig.selectMarketId==f.id&&(d=!0));d&&(b.find("[id^=naviMenu_][fcGroup="+c+"]").show(),NavigationHandler.setTabMarket(e),NavigationHandler.updateTabMarket())}}function p(a,b,c,d){var e=b.find("#listBoardTemplate").clone(),f=function(r){return function(){var k=$j("#listBoard");k.find("li").find("#name").removeClass("select");
k.find("#naviMenu_"+r.id.replace(".","_")).find("#name").addClass("select");k=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+r.eventId+"&marketId="+r.id;-1<r.marketType.indexOf("FORECAST")&&(PageConfig.fcId=d.split(".")[0],k+="&fcId="+PageConfig.fcId);location.href=k}}(a);let l=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+a.eventId+"&marketId="+a.id;-1<a.marketType.indexOf("FORECAST")&&(PageConfig.fcId=d.split(".")[0],l+="&fcId="+PageConfig.fcId);
e.prop("id",("naviMenu_"+a.id).replace(".","_"));e.attr("fcGroup",c);e.attr("type",a.type);e.find("#name").html(a.name);e.find("#name").on("click",f);e.find("#name").attr("href",l);e.find("#arrow").hide();PageConfig.selectMarketId==a.id&&e.find("#name").addClass("select");b.append(e)}function q(a,b){a=a[a.length-1];0==a.length||0<=a.toString().indexOf(".")||$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:
"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventId:a,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(c){try{for(var d=[],e=0;e<c.markets.length;e++){var f=c.markets[e],l=$j("#naviMenu_"+f.marketId.replace(".","_"));if(0<l.length&&(MarketUtil.isClosed(f.status)||MarketUtil.isCloseSite(f.closeSite,PageConfig.webSiteType))){l.remove();var r=l.attr("todaysCardGroup");NavigationHandler.removeMenuEventByTodaysCardGroup(c.eventId,r);var k=l.attr("fcGroup");NavigationHandler.removeMenuRaceByGroup(k)}d.push(f.marketId)}for(var t in b){var z=
b[t];l=$j("#naviMenu_"+z.replace(".","_"));0<l.length&&-1==ArrayUtil.indexOf(d,z)&&(l.remove(),r=l.attr("todaysCardGroup"),NavigationHandler.removeMenuEventByTodaysCardGroup(c.eventId,r),k=l.attr("fcGroup"),NavigationHandler.removeMenuRaceByGroup(k))}}catch(g){Trace.printStackTrace(g)}},error:function(c){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.printStackTrace(c)}})}
function v(a,b,c,d){$j.ajax({type:"POST",dataType:"JSON",url:"/member/playerService/querySingleMarket",data:{eventId:a,marketId:b.trim()},success:function(e){try{null==e.eventId&&null!=d&&"function"===typeof d&&d.call();var f="/member/#marketId#"+e.marketId+"#"+e.eventId;c.find("#name").attr("href",f)}catch(l){Trace.printStackTrace(l)}finally{}},error:function(e){Trace.printStackTrace(e)}})}function x(a,b){var c=null,d;for(d in b){var e=b[d];if(e.id==a){c=e;break}}return c}function u(a){null==PageConfig.selectMarketId?
(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{DataBase.markets.update(b.eventId,b.markets);var c=b.markets,d=b.eventId;b=null;for(var e in c){b=c[e];var f=
$j("#naviMenu_"+b.marketId.replace(".","_"));if(0<f.length){if(MarketUtil.isClosed(b.status)){f.remove();var l=f.attr("todaysCardGroup");NavigationHandler.removeMenuEventByTodaysCardGroup(d,l);var r=f.attr("fcGroup");NavigationHandler.removeMenuRaceByGroup(r);continue}if(1==b.inPlay){var k=f.find("#name").find("img");k.removeClass("icon-no_play");k.addClass("icon-in_play")}else k=f.find("#name").find("img"),k.removeClass("icon-in_play"),k.addClass("icon-no_play")}var t=$j("#tabMarket_"+b.marketId.replace(".",
"_"));0<t.length&&MarketUtil.isClosed(b.status)&&t.remove()}}catch(z){Trace.printStackTrace(z)}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}function D(a){0==NavigationHandler.menuCollectionEventIds.length?(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",
dataType:"JSON",url:"/member/playerService/queryOpenMarketCountsByEventIds",data:{eventIds:NavigationHandler.menuCollectionEventIds},success:function(b){try{var c=b.events;b=null;for(var d in c){b=c[d];var e=$j("#naviMenu_"+b.eventId);0<e.length&&0==b.openMarkets&&e.remove()}}catch(f){Trace.printStackTrace(f)}finally{a.check(),TaskExecuter.execute()}},error:function(){a.check();TaskExecuter.execute()}})}function G(){var a=null;$j.each(y,function(b,c){c.id==PageConfig.selectMarketId&&(a=c)});return a}
function K(a){var b=[];$j.each(y,function(c,d){d.marketDateTime==a&&b.push(d)});return b}NavigationHandler.navigationIds=[];NavigationHandler.menuCollectionEventIds=[];var y=[];NavigationHandler.init=function(){NavigationHandler.navigationIds=[];NavigationHandler.hideAllSports();NavigationHandler.getMenu([])};NavigationHandler.getMenu=function(a,b,c,d,e){null!=a&&(a=JSON.parse("["+a+"]"));$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?
QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMenuPath,data:{navigationIds:a,isTodaysCard:c,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(f){try{if(null!=f){if(null!=b&&1==b){var l=JSON.parse(f.result);NavigationBar.restoreFullBar(a,l);1==c&&NavigationBar.addTodaysCardNode(a[0])}NavigationHandler.updateNaviMenu(f,a,c,d,e);NavigationHandler.navigationIds=a}}catch(r){Trace.printStackTrace(r)}finally{}},error:function(f){PageConfig.enableQueryDataSubdomain&&null!=
QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.error(f)}})};NavigationHandler.getMenuCallBack=function(a,b,c){null!=a&&(a=JSON.parse("["+a+"]"));$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMenuPath,data:{navigationIds:a,isTodaysCard:b,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},
success:function(d){try{c&&c(d)}catch(e){Trace.printStackTrace(e)}},error:function(d,e,f){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.log(d.status);Trace.log(f)}})};NavigationHandler.updateNaviMenu=function(a,b,c,d,e){var f=JSON.parse(a.result);null!=a.fcResult&&0<a.fcResult.length&&(f=JSON.parse(a.fcResult));null!=b&&(b=JSON.parse("["+b+"]"));a=EventType.getInstanceOf(PageConfig.selectEventType);
var l=f.isFcCombo;let r=1==b.length?!0:!1;"EVENT_TYPE"==f.type&&(null==b&&(b=[],b.push(f.id)),f=l?f.children:NavigationHandler.naviMenuList(f,b));$j("#listBoard").find("[id^=naviMenu_]").remove();var k=[],t=[],z;for(z in f){var g=f[z];"EVENT"==g.type?k.push(g.id):"MARKET"==g.type&&t.push(g.id)}0<t.length&&null!=a&&a.isRacingEvent()&&NavigationHandler.setTabMarket(f);let O=EventType.SOCCER.value==a.value&&0<t.length;var H=null,L=null;null!=a&&a.isRacingEvent()&&1==c&&"EVENT"==f[1].type&&null==d&&null==
e&&(H=f[1]);0<t.length&&q(b,t);NavigationHandler.menuCollectionEventIds=0<k.length?k:[];k=1;t=$j("#listBoard");var M=1;NavigationHandler.showAllSports();for(z in f){JsCache.get("#listBoardLoading").hide();g=f[z];var w=g.type;if(PageConfig.isCheckBookMode&&(null==a||!WebSiteType.getInstanceOf(PageConfig.webSiteType).isFancyFairGroup()||!a.isRacingEvent()))if(PageConfig.ENABLE_OCER_NAVIGATION){if(null!=g.containBookMode&&!g.containBookMode)continue}else{var m=g.isBookMenu;if(("TOP_COMPETITION"==w||
"GROUP"==w||"EVENT"==w||"MANUALLY_COMPETITION"==w)&&!m)continue}if(null!=g.competitionCloseSite&&CompetitionUtils.isCloseSite(g.competitionCloseSite,PageConfig.webSiteType))continue;if(MarketUtil.isCloseSite(g.closeSite,PageConfig.webSiteType))continue;if(l){h(g,t,M);M++;continue}m=$j("#listBoardTemplate").clone();var C=B(b);a=EventType.getInstanceOf(C[0]);if(g.id==EventType.POLITICS.unique())continue;if(g.id==EventType.GREYHOUND_RACING.unique()&&!PageConfig.ENABLE_PLAYER_GREYHOUND_RACING_ENTER)continue;
if("MARKET"==g.type)m.find("#arrow").hide();else{if(1==c&&"EVENT_TYPE"==g.type)continue;else C.push(g.id);1==g.isTodaysCard&&m.find("#arrow").hide()}var P=function(E,A,n){return function(){var I=null==n.isTodaysCard?0:1;if(1==I){if("EVENT_TYPE"==n.type&&(PageConfig.selectEventType=A,NavigationHandler.getMenuCallBack(E,I,function(F){F&&(F=JSON.parse(F.result)[1],location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+F.id+"&marketId="+F.children[0].id+"&isTodaysCard=1")})),
"EVENT"==n.type){PageConfig.naviEventId=n.id;NavigationHandler.clickOpenTodaysCardMarket(n.children);var N=n.children[0];NavigationHandler.addSelectClass(N.id);NavigationHandler.setTabMarket(n.children);NavigationHandler.updateTabMarket();location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+n.id+"&marketId="+N.id+"&isTodaysCard="+I}}else if(NavigationBar.addNode(n),"MARKET"==n.type?NavigationHandler.addSelectClass(n.id):NavigationHandler.getMenu(E),"EVENT"==
n.type&&(PageConfig.naviEventId=n.id),"EVENT_TYPE"==n.type){if(n.id==EventType.HORSE_RACING.unique())location.href=PageConfig.landingPath+"/member/horse-racing/#Today";else if(n.id==EventType.GREYHOUND_RACING.unique())location.href=PageConfig.landingPath+"/member/greyhound-racing/#Today";else if(n.id==EventType.ELECTION.unique()||n.id==EventType.FANCYBET.unique()){PageConfig.selectEventType=A;return}MemberPage.selectSport(n.id);HighlightsHandler.selectHighlights(null,n.id,!0)}else"MARKET"==n.type&&
(location.href=null!=n.eventId?PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+n.eventId+"&marketId="+n.id:PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+PageConfig.naviEventId+"&marketId="+n.id)}}(C,C[0],g);let J=RacingSportUtil.getCountryNameWithType(w,g.name);m.attr("id",("naviMenu_"+g.id).replace(".","_"));m.attr("sortName",J);m.attr("marketType",g.marketType);m.attr("isTodaysCard",null==g.isTodaysCard?0:g.isTodaysCard);m.attr("todaysCardGroup",
k);m.attr("title",J);m.prop("sort",null==g.sort?0:g.sort);m.find("#name").attr("type",g.type);m.find("#name").html(J);"MARKET"==w?(w=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+(null!=g.eventId?g.eventId:PageConfig.naviEventId)+"&marketId="+g.id,m.find("#name").attr("href",w)):m.find("#name").click(P);if("EVENT"==g.type&&1==g.isTodaysCard&&(m.attr("marketDateTime",g.marketDateTime),(g.id==d||g.id==PageConfig.fcId)&&null!=g.children))for(w=0;w<g.children.length;w++)g.children[w].id==
e&&(L=g);"MARKET"==g.type&&g.id==PageConfig.selectMarketId&&(JsCache.get("#listBoard").find("li").find("#name").removeClass("select"),m.find("#name").addClass("select"));"MARKET"==g.type&&(m.find("#name").html('<img class="icon-no_play" src="/images/transparent.gif" /> '+g.name),m.attr("marketDateTime",g.marketDateTime));"MARKET"!=g.type&&(w=function(E,A){return function(){NavigationBar.addNode(A);NavigationHandler.getMenu(E);"EVENT_TYPE"==A.type&&(PageConfig.selectEventType=E[0]);"EVENT"==A.type&&
(PageConfig.naviEventId=A.id)}}(C,g),m.find("#arrow").click(w),m.find("#arrow").attr("type",g.type));if("EVENT_TYPE"==g.type)PageConfig.ENABLE_OCER_NAVIGATION&&1==g.isTodaysCard?$j("#commonGroup").show().append(m.show()):JsCache.get("#listBoard").append(m.show());else if("TOP_COMPETITION"==g.type)if(PageConfig.ENABLE_OCER_NAVIGATION)$j("#topCompetitions").show(),$j("#topCompetitions").append(m.show());else if(0<m.prop("sort"))$j("#topCompetitions").show(),$j("#topCompetitions").append(m.show());else continue;
else r?$j("#commonGroup").show().append(m.show()):$j("#listBoard").append(m.show());1==c&&(NavigationHandler.appendTodaysCardMarket(C,g,k),k++)}b=r?$j("#commonGroup"):$j("#listBoard");1==c||l||(NavigationHandler.sortTopCompetitionMenuNode(),O?NavigationHandler.sortSoccerMenuNode(b):NavigationHandler.sortMenuNode(b));null!=PageConfig.selectMarketId?(NavigationHandler.updateMenuMarketStatusTask.run(),null!=a&&a.isRacingEvent()?NavigationHandler.updateTabMarket():null!=JsCache.get("#tabMarketList")&&
JsCache.get("#tabMarketList").hide()):null!=JsCache.get("#tabMarketList")&&JsCache.get("#tabMarketList").hide();null!=a&&a.isRacingEvent()&&(null!=H&&null==d&&null==e?NavigationHandler.selectFirstTodaysCardMarket(H):null==H&&null!=d&&null!=e&&NavigationHandler.selectTargetTodaysCardMarket(d,e,L))};NavigationHandler.addSelectClass=function(a){JsCache.get("#listBoard").find("li").find("#name").removeClass("select");$j("#naviMenu_"+a.replace(".","_")).find("#name").addClass("select")};NavigationHandler.appendTodaysCardMarket=
function(a,b,c){for(var d in b.children){var e=b.children[d],f=JsCache.clone("#listBoardTemplate");f.find("#arrow").hide();f.attr("id",("naviMenu_"+e.id).replace(".","_"));f.attr("eventId",null==e.eventId?b.id:e.eventId);f.attr("marketId",e.id);f.attr("marketType",e.marketType);f.attr("name","todaysCardMarket");f.attr("todaysCardGroup",c);f.find("#name").html(e.name).click(function(l,r,k,t,z){return function(){NavigationBar.addNode(k);JsCache.get("#listBoard").find("li").find("#name").removeClass("select");
$j("#naviMenu_"+k.id.replace(".","_")).find("#name").addClass("select");PageConfig.naviEventId=t;NavigationHandler.setTabMarket(z);NavigationHandler.updateTabMarket();if(null!=k.eventId){var g=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+k.eventId+"&marketId="+k.id+"&isTodaysCard=1";k.eventId!=t&&(g+="&fcId="+t);location.href=g}else location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+"&eventId="+t+"&marketId="+k.id+"&isTodaysCard=1"}}(a,
a[0],e,b.id,b.children)).attr("type",e.type);JsCache.get("#commonGroup").append(f)}};NavigationHandler.clickOpenTodaysCardMarket=function(a){$j("#listBoard").find("[name=todaysCardMarket]").hide();for(var b in a){var c=$j("#naviMenu_"+a[b].id.replace(".","_"));null!=c&&0<c.length&&c.show()}};NavigationHandler.selectFirstTodaysCardMarket=function(a){if(null!=a&&null!=a.children&&0!=a.children.length){var b=a.id,c=a.children[0].id;0<location.href.indexOf("/member/horse-racing")&&(location.href=location.href.replace("/member/horse-racing",
"/member/#TodaysCard#"+EventType.HORSE_RACING.unique()));0<location.href.indexOf("/member/greyhound-racing")&&(location.href=location.href.replace("/member/greyhound-racing","/member/#TodaysCard#"+EventType.GREYHOUND_RACING.unique()));var d=$j("[id=naviMenu_"+c.replace(".","_")+"][eventId="+b+"]");0<d.length?(NavigationHandler.addSelectClass(c),NavigationHandler.setTabMarket(a.children),NavigationHandler.updateTabMarket(),location.href=PageConfig.fullMarketPath+"?eventType="+PageConfig.selectEventType+
"&eventId="+b+"&marketId="+c+"&isTodaysCard=1",a=d.attr("todaysCardGroup"),isNaN(a)||$j("[todaysCardGroup="+a+"]").show()):MemberPage.view("marketClose")}};NavigationHandler.selectTargetTodaysCardMarket=function(a,b,c){a=$j("[id=naviMenu_"+b.replace(".","_")+"][eventId="+a+"]");0<a.length?(NavigationHandler.addSelectClass(b),NavigationHandler.setTabMarket(c.children),NavigationHandler.updateTabMarket(),b=a.attr("todaysCardGroup"),isNaN(b)||$j("[todaysCardGroup="+b+"]").show()):MemberPage.view("marketClose")};
NavigationHandler.clickNextOpenRacingEvent=function(a,b,c){a=$j("[id^=naviMenu_"+a+"]");for(b=0;b<a.length;b++){var d=$j(a[b]);if(1==d.attr("isTodaysCard")&&d.attr("marketDateTime")==c){d.find("#name").click();break}}};NavigationHandler.getJustFullMarketEventHref=function(a,b){var c=[];EventType.getInstanceOf(a);a=function(d,e,f){return function(){v(d,e,f)}}(c[1].eventId,c[1].marketId,b);v(c[0].eventId,c[0].marketId,b,a)};NavigationHandler.naviMenuList=function(a,b){if(1==b.length)return null==a&&
(Trace.error(b),Trace.error(a)),a.children;var c=null,d=[],e;for(e in b)d.push(b[e]);d=d.splice(1,b.length);for(var f in d)b=d[f],c=0==f?x(b,a.children):x(b,c.children);return c.children};NavigationHandler.getNavigationPathFully=function(a,b){$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryNavigationPathFullyPath,data:{eventType:a,pathId:b,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},
success:function(c){try{NavigationHandler.navigationIds=c,NavigationHandler.getMenu(NavigationHandler.navigationIds,!0)}catch(d){Trace.printStackTrace(d)}finally{}},error:function(c){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.error(c)}})};NavigationHandler.sortMenuNode=function(a){var b=a.find("[id^=naviMenu_]");b.sort(function(c,d){c=$j(c);d=$j(d);
var e=c.attr("sortName").trim(),f=d.attr("sortName").trim(),l=c.find("#name").attr("type"),r=d.find("#name").attr("type");return NaviMenuUtil.sortMenuNode(PageConfig.selectEventType,e,f,l,r,c.attr("isTodaysCard"),d.attr("isTodaysCard"),c.attr("marketDateTime"),d.attr("marketDateTime"),c.attr("marketType"),d.attr("marketType"))});a.append(b)};NavigationHandler.sortSoccerMenuNode=function(a){var b=a.find("[id^=naviMenu_]");b.sort(function(c,d){var e=$j(c),f=$j(d);d=PageConfig.SOCCER_MENU_ORDER_MAP.get(e.attr("marketType").trim());
c=PageConfig.SOCCER_MENU_ORDER_MAP.get(f.attr("marketType").trim());"undefined"==typeof d&&(d=999);"undefined"==typeof c&&(c=999);e=e.attr("sortName").trim();f=f.attr("sortName").trim();return NaviMenuUtil.sortSoccerMenuNode(PageConfig.selectEventType,d,c,e,f)});a.append(b)};NavigationHandler.sortTopCompetitionMenuNode=function(){var a=JsCache.get("#listBoard").find("#topCompetitions").find("[id^=naviMenu_]");a.sort(function(b,c){var d=$j(b),e=$j(c);c=d.attr("sortName").trim();b=e.attr("sortName").trim();
d=d.prop("sort");e=e.prop("sort");return NaviMenuUtil.sortTopCompetitionMenuNode(c,b,d,e)});JsCache.get("#listBoard").find("#topCompetitions").append(a)};NavigationHandler.updateMenuMarketStatusTask=TaskExecuter.createTask(5,0,function(){u(this)});NavigationHandler.removeMenuEventByTodaysCardGroup=function(a,b){if(!isNaN(b)){var c=$j("[todaysCardGroup="+b+"]");null!=c&&1<c.length||(a=$j("[id=naviMenu_"+a+"][todaysCardGroup="+b+"]"),null!=a&&0<a.length&&a.remove())}};NavigationHandler.removeMenuRaceByGroup=
function(a){if(!isNaN(a)){var b=$j("#listBoard"),c=b.find("[type=MARKET][fcGroup="+a+"]");null!=c&&0<c.length||(a=b.find("[type=RACE][fcGroup="+a+"]"),null!=a&&0<a.length&&a.remove())}};NavigationHandler.updateMenuEventStatusTask=TaskExecuter.createTask(5,0,function(){D(this)});NavigationHandler.setTabMarket=function(a){y=a};NavigationHandler.updateTabMarket=function(){var a=JsCache.get("#tabMarketList"),b=G();null!=b&&null!=b.marketDateTime&&($j("[id^=tabMarket_]").remove(),b=K(b.marketDateTime),
$j.each(b,function(c,d){c=$j("#tabMarket_"+d.id.replace(".","_"));if(0==c.length){var e=d.name.slice(6,d.name.length);null!=d.isTodaysCard&&1==d.isTodaysCard&&(e=d.name);c=JsCache.clone("#tabMarketTemplate");c.attr("id","tabMarket_"+d.id.replace(".","_"));c.attr("sortName",e.toLowerCase());c.attr("sortType",d.marketType);c.attr("title",StringUtil.ucfirst(e));c.find("#tabName").html(StringUtil.ucfirst(e));"WIN"==d.marketType&&0>=d.name.indexOf("Win")&&c.find("#tabName").html(StringUtil.ucfirst(d.marketType));
null!=d.isTodaysCard&&1==d.isTodaysCard&&c.attr("isTodaysCard",d.isTodaysCard);c.find("#tabName").click(function(f){return function(){var l=$j("#naviMenu_"+f.id.replace(".","_"));0<l.length&&l.find("#name").click()}}(d));PageConfig.selectMarketId==d.id&&c.find("#tabName").addClass("select")}c.show();c.css("display","");a.append(c).show()}),b=a.find("[id^=tabMarket_]"),b.sort(function(c,d){var e=$j(c),f=$j(d);d=e.attr("sortName").trim();c=f.attr("sortName").trim();e=e.attr("sortType").trim();f=f.attr("sortType").trim();
return"WIN"==e?-1:"WIN"==f?1:"PLACE"==e?-1:"PLACE"==f?1:d.localeCompare(c)}),a.append(b),"true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.show())};NavigationHandler.showAllSports=function(){-1!=PageConfig.selectEventType&&$j("#allSports").show()};NavigationHandler.hideAllSports=function(){$j("#allSports").hide()}})();

