"undefined"==typeof NavigationOcerMenuHandler&&(NavigationOcerMenuHandler={});
(function(){function u(a){if(a.sports&&0!=a.sports.length){var d=JsCache.get("#sportStage");for(let f=0;f<a.sports.length;f++){let c=JsCache.clone("#listBoardTemplate"),e=a.sports[f];c.attr("id","naviMenu_"+e.eventType);c.attr("eventType",e.eventType);c.attr("eventName",e.eventName);c.attr("title",e.eventName);c.find("#arrow").hide();c.find("#name").html(EventType.getInstanceOf(e.eventType).desc).on("click",()=>{let b=EventType.getInstanceOf(e.eventType);b.unique()==EventType.SOCCER.unique()||b.unique()==
EventType.TENNIS.unique()||b.unique()==EventType.CRICKET.unique()||b.unique()==EventType.BASKETBALL.unique()||b.unique()==EventType.ELECTION.unique()||b.unique()==EventType.FANCYBET.unique()||b.unique()==EventType.KABADDI.unique()||b.unique()==EventType.E_SOCCER.unique()?(m(e.eventType),NavigationOcerMenuHandler.getMenu(e.eventType,"",-2,-1)):b.isRacingEvent()?(b.unique()==EventType.HORSE_RACING.unique()?hrefStr=PageConfig.landingPath+"/member/horse-racing/#Today":b.unique()==EventType.GREYHOUND_RACING.unique()&&
(hrefStr=PageConfig.landingPath+"/member/greyhound-racing/#Today"),location.href=hrefStr):(NavigationOcerMenuHandler.ClearNaviMenu(),NavigationOcerMenuHandler.toggleAllSports(),NavigationHandler.getMenu([e.eventType]))});d.append(c.show())}d.show()}}function v(){if(!JsCache.get("#naviMenu_"+PageConfig.selectEventType)){var a=JsCache.clone("#listBoardTemplate");a.attr("id","naviMenu_"+PageConfig.selectEventType);a.attr("eventType",PageConfig.selectEventType);a.attr("eventName",EventType.getInstanceOf(PageConfig.selectEventType).name);
a.attr("title",EventType.getInstanceOf(PageConfig.selectEventType).name);a.find("#arrow").hide();a.find("#name").html(EventType.getInstanceOf(PageConfig.selectEventType).desc).on("click",()=>{m(PageConfig.selectEventType);NavigationOcerMenuHandler.getMenu(PageConfig.selectEventType,"",-2,-1)});JsCache.get("#selectedMenu").append(a.show())}}function n(a,d,f){let c=null;"string"===typeof a?c=JsCache.get("#"+a):"object"===typeof a&&(c=a);for(a=0;a<d.length;a++){let e=JsCache.clone("#listBoardTemplate"),
b=d[a];e.attr("id","naviMenu_"+b.region);e.attr("region",b.region);e.attr("title",b.countryName);e.find("#arrow").hide();e.find("#name").html(b.countryName).on("click",()=>{m(b.region);NavigationOcerMenuHandler.getMenu(f,b.region,-2,-1)});c.append(e.show())}c.show()}function l(a,d,f,c,e,b){c=null;"string"===typeof a?c=JsCache.get("#"+a):"object"===typeof a&&(c=a);for(a=0;a<d.length;a++){e=JsCache.clone("#listBoardTemplate");let g=d[a];e.attr("id","naviMenu_"+g.competitionId);e.attr("competitionId",
g.competitionId);e.attr("competitionName",g.competitionName);e.attr("region",g.region);e.attr("title",g.competitionName);e.attr("isManualAddCompetition",g.isManualAddCompetition);e.find("#arrow").hide();e.find("#name").html(g.competitionName).on("click",()=>{m(g.competitionId);let h=$j(`#naviMenu_${g.competitionId}`).attr("isManualAddCompetition");h||(h=!1);NavigationOcerMenuHandler.getMenu(f,"",g.competitionId,-1,h)});c.append(e.show())}c.show()}function p(a,d,f,c,e,b){f=null;"string"===typeof a?
f=JsCache.get("#"+a):"object"===typeof a&&(f=a);for(a=0;a<d.length;a++){let g=d[a];c=JsCache.clone("#listBoardTemplate");c.attr("id","naviMenu_"+g.eventId);c.attr("eventId",g.eventId);c.attr("eventName",g.eventName);c.attr("marketId",g.marketId);c.attr("title",g.eventName);c.find("#arrow").hide();c.find("#name").html(g.eventName).on("click",()=>{m(g.eventId);NavigationOcerMenuHandler.getMenu(-1,"",-2,g.eventId)});f.append(c.show())}f.show()}function r(a,d){let f=null;"string"===typeof a?f=JsCache.get("#"+
a):"object"===typeof a&&(f=a);for(a=0;a<d.length;a++){let c=JsCache.clone("#listBoardTemplate"),e=JsCache.get("#ocerMarkets").find("#inplayIconTemplate").clone(),b=d[a];c.attr("id",("naviMenu_"+b.marketId).replace(".","_"));c.attr("marketId",b.marketId.replace(".","_"));c.attr("marketName",b.marketName);c.attr("marketType",b.marketType);c.attr("eventId",b.eventId);c.attr("eventType",b.eventType);c.attr("isInPlay",b.isInPlay);c.attr("title",b.marketName);c.find("#arrow").hide();let g=PageConfig.fullMarketPath+
"?eventType="+b.eventType+"&eventId="+b.eventId+"&marketId="+b.marketId;c.find("#name").attr("href",g).html(b.marketName);PageConfig.selectMarketId&&PageConfig.selectMarketId==b.marketId&&c.find("#name").addClass("select");f.append(c.show());e.attr("id",("inplayIcon_"+b.marketId).replace(".","_"));1==b.isInPlay?e.addClass("icon-in_play"):e.addClass("icon-no_play");c.find("#name").prepend(e.show())}f.show()}function m(a){for(JsCache.get("#selectedMenu").find(".menu-select-head").removeClass("menu-select-head");JsCache.get("#selectedMenu").find("#naviMenu_"+
a)&&0<JsCache.get("#selectedMenu").find("#naviMenu_"+a).next().length;)JsCache.get("#selectedMenu").find("#naviMenu_"+a).next().remove();JsCache.removeCache("#naviMenu_"+a);let d=JsCache.get("#naviMenu_"+a).not("#selectedMenu");d&&0<d.length&&JsCache.get("#selectedMenu").append(d);JsCache.get("#selectedMenu").find("#naviMenu_"+a).addClass("menu-select-head")}function q(a){return a.map(function(d){let f=null==CountryCodeType.getInstanceOf(d.region)?d.region:CountryCodeType.getInstanceOf(d.region).countryName;
d.countryName=f;return d})}function k(a,...d){return a.map(function(f){return f}).sort(function(f,c){return f[d[0]].localeCompare(c[d[0]])})}function t(a){return a.map(function(d){return d}).sort(function(d,f){return d.marketPriority-f.marketPriority||d.marketName.localeCompare(f.marketName)})}NavigationOcerMenuHandler.init=function(){NavigationOcerMenuHandler.getMenu(PageConfig.selectEventType,"",-2,-1)};NavigationOcerMenuHandler.getMenu=function(a=-1,d="",f=-2,c=-1,e=!1){return $j.ajax({type:"POST",
dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryOcerMenuPath,data:{eventType:a,region:d,competitionId:f,eventId:c,queryPass:PageConfig.queryPass,isManualAddCompetition:e},xhrFields:{withCredentials:!0},success:function(b){try{b&&NavigationOcerMenuHandler.updateNaviMenu(b,a,d,f,c)}catch(g){Trace.printStackTrace(g)}finally{}},error:function(b){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&
!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.error(b)}})};NavigationOcerMenuHandler.ClearNaviMenu=function(){JsCache.get("#othersEvents").hide().find(".listBoard").remove();JsCache.get("#common").hide().find(".listBoard").remove();JsCache.get("#ocerAllCompetition").hide().find(".listBoard").remove();JsCache.get("#ocerAllregion").hide().find(".listBoard").remove();JsCache.get("#ocerGroup").hide().find("ul[id^='ocerEventGroup_']").remove();
JsCache.get("#ocerGroup").hide().find("ul[id^='ocerMarketGroup_']").remove();JsCache.get("#ocerMarkets").hide().find(".listBoard").remove();JsCache.get("#ocerInternationalCompetitions").hide().find(".listBoard").remove();JsCache.get("#ocerCompetitions").hide().find(".listBoard").remove();JsCache.get("#ocerTopCountries").hide().find(".listBoard").remove();JsCache.get("#ocerTopCompetitions").hide().find(".listBoard").remove();JsCache.get("#sportStage").hide().find(".listBoard").remove()};NavigationOcerMenuHandler.updateNaviMenu=
function(a,d,f,c,e){NavigationOcerMenuHandler.ClearNaviMenu();-1==PageConfig.selectEventType?u(a):(v(),a.selectedCompetition&&0!=a.selectedCompetition.length&&l("selectedMenu",a.selectedCompetition,PageConfig.selectEventType,f,c,e),a.selectedEvent&&0!=a.selectedEvent.length&&p("selectedMenu",a.selectedEvent,PageConfig.selectEventType,f,c,e));if(a.topCompetitions&&0!=a.topCompetitions.length){var b=k(a.topCompetitions,"competitionName");l("ocerTopCompetitions",b,d,f,c,e)}a.topCountries&&0!=a.topCountries.length&&
(b=q(a.topCountries),b=k(b,"countryName"),n("ocerTopCountries",b,d));a.internationalCompetitions&&0!=a.internationalCompetitions.length&&(b=k(a.internationalCompetitions,"competitionName"),l("ocerInternationalCompetitions",b,d,f,c,e));a.commonAllRegion&&0!=a.commonAllRegion.length&&(b=q(a.commonAllRegion),b=k(b,"countryName"),n("common",b,d));a.commonAllCompetition&&0!=a.commonAllCompetition.length&&l("common",a.commonAllCompetition,d,f,c,e);a.commonOthers&&0!=a.commonOthers.length&&l("common",a.commonOthers,
d,f,c,e);a.allRegion&&0!=a.allRegion.length&&(b=q(a.allRegion),b=k(b,"countryName"),n("ocerAllregion",b,d));a.allCompetition&&0!=a.allCompetition.length&&(b=k(a.allCompetition,"competitionName"),l("ocerAllCompetition",b,d,f,c,e));a.regions&&0!=a.regions.length&&(b=k(a.regions,"competitionName"),l("ocerCompetitions",b,d,f,c,e));if(a.eventGroups&&0!=a.eventGroups.length){for(b=0;b<a.eventGroups.length;b++){var g=a.eventGroups[b];if(0!=g.events.length){var h=JsCache.clone("#ocerGroupTemplate");h.attr("id",
"ocerEventGroup_"+g.groupName);h.attr("groupName",g.groupName);h.find(".menu-group-title").html((new Date(Number(g.groupName))).toLocaleString("en-US",{month:"short",day:"2-digit",hour12:!1}));g=k(g.events,"eventName");p(h,g,d,f,c,e);JsCache.get("#ocerGroup").append(h)}}JsCache.get("#ocerGroup").show()}a.marketOutright&&0!=a.marketOutright.length&&(b=t(a.marketOutright),h=JsCache.clone("#ocerGroupTemplate"),h.attr("id","ocerMarketGroup_winnerMarket"),h.attr("groupName","winnerMarket"),h.find(".menu-group-title").html("More"),
r(h,b),JsCache.get("#ocerGroup").append(h),JsCache.get("#ocerGroup").show());a.othersEvents&&0!=a.othersEvents.length&&(b=k(a.othersEvents,"eventName"),p("othersEvents",b,d,f,c,e));a.markets&&0!=a.markets.length&&(a=t(a.markets),r("ocerMarkets",a));NavigationOcerMenuHandler.toggleAllSports();JsCache.get("#selectedMenu").find(".menu-select-head").removeClass("menu-select-head");JsCache.get("#selectedMenu").find("li:last").addClass("menu-select-head").show()};NavigationOcerMenuHandler.toggleAllSports=
function(){-1!=PageConfig.selectEventType||0==JsCache.get("#sportStage").children().length?JsCache.get("#allSports").show():JsCache.get("#allSports").hide()}})();

