"undefined"==typeof NoTxnIdleHandler&&(NoTxnIdleHandler={});
(function(){NoTxnIdleHandler.init=function(){NoTxnIdleHandler.enableCheckNoTxnIdle()&&d()};const d=()=>{setInterval(function(){NoTxnIdleHandler.checkNoTxnIdle()},12E5)};NoTxnIdleHandler.enableCheckNoTxnIdle=()=>PageConfig.ENABLE_NO_TXN_IDLE||!NoTxnIdleHandler.isLogin()?!1:!0;NoTxnIdleHandler.checkNoTxnIdle=()=>{if(NoTxnIdleHandler.enableCheckNoTxnIdle()){if(null==PageConfig.streamingChannel||"null"==PageConfig.streamingChannel||"0"==PageConfig.streamingChannel)return!1;(PageConfig.isMobileOrTablet?
$j("#openTV"):$j("#lmtOpenStreaming")).hasClass("close_tv")&&!NoTxnIdleHandler.isHasTxn()&&(PageConfig.isMobileOrTablet?(MobileMenuHandler.setCurrentPage(PageCommonConfig.homePage),MobileMenuHandler.loadPage(PageCommonConfig.homePage,!0),MobileMenuHandler.showMsg("#msgBox","error",I18N.get("msg.error.account.idleTimeTooLong"),!0)):(NoTxnIdleHandler.addNoTxnIdleMsgToCookie(),window.self.location=PageConfig.landingPage))}};NoTxnIdleHandler.showIdleTimeTooLongMessage=()=>{PageConfig.ENABLE_NO_TXN_IDLE||
PageConfig.isMobileOrTablet||(NoTxnIdleHandler.getNoTxnIdleMsgFromCookie()&&NoticeHandler.error(I18N.get("msg.error.account.idleTimeTooLong")),NoTxnIdleHandler.deleteNoTxnIdleMsgFromCookie())};NoTxnIdleHandler.isHasTxn=()=>{var a=DataBase.unMatchTicket.getByEventId(PageConfig.selectEventId,CategoryType.BETFAIR.unique());if(NoTxnIdleHandler.isHasEffectiveUnMatchTicket(a))return!0;a=DataBase.txn.getByEventId(PageConfig.selectEventId,CategoryType.BETFAIR.unique());if(NoTxnIdleHandler.isHasEffectiveTxn(a))return!0;
a=DataBase.fancyBetTxn.getByEventId(PageConfig.selectEventId,CategoryType.FANCY_BET.unique());if(NoTxnIdleHandler.isHasEffectiveTxn(a))return!0;a=DataBase.sportsBookUnMatchTicket.getByEventId(PageConfig.sportsBookEventId,CategoryType.SPORTRADAR_SPORTSBOOK.unique());if(NoTxnIdleHandler.isHasEffectiveUnMatchTicket(a))return!0;a=DataBase.sportsBookTxn.getByEventId(PageConfig.sportsBookEventId,CategoryType.SPORTRADAR_SPORTSBOOK.unique());if(NoTxnIdleHandler.isHasEffectiveTxn(a))return!0;a=DataBase.bookMakerTxn.getByEventId(PageConfig.selectEventId,
CategoryType.BOOK_MAKER.unique());if(NoTxnIdleHandler.isHasEffectiveTxn(a))return!0;a=DataBase.financialTxn.getByEventId(PageConfig.selectEventId,CategoryType.TS_BINARY.unique());return NoTxnIdleHandler.isHasEffectiveTxn(a)?!0:!1};NoTxnIdleHandler.isHasEffectiveUnMatchTicket=a=>{let c=!1;if("undefined"==typeof a||null==a||0==a.length)return!1;for(let b=0;b<a.length;b++)if(UnMatchTicketUtil.isActive(a[b].status)){c=!0;break}return c};NoTxnIdleHandler.isHasEffectiveTxn=a=>{let c=!1;if("undefined"==
typeof a||null==a||0==a.length)return!1;for(let b=0;b<a.length;b++)if(MyTransactionUtils.isActive(a[b].status)){c=!0;break}return c};NoTxnIdleHandler.isLogin=()=>PageConfig.isMobileOrTablet?"undefined"!=typeof PageCommonConfig.hasAccount&&PageCommonConfig.hasAccount:"undefined"!=typeof PageConfig.hasAccount||PageConfig.hasAccount;NoTxnIdleHandler.addNoTxnIdleMsgToCookie=()=>{CookieUtil.setCookie("noTxnIdleShowMsg",1,1)};NoTxnIdleHandler.deleteNoTxnIdleMsgFromCookie=()=>{CookieUtil.deleteCookie("noTxnIdleShowMsg")};
NoTxnIdleHandler.getNoTxnIdleMsgFromCookie=()=>CookieUtil.getCookie("noTxnIdleShowMsg")})();

