"undefined"==typeof PoliticsMarketViewHandler&&(PoliticsMarketViewHandler={});
(function(){function h(a){var b=DataBase.politicsMarkets.queryAll();$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.queryPoliticsMultiMarketsPath,data:{marketPks:JSON.stringify(b)},success:function(e){try{JsCache.get("#loading").hide();for(var f=e.multiMarkets,g=0;g<f.length;g++){var k=f[g],d=k.market;null!=d&&DataBase.markets.update(k.eventId,[d])}PoliticsMarketViewHandler.updateMultiMarketList(e)}catch(l){Trace.printStackTrace(l)}finally{a.check(),TaskExecuterV2.execute()}},error:function(){a.check();
TaskExecuterV2.execute()}})}PoliticsMarketViewHandler.getMarketsTask=null;PoliticsMarketViewHandler.initTask=function(){if(null==PoliticsMarketViewHandler.getMarketsTask){var a=TaskExecuterV2.createTask(PageConfig.getFullMarketsTaskCycleTime,0,function(){h(this)});PoliticsMarketViewHandler.getMarketsTask=a}else PoliticsMarketViewHandler.getMarketsTask.isStop=!1;PoliticsMarketViewHandler.getMarketsTask.run();TaskExecuterV2.execute()};PoliticsMarketViewHandler.abortTask=function(){null!=PoliticsMarketViewHandler.getMarketsTask&&
PoliticsMarketViewHandler.getMarketsTask.stop()};PoliticsMarketViewHandler.updateMultiMarketList=function(a){var b=$j("#overWrap");a=a.multiMarkets;b.find("#refreshButton").unbind("click").click(function(){JsCache.get("#loading").show();PoliticsMarketViewHandler.getMarketsTask.refresh()});for(var e=0;e<a.length;e++)PoliticsMarketViewHandler.updateMultiMarket(b,a[e])};PoliticsMarketViewHandler.updateMultiMarket=function(a,b){var e=b.eventType,f=b.eventId,g=b.marketId,k=f+"_"+g.replace(".","_"),d=b.market,
l=b.gameProductStatus,m=MarketUtil.isCloseSite(d.closeSite,PageConfig.webSiteType)||EventUtils.isCloseSite(b.eventCloseSite,PageConfig.webSiteType)||CompetitionUtils.isCloseSite(b.competitionCloseSite,PageConfig.webSiteType),n=MarketUtil.isBookModeShow(d.bookMode,PageConfig.webSiteType)&&MarketUtil.isBookModeShow(b.eventBookMode,PageConfig.webSiteType);if(null!=DataBase.politicsMarkets.getMarketPk(f,g)){var c=a.find("#multiMarket_"+k);if(0==c.length){if(MarketUtil.isClosed(d.status)||m||!n)return;
c=a.find("#fullMarketBetsWrap").clone();c.attr("id","multiMarket_"+k);c.attr("eventType",e);c.attr("eventId",f);c.attr("marketId",g);BetHandler.addSelectClass();a.find("#politicsMultiMarketsHead").after(c.show())}else{if(MarketUtil.isClosed(d.status)||m||!n){c.hide();return}c.show()}c.find("#marketName").html(d.marketName);null!=d.betLimitSetting&&0!=d.betLimitSetting.length&&(c.find("#min").html(MathUtil.roundp(d.betLimitSetting.minBet,2)),c.find("#max").html(MathUtil.roundp(d.betLimitSetting.maxBet,
2)));a=b.isOfferBetfairExchange;FullMarketUtil.updateFullMarket(c,c.find("#fullMarketBoard"),e,f,g,d,l,a)}}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.politicsMarkets={};var h=new HashMap;DataBase.politicsMarkets.addMarketPk=function(a,b,e){var f=DataBase.politicsMarkets.generateKey(b,e);h.put(f,{eventType:a,eventId:b,marketId:e,selectionTs:-1})};DataBase.politicsMarkets.getMarketPk=function(a,b){a=DataBase.politicsMarkets.generateKey(a,b);return h.get(a)};DataBase.politicsMarkets.generateKey=function(a,b){return a+"_"+b.replace(".","_")};DataBase.politicsMarkets.queryAll=function(){return h.values()}})();

