"undefined"==typeof PopularMarketHandler&&(PopularMarketHandler={});
(function(){function A(a){null==u.get(a)&&u.put(a,-1)}function D(a){-1==PageConfig.selectEventId||null==PageConfig.selectMarketId?(a.check(),TaskExecuter.execute()):$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},
success:function(d){try{JsCache.get("#listBoardLoading").hide(),JsCache.get("#loading").hide(),DataBase.markets.update(d.eventId,d.markets),1<B(d.markets)?JsCache.get("#popularMarkets").show():JsCache.get("#popularMarkets").hide(),PopularMarketHandler.updateMarkets(d.eventId),PopularMarketHandler.autoUpdateSelectionsTask.refresh()}catch(e){Trace.printStackTrace(e)}finally{a.check(),TaskExecuter.execute()}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&
!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);a.check();TaskExecuter.execute()}})}function E(a,d,e,h,m,b,g,n,c,k,r){null!=g&&0<g.length&&g.sort(function(F,G){return F.sortPriority-G.sortPriority});for(var p=EventType.getInstanceOf(a),t=0,q=!1;null!=g&&0<g.length&&t<g.length;){var f=g[t];t++;var v=f.selectionKey,l=n.find("#selection_"+v),w=SelectionUtil.isShowSelection(f.closeSite,f.bookMode,PageConfig.webSiteType),H=GameProductUtils.isClose(r)||
SelectionUtil.isShowSuspend(f.suspendSite,f.bookSuspend,PageConfig.webSiteType),I=1==f.isAutoSuspend;if(0==l.length){if(!w)continue;if(p.isRacingEvent()){if(!(SelectionUtil.isActive(f.status)||SelectionUtil.isRemoved(f.status)||SelectionUtil.isRemovedVacant(f.status)||SelectionUtil.isHidden(f.status)))continue}else if(!SelectionUtil.isActive(f.status))continue;q=!0;w="";w="<a onclick=\"window.open('market/marketDepth.jsp?eventId="+d+"&marketId="+h+"&selectionId="+f.selectionId+"&handicap="+f.handicap+
"','_blank','resizable=no,width=450,height=460')\"><img class=\"icon-predict\" src=\"/images/transparent.gif\"/></a>";l=JsCache.clone("#selectionTemplate");l.attr("id","selection_"+v);l.attr("eventType",a);l.attr("eventId",d);l.attr("marketId",h.replace(".","_"));l.attr("popSelectionItem",v);l.attr("selectionId",f.selectionId);l.attr("handicap",f.handicap);l.attr("sortpriority",f.sortPriority);l.find("#runner").html(w+f.runnerName+'<br /><span id="withoutBet" class="win" style="display: none;"></span><span id="lossWithoutBet" class="" style="display: none;"></span><span id="withBet" class="win" style="display: none;"></span><span id="lossWithBet" class="" style="display: none;"></span>');
!MarketUtil.isOpen(b)||MarketUtil.isSuspend(b)||MarketUtil.isClosed(b)||(l.find(".btn-back").click(function(){BetHandler.clickBtn(this,!1)}),l.find(".btn-lay").click(function(){BetHandler.clickBtn(this,!1)}));n.find("#moreLink").before(l.show())}else{if(!w){l.hide();continue}l.is(":visible")||l.show();if(p.isRacingEvent()){if(!(SelectionUtil.isActive(f.status)||SelectionUtil.isRemoved(f.status)||SelectionUtil.isRemovedVacant(f.status)||SelectionUtil.isHidden(f.status))){l.hide();continue}}else if(!SelectionUtil.isActive(f.status)){l.hide();
continue}}l.attr("eventName",e);v="&nbsp;";0<f.availableToBack.length&&(v=f.availableToBack[0].price,SparkHandler.addSparkClass(l.find(".btn-back"),v,null));w="&nbsp;";0<f.availableToLay.length&&(w=f.availableToLay[0].price,SparkHandler.addSparkClass(l.find(".btn-lay"),w,null));l.find(".btn-back").attr("selectionId",f.selectionId).attr("selectionKey",f.selectionKey).attr("runner",f.runnerName).attr("marketName",m).attr("handicap",f.handicap).html(v);l.find(".btn-lay").attr("selectionId",f.selectionId).attr("selectionKey",
f.selectionKey).attr("runner",f.runnerName).attr("marketName",m).attr("handicap",f.handicap).html(w);l.find(".btn-back").attr("inPlay",c);l.find(".btn-lay").attr("inPlay",c);l.find(".btn-back").attr("marketType",k);l.find(".btn-lay").attr("marketType",k);H?l.find("#selectionSuspend").show():l.find("#selectionSuspend").hide();I?l.addClass("disabled"):l.removeClass("disabled")}1==q&&(BetHandler.getWinLoss(d,h),BetHandler.addSelectClass())}function y(a,d){if(null!=a&&null!=d&&0!=d.length){for(var e=
"",h="",m=0;m<d.length;m++){e+=d[m]+",";var b=u.get(d[m]);null==b&&(b=-1);h+=b+","}$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.querySelectionsPath,data:{eventId:a,marketIds:e,selectionTsList:h},success:function(g){try{if(0!=g.markets.length)for(var n=$j("#overWrap"),c=0;c<g.markets.length;c++){var k=g.markets[c],r=k.marketId;DataBase.markets.update(k.eventId,[k]);null!=u.get(r)&&u.put(r,k.selectionTs);var p=n.find("#popMarketItem_"+r.replace(".","_"));if(0<p.length){E(g.eventType,g.eventId,
g.eventName,r,k.marketName,k.status,k.selections,p,k.inPlay,k.marketType,g.gameProductStatus);var t=CurrencyUtil.formatter(0<k.totalMatched?k.totalMatched:0,{precision:0,separateSign:",",currencySymbol:null==PageConfig.currencySymbol?"$":PageConfig.currencySymbol,formatter:function(f,v){return 0==f.indexOf("-")?"("+v.currencySymbol+f.replace("-","")+")":v.currencySymbol+f},"trailingZeros,":!1}),q="Matched: "+PageConfig.playerCurrencyType+" "+t;BetHandler.isEnableCheckLowLiquidity()?(BetHandler.isLowLiquidity(g.eventType,
a,r.replace("_","."))?(FullMarketUtil.disableBetButton(p,!0),FullMarketUtil.showLowLiquidityTag(p.find("#lowLiquidityTag"),!0)):(FullMarketUtil.disableBetButton(p,!1),FullMarketUtil.showLowLiquidityTag(p.find("#lowLiquidityTag"),!1)),p.find("#matched").contents().filter(function(){return 3==this.nodeType}).remove(),p.find("#lowLiquidityTag").after(q)):q!=p.find("#matched").html()&&p.find("#matched").html(q)}}}catch(f){Trace.printStackTrace(f)}finally{}},error:function(g){Trace.error(" expandedMarketsOnUI: "+
d);Trace.error(g)}})}}function B(a){var d=0,e;for(e in a){var h=a[e],m=MarketUtil.isCloseSite(h.closeSite,PageConfig.webSiteType);MarketUtil.isClosed(h.status)||m||d++}return d}PopularMarketHandler.needResetAutoUpdateSelectionsMap=!1;PopularMarketHandler.showPopName="popular";var x=new HashMap,C=-1;PopularMarketHandler.init=function(){var a=EventType.getInstanceOf(PageConfig.selectEventType);if(null==a)x.clear();else if(a=a.popularTabType,null==a||0==a.length)x.clear();else{if(PageConfig.selectEventType!=
C){x.clear();for(var d in a){var e=a[d];x.put(e.name,e)}C=PageConfig.selectEventType}PopularMarketHandler.showPopName=a[0].name;z();JsCache.get("#popularMarkets").find("#popularTab_"+a[0].name).find("a").addClass("select")}};PopularMarketHandler.clickPopularTab=function(a){z();JsCache.get("#popularMarkets").find("#popularTab_"+a).find("a").addClass("select");PopularMarketHandler.showPopName=a};var z=function(){JsCache.get("#popularMarkets").find("a").removeClass("select")};PopularMarketHandler.getTabTypeByName=
function(a){return x.get(a)};PopularMarketHandler.startsWithMapping=function(a){return a.match("OVER_UNDER")?"OVER_UNDER":a.match("TEAM_A")&&"TEAM_A_WIN_TO_NIL"!=a?"TEAM_A":a.match("TEAM_B")&&"TEAM_B_WIN_TO_NIL"!=a?"TEAM_B":a.match("FIRST_HALF_GOALS")?"FIRST_HALF_GOALS":a};PopularMarketHandler.appendPopMarketTab=function(a,d){var e=x.entrySet(),h;for(h in e){var m=e[h].value;for(h in d){var b=d[h],g=MarketUtil.isCloseSite(b.closeSite,PageConfig.webSiteType);PageConfig.selectMarketId==b.marketId||
MarketUtil.isClosed(b.status)||g||(b=b.marketType,1==PopularMarketHandler.isValidPopMarketType(b,m.marketTypes)&&PopularMarketHandler.appendTabByType(a,m),1==PopularMarketHandler.isOtherMarkets(b)&&PopularMarketHandler.appendTabByType(a,x.get("other_markets")))}}a=JsCache.get("#popularMarkets").show();d=a.find("[id^=popularTab_]");d.sort(function(n,c){n=$j(n).attr("tabName").trim();c=$j(c).attr("tabName").trim();if("other_markets"==n)return 1;if("other_markets"==c)return-1});a.append(d);z();e=$j(d[0]);
0<e.length&&(e.find("a").addClass("select"),PopularMarketHandler.showPopName=e.attr("tabName"));0==d.length&&a.hide()};PopularMarketHandler.appendTabByType=function(a,d){var e=JsCache.get("#popularMarkets"),h=$j("#popularTab_"+d.name);0==h.length&&(h=JsCache.clone("#popularMarketTemplate"),h.attr("id","popularTab_"+d.name),h.attr("tabName",d.name),h.attr("eventId",a),h.find("a").html(StringUtil.ucfirst(d.name.replace(/_/g," "))),h.click(function(m){return function(){PopularMarketHandler.clickPopularTab(m.name);
$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(b){try{DataBase.markets.update(b.eventId,b.markets),PopularMarketHandler.updateMarkets(b.eventId),PopularMarketHandler.reSortPopMarketItem(b.eventId),
PopularMarketHandler.needResetAutoUpdateSelectionsMap=!0,PopularMarketHandler.autoUpdateSelectionsTask.refresh()}catch(g){Trace.printStackTrace(g)}finally{}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}})}}(d)),e.append(h.show()))};PopularMarketHandler.appendAllTab=function(){-1==PageConfig.selectEventId||null==PageConfig.selectMarketId||
EventType.getInstanceOf(PageConfig.selectEventType).isRacingEvent()?JsCache.get("#popularMarkets").hide():($j("[id^=popularTab_]").remove(),$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryMarketsWithoutSelectionPath,data:{eventType:PageConfig.selectEventType,eventId:PageConfig.selectEventId,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(a){try{DataBase.markets.update(a.eventId,
a.markets),1<B(a.markets)?PopularMarketHandler.appendPopMarketTab(a.eventId,a.markets):JsCache.get("#popularMarkets").hide(),PopularMarketHandler.updateMarkets(a.eventId),PopularMarketHandler.reSortPopMarketItem(a.eventId),PopularMarketHandler.needResetAutoUpdateSelectionsMap=!0,PopularMarketHandler.autoUpdateSelectionsTask.refresh()}catch(d){Trace.printStackTrace(d)}finally{}},error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&
(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}}))};PopularMarketHandler.isValidPopMarketType=function(a,d){if(null==a)return!1;a=PopularMarketHandler.startsWithMapping(a);return-1!=ArrayUtil.indexOf(d,a)?!0:!1};PopularMarketHandler.isOtherMarkets=function(a){if(null==a)return!0;var d=!0;a=PopularMarketHandler.startsWithMapping(a);var e=x.values(),h;for(h in e)if(-1!=ArrayUtil.indexOf(e[h].marketTypes,a)){d=!1;break}return d};var u=new TreeMap;PopularMarketHandler.autoUpdateSelectionsTask=
null;PopularMarketHandler.initAutoUpdateSelectionsTask=function(){PopularMarketHandler.autoUpdateSelectionsTask=TaskExecuter.createTask(PageConfig.autoUpdateSelectionsTaskCycleTime,0,function(){try{var a=$j("#overWrap");if(-1==PageConfig.selectEventId||null==PageConfig.selectMarketId)0<u.length&&(u=new TreeMap);else{PopularMarketHandler.needResetAutoUpdateSelectionsMap&&(u=new TreeMap,PopularMarketHandler.needResetAutoUpdateSelectionsMap=!1);for(var d=[],e=u.keySet(),h=e.length,m=0;m<h;m++){var b=
e[m];a.find("#popMarketItem_"+b.replace(".","_")).hasClass("close")||(d[d.length]=b)}0<d.length&&y(PageConfig.selectEventId,d)}}catch(g){Trace.printStackTrace(g)}finally{this.check(),TaskExecuter.execute()}});PopularMarketHandler.autoUpdateSelectionsTask.run();TaskExecuter.execute()};PopularMarketHandler.getMarketsTask=null;PopularMarketHandler.initGetMarketsTask=function(){PopularMarketHandler.getMarketsTask=TaskExecuter.createTask(PageConfig.queryMarketsWithoutSelectionCycleTimes,0,function(){D(this)});
PopularMarketHandler.getMarketsTask.run();TaskExecuter.execute()};PopularMarketHandler.updateMarkets=function(a){var d=$j("#overWrap"),e=d.find("[id^=popMarketItem_]");$j.each(e,function(q,f){f=$j(f);PageConfig.selectEventId!=f.attr("eventId")&&f.remove()});var h=DataBase.markets.queryByEvent(a);e=DataBase.events.get(PageConfig.selectEventType,a);if(null!=e){for(var m=0;m<h.length;m++){for(var b=h[m],g=!1,n=0;n<e.markets.length;n++){var c=e.markets[n];if(b.marketId==c.marketId&&(c.status=b.status,
c.totalMatched=b.totalMatched,c.inPlay=b.inPlay,c.updateDate=b.updateDate,c.version=b.version,c.closeSite=b.closeSite,3!=b.status)){g=!0;for(var k=0;k<b.selections.length;k++){for(var r=b.selections[k],p=!1,t=0;t<c.selections.length;t++)r.selectionKey==c.selections[t].selectionKey&&(p=!0,c.selections[t]=r);0==p&&(c.selections[c.selections.length]=r)}}}0==g&&(e.markets[e.markets.length]=b)}e.markets.sort(function(q,f){return MarketHandler.sortRule(q.marketName,f.marketName,q.totalMatched,f.totalMatched,
q.marketId,f.marketId)});h=n=0;b=null;m=PopularMarketHandler.getTabTypeByName(PopularMarketHandler.showPopName);if(null!=m){for(;null!=e.markets&&0<e.markets.length&&n<e.markets.length;)if(b=e.markets[n],g=MarketUtil.isCloseSite(b.closeSite,PageConfig.webSiteType),n++,c=d.find("#popMarketItem_"+b.marketId.replace(".","_")),k=$j("#listBoard").find("#naviMenu_"+b.marketId.replace(".","_")),g)0<c.length&&c.hide(),0<k.length&&k.hide();else if(!PopularMarketHandler.isValidPopMarketType(b.marketType,m.marketTypes)&&
"other_markets"!=PopularMarketHandler.showPopName||!PopularMarketHandler.isOtherMarkets(b.marketType)&&"other_markets"==PopularMarketHandler.showPopName||g)c=d.find("#popMarketItem_"+b.marketId.replace(".","_")),0<c.length&&c.hide();else if(c=null,MarketUtil.isClosed(b.status)?0<k.length&&k.remove():k.is(":visible")||k.show(),c=d.find("#popMarketItem_"+b.marketId.replace(".","_")),PageConfig.selectMarketId==b.marketId)0<c.length&&c.hide();else{if(0==c.length){if(MarketUtil.isClosed(b.status)||g)continue;
c=JsCache.clone("#marketTemplate");c.attr("id","popMarketItem_"+b.marketId.replace(".","_"));c.attr("marketType",b.marketType);c.attr("eventId",e.id);c.attr("marketId",b.marketId);c.attr("totalMatched",b.totalMatched);c.attr("marketName",b.marketName);UiUtils.bindToExpand(c.find(".to-expand"));c.find(".to-expand").click(function(q){return function(){$this=$j(this);1==$this.parent().parent().find(".game-list").find("dl").length&&(A(q),y(PageConfig.selectEventId,[q]))}}(b.marketId));MultiMarketsHandler.bindPinEvent(c,
e.eventType,e.id,b.marketId);MultiMarketsHandler.checkIsMultiMarket(c.find("#multiMarketPin"),e.eventType,e.id,b.marketId)}else c=d.find("#popMarketItem_"+b.marketId.replace(".","_")),c.show();h++;c.find("#marketName").html(b.marketName);1==b.inPlay?(c.find("#marketName").html(b.marketName+' <img class="icon-irun" src="/images/transparent.gif" />'),0<k.length&&(k=k.find("#name").find("img"),k.removeClass("icon-no_play"),k.addClass("icon-in_play"))):0<k.length&&(k=k.find("#name").find("img"),k.removeClass("icon-in_play"),
k.addClass("icon-no_play"));4<h||A(b.marketId);0!=c.find("dl[popSelectionItem]").length&&(!MarketUtil.isOpen(b.status)||MarketUtil.isSuspend(b.status)||MarketUtil.isClosed(b.status)?MarketUtil.isSuspend(b.status)&&!MarketUtil.isClosed(b.status)?(c.find("#suspend").show(),c.find("#closed").hide()):(MarketUtil.isClosed(b.status)||g)&&c.hide():(c.find("#suspend").hide(),c.find("#closed").hide()));0==d.find("#popMarketItem_"+b.marketId.replace(".","_")).length&&(c.find("#moreLink").click(function(q,f){return function(){PageConfig.selectMarketId=
f;location.href=PageConfig.landingPath+"/member/fullMarket?eventType="+q.eventType+"&eventId="+q.id+"&marketId="+f}}(e,b.marketId)),b=PageConfig.fullMarketPath+"?eventType="+e.eventType+"&eventId="+e.id+"&marketId="+b.marketId,c.find("#moreLink").attr("href",b),4<h&&c.addClass("close"),1==h%2?JsCache.get("#fullMarketEventLeft").append(c.show()):JsCache.get("#fullMarketEventRight").append(c.show()))}y(a,u.keySet())}}};PopularMarketHandler.reSortPopMarketItem=function(a){var d=$j("#overWrap"),e=d.find("[id^=popMarketItem_]");
if(0!=e.length&&null!=a&&-1!=a){e.sort(function(n,c){n=$j(n);c=$j(c);var k=n.attr("marketName"),r=c.attr("marketName"),p=parseFloat(n.attr("totalMatched")),t=parseFloat(c.attr("totalMatched"));if(n.is(":visible")&&c.is(":visible"))return MarketHandler.sortRule(k,r,p,t,n.attr("marketId"),c.attr("marketId"));if(n.is(":visible"))return-1;if(c.is(":visible"))return 1});for(var h=0,m=[],b=0;b<e.length;b++){var g=d.find(e[b]);null==g||0==g.length||g.is(":hidden")||(h++,4<h?g.addClass("close"):(m.push(g.attr("marketId")),
g.removeClass("close")),1==h%2?JsCache.get("#fullMarketEventLeft").append(g):JsCache.get("#fullMarketEventRight").append(g))}y(a,m)}}})();

