"undefined"==typeof SportsBookEventHandler&&(SportsBookEventHandler={});
(function(){function w(a,c,d){var b=new Date;$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+"/exchange/member/playerService/querySportsBookEvent",data:c,xhrFields:{withCredentials:!0},success:function(e){try{if(e){null!=a&&(a.isInit=!1,e.version>a.version&&(a.version=Math.max(e.version,a.version)));var f=new Date,g=f.getTime()-b.getTime();500<g&&Trace.debug("UPDATE start:"+b.toString()+" end:"+
f.toString()+" ms:"+g+" market num: "+(null==e.sportsBookMarket?0:e.sportsBookMarket.length));SportsBookEventHandler.updateSportsBookEvent(d,e,c)}}catch(k){Trace.printStackTrace(k)}},error:function(e,f,g){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.log(e.status);Trace.log(g)}})}function h(a,c){var d=z.get(a);null==d&&(d=new HashMap,z.put(a,d));d.put(c,
-1)}function l(a,c,d){a=z.get(a);null!=a&&null!=a.get(c)&&a.remove(c)}function q(a){a=z.get(a);null!=a&&a.clear()}function t(a,c,d,b,e){null==d&&$j("#sportsBookWrap").find("[id^=sportsBookMarket_]").addClass("close").hide();e=null!=e&&0!=e.version?d.sportsBookMarket:DataBase.sportsBookMarkets.queryMarkets(a,c);var f;ApiSiteType.SPORTRADAR.unique()==a&&(f=EventType.CRICKET.unique()==PageConfig.selectEventType||EventType.TENNIS.unique()==PageConfig.selectEventType||EventType.E_SOCCER.unique()==PageConfig.selectEventType||
EventType.SOCCER.unique()==PageConfig.selectEventType||EventType.KABADDI.unique()==PageConfig.selectEventType?SportsBookMarketUtil.getFilterMarkets(SportsBookEventHandler.tab,e):e);ApiSiteType.OW.unique()==a&&(f=SportsBookMarketUtil.getOwFilterMarkets(SportsBookEventHandler.tab,e));r(a,c,d,f,b)}function r(a,c,d,b,e){var f=$j("#overWrap").find("#sportsBookWrap"),g={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,
"trailingZeros,":!1};c=!1;for(var k in b){var n=b[k].marketStatus;if(SportsBookMarketUtil.isOpen(n)||SportsBookMarketUtil.isSuspend(n)){c=!0;break}}c?f.find("#sportsBookNoBet").hide():f.find("#sportsBookNoBet").show();k=SportsBookEventHandler.isViewMultiMarket();n=!1;var p=!0,v=!1;null!=d&&(n=EventUtils.isCloseSite(d.closeSite,PageConfig.webSiteType),p=EventUtils.isBookModeShow(d.bookMode,PageConfig.webSiteType),v=GameProductUtils.isClose(d.gameProductStatus));for(var B in b){var m=b[B],u=m.eventType,
C=m.id;c=m.eventId;var D=m.marketStatus,x=MarketUtil.isCloseSite(m.closeSite,PageConfig.webSiteType),y=MarketUtil.isBookModeShow(m.bookMode,PageConfig.webSiteType),G=m.isExpand,K=m.betfairEventId,H=DataBase.sportsBookMarkets.getEventMarketKey(a,c,C),L=m.apiSiteMarketType;if(k){var A=SportsBookMarketUtil.isHideMarket(D)||x||n||!p||!y||v;G=1;f=E(f,H,m,d,A)}A=f.find("#sportsBookMarket_"+H);if(0==A.length){if(SportsBookMarketUtil.isHideMarket(D)||x||!y){l(a,C);continue}A=F(f,a,m);0==G?A.addClass("close"):
h(a,C)}else x=a,D=C,m=m.selectionTs,null!=m&&(y=z.get(x),null==y&&(y=new HashMap,z.put(x,y)),x=y.get(D),null==x||m<x||y.put(D,m));e&&1==G&&A.removeClass("close");MultiMarketsHandler.appendSportsBookPin(u,H,K,C,k,a);M(f,A,a,c,C,d,g,L)}(I||e)&&ApiSiteType.SPORTRADAR.unique()==a&&SportsBookEventHandler.extandMarket(f);I=!1}function F(a,c,d){var b=a.find("#sportsBookMarketTemplate").clone();b.prop("id","sportsBookMarket_"+DataBase.sportsBookMarkets.getEventMarketKey(c,d.eventId,d.id));b.prop("marketId",
d.id);b.prop("eventId",d.eventId);b.prop("betfairEventId",d.betfairEventId);b.prop("marketName",d.marketName);b.prop("marketStatus",d.marketStatus);b.prop("apiSiteType",c);b.find("#marketName").html(d.marketName);null!=d.marketType&&b.prop("sort",d.marketType.sort);b.find("#marketName").on("click",function(e,f,g,k){return function(){e.hasClass("close")?(h(f,k),w(null,{eventId:PageConfig.selectEventId,apiSiteType:f,version:SportsBookEventHandler.queryTasks[f].version,marketIds:k+",",selectionTsList:"-1,",
isDynamicUpdate:1,queryPass:PageConfig.queryPass},f),e.removeClass("close")):(l(f,k),e.addClass("close"),SportsBookBetHandler.removeBoardByMarket(f,g,k),SportsBookEventHandler.removeSelectClassByMarket(f,g,k))}}(b,c,d.eventId,d.id));a.find("#sportsBookNoBet").before(b);return b}function E(a,c,d,b,e){var f=a.find("#sportsBookTable_"+c);if(0==f.length){var g=b.eventType,k=b.eventName,n=b.highlightMarketId;f=a.find("#sportsBookTableTemplate").clone();f.attr("id","sportsBookTable_"+c);f.attr("name","multiMarketItem");
f.find(".multi_name").unbind("click").click(function(){location.href=PageConfig.fullMarketPath+"?eventType="+g+"&eventId="+d.betfairEventId+"&marketId="+n});f.find("#multiMarketRefresh").unbind("click").click(function(){f.find("#multiMarketLoading").show();setTimeout(function(){f.find("#multiMarketLoading").hide()},500)});1==b.isElectronic&&f.find("#sportsBookEIcon_"+g).show().css("display","inline-flex");ApiSiteType.SPORTRADAR.unique()==b.apisite&&f.find("#icon").text("Premium Cricket");ApiSiteType.OW.unique()==
b.apisite&&f.find("#icon").text("Premium Tennis");SportsBookEventUtil.isLive(b.live)?f.find("#icon").addClass("in-play"):f.find("#icon").removeClass("in-play");f.find("#eventName").text(k);f.find("#marketName").text(d.marketName);a.append(f);f.show();a.show()}e?a.find(f).remove():a.show();return f}function M(a,c,d,b,e,f,g,k){b=DataBase.sportsBookMarkets.get(d,b,e);if(null==b)Trace.log("SportsBook market "+e+" is null");else{e=b.sportsBookSelection;g=!1;if(null!=e){e.sort(function(B,m){return SportsBookMarketUtil.sortSelections(B,
m,d,k)});for(var n in e){var p=e[n],v=c.find("#sportsBookSelection_"+SportsBookEventHandler.getSelectionKey(d,p));0==v.length&&(v=N(a,c,d,p),g=!0);O(c,p,f,b,d)}}P(c,d,f,b,g)}}function P(a,c,d,b,e){d=b.marketStatus;var f=MarketUtil.isCloseSite(b.closeSite,PageConfig.webSiteType),g=MarketUtil.isBookModeShow(b.bookMode,PageConfig.webSiteType);a.prop("updateDate",b.updateDate);a.find("#marketName").html(b.marketName);SportsBookMarketUtil.isHideMarket(d)||f||!g?(l(c,b.id),a.hide(),SportsBookBetHandler.removeBoardByMarket(c,
b.eventId,b.id),SportsBookEventHandler.removeSelectClass()):(a.hasClass("close")||h(c,b.id),a.show(),a.hasClass("close")||((e||SportsBookMarketUtil.isSuspend(d))&&SportsBookBetHandler.getExposure(c,b.eventId,b.id),SportsBookMarketUtil.isSuspend(d)&&(SportsBookBetHandler.removeBoardByMarket(c,b.eventId,b.id),SportsBookEventHandler.removeSelectClass())))}function N(a,c,d,b){var e=a.find("#sportsBookTemplateTable"),f=DataBase.sportsBookMarkets.getEventMarketKey(d,b.eventId,b.marketId);a=e.find("#sportsBookSelectionTemplate").clone();
a.prop("id","sportsBookSelection_"+SportsBookEventHandler.getSelectionKey(d,b));a.prop("betfairEventId",b.betfairEventId);a.prop("eventType",b.eventType);a.prop("eventId",b.eventId);a.prop("marketId",b.marketId);a.prop("selectionName",b.selectionName);a.prop("handicap",b.handicap);a.prop("updateDate",b.updateDate);a.prop("apiSiteType",d);a.attr("marketPk",f);ApiSiteType.OW.unique()==d&&0!=b.handicap?a.find("#selectionName").html(b.selectionName+" <span>"+b.handicap+"</span>"):a.find("#selectionName").html(b.selectionName);
a.show();a.prop("style","");Q(a,a.find("#back_1"),d,b);e=e.find("#sportsBookSuspendTemplate").clone();e.prop("id","sportsBookSuspend_"+SportsBookEventHandler.getSelectionKey(d,b));e.attr("eventId",b.eventId);e.prop("marketId",b.marketId);e.prop("selectionId",b.id);c.find("tbody").append(e);c.find("tbody").append(a);return a}function O(a,c,d,b,e){var f=a.find("#sportsBookSelection_"+SportsBookEventHandler.getSelectionKey(e,c)),g=a.find("#sportsBookSuspend_"+SportsBookEventHandler.getSelectionKey(e,
c));if(0!=g.length&&0!=f.length){b=b.marketStatus;var k=c.isActive;f.attr("isActive",k);f.attr("status",b);g.attr("isActive",k);g.attr("status",b);0==k||a.hasClass("close")?(f.hide(),g.hide()):(1==k&&f.show(),a="Suspend",ApiSiteType.SPORTRADAR.unique()==e&&(a="Ball Run"),(null!=d&&SportsBookEventUtil.isSuspend(d.eventStatus)||SportsBookMarketUtil.isSuspend(b))&&1==k?(g.find("span").html(a),g.show()):SportsBookMarketUtil.isClosed(b)&&1==k?(g.find("span").html("Closed"),g.show()):g.hide(),d=c.odds,
f.find("#selectionName").html(c.selectionName),f.find("#info").prop("odds",d),f.find("#info").html(0==d?"":d),SparkHandler.addSparkClass(f.find("#back_1"),d))}}function Q(a,c,d,b){a=function(e,f,g,k,n,p,v,B){return function(){var m=f.find("#info").prop("odds")||0;0!=m&&("true"==PageConfig.ENABLE_ONE_CLICK_BET&&OneClickBetHandler.isEnable()&&1==PageConfig.isOneClickBet&&PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?OneClickBetHandler.isEnableSubmitOneClickBet()&&OneClickBetHandler.placeSportsBookBet(e,
g,k,n,p,v,m):(SportsBookEventHandler.removeSelectClass(),f.addClass("select"),SportsBookBetHandler.appendBoard(e,g,k,n,p,v,m)))}}(a,c,d,b.eventType,b.eventId,b.marketId,b.id);c.on("click",a)}function J(){$j("#fancyBetHead").find("#showSportsBookBtn").show();FancyBetMarketHandler.isShowFancyBet()||(FullMarketUtil.view("sportsBookBet"),$j("#sportsBookWrap").find("#showFancyBetBtn").hide())}SportsBookEventHandler.queryTasks=[];SportsBookEventHandler.tab="All";var z=new HashMap,I=!1;SportsBookEventHandler.init=
function(a,c){q(a);if(!AccountUtil.isEnableSportsBook(PageConfig.isAllowSportsbook,a)&&ApiSiteType.OW.value==a&&(EventType.SOCCER.value==PageConfig.selectEventType||EventType.E_SOCCER.value==PageConfig.selectEventType)&&PageConfig.isOfferOwSportsBook)SportsBookEventHandler.initTask(a,!0);else if(c){J();$j("#overWrap").find("#sportsBookNoBet").show();FancyBetMarketHandler.isShowFancyBet()||SportsBookEventHandler.initTask(a,!1);$j("#showFancyBetBtn").on("click",function(){FullMarketUtil.view("fancyBet");
FancyBetMarketHandler.initTask();SportsBookEventHandler.isShowSportsBook()&&SportsBookEventHandler.abortTask(ApiSiteType.SPORTRADAR.unique());SportsBookEventHandler.isShowOwSportsBook()&&SportsBookEventHandler.abortTask(ApiSiteType.OW.unique())});var d=$j("#sportsBookTab_"+a+"_"+PageConfig.selectEventType);d.show();d.find("[id^=tab_]").on("click",function(){var b=$j(this).html();SportsBookEventHandler.tab=b;b=PageConfig.sportsBookEventId;ApiSiteType.OW.unique()==a&&(b=PageConfig.owSportsBookEventId);
q(a);t(a,b,null,!0);SportsBookBetHandler.resetAllBetBoard();d.find("#moreDropList").hide()});d.find("#moreDropBtn").on("click",function(b){var e=d.find("#moreDropList");$j(document).on("click",function(){$j(document).off("click");e.hide()});e.is(":visible")?e.hide():e.show();b.stopPropagation()});c=$j("#sportsBookWrap").find("#sportsBookHead");ApiSiteType.OW.unique()!=a&&ApiSiteType.SPORTRADAR.unique()!=a||c.find("#sportsBookName").html("Premium "+EventType.getInstanceOf(PageConfig.selectEventType).desc);
c.find("#sportsBookRules").on("click",function(){var b=$j("[id^=sportsBookRulesWrap_"+a+"]"),e="Rules of Premium "+EventType.getInstanceOf(PageConfig.selectEventType).desc;b.find("#sportsbookRulesTitle").html(e);if(ApiSiteType.SPORTRADAR.unique()==a)EventType.TENNIS.value==PageConfig.selectEventType?(b.find("#sportradarTennisRules").show(),b.find("#sportradarCricketRules").hide(),b.find("#sportradarSoccerRules").hide(),b.find("#sportradarKabaddiRules").hide()):EventType.CRICKET.value==PageConfig.selectEventType?
(b.find("#sportradarCricketRules").show(),b.find("#sportradarTennisRules").hide(),b.find("#sportradarSoccerRules").hide(),b.find("#sportradarKabaddiRules").hide()):EventType.SOCCER.value==PageConfig.selectEventType||EventType.E_SOCCER.value==PageConfig.selectEventType?(b.find("#sportradarCricketRules").hide(),b.find("#sportradarTennisRules").hide(),b.find("#sportradarKabaddiRules").hide(),b.find("#sportradarSoccerRules").show()):EventType.KABADDI.value==PageConfig.selectEventType&&(b.find("#sportradarCricketRules").hide(),
b.find("#sportradarTennisRules").hide(),b.find("#sportradarSoccerRules").hide(),b.find("#sportradarKabaddiRules").show());else if(ApiSiteType.OW.unique()==a)if(EventType.TENNIS.value==PageConfig.selectEventType)b.find("#owSoccerRulesContent").hide(),b.find("#owTennisRulesContent").show();else if(EventType.SOCCER.value==PageConfig.selectEventType||EventType.E_SOCCER.value==PageConfig.selectEventType)b.find("#owTennisRulesContent").hide(),b.find("#owSoccerRulesContent").show();b.fadeIn()});I=!0}};SportsBookEventHandler.activeSportsBook=
function(){FullMarketUtil.view("sportsBookBet");SportsBookEventHandler.isShowSportsBook()&&SportsBookEventHandler.initTask(ApiSiteType.SPORTRADAR.unique(),!1);SportsBookEventHandler.isShowOwSportsBook()&&SportsBookEventHandler.initTask(ApiSiteType.OW.unique(),!1);FancyBetMarketHandler.abortTask()};SportsBookEventHandler.isEnableSportsBookBet=function(){return AccountUtil.isEnableSportsBook(PageConfig.isAllowSportsbook,ApiSiteType.SPORTRADAR.unique())&&PageConfig.isOfferSportradarSportsBook};SportsBookEventHandler.isEnableOwSportsBookBet=
function(){return AccountUtil.isEnableSportsBook(PageConfig.isAllowSportsbook,ApiSiteType.OW.unique())&&PageConfig.isOfferOwSportsBook};SportsBookEventHandler.isShowSportsBook=function(){return SportsBookEventHandler.isEnableSportsBookBet()&&PageConfig.hasSportsBookMarkets};SportsBookEventHandler.isShowOwSportsBook=function(){return SportsBookEventHandler.isEnableOwSportsBookBet()&&PageConfig.hasOwSportsBookMarkets};SportsBookEventHandler.isViewMultiMarket=function(){return-1<location.href.indexOf("multiMarkets")};
SportsBookEventHandler.initTask=function(a,c){if(null==SportsBookEventHandler.queryTasks[a]){var d=TaskExecuterV2.createTask(PageConfig.getSportsBookEventTaskCycleTime,0,function(){SportsBookEventHandler.querySportsBookEvent(this,a,c)});d.apiSiteType=a;SportsBookEventHandler.queryTasks[a]=d}else SportsBookEventHandler.queryTasks[a].isStop=!1;d=0;c&&(d=1);SportsBookEventHandler.queryTasks[a].isInit=!0;SportsBookEventHandler.queryTasks[a].version=d;SportsBookEventHandler.queryTasks[a].run();TaskExecuterV2.execute()};
SportsBookEventHandler.abortTask=function(a){null!=SportsBookEventHandler.queryTasks[a]&&SportsBookEventHandler.queryTasks[a].stop()};SportsBookEventHandler.querySportsBookEvent=function(a,c,d){try{var b={eventId:PageConfig.selectEventId,apiSiteType:a.apiSiteType,version:a.version,queryPass:PageConfig.queryPass};if(!a.isInit){var e="",f="";if(!d){var g=z.get(c);if(null!=g&&0!=g.size()){var k=g.keySet();for(d=0;d<k.length;d++){var n=k[d].toString();e+=n+",";var p=g.get(n);null==p&&(p=-1);f+=p+","}}}b.marketIds=
e;b.selectionTsList=f}w(a,b,c)}catch(v){Trace.printStackTrace(v)}finally{a.check(),TaskExecuterV2.execute()}};SportsBookEventHandler.updateSportsBookEvent=function(a,c,d){if(null!=c){var b=c.eventId;var e=$j("#sportsBookWrap"),f=c.eventUpdateDate,g=c.producerUpdateDate,k=c.mappingUpdateDate,n=c.settingUpdateDate,p=c.gameProductUpdateDate;if(e.prop("eventUpdateDate")!=f||e.prop("producerUpdateDate")!=g||e.prop("mappingUpdateDate")!=k||e.prop("settingUpdateDate")!=n||e.prop("gameProductUpdateDate")!=
p){e.prop("eventUpdateDate",f);e.prop("producerUpdateDate",g);e.prop("mappingUpdateDate",k);e.prop("settingUpdateDate",n);e.prop("gameProductUpdateDate",p);f=e.find("#sportsBookHead");g=c.eventId;k=c.eventStatus;n=c.producerStatus;p=c.mappingStatus;var v=c.gameProductStatus,B=EventUtils.isCloseSite(c.closeSite,PageConfig.webSiteType),m=EventUtils.isBookModeShow(c.bookMode,PageConfig.webSiteType);SportsBookEventUtil.isLive(c.live)?f.find("h4").addClass("in-play"):f.find("h4").removeClass("in-play");
SportradarProducerUtil.isDown(n)||SportsBookEventUtil.isHideEvent(k)||B||0==p||GameProductUtils.isClose(v)||!m?(e.hide(),$j("#fancyBetHead").find("#showSportsBookBtn").hide(),PageConfig.isEnableFancyBet&&FullMarketUtil.view("fancyBet")):(SportsBookEventHandler.isShowSportsBook()||SportsBookEventHandler.isShowOwSportsBook())&&J();SportsBookEventUtil.isSuspend(k)?(e=e.find("[id^=sportsBookSuspend_][isActive=1][eventId="+g+"]"),0<e.length&&e.show()):(e=e.find("[id^=sportsBookSuspend_][isActive=1][status="+
SportsBookMarketStatusType.OPEN.unique()+"][eventId="+g+"]"),0<e.length&&e.hide());e={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};f.show();f.find("#minMaxWrap_"+a).show();var u;ApiSiteType.SPORTRADAR.unique()==a&&(u=CurrencyUtil.formatter(c.min,e));ApiSiteType.OW.unique()==a&&(u=CurrencyUtil.formatter(c.min,e)+"/"+CurrencyUtil.formatter(c.max,e));f.find("#minMaxInfo_"+a).html(u);
null==c.rebateRatio||0==c.rebateRatio?(f.find("#rebateRatio_"+a).hide(),f.find("#rebateName_"+a).hide()):(f.find("#rebateRatio_"+a).html(MathUtil.decimal.multiply(c.rebateRatio,100)+"%"),f.find("#rebateRatio_"+a).show(),f.find("#rebateName_"+a).show())}SportsBookEventHandler.isViewMultiMarket()||1!=c.live||PageConfig.hasLiveMatchTracker||PageConfig.useBetfairScores||(u=!1,e=null,c.score?e=JSON.parse(c.score):c.apiSiteCompetitionStatus&&EventType.CRICKET.unique()==PageConfig.selectEventType&&(u=!0,
e=JSON.parse(c.apiSiteCompetitionStatus)),null!=e&&(MemberPage.view("marketLiveScore"),ApiSiteType.SPORTRADAR.unique()==a?(PageConfig.useSportradarScorecard=!0,SportradarScorecardHandler.appendInfo(e,c,u)):ApiSiteType.OW.unique()==a&&(PageConfig.useSportsBookScorecard=!0,OwScorecardHandler.appendInfo(e,c)),UiUtils.appendHeight()));u=c.sportsBookMarket;null!=u&&0!=u.length&&(DataBase.sportsBookMarkets.update(a,b,u),SportsBookEventHandler.isViewMultiMarket()?r(a,b,c,u,!1):t(a,b,c,!1,d))}};SportsBookEventHandler.extandMarket=
function(a){SportsBookEventHandler.isViewMultiMarket()||a.find("[id^=sportsBookMarket_]:visible:lt("+PageConfig.sportsBookMarketExtendNumber+")").each(function(){var c=$j(this);c.removeClass("close");var d=c.prop("id");d=d.substring(d.lastIndexOf("_")+1,d.length);c=c.prop("apiSiteType");h(c,d)})};SportsBookEventHandler.getSelectionKey=function(a,c){return a+"_"+c.eventId+"_"+c.marketId+"_"+c.id};SportsBookEventHandler.removeSelectClass=function(){$j("#overWrap").find("#sportsBookWrap").find("[id^=sportsBookSelection_]").find("#back_1").removeClass("select")};
SportsBookEventHandler.removeSelectClassByMarket=function(a,c,d){var b=$j("#overWrap").find("#sportsBookWrap");a=DataBase.sportsBookMarkets.getEventMarketKey(a,c,d);b=b.find("[id^=sportsBookSelection_][marketPk="+a+"]");b.hide();b.find("#back_1").removeClass("select")}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.sportsBookMarkets={};var w=new HashMap;DataBase.sportsBookMarkets.update=function(h,l,q){l=DataBase.sportsBookMarkets.getEventKey(h,l);h=w.get(l);null==h&&(h=new HashMap,w.put(l,h));for(l=0;l<q.length;l++){var t=q[l],r=h.get(t.id);null==r||null!=t.sportsBookSelection&&0!=t.sportsBookSelection.length||(t.sportsBookSelection=r.sportsBookSelection);h.put(t.id,t)}};DataBase.sportsBookMarkets.getEventKey=function(h,l){return h+"_"+l};DataBase.sportsBookMarkets.getEventMarketKey=function(h,
l,q){return h+"_"+l+"_"+q};DataBase.sportsBookMarkets.queryAll=function(){return w.values()};DataBase.sportsBookMarkets.get=function(h,l,q){h=DataBase.sportsBookMarkets.getEventKey(h,l);h=w.get(h);return null==h?null:h.get(q)};DataBase.sportsBookMarkets.queryMarkets=function(h,l){h=DataBase.sportsBookMarkets.getEventKey(h,l);l=w.get(h);null==l&&(l=new HashMap,w.put(h,l));return l.values()};DataBase.sportsBookMarkets.queryMarketsByBetfairEventId=function(h,l){let q=[];for(let t in w.values()){let r=
w.values()[t].values();if(null!=r&&0!=r.length)for(let F=0;F<r.length;F++){let E=r[F];E.apisite==h&&E.betfairEventId==l&&q.push(E)}}return q};DataBase.sportsBookMarkets.getSelection=function(h,l,q,t){h=DataBase.sportsBookMarkets.get(h,l,q);if(null==h)return null;h=h.sportsBookSelection;if(null==h||0==h.length)return null;for(var r in h)if(null!=h[r]&&h[r].id==t)return h[r];return null}})();

