"undefined"==typeof SportsBookBetHandler&&(SportsBookBetHandler={});
(function(){function w(a,b,d,c,e,l,p){a.find("#placeBet").unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var g=n(a,b,d,c);var f=a.find("#inputStake"),m=parseFloat(f.val())||0,k=DataBase.sportsBookBet.get(b,d,c,e),x="",u=h(k);if(!u){var v=DataBase.sportsBookMarkets.get(k.apiSiteType,k.eventId,k.marketId);k=v.min;v=v.max;k&&v||Trace.log(I18N.get("msg.error.validation.minMaxBetIsNotValid"));m<k?(f.val(k),DataBase.sportsBookBet.updateStake(b,d,c,e,k),
x+=I18N.get("msg.member.minBet")):m>v&&(f.val(v),DataBase.sportsBookBet.updateStake(b,d,c,e,v),x+=I18N.get("msg.member.maxBet"))}""==x||u||r(g,"warning",x,!0);SportsBookBetHandler.getExposure(b,d,c);u?(k=DataBase.sportsBookBet.getForBet(b,d,c,e),f=$j("#sportsBookBetBar_"+l),0==f.length&&(f=$j("#overWrap").find("#sportsBookTemplateTable").find("#sportsBookBetBarTemplate").clone(),f.prop("id","sportsBookBetBar_"+l),a.after(f)),m=a.find("#sportsBookAcceptAnyOdds").is(":checked")?1:0,SportsBookBetHandler.submitBet(k,
b,m,f,g),a.hide()):a.find("#placeBet").removeClass("disable")}});a.find("#cancel").unbind("click").click(function(){DataBase.sportsBookBet.clear();a.hide();SportsBookEventHandler.removeSelectClass();SportsBookBetHandler.getExposure(b,d,c)});a.find("#inputStake").click(function(){a.find("#inputStake").select()});a.find("#inputStake").change(function(){var g=parseFloat(a.find("#inputStake").val())||0;n(a,b,d,c);g=DataBase.sportsBookBet.updateStake(b,d,c,e,g);SportsBookBetHandler.eventCalculate(a,b,
d,c,e,g)});a.find("#inputStake").blur(function(){CoinHandler.hideStakePopupList();var g=parseFloat(a.find("#inputStake").val())||0;n(a,b,d,c);g=DataBase.sportsBookBet.updateStake(b,d,c,e,g);SportsBookBetHandler.eventCalculate(a,b,d,c,e,g)});a.find("#inputStake").keydown(function(g){var f=g.which;KeyEventUtils.isNumberKey(g)||KeyEventUtils.isBackspaceKey(f)||KeyEventUtils.isDeleteKey(f)||KeyEventUtils.isArrowKey(f)||KeyEventUtils.isTabKey(f)||KeyEventUtils.isEnterKey(f)||WindowEventUtil.stopEvent(g)});
a.find("#inputStake").keyup(function(g){$j(this).val(function(m,k){return StringUtil.commaSeparateNumber(k)});var f=parseFloat(a.find("#inputStake").val())||0;n(a,b,d,c);f=DataBase.sportsBookBet.updateStake(b,d,c,e,f);SportsBookBetHandler.eventCalculate(a,b,d,c,e,f);g=g.which;KeyEventUtils.isEnterKey(g)&&a.find("#placeBet").click();KeyEventUtils.isTabKey(g)&&a.find("#inputStake").is(":focus")&&a.find("#inputStake").select()});if(ApiSiteType.OW.unique()==b)a.find("#getSportsBookMaxStakeBtn").hide();
else if(ApiSiteType.SPORTRADAR.unique()==b)a.find("#getSportsBookMaxStakeBtn").off("click").on("click",function(){SportsBookBetHandler.getSportsBookMaxStake(a,p)})}function h(a){if(null==a)return!1;var b=DataBase.sportsBookMarkets.get(a.apiSiteType,a.eventId,a.marketId);if(null==b)return!1;var d=b.min;b=b.max;if(!d||!b)return!1;a=parseFloat(a.stake||"0");return a<d||a>b?!1:!0}function q(a,b,d){var c=d.find("#progressBar"),e=t(a,b);c.css("width",e);d.find("#secRemain").html(MathUtil.decimal.divide(a,
10)+" sec remaining…");0<a&&(a--,setTimeout(function(){q(a,b,d)},100))}function t(a,b){a=MathUtil.decimal.subtract(b,a);b=MathUtil.decimal.divide(a,b);1<b&&(b=1);b=MathUtil.decimal.multiply(b,100);return Math.round(b)+"%"}function n(a,b,d,c){var e=$j("#overWrap").find("#sportsBookBetMessage_"+(b+"_"+d+"_"+c));0==e.length&&(e=$j("#overWrap").find("#sportsBookTemplateTable").find("#sportsBookBetMessageTemplate").clone(),e.prop("id","sportsBookBetMessage_"+(b+"_"+d+"_"+c)));a.after(e);return e}function r(a,
b,d,c,e,l){e=a.find("#header");a.find("#info").contents().filter(function(){return 3==this.nodeType}).remove();a.find("#classWrap").removeClass("success").removeClass("error").removeClass("warning").addClass(b);null!=d&&e.html(d);null!=l&&(d=l.stake,b=CurrencyType.getInstanceOf(PageConfig.playerCurrency),d=b.name+b.symbol+d+" at odds "+l.odds,CurrencyUtil.updateSetting({currencySymbol:b.symbol}),d=d+" Profit: "+UnMatchTicketUtil.getPL(l.odds,l.stake),e.html("Bet Matched"),e.after(d));a.find("#close").unbind("click").click(function(){a.fadeOut()});
c&&setTimeout(function(){a.fadeOut()},3E3);a.fadeIn()}SportsBookBetHandler.appendBoard=function(a,b,d,c,e,l,p){SportsBookBetHandler.clearBoard();var g=DataBase.sportsBookBet.generateKey(b,c,e,l),f=DataBase.sportsBookMarkets.getSelection(b,c,e,l);if(null!=f){var m=a.prop("handicap");d=DataBase.sportsBookBet.add(b,d,c,e,l,p,f.selectionName,f.betfairEventId,m);p=!1;f=$j("#overWrap");m=f.find("#sportsBookBetBoard_"+g);if(0==m.length){f=f.find("#sportsBookTemplateTable").find("#sportsBookBetTemplate").clone();
m=f.find("#sportsBookBetHeader");var k=f.find("#oddsHeader");f.prop("id","sportsBookBetBoard_"+g);f.prop("eventId",c);f.prop("marketId",e);f.prop("selectionId",l);f.prop("apiSiteType",b);f.attr("marketPk",DataBase.sportsBookMarkets.getEventMarketKey(b,c,e));m.find("#gameTypeName").before(" "+d.selectionName+" ");k.find("#odds").html(d.odds);w(f,b,c,e,l,g,d);m=f}m.find("#sportsBookAcceptAnyOdds").prop("checked",TopMenuHandler.isAcceptAnyOdds("sportsBook"));UiUtils.removeContents(m.find("#sportsBookMaxStake"));
g=m;a.after(g.fadeIn());g.find("#odds").html(d.odds);null!=PageConfig.userCoin&&0<PageConfig.userCoin?(a=DataBase.sportsBookMarkets.get(b,c,e),d=parseFloat(PageConfig.userCoin),a.min&&parseFloat(a.min)>PageConfig.userCoin&&(d=parseFloat(a.min)),g.find("#inputStake").val(d),p=DataBase.sportsBookBet.updateStake(b,c,e,l,d)):g.find("#inputStake").val("");n(g,b,c,e);SportsBookBetHandler.eventCalculate(g,b,c,e,l,p);g.find("#odds").select();SportsBookBetHandler.updateExposure();CoinHandler.showSportsBookBetCoin(g)}};
SportsBookBetHandler.clearBoard=function(){var a=$j("#sportsBookWrap"),b=a.find("[id^=sportsBookBetBoard_]");$j.each(b,function(d,c){c=a.find(c);0<c.length&&(c.prop("eventId"),c.prop("marketId"),c.prop("selectionId"),c.hide())});DataBase.sportsBookBet.clear()};SportsBookBetHandler.removeBoardByMarket=function(a,b,d){var c=$j("#sportsBookWrap"),e=DataBase.sportsBookMarkets.getEventMarketKey(a,b,d);c.find("[id^=sportsBookBetBoard_][marketPk="+e+"]").hide();DataBase.sportsBookBet.removeByMarket(a,b,
d);SportsBookBetHandler.getExposure(a,b,d)};SportsBookBetHandler.resetAllBetBoard=function(){$j("#sportsBookWrap").find("[id^=sportsBookBetBoard_]").hide();SportsBookEventHandler.removeSelectClass();SportsBookBetHandler.updateExposure()};SportsBookBetHandler.eventCalculate=function(a,b,d,c,e,l){e=DataBase.sportsBookBet.get(b,d,c,e);e=h(e);a=a.find("#placeBet");e?a.removeClass("disable"):a.addClass("disable");SportsBookBetHandler.getExposure(b,d,c)};SportsBookBetHandler.submitBet=function(a,b,d,c,
e,l){var p=0,g=0;$j.ajax({type:"POST",dataType:"JSON",url:PageConfig.landingPath+"/member/playerService/sportsBookBet",data:{sportsBookBets:JSON.stringify([a]),isOneClickBet:l,isAcceptAnyOdds:d,apiSiteType:b},beforeSend:function(){if(null!=c){c.show();c.find("#secRemain").empty();var f=MathUtil.decimal.multiply(5,10),m=""+MathUtil.decimal.multiply(5,10);0<=f&&q(f,m,c)}},complete:function(){},success:function(f){try{if(f.error)null!=e?r(e,"error",f.error,!0):NoticeHandler.error(f.error);else if(0!=
f.result.length){for(var m in f.result){var k=f.result[m];"SUCCESS"==k.status?(0==p&&0==g&&(p=k.eventId,g=k.marketId),null!=k.unMatchTicket&&DataBase.sportsBookUnMatchTicket.update([k.unMatchTicket]),null!=k.txn&&(DataBase.sportsBookTxn.update([k.txn]),null!=e&&r(e,"success",null,!0,"txn",k.txn))):k.error&&(null!=e?r(e,"error",k.error,!0):NoticeHandler.error(k.error))}0!=p&&""!=g&&(f="",ApiSiteType.SPORTRADAR.unique()==b&&(f=CategoryType.SPORTRADAR_SPORTSBOOK.unique()),ApiSiteType.OW.unique()==b&&
(f=CategoryType.OW_SPORTSBOOK.unique()),TxnHandler.setEventIdAndMarketId(p,g,f),p=0,g="");TxnHandler.updateOpenBetSelectionBox();TxnHandler.checkToHideOpenBets();var x=BetHandler.calculateTotalLiability();JsCache.get("#betSlipFullBtn").find("#total").html(CurrencyUtil.formatter(x))}}catch(u){Trace.printStackTrace(u)}finally{null!=c&&(c.hide(),c.remove()),SportsBookEventHandler.removeSelectClass(),DataBase.sportsBookBet.clear(),SportsBookBetHandler.getExposure(a.apiSiteType,a.eventId,a.marketId)}},
error:function(f){Trace.printStackTrace(f);null!=c&&(c.hide(),c.remove())}});JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()};SportsBookBetHandler.getExposure=function(a,b,d){try{if(ExposureUtil.isEnableShowSportsBookExposure(a,PageConfig.ENABLE_SHOW_SPORTRADAR_SPORTSBOOK_FORECAST,PageConfig.ENABLE_SHOW_OW_SPORTSBOOK_FORECAST)){var c=DataBase.sportsBookMarkets.get(a,b,d);if(null==c)Trace.printStackTrace("SportsBook market "+d+" is null");else{if(ApiSiteType.SPORTRADAR.unique()==
a){var e=SportradarMarketType.getInstanceOf(c.eventType,c.apiSiteMarketId);if(null==e||!e.isNeedForecast)return}var l=c.sportsBookSelection;if(null==l)Trace.printStackTrace("sportsBookSelections "+d+" is null");else{var p=DataBase.sportsBookBet.getByMarketId(a,b,d),g=DataBase.sportsBookUnMatchTicket.getByMarketId(b,d,null,CategoryType.SPORTRADAR_SPORTSBOOK.unique()),f=DataBase.sportsBookTxn.getByMarketId(b,d+"",null,null,CategoryType.SPORTRADAR_SPORTSBOOK.unique());if(0!=p.length||0!=g.length||0!=
f.length){var m=ExposureUtil.calculateSportsBookExposure(a,b,d,c.numberOfWinner,c.numberOfActiveRunners,p,f);var k=$j("#sportsBookWrap").find("#sportsBookMarket_"+DataBase.sportsBookMarkets.getEventMarketKey(a,b,d));if(0!=k.length){var x=WebSiteType.getInstanceOf(PageConfig.webSiteType),u={precision:2,separateSign:",",currencySymbol:CurrencyType.getInstanceOf(PageConfig.playerCurrency).symbol,formatter:CurrencyUtil.DefaultFormatter,"trailingZeros,":!1};x.isFancyFairGroup()&&(u.precision=0,u.roundingMode=
"DOWN");for(var v in l){var A=l[v],C=k.find("#sportsBookSelection_"+SportsBookEventHandler.getSelectionKey(a,A));if(0!=C.length){var y=C.find("#before"),z=C.find("#after");if(m.exposureBeforeBet){var D=m.exposureBeforeBet.betSelections;c=0;c=null==D[A.id]?D[0].minExposure:D[A.id].minExposure;y.removeClass();0<=parseFloat(c)?y.addClass("win"):y.addClass("lose");y.html(CurrencyUtil.formatter(c,u));y.show()}else y.hide();if(m.exposureAfterBet){var E=m.exposureAfterBet.betSelections;c=0;c=null==E[A.id]?
E[0].minExposure:E[A.id].minExposure;z.removeClass();0<=parseFloat(c)?z.addClass("to-win"):z.addClass("to-lose");z.html(CurrencyUtil.formatter(c,u));z.show()}else z.hide()}}}}var F=$j("#sportsBookWrap").find("#sportsBookMarket_"+DataBase.sportsBookMarkets.getEventMarketKey(a,b,d));if(0!=F.length){var B=F.find("[id^=sportsBookSelection_]"),G=DataBase.sportsBookBet.getByMarketId(a,b,d),H=DataBase.sportsBookTxn.getByMarketId(b,d+"",null,null,CategoryType.SPORTRADAR_SPORTSBOOK.unique());0<G.length?B.find("#after").show():
B.find("#after").hide();0<H.length?B.find("#before").show():B.find("#before").hide()}}}}}catch(I){Trace.printStackTrace(I)}};SportsBookBetHandler.updateExposure=function(){if(PageConfig.ENABLE_SHOW_SPORTRADAR_SPORTSBOOK_FORECAST||PageConfig.ENABLE_SHOW_OW_SPORTSBOOK_FORECAST){var a=$j("#sportsBookWrap");if(0!=a.length&&a.is(":visible")){var b=a.find("[id^=sportsBookMarket_]:visible");if(0!=b.length)for(var d in b){var c=a.find(b[d]),e=c.prop("eventId"),l=c.prop("marketId"),p=c.prop("apiSiteType");
if(0==c.length||null==e||null==l)break;SportsBookBetHandler.getExposure(p,e,l)}}}};SportsBookBetHandler.getSportsBookMaxStake=function(a,b){var d=a.find("#sportsBookAcceptAnyOdds").is(":checked")?1:0,c=DataBase.sportsBookMarkets.get(b.apiSiteType,b.eventId,b.marketId),e=b.stake;null!=e&&0!=e||null==c||(e=null==c.min?1:c.min);var l=n(a,b.apiSiteType,b.eventId,b.marketId);SportsBookMarketUtil.getSportsBookMaxStake(b.apiSiteType,b.eventType,b.eventId,b.marketId,b.selectionId,b.odds,e,b.betfairEventId,
d,function(p){try{var g=p.sportsBookMaxStake,f=a.find("#sportsBookMaxStake");UiUtils.removeContents(f);f.find("#getSportsBookMaxStakeBtn").after(g);p.error&&(null!=l?r(l,"error",p.error,!0):NoticeHandler.error(p.error))}catch(m){Trace.printStackTrace(m)}})}})();"undefined"==typeof DataBase&&(DataBase={});
(function(){DataBase.sportsBookBet={};var w=new HashMap;DataBase.sportsBookBet.add=function(h,q,t,n,r,a,b,d,c){q={apiSiteType:h,eventType:q,eventId:t,marketId:n,selectionId:r,odds:a,selectionName:b,betfairEventId:d,handicap:c};h=DataBase.sportsBookBet.generateKey(h,t,n,r);w.put(h,q);return q};DataBase.sportsBookBet.generateKey=function(h,q,t,n){return h+"_"+q+"_"+t+"_"+n};DataBase.sportsBookBet.get=function(h,q,t,n){h=DataBase.sportsBookBet.generateKey(h,q,t,n);return w.get(h)};DataBase.sportsBookBet.remove=
function(h,q,t,n){h=DataBase.sportsBookBet.generateKey(h,q,t,n);return w.remove(h)};DataBase.sportsBookBet.removeByMarket=function(h,q,t){var n=DataBase.sportsBookBet.getByMarketId(h,q,t);$j.each(n,function(r){r=n[r];if(null==r)return!0;DataBase.sportsBookBet.remove(r.apiSiteType,r.eventId,r.marketId,r.selectionId)})};DataBase.sportsBookBet.queryAll=function(){return w.values()};DataBase.sportsBookBet.clear=function(){w.clear()};DataBase.sportsBookBet.updateStake=function(h,q,t,n,r){var a=!1;h=DataBase.sportsBookBet.get(h,
q,t,n);if(null!=h){if(null==h.stake||null!=h.stake&&h.stake!=r)a=!0;h.stake=r;return a}};DataBase.sportsBookBet.getForBet=function(h,q,t,n){h=DataBase.sportsBookBet.get(h,q,t,n);return{apiSiteType:h.apiSiteType,eventType:h.eventType,eventId:h.eventId,marketId:h.marketId,selectionId:h.selectionId,odds:h.odds,stake:h.stake,betfairEventId:h.betfairEventId,handicap:h.handicap,timestamp:(new Date).getTime()}};DataBase.sportsBookBet.getByMarketId=function(h,q,t){var n=[];$j.each(w.values(),function(r,a){q==
a.eventId&&t==a.marketId&&n.push(a)});return n}})();

