"undefined"==typeof StreamingHandler&&(StreamingHandler={});
(function(){function l(){document.webkitFullscreenElement?$j("#fullScreen").attr("class","btn-collapse"):$j("#fullScreen").attr("class","btn-fullscreen")}function m(b,c){Trace.error("Id:["+b+"] HLS on Error:["+c+"] to do change line!!");null!=a.playerObj&&StreamingUtil.changeLine(a,PageConfig.webSiteType,PageConfig.userID,d,e)}function h(){if(a.playerObj){a.initStreaming&&clearTimeout(a.initStreaming);var b=$j("#tv-wrap");a.video=$j("#video");$j(a.video).attr("height",$j(b).height());$j(a.video).attr("width",
$j(b).width());StreamingUtil.setPlayerChannel(a,PageConfig.webSiteType,PageConfig.userID,d,a.channel,a.eventType,e)}else a.initStreaming=setTimeout(function(){h()},100)}function e(){$j("#tvLine").html(a.urlIndex+1)}function f(b){b?($j("#closeStreamingBox").fadeIn(),$j("#mute").fadeIn(),$j("#changeLineBtn").fadeIn(),$j("#fullScreen").fadeIn()):($j("#closeStreamingBox").fadeOut(),$j("#mute").fadeOut(),$j("#changeLineBtn").fadeOut(),$j("#fullScreen").fadeOut())}var a={},d={};a.urlIndex=0;a.playUrlObjList=
[];var g=null;StreamingHandler.init=function(){a.playUrlObjList=StreamingUtil.getPlayUrlObjList(PageConfig.country);d=StreamingUtil.setJblChannelObj("Desktop",PageConfig.country,PageConfig.jblChannelId);$j("#openStreaming, #lmtOpenStreaming").on("click",function(){$j("#lmtOpenStreaming").hide();$j("#openStreaming").hide();"undefined"!=typeof LoginHandler&&!LoginHandler.userIsLogin()||null==PageConfig.streamingChannel||"null"==PageConfig.streamingChannel||"0"==PageConfig.streamingChannel||(null==a.playerObj?
(StreamingHandler.openStreamingBox(PageConfig.streamingChannel,PageConfig.selectEventType),PageConfig.userCloseStreaming=!1):$j("#closeStreamingBox").click(),setTimeout(function(){$j("#lmtOpenStreaming").show();$j("#openStreaming").show()},700))});$j("#closeStreamingBox").on("click",function(){StreamingHandler.closeStreamingBox();PageConfig.userCloseStreaming=!0;document.webkitFullscreenElement&&document.exitFullscreen()});$j("#changeLineBtn").on("click",function(){StreamingUtil.changeLine(a,PageConfig.webSiteType,
PageConfig.userID,d,e)});$j("#tv-wrap").on("mouseenter",function(){f(!0)});$j("#tv-wrap").on("mouseleave",function(){f(!1)});$j("#mute").on("click",function(){a.mute?StreamingUtil.mute(a,!1):StreamingUtil.mute(a,!0)});$j("#fullScreen").on("click",function(){const b=document.getElementById("tv");document.webkitFullscreenElement?document.exitFullscreen():b.webkitRequestFullScreen()});document.addEventListener("webkitfullscreenchange",l);StreamingHandler.hideTvControl()};StreamingHandler.update=function(b,
c,n){var k=$j("#tv-wrap");k&&(k.fadeIn(),a.playerObj||StreamingUtil.initPlayerObj(a,b,c,n,m,h,PageConfig.userID,PageConfig.JblName,d),a.playerObj&&b&&a.channel!=b&&(StreamingUtil.setPlayerChannel(a,PageConfig.webSiteType,PageConfig.userID,d,b,c,e),a.channel=b,a.eventType=c,StreamingUtil.setPlayerMaxSeekSec(a)),a.mute?$j("#mute").attr("class","btn-volume_off"):$j("#mute").attr("class","btn-volume_on"))};StreamingHandler.openStreamingBox=function(b,c){PageConfig.hasAccount?($j("#lmtOpenStreaming").show(),
$j("#openStreaming").show(),$j("#lmtOpenStreaming").addClass(" close_tv"),$j("#openStreaming").addClass(" close_tv"),$j("#tv-wrap").fadeIn(),null!=b&&null!=c&&StreamingHandler.update(b,c),b=$j("#video"),b.autoplay=!0,b.load()):$j("#tv-wrap").fadeOut()};StreamingHandler.closeStreamingBox=function(){$j("#tv-wrap").fadeOut();$j("#lmtOpenStreaming").removeClass(" close_tv");$j("#openStreaming").removeClass(" close_tv");StreamingUtil.stopVideo(a)};StreamingHandler.hideTvControl=function(){f(!0);null!=
g&&clearTimeout(g);g=setTimeout(function(){f(!1)},5E3)}})();

