"undefined"==typeof AnnouncementUtilHandler&&(AnnouncementUtilHandler={});"undefined"==typeof PageCommonConfig&&(PageCommonConfig={});
(function(){function k(f){if("undefined"!=typeof PageConfig.enableQueryDataSubdomain){var h=PageConfig.enableQueryDataSubdomain;var g=PageConfig.queryPass}else h=PageCommonConfig.enableQueryDataSubdomain,g=PageCommonConfig.queryPass;var d=(h&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+AnnouncementUtilHandler.getUrl()+"getActiveAnnouncement";$j.ajax({type:"POST",dataType:"JSON",url:d,data:{pageNumber:1,pageSize:100,queryPass:g},xhrFields:{withCredentials:!0},success:function(c){try{isEqual(f.oldAnnouncement,
c.resultList)||($content=$j(".marquee"),$content.empty(),$j.each(c.resultList,function(a,b){$content.append("<a><span>"+DateUtil.format(b.publishDate,"dd MMM yyyy")+"</span>"+b.message+"</a>")}),f.oldAnnouncement=c.resultList,$j(".marquee").find("a").click(function(){"player"==PageCommonConfig.announcementPageType?($j("#announcementPopUp").css("display","flex"),AnnouncementUtilHandler.initAllAnnouncementPage()):window.open(PageConfig.allAnnouncementPagePath,"_blank",config="height=640,width=880,location=no")}),
$j(".marquee").marquee({duration:16E3,gap:0,delayBeforeStart:0,direction:"left",duplicated:!1}))}catch(a){Trace.printStackTrace(a)}finally{f.check(),TaskExecuterV2.execute()}},error:function(){h&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);f.check();TaskExecuterV2.execute()}})}AnnouncementUtilHandler.listAnnouncement=function(f){var h=(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?
QueryDataSubDomainUtil.queryHost:"")+AnnouncementUtilHandler.getUrl()+"getActiveAnnouncement";$j.ajax({type:"POST",dataType:"JSON",url:h,data:{pageNumber:f,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:function(g){try{PageHandler.init(g.currentPage,g.totalPage,function(c){AnnouncementUtilHandler.listAnnouncement(c)});PageHandler.pageList();var d=$j("#announcementContent");d.empty();$j.each(g.resultList,function(c,a){var b=JsCache.get("#announcementTemplate").clone();b.find("#date").attr("id",
"date_"+c).html(DateUtil.format(a.publishDate,"dd"));b.find("#month").attr("id","month_"+c).html(DateUtil.format(a.publishDate,"MMM"));b.find("#year").attr("id","year_"+c).html(DateUtil.format(a.publishDate,"yyyy"));b.find("#textByLanguageType").attr("id","textByLanguageType_"+c).html(a.message);d.append(b)});0==g.resultList.length?($j("#announcementContent").addClass("nofound"),d.append(JsCache.get("#announcementNotFound").clone())):$j("#announcementContent").removeClass("nofound")}catch(c){Trace.printStackTrace(c)}finally{}},
error:function(){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0)}})};AnnouncementUtilHandler.search=function(f,h){var g={};g.publishDate=$j("#searchDateStr").val().trim();g.pageNumber=f;"manager"==PageConfig.announcementPageType&&(g.status=$j("#status").val());$j.ajax({type:"POST",dataType:"JSON",url:AnnouncementUtilHandler.getUrl()+"queryAnnouncement",data:g,
beforeSend:function(){},complete:function(){h&&h()},success:function(d){if(d)if(d.error)alert(d.error);else{PageHandler.init(d.currentPage,d.totalPage,function(a){AnnouncementUtilHandler.search(a)});PageHandler.pageList();var c=$j("#announcementContent");c.empty();$j.each(d.resultList,function(a,b){a=b.id;var e=JsCache.get("#announcementTemplate").clone();e.find("#id").attr("id","id_"+a).html(a);e.find("#status").attr("id","status_"+a).html(AnnouncementStatusType.getInstanceOf(b.status).name);e.find("#receiverType").attr("id",
"receiverType_"+a).html(AnnouncementReceiverType.getInstanceOf(b.receiverType).name1);e.find("#publishDate").attr("id","publishDate_"+a).html(b.publishDate);e.find("#updateDate").attr("id","updateDate_"+a).html(b.updateDate);e.find("#durationHr").attr("id","durationHr_"+a).html(b.durationHr+" hr");e.find("#creator").attr("id","creator_"+a).html(b.creator);e.find("#updator").attr("id","updator_"+a).html(b.updator);e.prop("id",a);e.prop("status",b.status);"manager"==PageConfig.announcementPageType&&
AnnouncementHandler.bindButton(e,b.id,b.status);e.find("#englishText").attr("id","englishText_"+a).html(b.englishText.replace(/<[^>]*>/g,""));c.append(e)})}},error:function(d,c,a){Trace.log(d.status);Trace.log(a)}})};AnnouncementUtilHandler.initPlayerAnnouncementPage=function(){AnnouncementUtilHandler.initAnnouncementTask();UiUtils.appendHeight()};AnnouncementUtilHandler.showAnnouncementTask=null;AnnouncementUtilHandler.initAnnouncementTask=function(){if(AnnouncementUtilHandler.isLogin()){if(null==
AnnouncementUtilHandler.showAnnouncementTask){var f=TaskExecuterV2.createTask(60,0,function(){k(this)});AnnouncementUtilHandler.showAnnouncementTask=f}else AnnouncementUtilHandler.showAnnouncementTask.isStop=!1;AnnouncementUtilHandler.showAnnouncementTask.run();TaskExecuterV2.execute()}else $j(".marquee-box").hide()};AnnouncementUtilHandler.initAllAnnouncementPage=function(){AnnouncementUtilHandler.listAnnouncement(1)};AnnouncementUtilHandler.getUrl=function(){return"player"==PageCommonConfig.announcementPageType?
PageCommonConfig.ajaxPath:PageConfig.ajaxPath};AnnouncementUtilHandler.isLogin=function(){return"undefined"!=typeof PageConfig.userName||PageConfig.hasAccount||"undefined"!=typeof PageCommonConfig.hasAccount&&PageCommonConfig.hasAccount}})();var isEqual=function(k,f){return JSON.stringify(k)===JSON.stringify(f)};

