var CDN_TYPE={_WANGSU:"wansu",_GRIFFINMAS:"griffinmas",_AKAMAI:"akamai",_ERROR:-999};
class StreamPlayer{constructor(a,b,c){this.Version="v 024.07.11.01T";this.HLSObj=null;this.debug=b?b:!1;this.isMonitor=c?c:!1;this.options=a?a:{};console.log("Player Version: "+this.Version);this.lastSoundState=this.playState=null;this.lastclientTime=this.lastBufferd=this.lastCurrent=0;this.lastbase="";this.chkPlayBackTimes=this.chkBasetimes=this.chkLoadErrorTimes=this.chkSeekTimes=this.chkReadyStateTimes=this.chkBufferdTimes=this.chkCurrentTimes=0;this.chkBase="";this.hlsSupport=Hls.isSupported();
this.iOS=!!navigator.platform&&/iPad|iPhone|iPod/.test(navigator.platform);this.userAgent=navigator.userAgent;this.linePart=0;this.m3u8Url=this.errDetails="";this.delayTime=this.currentTime=this.readyState=this.bufferTime=0;this.varObj={};this.varObj.maxMaxBufferLength=500;this.varObj.maxBufferSize=5E7;this.varObj.fragLoadingMaxRetry=1;this.varObj.manifestLoadingMaxRetry=1;this.varObj.levelLoadingMaxRetry=0;this.varObj.liveSyncDurationCount=3;this.varObj.liveMaxLatencyDurationCount=4;this.varObj.initialLiveManifestSize=
1;this.varObj.forceKeyFrameOnDiscontinuity=!0;this.varObj.enableWebVTT=!1;this.varObj.enableCEA708Captions=!1;this.varObj.playerObject=this;this.varObj.wasmUrl=a.wasmUrl;this.todoErrorHint=!1;this.rateOffset="undefined"!=typeof this.options.rateOffset?this.options.rateOffset:0;this.autoSwitch="undefined"!=typeof this.options.autoSwitch?this.options.autoSwitch:!0;this.defaultMuted="undefined"!=typeof this.options.defaultMuted?this.options.defaultMuted:!0;this.maxChkCurrentTimes="undefined"!=typeof this.options.maxChkCurrentTimes?
this.options.maxChkCurrentTimes:2;this.maxChkBufferdTimes="undefined"!=typeof this.options.maxChkBufferdTimes?this.options.maxChkBufferdTimes:5;this.maxChkReadyStateTimes="undefined"!=typeof this.options.maxChkReadyStateTimes?this.options.maxChkReadyStateTimes:5;this.maxChkSeekTimes="undefined"!=typeof this.options.maxChkSeekTimes?this.options.maxChkSeekTimes:2;this.maxDelaySec="undefined"!=typeof this.options.maxDelaySec?this.options.maxDelaySec:8;this.errorSendBack="undefined"!=typeof this.options.errorCallBack?
this.options.errorCallBack:null;this.doInfo=-1;this.iNowNetErrorErrorCnt=0;this.RegId="undefined"!=typeof this.options.RegId?this.options.RegId:(new Date).getTime();this.bIsFirstPlayHint=!1;this.TotalChangeLineCnt=this.iErrorTotalCnt=0;this.MaxTotalChangeLineCnt=10;this.DelayStartTime=0;this.MaxDelayTimeGap=60}InitConnect(a,b,c,f){this.Stop();this.showLogs("Player InitConnect");var d=this;this.init=!0;this.bIsFirstPlayHint=!1;this.vUrl=b;this.linePart=c;this.chkLoadErrorTimes=0;this.resetVar();-1!=
this.doInfo&&(clearInterval(this.doInfo),this.doInfo=-1);this.doInfo=setInterval(this.info.bind(this),1E3);"undefined"!==typeof f&&(this.maxDelaySec=this.options.maxDelaySec=f);if(null==this.videoElm)if(this.videoElm=document.getElementById(a),this.videoElm.defaultMuted=this.defaultMuted,this.lastSoundState=this.videoElm.muted=this.defaultMuted,this.addTimedMetadataEvent(),!0===this.hlsSupport)this.HLSObj=new Hls(this.varObj),console.log("HLS Version:["+Hls.version+"]"),this.SetPloader(),this.HLSObj.startPosition=
0,this.hlsEvent();else for(this.videoElm.crossorigin="use-credentials",this.videoElm.addEventListener("play",function(){d.showLogs("ElementEvent play")}),this.videoElm.addEventListener("loadstart",function(){d.showLogs("ElementEvent loadstart");var e=new XMLHttpRequest;e.onreadystatechange=function(){4==e.readyState&&200==e.status&&d.m3u8URLParse(e.responseText)};e.open("GET",d.vUrl,!0);e.send(null)}),this.videoElm.addEventListener("error",function(e){d.showLogs("Error code: "+e.currentTarget.error.code);
e.currentTarget.error.message&&d.showLogs("Error message: "+e.currentTarget.error.message);d.showLogs("Error loading: "+d.vUrl);4===e.currentTarget.error.code&&(d.showLogs("call restart"),d.restart())}),this.videoElm.addEventListener("loadedmetadata",function(){d.showLogs("ElementEvent loadedmetadata")}),a=0;a<this.videoElm.textTracks.length;a++)"hidden"!=this.videoElm.textTracks[a].mode&&(this.videoElm.textTracks[a].mode="hidden");else this.videoElm.defaultMuted=this.lastSoundState,this.videoElm.muted=
this.lastSoundState;!0===this.hlsSupport?(null!==this.playState?(this.showLogs("============= Restart Now ==============="),this.restart()):(this.HLSObj.loadSource(this.vUrl),this.HLSObj.attachMedia(this.videoElm),this.showLogs(this.vUrl)),this.todoErrorHint=!1):(this.todoErrorHint=!1,null!==this.playState?(this.showLogs("============= Restart Now ==============="),this.restart()):(this.videoElm.src=this.vUrl,this.videoElm.play(),this.playState=!0,this.init=!1))}addTimedMetadataEvent(){var a=this;
this.videoElm.textTracks.addEventListener("addtrack",function(b){a.showLogs("textTracks: "+b.track.kind);"metadata"===b.track.kind&&(b.track.mode="hidden",b.track.addEventListener("cuechange",function(c){c=c.currentTarget.activeCues[c.currentTarget.activeCues.length-1];try{a.timedMeta=c.value.info}catch(f){a.timedMeta=null}null!=a.timedMeta&&(a.timedMetaTime=new Date(parseInt(a.timedMeta)))}))})}restart(){!1===this.init&&!0===this.autoSwitch?(this.linePart=0==this.linePart?1:0,this.errDetails="switch,"+
this.linePart):(this.iNowNetErrorErrorCnt=0,!0===this.hlsSupport?(null!==this.HLSObj&&this.HLSObj.destroy(),this.playState=!1,this.HLSObj=new Hls(this.varObj),this.SetPloader(),this.hlsEvent(),this.HLSObj.loadSource(this.vUrl),this.HLSObj.attachMedia(this.videoElm)):(this.Pause(),this.playState=!1,this.videoElm.removeAttribute("src"),this.videoElm.src="",this.videoElm.src=this.vUrl,this.videoElm.play(),this.playState=!0,this.init=!1),-1!=this.doInfo&&(clearInterval(this.doInfo),this.doInfo=-1),this.resetVar(),
this.doInfo=setInterval(this.info.bind(this),1E3),this.showLogs(this.vUrl))}hlsEvent(){var a=this;this.HLSObj.on(Hls.Events.MEDIA_ATTACHED,function(){a.showLogs("MEDIA_ATTACHED");a.init=!1});this.HLSObj.on(Hls.Events.LEVEL_SWITCHING,function(b,c){a.showLogs("LEVEL_SWITCHING")});this.HLSObj.on(Hls.Events.MEDIA_DETACHED,function(){a.showLogs("MEDIA_DETACHED")});this.HLSObj.on(Hls.Events.MANIFEST_PARSED,function(){a.showLogs("MANIFEST_PARSED")});this.HLSObj.on(Hls.Events.LEVEL_LOADED,function(b,c){b=
(new Date).getTime();if(!0===a.playState&&(0==a.lastclientTime||2E3<b-a.lastclientTime)){a.chkBase=btoa(c.networkDetails.responseText);a.chkBase===a.lastbase?++a.chkBasetimes:a.chkBasetimes=0;if(5<=a.chkBasetimes){a.restart();return}a.lastclientTime=b}a.lastbase=a.chkBase});this.HLSObj.on(Hls.Events.INIT_PTS_FOUND,function(b,c){a.showLogs("INIT_PTS_FOUND")});this.HLSObj.on(Hls.Events.FRAG_PARSING_INIT_SEGMENT,function(b,c){a.showLogs("FRAG_PARSING_INIT_SEGMENT");!1===a.todoErrorHint?(a.videoElm.play(),
a.playState=!0,a.showLogs("start play")):(a.HLSObj.destroy(),a.showLogs("do destory"))});this.HLSObj.on(Hls.Events.FRAG_CHANGED,function(b,c){});this.HLSObj.on(Hls.Events.FRAG_PARSING_METADATA,function(b,c){a.showLogs("FRAG_PARSING_METADATA");a.showLogs(c.samples)});this.HLSObj.on(Hls.Events.FRAG_PARSING_DATA,function(b,c){a.TotalChangeLineCnt=0});this.HLSObj.on(Hls.Events.FRAG_BUFFERED,function(b,c){});this.HLSObj.on(Hls.Events.FPS_DROP,function(b,c){a.showLogs("FPS_DROP: "+c.currentDropped+"/"+
c.currentDecoded)});this.HLSObj.on(Hls.Events.DESTROYING,function(b,c){a.showLogs("Events.DESTROYING")});this.HLSObj.on(Hls.Events.ERROR,function(b,c){a.showLogs("ERROR: "+c.type+"/"+c.details);a.iNowNetErrorErrorCnt+=1;a.showLogs("THISROOT.iNowNetErrorErrorCnt :["+a.iNowNetErrorErrorCnt+"]");if(c.fatal)switch(a.showLogs("Fatal error :"+c.type+"/"+c.details),c.type){case Hls.ErrorTypes.NETWORK_ERROR:"manifestLoadError"==c.details&&a.restart();!0===a.playState&&a.HLSObj.startLoad();break;case Hls.ErrorTypes.MEDIA_ERROR:a.HLSObj.recoverMediaError();
break;case Hls.ErrorTypes.OTHER_ERROR:break;default:a.showLogs("cannot recover"),a.HLSObj.destroy()}else switch(c.type){case Hls.ErrorTypes.MEDIA_ERROR:switch(c.details){case Hls.ErrorDetails.BUFFER_NUDGE_ON_STALL:a.showLogs("BUFFER_NUDGE_ON_STALL"),a.HLSObj.startLoad()}}})}SetPloader(){-1!=this.vUrl.indexOf("cdn4c-mx.akamaized.net")&&(this.HLSObj.config.xhrSetup=function(a,b){a.withCredentials=!0})}Pause(){this.videoElm&&!1===this.videoElm.paused&&this.videoElm.pause()}Resume(){this.videoElm&&!0===
this.videoElm.paused&&this.videoElm.play()}Mute(){this.videoElm&&!1===this.videoElm.muted&&(this.videoElm.muted=!0,this.lastSoundState=this.videoElm.defaultMuted=!0)}unMute(){this.videoElm&&!0===this.videoElm.muted&&(this.videoElm.muted=!1,this.lastSoundState=this.videoElm.defaultMuted=!1)}Stop(){-1!=this.doInfo&&(clearInterval(this.doInfo),this.doInfo=-1);this.resetVar();this.videoElm&&(!1===this.hlsSupport?this.Pause():(this.Pause(),null!=this.HLSObj&&(this.HLSObj.stopLoad(),this.HLSObj.detachMedia()),
this.showLogs(" do HLS Stop!! ")),this.vUrl=null,this.videoElm.removeAttribute("src"),this.videoElm.load(),this.playState=!1)}Volume(a){this.videoElm&&(this.videoElm.volume=a)}Seek(a){this.videoElm&&(this.showLogs("seek to "+a+" sec"),this.videoElm.currentTime=a)}UpdateURL(a){this.vUrl=a}PlaybackRate(a){this.videoElm&&(this.videoElm.playbackRate=a)}info(){var a=this,b=parseInt(this.videoElm.buffered.length)-1;0>b&&(this.debug&&a.showLogs("Error: Buffered length error"),b=0);try{this.bufferTime=this.videoElm.buffered.end(b)}catch(d){this.bufferTime=
0}this.readyState=this.videoElm.readyState;this.currentTime=this.videoElm.currentTime;this.delayTime=this.bufferTime-this.currentTime;this.logId&&(document.getElementById("readyState").innerHTML="<b>ReadyState: "+this.readyState+"<b>",document.getElementById("currentTime").innerHTML="<b>Current: "+this.currentTime+"<b>",document.getElementById("bufferTime").innerHTML="<b>Buffered: "+this.bufferTime+"<b>",document.getElementById("delayTime").innerHTML="<b>Delay: "+this.delayTime+"<b>",this.isMonitor||
(document.getElementById("timedMeta").innerHTML="<b>TimedMeta: "+this.timedMeta+"<b>",document.getElementById("timedMetaTime").innerHTML="<b>TimedMetaTime: "+this.timedMetaTime+"<b>",this.videoElm.getVideoPlaybackQuality&&typeof this.videoElm.getVideoPlaybackQuality===typeof Function?document.getElementById("dropFrame").innerHTML="<b>DropFrame: "+this.videoElm.getVideoPlaybackQuality.droppedVideoFrames+"<b>":document.getElementById("dropFrame").innerHTML="<b>DropFrame: "+this.videoElm.webkitDroppedFrameCount+
"<b>"));if(!1===this.videoElm.paused){if(this.lastCurrent!=this.currentTime?(this.lastCurrent=this.currentTime,this.chkCurrentTimes=0):(++this.chkCurrentTimes,a.showLogs("check Current: "+this.chkCurrentTimes)),this.chkCurrentTimes>=this.maxChkCurrentTimes){a.showLogs("check current to max count.");this.ErrorHint("403");return}}else this.chkCurrentTimes=0;this.lastBufferd!=this.bufferTime?(this.lastBufferd=this.bufferTime,this.chkBufferdTimes=0):(++this.chkBufferdTimes,a.showLogs("check bufferd: "+
this.chkBufferdTimes));if(this.chkBufferdTimes>=this.maxChkBufferdTimes)a.showLogs("check bufferd to max count."+this.maxChkBufferdTimes),this.ErrorHint("403");else if(2>this.readyState?(++this.chkReadyStateTimes,a.showLogs("check ReadyState: "+this.chkReadyStateTimes)):this.chkReadyStateTimes=0,this.chkReadyStateTimes>this.maxChkReadyStateTimes)a.showLogs("check ReadyState to max count."),this.ErrorHint("403");else{if(!0===this.iOS){var c=(new Date).getTime();if(0==this.lastclientTime||2E3<c-this.lastclientTime){var f=
new XMLHttpRequest;f.onreadystatechange=function(){if(4==f.readyState&&200==f.status){a.chkBase=btoa(f.responseText);a.chkBase===this.lastbase?++this.chkBasetimes:this.chkBasetimes=0;if(5<=this.chkBasetimes){a.showLogs("check Loop to max count.");this.ErrorHint("403");return}this.lastclientTime=c}this.lastbase=a.chkBase};f.open("GET",a.m3u8Url,!0);f.send(null)}}!0!==this.hlsSupport&&!0!==this.iOS||this.chkSeek()}}m3u8URLParse(a){this.m3u8URLtag=a.split("#");this.firstLevel=null;for(var b in this.m3u8URLtag)if(-1<
this.m3u8URLtag[b].indexOf("EXT-X-STREAM-INF")){this.firstLevelarr=this.m3u8URLtag[b].split("\n");for(var c in this.firstLevelarr)if(-1<this.firstLevelarr[c].indexOf("m3u8")){this.firstLevel=this.firstLevelarr[c];break}}null!=this.firstLevel?-1<this.firstLevel.indexOf("http")?this.m3u8Url=this.firstLevel:(this.urlArr=this.vUrl.split("/"),this.m3u8Url=this.vUrl.replace(new RegExp(this.urlArr[this.urlArr.length-1],"g"),this.firstLevel)):this.m3u8Url=this.vUrl}chkSeek(){if(this.videoElm&&0!==this.delayTime){this.chkPlayBackTimes=
this.delayTime-this.rateOffset>this.maxDelaySec/2+1?this.chkPlayBackTimes+1:0;2<this.chkPlayBackTimes?this.PlaybackRate(1.2):this.PlaybackRate(1);if(4<this.chkSeekTimes)if(!0===this.iOS){try{this.seekableEnd=this.videoElm.seekable.end(0)}catch(a){this.seekableEnd=0}this.showLogs("iOS seek time range->["+this.videoElm.seekable.start(0)+","+this.videoElm.seekable.end(0)+"]");this.seekableEnd>this.videoElm.currentTime&&this.Seek(this.seekableEnd)}else!0===this.hlsSupport&&(this.seekTime=this.delayTime-
this.maxDelaySec,this.Seek(this.videoElm.currentTime+this.seekTime));this.chkSeekTimes=this.delayTime>this.maxDelaySec?this.chkSeekTimes+1:0;this.delayTime>this.maxDelaySec&&this.chkSeekTimes>=this.maxChkSeekTimes&&(this.showLogs("Delay > "+this.maxDelaySec+" and seek failed, restart connect now "),this.restart())}}resetVar(){this.chkPlayBackTimes=this.chkBasetimes=this.chkLoadErrorTimes=this.chkSeekTimes=this.chkReadyStateTimes=this.chkBufferdTimes=this.chkCurrentTimes=this.lastbase=this.lastclientTime=
this.lastBufferd=this.lastCurrent=this.delayTime=this.currentTime=this.readyState=this.bufferTime=0;this.errDetails=""}setLogId(a){this.logId=a;a=document.createElement("div");a.setAttribute("id","readyState");a.setAttribute("style","margin-top:10px");a.innerHTML="<b>ReadyState: <b>";document.body.appendChild(a);a=document.createElement("div");a.setAttribute("id","currentTime");a.setAttribute("style","margin-top:10px");a.innerHTML="<b>Current: <b>";document.body.appendChild(a);a=document.createElement("div");
a.setAttribute("id","bufferTime");a.setAttribute("style","margin-top:10px");a.innerHTML="<b>Buffer: <b>";document.body.appendChild(a);a=document.createElement("div");a.setAttribute("id","delayTime");a.setAttribute("style","margin-top:10px");a.innerHTML="<b>Delay: <b>";document.body.appendChild(a);this.isMonitor||(a=document.createElement("div"),a.setAttribute("id","dropFrame"),a.setAttribute("style","margin-top:10px"),a.innerHTML="<b>DropFrame: <b>",document.body.appendChild(a),a=document.createElement("div"),
a.setAttribute("id","timedMeta"),a.setAttribute("style","margin-top:10px"),a.innerHTML="<b>TimedMeta: <b>",document.body.appendChild(a),a=document.createElement("div"),a.setAttribute("id","timedMetaTime"),a.setAttribute("style","margin-top:10px"),a.innerHTML="<b>TimedMetaTime: <b>",document.body.appendChild(a),a=document.createElement("div"),a.setAttribute("id",this.logId),a.setAttribute("style","width:600px; height:300px; overflow:auto; background-color:#eee; margin-top:10px; "),document.body.appendChild(a))}ErrorHint(a){var b=
!1;!0===this.todoErrorHint?console.log("errorhint be return :["+a+"]"):("001"!==a&&(this.TotalChangeLineCnt+=1,this.TotalChangeLineCnt<=this.MaxTotalChangeLineCnt?(b=!0,this.DelayStartTime=Date.now()/1E3):Date.now()/1E3-this.DelayStartTime>=this.MaxDelayTimeGap&&(b=!0,this.DelayStartTime=Date.now()/1E3)),1==b&&(this.todoErrorHint=!0,-1!=this.doInfo&&(this.showLogs("to do stop info setInterval!!"),clearInterval(this.doInfo),this.doInfo=-1),this.Stop(),null!=this.errorSendBack&&this.errorSendBack(this.RegId,
a)))}showLogs(a){var b=new Date;b="["+b.getFullYear()+"-"+(b.getMonth()+1)+"-"+b.getDate()+" "+b.getHours()+":"+b.getMinutes()+":"+b.getSeconds()+":"+b.getMilliseconds()+"]";if(!0===this.debug&&(console.warn(b+" "+a),""!=this.logId)){var c="<br/>"+$("#"+this.logId).html();$("#"+this.logId).html(b+" "+a+c)}}pStatus(a){this.showLogs(a)}}
;
