"undefined"==typeof Browser&&(Browser={});
(function(){var f=function(a){var b=0,c=0;a||(a=window.event);if(a.pageX||a.pageY)b=a.pageX,c=a.pageY;else if(a.clientX||a.clientY)b=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[b,c]},h=function(){this.name="IE";this.getCursorPosition=function(a){return f(a)};this.attachEventListener=function(a,b,c,d){a.attachEvent("on"+b,c);return!0};this.addLoadListener=function(a){window.attachEvent("onload",
a)};this.getPageDimensions=function(){var a=document.getElementsByTagName("body")[0],b=[0,0];"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.scrollWidth&&(b[0]=document.documentElement.scrollWidth,b[1]=document.documentElement.scrollHeight);var c=a.offsetWidth;var d=a.offsetHeight;var e=a.scrollWidth;a=a.scrollHeight;c>b[0]&&(b[0]=c);d>b[1]&&(b[1]=d);e>b[0]&&(b[0]=e);a>b[1]&&(b[1]=a);return b};this.getScrollingPosition=function(){var a=0,b=0;document.body&&
(document.body.scrollLeft||document.body.scrollTop)?(a=document.body.scrollTop,b=document.body.scrollLeft):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&(a=document.documentElement.scrollTop,b=document.documentElement.scrollLeft);return[b,a]};this.getViewportSize=function(){return 0==document.documentElement.clientWidth&&0==document.documentElement.clientHeight?[document.body.clientWidth,document.body.clientHeight]:[document.documentElement.clientWidth,
document.documentElement.clientHeight]};this.setIFrameHeight=function(a,b){frame=document.getElementById(a);innerDoc=frame.contentDocument?frame.contentDocument:frame.contentWindow.document;objToResize=frame.style?frame.style:frame;objToResize.height=innerDoc.body.scrollHeight+18+(b?b:0)};this.setTextContent=function(a,b){a.innerText=b};this.getTextContent=function(a){return a.innerText}},k=function(){this.name="Mozilla";this.getCursorPosition=function(a){return f(a)};this.attachEventListener=function(a,
b,c,d){a.addEventListener(b,c,d);return!0};this.addLoadListener=function(a){window.addEventListener("load",a,!1)};this.getPageDimensions=function(){var a=document.getElementsByTagName("body")[0],b=[0,0];"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.scrollWidth&&(b[0]=document.documentElement.scrollWidth,b[1]=document.documentElement.scrollHeight);var c=a.offsetWidth;var d=a.offsetHeight;var e=a.scrollWidth;a=a.scrollHeight;c>b[0]&&(b[0]=c);d>b[1]&&(b[1]=
d);e>b[0]&&(b[0]=e);a>b[1]&&(b[1]=a);return b};this.getScrollingPosition=function(){var a=[0,0];"undefined"!=typeof window.pageYOffset?a=[window.pageXOffset,window.pageYOffset]:"undefined"!=typeof document.body.scrollTop&&(a=[document.body.scrollLeft,document.body.scrollTop]);return a};this.getViewportSize=function(){return[window.innerWidth,window.innerHeight]};this.setIFrameHeight=function(a,b){a=document.getElementById(a);a.height=a.contentDocument.body.offsetHeight+(b?b:0)};this.setTextContent=
function(a,b){a.textContent=b};this.getTextContent=function(a){return a.textContent}},g=function(){this.name="Undefined";this.getCursorPosition=function(a){return f(a)};this.attachEventListener=function(a,b,c,d){if("undefined"!=typeof a.addEventListener)a.addEventListener(b,c,d);else if("undefined"!=typeof a.attachEvent)a.attachEvent("on"+b,c);else if(b="on"+b,"function"!=typeof a[b])a[b]=c;else{var e=a[b];a[b]=function(){e();return c()};return!0}};this.addLoadListener=function(a){if("undefined"!=
typeof window.addEventListener)window.addEventListener("load",a,!1);else if("undefined"!=typeof document.addEventListener)document.addEventListener("load",a,!1);else if("undefined"!=typeof window.attachEvent)window.attachEvent("onload",a);else if("function"!=typeof window.onload)window.onload=a;else{var b=window.onload;window.onload=function(){b();a()}}};this.getPageDimensions=function(){var a=document.getElementsByTagName("body")[0],b=[0,0];"undefined"!=typeof document.documentElement&&"undefined"!=
typeof document.documentElement.scrollWidth&&(b[0]=document.documentElement.scrollWidth,b[1]=document.documentElement.scrollHeight);var c=a.offsetWidth;var d=a.offsetHeight;var e=a.scrollWidth;a=a.scrollHeight;c>b[0]&&(b[0]=c);d>b[1]&&(b[1]=d);e>b[0]&&(b[0]=e);a>b[1]&&(b[1]=a);return b};this.getScrollingPosition=function(){var a=[0,0];"undefined"!=typeof window.pageYOffset&&(a=[window.pageXOffset,window.pageYOffset]);"undefined"!=typeof document.documentElement.scrollTop&&0<document.documentElement.scrollTop?
a=[document.documentElement.scrollLeft,document.documentElement.scrollTop]:"undefined"!=typeof document.body.scrollTop&&(a=[document.body.scrollLeft,document.body.scrollTop]);return a};this.getViewportSize=function(){return"undefined"!=typeof window.innerWidth?[window.innerWidth,window.innerHeight]:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?[document.documentElement.clientWidth,document.documentElement.clientHeight]:
[document.getElementsByTagName("body")[0].clientWidth,document.getElementsByTagName("body")[0].clientHeight]};this.setIFrameHeight=function(a,b){frame=document.getElementById(a);innerDoc=frame.contentDocument?frame.contentDocument:frame.contentWindow.document;objToResize=frame.style?frame.style:frame;objToResize.height=innerDoc.body.scrollHeight+18+(b?b:0)};this.setTextContent=function(a,b){try{a.textContent=b}catch(c){a.innerText=b}};this.getTextContent=function(a){try{return a.textContent}catch(b){return a.innerText}}},
l={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(a){for(var b=0;b<a.length;b++){var c=a[b].string,d=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(c){if(-1!=c.indexOf(a[b].subString))return a[b].identity}else if(d)return a[b].identity}},searchVersion:function(a){var b=
a.indexOf(this.versionSearchString);if(-1!=b)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,
subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],
dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};Browser=function(){var a=navigator.userAgent.toLowerCase();if("undefined"!=typeof navigator.vendor&&"KDE"==navigator.vendor&&"undefined"!=typeof window.sidebar)return new g;if("undefined"!=typeof window.opera)return parseFloat(a.replace(/.*opera[\/ ]([^ $]+).*/,
"$1")),new g;if("undefined"!=typeof document.all)return"undefined"!=typeof document.getElementById&&(a=a.replace(/.*ms(ie[\/ ][^ $]+).*/,"$1").replace(/ /,""),"undefined"!=typeof document.uniqueID&&a.indexOf("5.5")),new h;if("undefined"!=typeof document.getElementById){if(-1!=navigator.vendor.indexOf("Apple Computer, Inc."))return new g;if(-1!=a.indexOf("gecko"))return new k}return new h}();Browser.browserDetect=l})();

