"undefined"==typeof EventHighlightUtil&&(EventHighlightUtil={});
(function(){EventHighlightUtil.collectRemoveEventIds=[];EventHighlightUtil.updateEvents=a=>{let b=a.gameProductStatus,c=DataBase.pinHighlightEvents.queryAll().filter(g=>EventHighlightUtil.filterCompetition(g)&&EventHighlightUtil.filterEvent(g)&&EventHighlightUtil.filterMarket(g)&&EventHighlightUtil.filterSelection(g));EventHighlightUtil.markAllEventNotRefreshYet().then(()=>{for(let g=0;g<c.length;g++)EventHighlightUtil.appendEventHighlight(g,c[g],c,b)}).then(()=>{EventHighlightUtil.removeEventWithNotRefresh()}).then(()=>
{BetHandler.addSelectClass();EventHighlightUtil.displayShowHighlightWrap()})};EventHighlightUtil.appendEventHighlight=(a,b,c,g)=>{let e=EventHighlightUtil.getEventPinHighlightId(b.id),f=$j("#"+e),d=EventHighlightUtil.getHighlightMarket(b);0==$j("#"+e).length&&(f=JsCache.clone("#eventTemplate"),f.attr("id",e),f.find("#multiMarketPin").hide(),EventHighlightUtil.goToFullMarket(b,d,f),EventHandler.bindEvent(f),EventHighlightUtil.appendEventHighlightWithPosition(a,b,c,f));f.attr("eventType",b.eventType);
f.attr("eventId",b.id);f.attr("marketId",d.marketId);f.attr("eventName",b.name);f.attr("openDate",b.openDate);f.attr("openDateTime",b.openDateTime);f.attr("totalMatched",d.totalMatched);f.attr("elapsedTime",b.elapsedTime);f.attr("inPlay",d.inPlay);f.attr("priority",b.priority);f.attr("boardType","pinHighlight");f.attr("refresh","1");f.find("#vsName").html(EventHighlightUtil.displayTwoTeamsEvent(b,d));EventHighlightUtil.displayAllBoardTotalMatched(b,d);EventHighlightUtil.displayEventHasDraw(b,f);EventHighlightUtil.displayEventCategoryIcon(b,
f);EventHighlightUtil.displayEventStreamIcon(b,f);EventHighlightUtil.displayMarketInPlayIcon(d,f);EventHighlightUtil.displayMarketInPlayDateTime(b,d,f);EventHighlightUtil.displayAllBoardMarketShowDisabled(b,d);EventHighlightUtil.displayAllBoardSelections(b,d,g)};EventHighlightUtil.appendEventHighlightWithPosition=(a,b,c,g)=>{for(b=null;0<=a;--a){let e=c[a].id;if(0<$j("#"+EventHighlightUtil.getEventPinHighlightId(e)).length){b=$j("#"+EventHighlightUtil.getEventPinHighlightId(e));break}}c=b;null==c?
$j("#eventPinHighlightBoard").prepend(g.css("display","flex")):c.after(g.css("display","flex"))};EventHighlightUtil.filterCompetition=a=>CompetitionUtils.isCloseSite(a.competitionCloseSite,PageConfig.webSiteType)?!1:!0;EventHighlightUtil.filterEvent=a=>a.isManualEvent&&a.isManualEventClosed||0<(a.status&16)||0<(a.status&48)||EventUtils.isCloseSite(a.closeSite,PageConfig.webSiteType)?!1:!0;EventHighlightUtil.filterMarket=a=>{if(0==a.markets.length||0<a.markets.length&&3==a.markets[0].status)return!1;
a=EventHighlightUtil.getHighlightMarket(a);return null==a||MarketUtil.isClosed(a.status)||MarketUtil.isCloseSite(a.closeSite,PageConfig.webSiteType)?!1:!0};EventHighlightUtil.filterSelection=a=>0!=a.markets[0].selections.length||a.isManualEvent?!0:!1;EventHighlightUtil.sortEventHighlightStrategy=(a,b)=>EventHandler.sortEventsOnUI(a,b);EventHighlightUtil.getEventPinHighlightId=a=>"eventPinHighlight_"+a;EventHighlightUtil.isViewHighlightPage=()=>-1<location.href.indexOf("index");EventHighlightUtil.collectEventId=
a=>{let b="";for(let c=0;c<a.length;c++)b+=a[c].eventId+",";return 0<b.length?b.substring(0,b.length-1):""};EventHighlightUtil.getHighlightMarket=a=>{let b=null;for(let c=0;c<a.markets.length;c++)if(1==a.markets[c].isHighLight||("EXTRA_TIME"==a.markets[c].marketType||"SUPER_OVER"==a.markets[c].marketType)&&!MarketUtil.isCloseSite(a.markets[c].closeSite,PageConfig.webSiteType)){b=a.markets[c];break}return b};EventHighlightUtil.goToFullMarket=(a,b,c)=>{a=PageConfig.fullMarketPath+"?eventType="+a.eventType+
"&eventId="+a.id+"&marketId="+b.marketId;c.find("#eventInfo").find("#vsName").attr("href",a)};EventHighlightUtil.displayEventCategoryIcon=(a,b)=>{FancyBetMarketHandler.isEnableFancyBet()&&a.hasFancyBetMarkets?(b.find("#fancyBetIcon").show().css("display","inline-flex"),a.hasInPlayFancyBetMarkets?b.find(".game-fancy").addClass("in-play"):b.find(".game-fancy").removeClass("in-play")):b.find("#fancyBetIcon").hide();if(PageConfig.isEnableBookMaker&&a.hasBookMakerMarkets){let c=b.find("#bookMakerIcon");
c.show().css("display","inline-flex");a.hasInPlayBookMakerMarkets?c.addClass("in-play"):c.removeClass("in-play")}else b.find("#bookMakerIcon").hide();SportsBookEventHandler.isEnableSportsBookBet()&&a.hasSportsBookMarkets&&b.find("#sportsBookIcon_"+ApiSiteType.SPORTRADAR.unique()).show().css("display","inline-flex");SportsBookEventHandler.isEnableOwSportsBookBet()&&a.hasOwSportsBookMarkets&&b.find("#sportsBookIcon_"+ApiSiteType.OW.unique()).show().css("display","inline-flex");a.hasSportsBookMarkets||
a.hasOwSportsBookMarkets||b.find("#sportsBookIcon_"+ApiSiteType.OW.unique()).hide();1==a.isElectronic&&b.find("#sportsBookEIcon_"+a.eventType).show().css("display","inline-flex");HeadToHeadHandler.displayH2HIconButton(a,b,"pin")};EventHighlightUtil.displayAllBoardTotalMatched=(a,b)=>{let c=[$j("#"+EventHighlightUtil.getEventPinHighlightId(a.id)),$j("#highLightEvent_"+a.id)];for(let g=0;g<c.length;g++){let e=c[g];0<e.length&&e.find("#matched").html(EventHighlightUtil.displayTotalMatched(a,b))}};EventHighlightUtil.displayTotalMatched=
(a,b)=>CurrencyUtil.formatNumberToKM(0<b.totalMatched?b.totalMatched:0,{precision:0,separateSign:",",currencySymbol:PageConfig.playerCurrencyType,formatter:CurrencyUtil.DefaultFormatter,trailingZeros:!1});EventHighlightUtil.displayTwoTeamsEvent=(a,b)=>{var c=a.name;if(!EventType.getInstanceOf(a.eventType).isTwoTeamsEvent())return c;let g=" v ";0<a.name.indexOf(" vs ")?g=" vs ":0<a.name.indexOf(" @ ")&&(g=" @ ");let e=a.name.split(g);if(1==e.length)return c;let f="",d="";for(c=0;c<b.selections.length;c++){let h=
b.selections[c];1==h.sortPriority?f=h.runnerName:2==h.sortPriority&&(d=h.runnerName);if(""!=f&&""!=d)break}""!=f&&""!=d?c=f+"<span>"+g.trim()+"</span>"+d:(f=e[0],d=e[1],c=e[0]+"<span>"+g.trim()+"</span>"+e[1]);1==b.inPlay&&(a=EventHandler.getScoreInfo(a,f,d),c=f+a+d);return c};EventHighlightUtil.displayEventStreamIcon=(a,b)=>{null!=a.streamingChannel&&0!=a.streamingChannel.length&&0!=a.streamingChannel?b.find("#streamingIcon").show().css("display","inline-flex"):b.find("#streamingIcon").hide()};EventHighlightUtil.displayMarketInPlayIcon=
(a,b)=>{null!=a.inPlay&&1==a.inPlay&&(b.find("#playIcon").removeClass("icon-no_play"),b.find("#playIcon").addClass("icon-in_play"))};EventHighlightUtil.displayMarketInPlayDateTime=(a,b,c)=>{null!=b.inPlay&&1==b.inPlay?EventHandler.updateEventCountdown(a,b,c):EventHandler.updateDateTimeInfo(b,c)};EventHighlightUtil.displayAllBoardSelections=(a,b,c)=>{let g=[$j("#"+EventHighlightUtil.getEventPinHighlightId(a.id)),$j("#highLightEvent_"+a.id)];for(let e=0;e<g.length;e++){let f=g[e];0<f.length&&EventHighlightUtil.displaySelections(a,
b,f,c)}};EventHighlightUtil.displaySelections=(a,b,c,g)=>{for(let f=0;f<b.selections.length;f++){let d=b.selections[f],h;if(1==d.sortPriority)h=".col-visit";else if(2==d.sortPriority)h=".col-home";else if(3==d.sortPriority)h=".col-draw";else continue;var e=c.find(h+" > a");if(0==e.length)continue;let k=$j(e[0]);e=$j(e[1]);k.prev().prop("id","suspend_"+a.id+"_"+d.selectionKey);k.attr("selectionId",d.selectionId);k.attr("selectionKey",d.selectionKey);k.attr("runner",d.runnerName);k.attr("marketName",
b.marketName);k.attr("inPlay",b.inPlay);k.attr("marketType",b.marketType);k.attr("handicap",d.handicap);e.attr("selectionId",d.selectionId);e.attr("selectionKey",d.selectionKey);e.attr("runner",d.runnerName);e.attr("marketName",b.marketName);e.attr("inPlay",b.inPlay);e.attr("marketType",b.marketType);e.attr("handicap",d.handicap);0<d.availableToBack.length?(k.html(d.availableToBack[0].price),SparkHandler.addSparkClass(k,d.availableToBack[0].price,null)):k.html("&nbsp;");0<d.availableToLay.length?
(e.html(d.availableToLay[0].price),SparkHandler.addSparkClass(e,d.availableToLay[0].price,null)):e.html("&nbsp;");SelectionUtil.isShowSelection(d.closeSite,d.bookMode,PageConfig.webSiteType)?(c.find("a#btnBack[selectionid="+d.selectionId+"]").show(),c.find("a#btnLay[selectionid="+d.selectionId+"]").show(),MarketUtil.isSuspend(b.status)||SelectionUtil.isShowSuspend(d.suspendSite,d.bookSuspend,PageConfig.webSiteType)||GameProductUtils.isClose(g)?c.find("#suspend_"+a.id+"_"+d.selectionKey).show():c.find("#suspend_"+
a.id+"_"+d.selectionKey).hide(),1==d.isAutoSuspend?c.find(h).addClass("disabled"):c.find(h).removeClass("disabled")):(c.find("a#btnBack[selectionid="+d.selectionId+"]").hide(),c.find("a#btnLay[selectionid="+d.selectionId+"]").hide())}};EventHighlightUtil.displayAllBoardMarketShowDisabled=(a,b)=>{let c=[$j("#"+EventHighlightUtil.getEventPinHighlightId(a.id)),$j("#highLightEvent_"+a.id)];for(let g=0;g<c.length;g++){let e=c[g];0<e.length&&EventHighlightUtil.displayMarketShowDisabled(a,b,e)}};EventHighlightUtil.displayMarketShowDisabled=
(a,b,c)=>{let g=!1,e=!1;BetHandler.isEnableCheckLowLiquidity()&&BetHandler.isLowLiquidity(a.eventType,a.id,b.marketId.replace("_","."))&&(e=!0);WebSiteUtil.isDisableBettingSite(b.disableBettingSite,PageConfig.webSiteType)&&(g=!0);WebSiteUtil.isDisableBettingSite(b.autoDisableBettingSite,PageConfig.webSiteType)&&(g=!0);g||e?c.addClass("disabled"):c.hasClass("cooldown")||c.removeClass("disabled")};EventHighlightUtil.displayEventHasDraw=(a,b)=>{EventType.getInstanceOf(a.eventType).hasDraw()?(b.find(".col-draw").show(),
$j("#eventPinHighlightWrap").addClass("col3"),$j("#eventPinHighlightWrap .col-game").css("width","")):(b.find(".col-draw").hide(),$j("#eventPinHighlightWrap").removeClass("col3"),$j("#eventPinHighlightWrap .col-game").css("width","calc(64.1% - 41px)"))};EventHighlightUtil.markAllEventNotRefreshYet=async()=>{let a=$j("#eventPinHighlightBoard").find("[id^=eventPinHighlight_]").clone();for(let b=0;b<a.length;b++)$j("#"+a[b].id).attr("refresh","0")};EventHighlightUtil.removeEventWithNotRefresh=()=>{let a=
$j("#eventPinHighlightBoard").find("[id^=eventPinHighlight_]").clone();for(let b=0;b<a.length;b++){let c=$j("#"+a[b].id);"0"===c.attr("refresh")&&c.remove()}};EventHighlightUtil.displayShowHighlightWrap=()=>{let a=$j("#eventPinHighlightWrap"),b=$j("#eventPinHighlightBoard");0==b.find("[id^=eventPinHighlight_]").length?a.hide():a.show();EventType.getInstanceOf(PageConfig.highlightEventType).hasDraw()?(a.find(".col-draw").show(),a.find(".col-game").css("width","")):(b.find("dt").css("width","calc(64.1% - 41px)"),
a.find(".col-draw").hide(),a.find(".col-game").css("width","calc(64.1% - 41px)"),a.removeClass("col3"))}})();

