"undefined"==typeof FancyBetRulesHandler&&(FancyBetRulesHandler={mainId:1,subId:1});
(function(){function l(){$j.each($j("[name=seq]"),function(b,a){$j(a).text(b)})}function m(){var b=$j("#settingContent").find("[id^=mainRule]");if(0==b.length)alert("At least input one rule");else{var a={};$j.each(b,function(e,c){var d=$j(c).attr("id").split("_")[1],f=$j("#mainRule_"+d).val().trim();if(""!=f){c={};c.mainRule=f;d=$j("[id^=subRule_][mainid="+d+"]");var g={};$j.each(d,function(k,h){h=$j(h).val().trim();""!=h&&(g[k+1]=h.trim())});c.subRule=g;a[e+1]=c}});return a}}FancyBetRulesHandler.data=
"";FancyBetRulesHandler.initForManager=function(){FancyBetRulesHandler.showFancyBetRules("manager");$j("#addMainContent").click(function(){FancyBetRulesHandler.addMainContent("")});$j("#update").click(function(){FancyBetRulesHandler.updateFancyBetRule()});$j("#webSiteGroup").change(function(){FancyBetRulesHandler.showFancyBetRules("manager")})};FancyBetRulesHandler.addMainContent=function(b){var a=FancyBetRulesHandler.mainId,e=$j("#settingContent"),c=$j("#mainTemplate").clone();c.attr("id","mainTemplate_"+
a);c.find("#mainRule").attr("id","mainRule_"+a).html(b);c.find("#addSubContent").attr("id","addSubContent_"+a).click(function(){FancyBetRulesHandler.addSubContent(a,"")});c.find("#deleteMainContent").attr("id","deleteMainContent_"+a).click(function(){$j("#mainTemplate_"+a).remove();$j("[id^=subTemplate_][mainid^="+a+"]").remove();l()});e.append(c);l();FancyBetRulesHandler.mainId++};FancyBetRulesHandler.addSubContent=function(b,a){var e=FancyBetRulesHandler.subId,c=$j("#mainTemplate_"+b),d=$j("#subTemplate").clone();
d.attr("id","subTemplate_"+e).attr("mainid",b);d.find("#subRule").attr("id","subRule_"+e).attr("mainid",b).html(a);d.find("#deleteSubContent").attr("id","deleteSubContent_"+e).click(function(){$j("#subTemplate_"+e).remove()});0==$j("[id^=subTemplate_][mainid="+b+"]").length?c.after(d):$j("[id^=subTemplate_][mainid="+b+"]").last().after(d);FancyBetRulesHandler.subId++};FancyBetRulesHandler.updateFancyBetRule=function(){var b=m();null!=b&&$j.ajax({type:"POST",url:"/manage/marketManagementController/updateFancyBetRule",
data:{fancyBetRules:JSON.stringify(b),webSiteGroup:$j("#webSiteGroup").val()},beforeSend:function(){JsCache.get("#loading").show()},complete:function(){JsCache.get("#loading").hide()},success:function(a){try{a.error?NoticeHandler.error(a.error):a.success&&NoticeHandler.success(a.success)}catch(e){Trace.printStackTrace(e)}finally{}},error:function(a,e,c){Trace.log(a.status);Trace.log(c)}})};FancyBetRulesHandler.showFancyBetRules=function(b,a){var e="/manage/marketManagementController/queryFancyBetRule";
let c=$j("#webSiteGroup").val();"player"==b&&(e="/exchange/member/playerService/queryFancyBetRule",c=a);$j.ajax({type:"GET",dataType:"JSON",url:e,data:{webSiteGroup:c},beforeSend:function(){JsCache.get("#loading").show()},complete:function(){JsCache.get("#loading").hide()},success:function(d){d&&(d.error?NoticeHandler.error(d.error):$j.isEmptyObject(d)||(FancyBetRulesHandler.data=d,"player"==b?FancyBetRulesHandler.populateForPlayer():FancyBetRulesHandler.populateForManager()))},error:function(d,f,
g){Trace.log(d.status);Trace.log(g)}})};FancyBetRulesHandler.populateForPlayer=function(b){b=$j("[name^=fancyBetRules]");b.empty();var a="",e=Object.keys(FancyBetRulesHandler.data);$j.each(e,function(c,d){a+="<li>"+FancyBetRulesHandler.data[d].mainRule;var f=FancyBetRulesHandler.data[d].subRule;c=Object.keys(f);$j.each(c,function(g,k){a+="<ul>"+f[k]+"</ul>"});a+="</li>"});b.append(a)};FancyBetRulesHandler.populateForManager=function(b){$j("#settingContent").empty();b=Object.keys(FancyBetRulesHandler.data);
$j.each(b,function(a,e){FancyBetRulesHandler.addMainContent(FancyBetRulesHandler.data[e].mainRule);var c=FancyBetRulesHandler.data[e].subRule;a=Object.keys(c);$j.each(a,function(d,f){FancyBetRulesHandler.addSubContent(FancyBetRulesHandler.mainId-1,c[f])})})}})();

