"undefined"==typeof FullMarketUtil&&(FullMarketUtil={});
(function(){function E(c,d,e,f,l){let h=0;if(!PageConfig.ENABLE_REDUCE_BETFAIR_SIZE_FROM_FRONTEND)return h;d=DataBase.unMatchTicket.getActiveTickets(d,e,f,l);$j.each(d,function(b,p){c==p.odds&&(b=p.betfairLastPrice,PageConfig.playerCurrency!=PageConfig.berfairCurrency&&(b=MathUtil.roundp(RateUtils.convertRate(b,PageConfig.playerCurrencyRate,PageConfig.betfairCurrencyRate),2)),h+=p.lastPrice-b)});return h}FullMarketUtil.updateFullMarket=function(c,d,e,f,l,h,b,p){$j("#fullMarketBetsWrap");let r=EventType.getInstanceOf(e);
null!=DataBase.events.get(e,f)&&(c.find("#multiMarketRefresh").unbind("click").click(function(){c.find("#multiMarketLoading").show();setTimeout(function(){c.find("#multiMarketLoading").hide()},500)}),c.find("#backAll").unbind("click").click(function(){FullMarketUtil.betAll(this,c)}),c.find("#layAll").unbind("click").click(function(){FullMarketUtil.betAll(this,c)}),WebSiteUtil.isNotAllowRaceEventLay(r)&&c.find("#layAll").unbind("click"),PageConfig.ENABLE_LINE_MARKET&&MarketUtil.isLineMarket(h.marketType,
h.bettingType)?c.find("#selectionCounts").hide():c.find("#selectionCounts").html(h.numberOfActiveRunners+" selections").show(),h=h.selections,null!=h&&p&&FullMarketUtil.updateSelection(c,d,e,f,l,h,!1,b))};FullMarketUtil.updateSelection=function(c,d,e,f,l,h,b,p){var r=$j("#fullMarketBetsWrap"),x=EventType.getInstanceOf(e),B=!0,t=!1,k=DataBase.events.get(e,f);if(null!=k&&(b=DataBase.markets.get(f,l),null!=b)){var y={precision:0,separateSign:",",currencySymbol:null==PageConfig.currencySymbol?"$":PageConfig.currencySymbol,
formatter:CurrencyUtil.DefaultFormatter,trailingZeros:!1},A=1.01;PageConfig.ENABLE_LINE_MARKET&&MarketUtil.isLineMarket(b.marketType,b.bettingType)&&(A=2);FullMarketUtil.isViewMultiMarket()||PageConfig.isPoliticsPage||(0==h.length?r.hide():r.show());h.sort(function(F,G){return F.sortPriority>G.sortPriority?1:F.sortPriority<G.sortPriority?-1:0});for(var C in h){var g=h[C],q=g.selectionId,v=g.selectionKey,a=c.find("#fullSelection_"+v),m=SelectionUtil.isShowSelection(g.closeSite,g.bookMode,PageConfig.webSiteType),
H=GameProductUtils.isClose(p)||SelectionUtil.isShowSuspend(g.suspendSite,g.bookSuspend,PageConfig.webSiteType),I=1==g.isAutoSuspend,z="";if(0==a.length){if(!m)continue;if(x.isRacingEvent()){if(!(SelectionUtil.isActive(g.status)||SelectionUtil.isRemoved(g.status)||SelectionUtil.isRemovedVacant(g.status)||SelectionUtil.isHidden(g.status)))continue}else if(!SelectionUtil.isActive(g.status))continue;t=!0;m="";a=450;z=460;PageConfig.ENABLE_FULL_MARKET_DEPTH&&(a=920,z=600);z="window.open('market/marketDepth.jsp?eventId="+
f+"&marketId="+l+"&selectionId="+g.selectionId+"&handicap="+g.handicap+"','_blank','resizable=no,width="+a+",height="+z+"')";m='<a onclick="'+z+'"><img class="icon-predict" src="/images/transparent.gif"/></a>';a=r.find("#fullSelectionTemplate").clone();a.attr("id","fullSelection_"+v);a.attr("eventType",k.eventType);a.attr("eventId",k.id);a.attr("marketId",b.marketId.replace(".","_"));a.attr("selectionId",q);a.attr("selectionKey",v);a.attr("eventName",k.name);a.attr("status",g.status);a.attr("sortPriority",
g.sortPriority);a.attr("handicap",g.handicap);a.find("p").append(m+g.runnerName);a.find("td[class^='back-']").attr("selectionId",q).attr("selectionKey",v).attr("runner",g.runnerName).attr("marketName",b.marketName).attr("marketType",b.marketType).attr("handicap",g.handicap);a.find("td[class^='lay-']").attr("selectionId",q).attr("selectionKey",v).attr("runner",g.runnerName).attr("marketName",b.marketName).attr("marketType",b.marketType).attr("handicap",g.handicap);FullMarketUtil.bindEvent(a);d.append(a.show());
B&&(TxnHandler.changeOpenBetInFullMarkets(f,l),B=!1)}else{if(!m){a.hide();continue}a.is(":visible")||a.show();if(x.isRacingEvent()){if(!(SelectionUtil.isActive(g.status)||SelectionUtil.isRemoved(g.status)||SelectionUtil.isRemovedVacant(g.status)||SelectionUtil.isHidden(g.status))){a.remove();continue}}else if(!SelectionUtil.isActive(g.status)){a.remove();continue}}q=a.find("td[class^='back-']");m=a.find("td[class^='lay-']");q.attr("fullMarketOdds",A).attr("inPlay",b.inPlay).removeClass("spark");UiUtils.removeContents(q.find("a"));
UiUtils.removeContents(q.find("span"));m.attr("fullMarketOdds",A).attr("inPlay",b.inPlay).removeClass("spark");UiUtils.removeContents(m.find("a"));UiUtils.removeContents(m.find("span"));if(MarketUtil.isOpen(b.status)){q=1;m=g.availableToBack;for(var D in m){var n=m[D],w=a.find("#back_"+q);w.attr("fullMarketOdds",n.price);SparkHandler.addSparkClass(w,n.price,n.size);CurrencyUtil.updateSetting({currencySymbol:null==PageConfig.currencySymbol?"$":PageConfig.currencySymbol});var u=CurrencyUtil.formatter(n.size,
y);u=E(n.price,f,l,v,SideType.Lay.unique());u=CurrencyUtil.formatNumberToKM(n.size+u,y);w.find("span").before(n.price).append(u);q++}q=1;m=g.availableToLay;for(D in m)n=m[D],w=a.find("#lay_"+q),w.attr("fullMarketOdds",n.price),SparkHandler.addSparkClass(w,n.price,n.size),CurrencyUtil.updateSetting({currencySymbol:null==PageConfig.currencySymbol?"$":PageConfig.currencySymbol}),u=CurrencyUtil.formatter(n.size,y),u=E(n.price,f,l,v,SideType.Back.unique()),u=CurrencyUtil.formatNumberToKM(n.size+u,y),w.find("span").before(n.price).append(u),
q++;WebSiteUtil.isNotAllowRaceEventLay(x)&&(a.find("td[class^='lay-']").remove(),a.find("#horseGreyOut").show())}I?a.addClass("disabled"):a.removeClass("disabled");H?(a.find("#suspend").show(),a.find("#closed").hide(),a.find("#nonRunner").hide(),a.find("td[class^='back-']").hide(),a.find("td[class^='lay-']").hide(),a.find("#horseGreyOut").hide()):(MarketUtil.isOpen(b.status)?(a.find("#suspend").hide(),a.find("#closed").hide(),a.find("#nonRunner").hide(),a.find("td[class^='back-']").show(),a.find("td[class^='lay-']").show()):
H||MarketUtil.isSuspend(b.status)&&!MarketUtil.isClosed(b.status)?(a.find("#suspend").show(),a.find("#closed").hide(),a.find("#nonRunner").hide(),a.find("td[class^='back-']").hide(),a.find("td[class^='lay-']").hide(),a.find("#horseGreyOut").hide()):MarketUtil.isClosed(b.status)&&(a.find("#suspend").hide(),a.find("#closed").show(),a.find("#nonRunner").hide(),a.find("td[class^='back-']").hide(),a.find("td[class^='lay-']").hide(),a.find("#horseGreyOut").hide()),x.isRacingEvent()&&(SelectionUtil.isHidden(g.status)||
SelectionUtil.isRemoved(g.status)||SelectionUtil.isRemovedVacant(g.status))&&(a.find("#suspend").is(":hidden")&&a.find("#closed").is(":hidden")&&a.find("#nonRunner").show(),a.find("td[class^='back-']").hide(),a.find("td[class^='lay-']").hide(),a.find("#horseGreyOut").hide()));FullMarketUtil.appendJockeyColor(a,k,b,g,z,e)}1==t&&(BetHandler.getWinLoss(f,l.replace(".","_")),BetHandler.addSelectClass());FullMarketUtil.showBetBookPercent(h,d,e);"true"==PageConfig.ENABLE_CASH_OUT&&CashOutHandler.updatePending(l,
g);h=c=!1;BetHandler.isEnableCheckLowLiquidity()&&BetHandler.isLowLiquidity(e,f,l.replace("_","."))&&(h=!0);e=b.autoDisableBettingSite;if(WebSiteUtil.isDisableBettingSite(b.disableBettingSite,PageConfig.webSiteType)||WebSiteUtil.isDisableBettingSite(e,PageConfig.webSiteType))c=!0;c||h?d.addClass("disabled"):d.hasClass("cooldown")||d.removeClass("disabled")}};FullMarketUtil.bindEvent=function(c){c.find("td[class^='back-']").mouseup(function(){BetHandler.clickBtn(this,!0)});c.find("td[class^='lay-']").mouseup(function(){BetHandler.clickBtn(this,
!0)})};FullMarketUtil.betAll=function(c,d){c=$j(c).attr("id");var e=[];"backAll"==c?e=d.find("td[id^='back_1']"):"layAll"==c&&(e=d.find("td[id^='lay_1']"));BetHandler.betAll(e,!0,d.attr("eventType"),d.attr("eventId"),d.attr("marketId"))};FullMarketUtil.showBetBookPercent=function(c,d,e){var f=0,l=0,h;for(h in c){var b=c[h],p=0;null!=b.availableToBack[0]&&(p=parseFloat(b.availableToBack[0].price));var r=0;null!=b.availableToLay[0]&&(r=parseFloat(b.availableToLay[0].price));f=0!=p?f+MathUtil.decimal.divide(1,
p):f+1;0!=r&&(l+=MathUtil.decimal.divide(1,r))}f=MathUtil.decimal.multiply(f,100);l=MathUtil.decimal.multiply(l,100);f=MathUtil.roundp(f,1);l=MathUtil.roundp(l,1);c=d.find("#backPercent");d=d.find("#layPercent");null!=c&&0!=c.length&&c.html(f+"%");EventType.getInstanceOf(e).isRacingEvent()||null==d||0==d.length||d.html(l+"%")};FullMarketUtil.showLowLiquidityTag=function(c,d){d?c.show():c.hide()};FullMarketUtil.disableBetButton=function(c,d){d?c.addClass("disable"):c.removeClass("disable")};FullMarketUtil.appendJockeyColor=
function(c,d,e,f,l,h){if(null==e.marketType||"WIN"==e.marketType||"PLACE"==e.marketType||"OTHER_PLACE"==e.marketType)if(EventType.GREYHOUND_RACING.unique()==h)FullMarketUtil.appendGreyhoundJockeyColor(c,d,e,f,l);else if(null!=f.runnerMetadata&&0!=f.runnerMetadata.length){var b=null;try{b=JSON.parse(f.runnerMetadata)}catch(g){Trace.log(g)}if(null!=b&&0!=b.length&&(e=!1,null!=d.countryCode&&"US"==d.countryCode&&(e=!0),d=b.COLOURS_FILENAME,null!=d||e)){h=b.CLOTH_NUMBER_ALPHA;var p=b.STALL_DRAW,r=b.JOCKEY_NAME,
x=null==b.TRAINER_NAME?"N/A":b.TRAINER_NAME,B=null==b.AGE?"N/A":b.AGE,t=b.WEIGHT_VALUE,k=b.WEIGHT_UNITS,y=null==b.FORM?"N/A":b.FORM,A=null==b.DAYS_SINCE_LAST_RUN?"N/A":b.DAYS_SINCE_LAST_RUN,C=null==b.JOCKEY_CLAIM?"N/A":b.JOCKEY_CLAIM;b=null==b.WEARING?"N/A":b.WEARING;null==d&&e&&(d="saddle_"+h);null==k||null==t?t="N/A":"pounds"==k?(k=parseInt(MathUtil.decimal.multiply(t,.071429)),t=k+"-"+parseInt(t-14*k)):t+=k;k=c.find("#horseInfo");e?k.find("#horseBox").hide():null!=h&&null!=p?(k.find("#clothNumberAlpha").html(h),
k.find("#stallDraw").html("("+p+")")):(k.find("#clothNumberAlpha").html(h),k.find("#stallDraw").hide());e?(k.find("#uniform").addClass(d.replace(".gif","")),k.find("#uniform").find("img").hide()):k.find("#uniform").find("img").prop("src","https://content-cache.cdnbf.net/feeds_images/Horses/SilkColours/"+d);null==r?k.find("#jockyName").hide():k.find("#jockyName").html(r);k.find("#runnerName").html(f.runnerName);k.find("#trainerName").html(x);k.find("#ageWeight").html(B+" / "+t);k.find("#form").html(y);
k.find("#daysSinceLastRun").html(A);k.find("#jockeyClam").html(C);k.find("#wearing").html(b);k.show();0<l.length&&k.find("#marketDepthBtn").attr("onclick",l);c.find("p").hide()}}};FullMarketUtil.appendGreyhoundJockeyColor=function(c,d,e,f,l){e=c.find("#horseInfo");if(!e.is(":visible")){e.removeClass("horse-info").addClass("dog-info");e.find("#horseInfoHover").hide();e.find("#horseBox").hide();var h=!1;null==d.countryCode||"AU"!=d.countryCode&&"NZ"!=d.countryCode||(h=!0);d=f.runnerName;f=[];-1<d.indexOf(".")&&
(f=d.split("."));d=f[0];f=f[1];var b="";h&&(b+="aus_");b+="silk_"+d+".png";e.find("#jockyName").html(f);e.find("#uniform").find("img").prop("src","/images/greyhound/"+b);e.show();0<l.length&&e.find("#marketDepthBtn").attr("onclick",l);c.find("p").hide()}};FullMarketUtil.setBrowserTabName=function(c){if(c&&0<c.length)try{$j("head title",window.parent.document).text(c)}catch(d){Trace.printStackTrace(d)}};var J=[{name:"fancyBet",elem:["[id^=fancyBetTable_]"]},{name:"sportsBookBet",elem:["#sportsBookWrap"]}];
FullMarketUtil.view=function(c){UiUtils.view(c,J);"sportsBookBet"==c&&(c=$j("#overWrap").find("#sportsBookWrap"),SportsBookEventHandler.extandMarket(c))};FullMarketUtil.isViewMultiMarket=function(){return-1<location.href.indexOf("multiMarkets")}})();

