var StringUtil={startsWith:function(a,b){return a.substr(0,b.length)==b},endsWith:function(a,b){return a.substring(a.length-b.length)==b},concat:function(a,b){return new String(a.toString()+b)},toCharArray:function(a){for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a.charAt(c);return b},containedChinese:function(a){return/[^\x00-\xff]/g.test(a)},getlength:function(a){var b=a.match(/[^\x00-\xff]/ig);return a.length+(null==b?0:b.length)},trim:function(a){return a.replace(/(^\s*)|(\s*$)/g,"")},getXMLEncode:function(a){a=
a.replace("&","&amp;");a=a.replace("<","&lt;");a=a.replace(">","&gt;");a=a.replace("'","&apos;");a.replace('"',"&quot;")},replaceAll:function(a,b,c){for(var d=a.indexOf(b);-1!=d;)a=a.replace(b,c),d=a.indexOf(b);return a},isOnlyNumberAndColon:function(a){return/^[\d:]+$/.test(a)?!0:!1},ucfirst:function(a){a=a.toLowerCase();return a=a.replace(/\b\w+\b/g,function(b){return b.substring(0,1).toUpperCase()+b.substring(1)})},commaSeparateNumber:function(a){return a.toString().replace(/\D/g,"").replace(/\B(?=(\d{3})+(?!\d))/g,
"")},isEmpty:function(a){a&&(a=StringUtil.trim(a));return!a}},ArrayUtil={max:function(a){var b,c=a[0];for(b=1;b<a.length;b++)c<a[b]&&(c=a[b]);return c},contains:function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return!0;return!1},remove:function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return a.splice(c,1),!0;return!1},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},indexOf:function(a,b,c){if("function"==typeof a.indexOf)return a.indexOf(b,c);c=c||0;for(var d=a.length;c<
d;c++)if(a[c]===b)return c;return-1}},ElementUtil={hiddenElement:function(a){a=document.getElementsByTagName(a);for(var b=0;b<a.length;b++)a[b].style.visibility="hidden"},showElement:function(a){a=document.getElementsByTagName(a);for(var b=0;b<a.length;b++)a[b].style.visibility=""}},SelectUtil={selectOption:function(a,b,c){isNaN(c)?document.getElementsByName(a)[0].value=b:document.getElementsByName(a)[c].value=b},addSelectOption:function(a,b,c){var d=document.createElement("OPTION");d.text=b;d.value=
c;a.options.add(d);return d},removeSelectOption:function(a){a=document.getElementsByName(a)[0];for(var b=a.options.length-1;0<=b;b--)a.options[b].selected&&a.removeChild(a.options[b])}},CheckboxUtil={checkedByValues:function(a,b,c){a=document.getElementsByName(a);var d=b;ArrayUtil.isArray(d)||(d=[b]);for(b=0;b<d.length;b++)for(var f=0;f<a.length;f++)if(a[f].value==d[b]){a[f].checked=c;break}},checkedAll:function(a){for(var b=document.getElementsByTagName("input"),c=0;c<b.length;c++)"checkbox"==b[c].type&&
(b[c].checked=a)}},RadioUtil={checkedByValue:function(a,b){a=document.getElementsByName(a);if(""===b)a[0].checked=!0;else for(var c=0;c<a.length;c++)if(a[c].value==b){a[c].checked=!0;break}},getIndex:function(a){a=document.getElementsByName(a);for(var b=0;b<a.length;b++)if(a[b].checked)return b;return-1},getChecked:function(a){a=document.getElementsByName(a);for(var b=0;b<a.length;b++)if(a[b].checked)return a[b].value;return null}},ObjectUtil={isObject:a=>"undefined"!==typeof a&&null!==a,isNotObject:a=>
!ObjectUtil.isObject(a),clone:function(a){var b={};for(elements in a)b[elements]=a[elements];return b},cloneAll:function(a){function b(){}b.prototype=a;a=new b;for(var c in a)"object"==typeof a[c]&&(a[c]=a[c].cloneAll());return a},isEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},toJSON:function(a){var b="";for(e in a)"function"!==typeof a[e]&&(b=b+'"'+e+'":',b="string"===typeof a[e]?b+'"'+a[e]+'",':b+a[e]+",");return"{"+b.substring(0,b.length-1)+"}"}},IFrameUtil={calcHeight:function(a){var b=
document.getElementById(a);b.contentWindow.scrollTo(0,0);var c=b.contentWindow.document.documentElement.scrollHeight;b=b.contentWindow.document.body.scrollHeight;b>c&&(c=b);document.getElementById(a).height=c},SetCwinHeight:function(a,b){a=document.getElementById(a);if(document.getElementById&&a&&!window.opera)if("number"==typeof window.innerWidth){var c=a.contentDocument.body.offsetHeight;a.height=c+(b?b:0)}else c=a.contentWindow.document.body.scrollHeight+"px",a.style.height=c+(b?b:0)},reinitIframe:function(a){try{a.height=
Math.max(a.contentWindow.document.body.scrollHeight+20,a.contentWindow.document.documentElement.scrollHeight+20)}catch(b){}}};
function TreeMap(){this.elements=[];this.size=function(){return this.elements.length};this.put=function(a,b){for(var c=0;c<this.elements.length;c++)if(this.elements[c].key==a){this.elements[c].value=b;return}c==this.elements.length&&this.elements.push({key:a,value:b})};this.putAll=function(a){a=a.entrySet();for(var b=0;b<a.length;b++)this.put(a[b].key,a[b].value)};this.remove=function(a){for(var b=0;b<this.elements.length;b++)if(this.elements[b].key==a)return this.elements.splice(b,1),!0;return!1};
this.containsKey=function(a){for(var b=0;b<this.elements.length;b++)if(this.elements[b].key==a)return!0;return!1};this.get=function(a){for(var b=0,c=this.elements.length;b<c;b++)if(this.elements[b].key==a)return this.elements[b].value;return null};this.values=function(){for(var a=Array(this.elements.length),b=0;b<this.elements.length;b++)a[b]=this.elements[b].value;return a};this.sort=function(a){this.elements=this.elements.sort(a)};this.entrySet=function(){return this.elements};this.clear=function(){this.elements.length=
0};this.keySet=function(){for(var a=Array(this.elements.length),b=0;b<this.elements.length;b++)a[b]=this.elements[b].key;return a};this.showOrder=function(){for(var a="",b=0;b<this.elements.length;b++)a+=this.elements[b].key+",";return a};this.sortByKey=function(){this.elements.sort(function(a,b){return a.key-b.key})}}
function HashMap(){this.length=0;this.elements={};this.size=function(){return this.length};this.put=function(a,b){this.elements.hasOwnProperty(a)||this.length++;this.elements[a]=b};this.putAll=function(a){for(var b in a)this.elements.hasOwnProperty(b)||this.length++,this.elements[b]=a[b]};this.remove=function(a){return this.elements.hasOwnProperty(a)?(this.length--,delete this.elements[a],!0):!1};this.containsKey=function(a){return this.elements.hasOwnProperty(a)};this.get=function(a){return this.elements.hasOwnProperty(a)?
this.elements[a]:null};this.values=function(){var a=Array(this.length),b=0,c;for(c in this.elements)a[b++]=this.elements[c];return a};this.entrySet=function(){var a=Array(this.length),b=0,c;for(c in this.elements)a[b++]={key:c,value:this.elements[c]};return a};this.clear=function(){this.elements={};this.length=0};this.keySet=function(){var a=Array(this.length),b=0,c;for(c in this.elements)a[b++]=c;return a}}"undefined"==typeof EventUtils&&(EventUtils={});
(function(){EventUtils.isReady=function(a){return 0<(a&EventStatusType.READY.unique())};EventUtils.isCancel=function(a){return 0<(a&EventStatusType.CANCEL.unique())};EventUtils.isOpen=function(a){return 0<(a&EventStatusType.OPEN.unique())};EventUtils.isSuspend=function(a){return 0<(a&EventStatusType.SUSPEND.unique())};EventUtils.isClose=function(a){return 0<(a&EventStatusType.CLOSE.unique())};EventUtils.isEnd=function(a){return 0<(a&EventStatusType.END.unique())};EventUtils.isUnsettled=function(a){return 0<
(a&EventStatusType.UNSETTLED.unique())};EventUtils.isSettled=function(a){return 0<(a&EventStatusType.SETTLED.unique())};EventUtils.isVoided=function(a){return 0<(a&EventStatusType.VOIDED.unique())};EventUtils.isCloseSite=function(a,b){return WebSiteUtil.isCloseSite(a,b)};EventUtils.isBookModeShow=function(a,b){var c=WebSiteType.getInstanceOf(b);return null==c||!c.isSkyInplayGroup()&&!c.isFancyFairGroup()?!0:WebSiteUtil.isBookMode(a,b)}})();"undefined"==typeof CompetitionUtils&&(CompetitionUtils={});
(function(){CompetitionUtils.isCloseSite=function(a,b){return WebSiteUtil.isCloseSite(a,b)}})();"undefined"==typeof GameProductUtils&&(GameProductUtils={});(function(){GameProductUtils.isClose=function(a){return 0==a}})();"undefined"==typeof JsCache&&(JsCache={});
(function(){var a={};JsCache.get=function(b){if(null==b||0==b.length)return null;var c=a[b];if(!c){c=$j(b);if(0==c.length)return;a[b]=c}return c};JsCache.clone=function(b){b=JsCache.get(b);return null==b?null:b.clone()};JsCache.removeCache=function(b){if(null==b||0==b.length)return null;a[b]=null}})();"undefined"==typeof JsonUtil&&(JsonUtil={});
(function(){JsonUtil.stringify=function(a){if("JSON"in window)return JSON.stringify(a);var b=typeof a;if("object"!=b||null===a)return"string"==b&&(a='"'+a.replace(/"/g,'\\"')+'"'),String(a);var c,d=[],f=a&&a.constructor==Array;for(c in a){var g=a[c];b=typeof g;a.hasOwnProperty(c)&&("string"==b?g='"'+g.replace(/"/g,'\\"')+'"':"object"==b&&null!==g&&(g=JsonUtil.stringify(g)),d.push((f?"":'"'+c+'":')+String(g)))}return(f?"[":"{")+String(d)+(f?"]":"}")}})();
"undefined"==typeof WindowEventUtil&&(WindowEventUtil={});(function(){WindowEventUtil.stopEvent=function(a,b,c){a||(a=window.event);b||c||(c=b=!0);b&&(a.stopPropagation?a.stopPropagation():a.cancelBubble=!0);c&&(a.preventDefault?a.preventDefault():a.returnValue=!1);return!1}})();"undefined"==typeof UiUtils&&(UiUtils={});
(function(){var a="- Sun Mon Tue Wed Thu Fri Sat".split(" "),b="- Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");UiUtils.bindToExpand=function(c,d,f){var g=c.parent().parent();c.click(function(){g.hasClass("close")?(g.removeClass("close"),null!=d&&"function"===typeof d&&d.call(this,c)):(g.addClass("close"),null!=f&&"function"===typeof f&&f.call(this,c))})};UiUtils.getShortDayName=function(c){return c<a.length?a[c]:"-"};UiUtils.getDayName=function(c){return c<b.length?b[c]:"-"};
UiUtils.view=function(c,d){for(var f=0;f<d.length;f++)for(var g=0;g<d[f].elem.length;g++){var h=d[f].elem[g];c==d[f].name?null!=$j(h)?$j(h).show():Trace.error(h+" not found"):null!=$j(h)?$j(h).hide():Trace.error(h+" not found")}};UiUtils.appendHeight=function(c){var d=0,f=$j("#overWrap"),g=$j("#gameHead"),h=$j("#inPlayTab"),k=$j("#sportFilter"),l=$j(".marquee-box");g.is(":visible")&&0<g.height()&&(d=g.height());h.is(":visible")&&0<h.height()&&(d+=49);k.is(":visible")&&0<k.height()&&(d+=55);c&&(d=
0);"true"==PageConfig.ENABLE_ONE_CLICK_BET&&$j("[name=oneClickBetStakeBox]").is(":visible")&&(0<d&&!h.is(":visible")&&(d+=15),d+=31);l.is(":visible")&&0<l.height()&&(d=h.is(":visible")&&0<h.height()?d+25:d+26);f.attr("style","height: calc(100% - "+d+"px)")};UiUtils.removeContents=function(c){c.contents().filter(function(){return 3==this.nodeType}).remove()};UiUtils.scrollToElement=function(c,d){if(0!=c.length){d=d.offset().top;c=c.offset().top;var f=$j("body").scrollTop();180==orientation||0==orientation?
$j("html, body").animate({scrollTop:c-d},"fast"):(90==orientation||-90==orientation)&&$j("html, body").animate({scrollTop:c+f},"fast")}}})();String.prototype.endsWith||(String.prototype.endsWith=function(a,b){var c=this.toString();if("number"!==typeof b||!isFinite(b)||Math.floor(b)!==b||b>c.length)b=c.length;b-=a.length;a=c.lastIndexOf(a,b);return-1!==a&&a===b});"undefined"==typeof PositionUtils&&(PositionUtils={});
(function(){PositionUtils.getPosition=function(a){for(var b=0,c=0,d=0;d<a.length;d++){var f=a[d].position();b=MathUtil.decimal.add(f.left,b);c=MathUtil.decimal.add(f.top,c)}"true"==PageConfig.ENABLE_ZOOM&&1<ZoomHandler.zoomLevel&&(BrowserUtil.isFirefox()||BrowserUtil.isIE()||BrowserUtil.isEdge())&&(b=MathUtil.decimal.divide(b,ZoomHandler.zoomLevel),c=MathUtil.decimal.divide(c,ZoomHandler.zoomLevel));return{left:b,top:c}}})();"undefined"==typeof RateUtils&&(RateUtils={});
(function(){RateUtils.convertRate=function(a,b,c){return MathUtil.decimal.divide(MathUtil.decimal.multiply(a,b),c)}})();"undefined"==typeof BrowserUtil&&(BrowserUtil={});
(function(){var a=!!window.opr&&!!opr.addons||!!window.opera||0<=navigator.userAgent.indexOf(" OPR/"),b="undefined"!==typeof InstallTrigger,c=/constructor/i.test(window.HTMLElement)||"[object SafariRemoteNotification]"===(!window.safari||safari.pushNotification).toString(),d=!!document.documentMode,f=!d&&!!window.StyleMedia,g=!!window.chrome&&!!window.chrome.webstore,h=(g||a)&&!!window.CSS;BrowserUtil.isOpera=function(){return a};BrowserUtil.isFirefox=function(){return b};BrowserUtil.isSafari=function(){return c};
BrowserUtil.isIE=function(){return d};BrowserUtil.isEdge=function(){return f};BrowserUtil.isChrome=function(){return g};BrowserUtil.isBlink=function(){return h}})();"undefined"==typeof MarketUtil&&(MarketUtil={});
(function(){MarketUtil.isInactive=function(a){return a==MarketStatusType.Inactive.unique()};MarketUtil.isOpen=function(a){return a==MarketStatusType.Open.unique()};MarketUtil.isSuspend=function(a){return a==MarketStatusType.Suspend.unique()};MarketUtil.isClosed=function(a){return a==MarketStatusType.Closed.unique()};MarketUtil.isCloseSite=function(a,b){return WebSiteUtil.isCloseSite(a,b)};MarketUtil.isBookModeShow=function(a,b){var c=WebSiteType.getInstanceOf(b);return null==c||!c.isSkyInplayGroup()&&
!c.isFancyFairGroup()?!0:WebSiteUtil.isBookMode(a,b)};MarketUtil.isLineMarket=function(a,b){return"INNINGS_RUNS"==a&&BetfairMarketBettingType.LINE.unique()==b};MarketUtil.isAsiaHandicapMarket=function(a){return null==a?!1:"ASIAN_HANDICAP"==a.marketType};MarketUtil.getLineMarketActualRuns=function(a){return MathUtil.decimal.subtract(a,.5)};MarketUtil.getLineMarketDisplayRuns=function(a){return MathUtil.decimal.add(a,.5)}})();"undefined"==typeof SelectionUtil&&(SelectionUtil={});
(function(){SelectionUtil.isRemoved=function(a){return a==SelectionStatusType.Removed.unique()};SelectionUtil.isActive=function(a){return a==SelectionStatusType.Active.unique()};SelectionUtil.isWinner=function(a){return a==SelectionStatusType.Winner.unique()};SelectionUtil.isLoser=function(a){return a==SelectionStatusType.Loser.unique()};SelectionUtil.isPlaced=function(a){return a==SelectionStatusType.Placed.unique()};SelectionUtil.isRemovedVacant=function(a){return a==SelectionStatusType.RemovedVacant.unique()};
SelectionUtil.isHidden=function(a){return a==SelectionStatusType.Hidden.unique()};SelectionUtil.isCloseSite=function(a,b){return WebSiteUtil.isCloseSite(a,b)};SelectionUtil.isSuspendSite=function(a,b){return WebSiteUtil.isSuspendSite(a,b)};SelectionUtil.isBookMode=function(a,b){return WebSiteUtil.isBookMode(a,b)};SelectionUtil.isBookSuspend=function(a,b){return WebSiteUtil.isBookSuspend(a,b)};SelectionUtil.isShowSelection=function(a,b,c){return WebSiteType.getInstanceOf(c).isBookModeGroup()?SelectionUtil.isBookMode(b,
c):!SelectionUtil.isCloseSite(a,c)};SelectionUtil.isShowSuspend=function(a,b,c){return WebSiteType.getInstanceOf(c).isBookModeGroup()?SelectionUtil.isBookSuspend(b,c):SelectionUtil.isSuspendSite(a,c)}})();"undefined"==typeof MapUtil&&(MapUtil={});(function(){MapUtil.cloneMap=function(a){var b=new HashMap;a=a.entrySet();for(var c in a){var d=JSON.parse(JSON.stringify(a[c].key)),f=JSON.parse(JSON.stringify(a[c].value));b.put(d,f)}return b}})();
var IPCheckUtil={isIPv6Format:function(a){return/((^s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))s*$)|(^s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]d|1dd|[1-9]?d)(.(25[0-5]|2[0-4]d|1dd|[1-9]?d)){3}))|:)))(%.+)?s*$))/.test(a)?!0:
!1},isIPv4Format:function(a){return/^([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])$/.test(a)?!0:!1},isIPv4SubnetFormat:function(a){return/^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9]))$/.test(a)}};"undefined"==typeof WebSiteUtil&&(WebSiteUtil={});
(function(){WebSiteUtil.isCloseSite=function(a,b){return WebSiteType.getInstanceOf(b).isSkyInplayGroup()||WebSiteType.getInstanceOf(b).isFancyFairGroup()?!1:WebSiteUtil.isContainSite(a,b)};WebSiteUtil.isSuspendSite=function(a,b){return WebSiteUtil.isCloseSite(a,b)};WebSiteUtil.isBookMode=function(a,b){b=WebSiteType.getInstanceOf(b);if(null==b||!b.isSkyInplayGroup()&&!b.isFancyFairGroup())return!1;var c=WebSiteType.SKYINPLAY.unique();b.isFancyFairGroup()&&(c=WebSiteType.FANCYFAIR.unique());return WebSiteUtil.isContainSite(a,
c)};WebSiteUtil.isBookSuspend=function(a,b){b=WebSiteType.getInstanceOf(b);if(null==b||!b.isSkyInplayGroup()&&!b.isFancyFairGroup())return!1;var c=WebSiteType.SKYINPLAY.unique();b.isFancyFairGroup()&&(c=WebSiteType.FANCYFAIR.unique());return WebSiteUtil.isContainSite(a,c)};WebSiteUtil.isDisableBettingSite=function(a,b){if(null==a||0==a.length)return!1;b=WebSiteType.getInstanceOf(b);if(null==b||!b.isSkyInplayGroup()&&!b.isFancyFairGroup())return!1;var c=WebSiteType.SKYINPLAY.unique();b.isFancyFairGroup()&&
(c=WebSiteType.FANCYFAIR.unique());return WebSiteUtil.isContainSite(a,c)};WebSiteUtil.isContainSite=function(a,b){if(null==a)return!1;try{if(-1<JSON.parse(a).indexOf(b.toString()))return!0}catch(c){Trace.log(c)}return!1};WebSiteUtil.isAllowRaceEventLay=function(a){return a.isRacingEvent()?a.value==EventType.HORSE_RACING.value?PageConfig.ENABLE_RACING_WEBSITE_HORSE_PLAY_LAY||PageCommonConfig.ENABLE_RACING_WEBSITE_HORSE_PLAY_LAY:a.value==EventType.GREYHOUND_RACING.value?PageConfig.ENABLE_RACING_WEBSITE_GREYHOUND_PLAY_LAY||
PageCommonConfig.ENABLE_RACING_WEBSITE_GREYHOUND_PLAY_LAY:!1:!0};WebSiteUtil.isNotAllowRaceEventLay=function(a){return!WebSiteUtil.isAllowRaceEventLay(a)}})();"undefined"==typeof BookMakerTransactionUtils&&(BookMakerTransactionUtils={});(function(){BookMakerTransactionUtils.isFancyBetPLEventType=function(a){return EventType.CRICKET.unique()===a||EventType.TENNIS.unique()===a||EventType.KABADDI.unique()===a||EventType.ELECTION.unique()===a}})();"undefined"==typeof RetryUtils&&(RetryUtils={});
(function(){RetryUtils.retry=(a,b=3)=>new Promise(async(c,d)=>{for(;0<b;){b--;try{const f=await a();c(f);break}catch(f){0===b&&d(f)}}})})();

