"undefined"==typeof NaviMenuUtil&&(NaviMenuUtil={});
(function(){NaviMenuUtil.naviMenuList=function(e,a){if(1==a.length)return null==e&&(Trace.error(a),Trace.error(e)),e.children;var b=null,c=[],d;for(d in a)c.push(a[d]);c=c.splice(1,a.length);for(var f in c)a=c[f],b=0==f?NaviMenuUtil.searchList(a,e.children):NaviMenuUtil.searchList(a,b.children);return b.children};NaviMenuUtil.searchList=function(e,a){var b=null,c;for(c in a){var d=a[c];if(d.id==e){b=d;break}}return b};NaviMenuUtil.copyLastNaviIds=function(e){var a=[];if(null!=e&&0<e.length)for(var b in e)a.push(e[b]);
return a};NaviMenuUtil.sortMenuNode=function(e,a,b,c,d,f,m,g,h,k,l){if("Others"==a)return 1;if("Others"==b)return-1;e=EventType.getInstanceOf(e);if(!(null==e||PageConfig.isEnterFairGroup||EventType.SOCCER.unique()!=e.unique()&&EventType.E_SOCCER.unique()!=e.unique()||"GROUP"!=c&&"EVENT"!=c&&"GROUP"!=d&&"EVENT"!=d)){if("English Soccer"==a)return-1;if("English Soccer"==b)return 1;if("Italian Soccer"==a)return-1;if("Italian Soccer"==b)return 1;if("Spanish Soccer"==a)return-1;if("Spanish Soccer"==b)return 1;
if("Scottish Soccer"==a)return-1;if("Scottish Soccer"==b)return 1;if("Portuguese Soccer"==a)return-1;if("Portuguese Soccer"==b)return 1;if("UEFA Champions League"==a)return-1;if("UEFA Champions League"==b)return 1;if("UEFA Europa League"==a)return-1;if("UEFA Europa League"==b)return 1;if("FIFA World Cup 2018"==a)return-1;if("FIFA World Cup 2018"==b)return 1;if("English Premier League"==a)return-1;if("English Premier League"==b)return 1;if("The Championship"==a)return-1;if("The Championship"==b)return 1;
if("League One"==a)return-1;if("League One"==b)return 1;if("League Two"==a)return-1;if("League Two"==b)return 1;if("Serie A"==a)return-1;if("Serie A"==b)return 1;if("Spanish Cup"==a)return-1;if("Spanish Cup"==b)return 1;if("Scottish Premiership"==a)return-1;if("Scottish Premiership"==b)return 1;if("Primeria Liga"==a)return-1;if("Primeria Liga"==b)return 1;a.localeCompare(b);return a.localeCompare(b)}if(0!=c.localeCompare(d)){if("GROUP"==c&&"Game Betting"==a)return 1;if("GROUP"==d&&"Game Betting"==
b||"GROUP"==c&&"MARKET"==d)return-1;if("GROUP"==d&&"MARKET"==c||"MARKET"==c&&"EVENT"==d)return 1;if("MARKET"==d&&"EVENT"==c)return-1;if(PageConfig.selectEventType==EventType.HORSE_RACING.value){if("GROUP"==c&&"EVENT"==d)return-1;if("GROUP"==d&&"EVENT"==c||"RACE"==c&&"RACE"!=d)return 1;if("RACE"==d&&"RACE"!=c)return-1}if("EVENT_TYPE"==c&&1==f)return-1;if("EVENT_TYPE"==d&&1==m)return 1}if(null!=e&&e.isRacingEvent()&&"MARKET"==c&&"MARKET"==d)return 0==g.localeCompare(h)?"WIN"==k?-1:"WIN"==l?1:"PLACE"==
k?-1:"PLACE"==l?1:a.localeCompare(b):g.localeCompare(h);if("Match Odds"==a)return-1;if("Match Odds"==b)return 1;if("Moneyline"==a)return-1;if("Moneyline"==b)return 1;if(0<=a.indexOf("(F/C)")&&0<=b.indexOf("(F/C)"))return a.localeCompare(b);if(0<=a.indexOf("(F/C)"))return 1;if(0<=b.indexOf("(F/C)"))return-1;if("EVENT_TYPE"!=c&&"EVENT_TYPE"!=d)return a.localeCompare(b)};NaviMenuUtil.sortSoccerMenuNode=function(e,a,b,c,d){return a<b?-1:a>b?1:"Match Odds"==c?-1:"Match Odds"==d?1:"Moneyline"==c?-1:"Moneyline"==
d?1:0<=c.indexOf("(F/C)")&&0<=d.indexOf("(F/C)")?c.localeCompare(d):0<=c.indexOf("(F/C)")?1:0<=d.indexOf("(F/C)")?-1:c.localeCompare(d)};NaviMenuUtil.sortTopCompetitionMenuNode=function(e,a,b,c){return b==c?e.localeCompare(a):b>c?1:-1};NaviMenuUtil.sortFcMarket=function(e,a){var b=e.marketType,c=a.marketType;return"WIN"==b?-1:"WIN"==c?1:"PLACE"==b?-1:"PLACE"==c?1:"FORECAST"==b?-1:"FORECAST"==c?1:e.name.localeCompare(a.name)}})();

