"undefined"==typeof OneClickBetHandler&&(OneClickBetHandler={});
(function(){function u(a){var b=$j("#oneClickLoadingWrap"),e=JsCache.get("#openBetSlip"),c=b.find("#loadPending"),d=b.find("#pendingNum"),g=b.find("#oneClickTime"),h=OneClickBetHandler.pending.length;1<h?c.show():c.hide();0<h?(null!=a&&(null!=l&&(clearTimeout(l),l=null),v(g,5)),d.html(h-1),b.show(),e.css("height","calc(100% - 131px)"),a=JsCache.get(".matched-wrap"),a.is(":visible")||(a.show(),JsCache.get(".slip-wrap").removeClass("no-open-bet_slip"))):(b.hide(),e.css("height","calc(100% - 35px)"))}
function v(a,b){0<b?(a.html(I18N.get("form.button.placeBets")+I18N.get("form.button.placeBets.forNumberSec",[b])),b--,l=setTimeout(function(){v(a,b)},1E3)):(a.html(I18N.get("form.button.placeBets")+I18N.get("form.button.placeBets.processing")),clearTimeout(l),l=null)}function p(a,b,e){$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/setPlayerOneClickBet",data:{isOneClickBet:a,oneClickBetStakeIndex:b,isConfirmOneClickBet:e},success:function(c){c&&("SUCCESS"==c.result?(null!=
c.isOneClickBet&&c.isOneClickBet!=PageConfig.isOneClickBet&&(PageConfig.isOneClickBet=c.isOneClickBet,q()),null!=c.oneClickBetStakeIndex&&PageConfig.oneClickBetStakeIndex!=c.oneClickBetStakeIndex&&(PageConfig.oneClickBetStakeIndex=c.oneClickBetStakeIndex),null!=c.isConfirmOneClickBet&&c.isConfirmOneClickBet!=PageConfig.isConfirmOneClickBet&&(PageConfig.isConfirmOneClickBet=c.isConfirmOneClickBet)):(PageConfig.isOneClickBet=0,q()))},error:function(c){Trace.log(c);PageConfig.isOneClickBet=0;q()}})}
function y(a){a.removeClass("select");1==PageConfig.isOneClickBet&&a.addClass("select")}function q(){var a=$j("#oneClickBetStakeBox"),b=$j("#editOneClickBetStakeBox");1==PageConfig.isOneClickBet&&OneClickBetHandler.isEnable()?a.show():(a.hide(),b.hide());UiUtils.appendHeight();a=CookieUtil.getCookie("isHideOneClickBetDialog_"+PageConfig.userID);b=JsCache.get("[name=oneClickBetDialog]");var e=JsCache.get("#oneClickBetStakeBox"),c=JsCache.get("#oneClickBetDialog");e.removeClass("white-halo");c.removeClass("white-halo");
1==PageConfig.isOneClickBet&&null==a&&OneClickBetHandler.isEnable()&&0==PageConfig.isConfirmOneClickBet?(b.fadeIn(),e.addClass("white-halo"),c.addClass("white-halo")):b.fadeOut()}function m(){var a=w(),b=$j("#oneClickBetStakeBox"),e=$j("#editOneClickBetStakeBox"),c=b.find("[name=betStake]"),d=e.find("[name=editBetStake]");$j.each(c,function(g,h){h=b.find(h);h.html(a[g]);h.removeClass("select");PageConfig.oneClickBetStakeIndex==g&&(h.addClass("select"),PageConfig.selectBetStake=a[g])});$j.each(d,function(g,
h){h=e.find(h);h.val(a[g])})}function z(a){var b=[],e=a.find("[name=editBetStake]");$j.each(e,function(c,d){d=a.find(d);c=d.val();MathUtil.isNumeric(c,!1,!1)&&8>=c.length?(c<PageConfig.minBet&&(c=PageConfig.minBet),b.push(c)):NoticeHandler.error("[ "+c+" ] is illegal")});b.toString()==PageConfig.oneClickBetStake?(m(),OneClickBetHandler.view("normal")):4!=b.length?(m(),OneClickBetHandler.view("normal")):A(b.toString())}function A(a){$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/setOneClickBetStake",
data:{newOneClickBetStake:a},success:function(b){b&&(b.error?(NoticeHandler.error(b.error),x()):("SUCCESS"==b.result&&null!=b.oneClickBetStake&&(PageConfig.oneClickBetStake=b.oneClickBetStake,m()),OneClickBetHandler.view("normal")))},error:function(b){Trace.log(b);x()}})}function x(){PageConfig.oneClickBetStake="";m();OneClickBetHandler.view("normal")}function w(){if("null"==PageConfig.oneClickBetStake||""==PageConfig.oneClickBetStake)for(var a=1;4>=a;a++){var b=CoinType.getInstanceOf(PageConfig.playerCurrency,
a);PageConfig.oneClickBetStake=1==a?b.amounts:PageConfig.oneClickBetStake+(","+b.amounts)}return PageConfig.oneClickBetStake.split(",")}function B(a){var b=a.eventId;a=a.marketId;if(MultiMarketsHandler.isViewMultiMarket()||1==PageConfig.isPoliticsPage)var e=$j("[id^=multiMarket_"+b+"_"+a.replace(".","_")+"]");else if(-1==PageConfig.selectEventId)e="#InPlay"==location.hash?$j("#event_"+b):$j("#highLightEvent_"+b);else{var c=$j("#fullMarketBetsWrap:visible");b==c.attr("eventid")&&a==c.attr("marketid")?
e=c:0<$j("#popMarketItem_"+a.replace(".","_")).length&&(e=$j("#popMarketItem_"+a.replace(".","_")))}return e}function r(a,b){b?(a.addClass("disabled"),a.addClass("cooldown")):(a.removeClass("cooldown"),a.removeClass("disabled"))}OneClickBetHandler.pending=[];OneClickBetHandler.init=function(){var a=$j("#oneClickSetting"),b=$j("#oneClickBetStakeBox"),e=b.find("[name=betStake]"),c=$j("#editOneClickBetStakeBox"),d=c.find("[name=editBetStake]"),g=$j("[name=oneClickBetDialog]");OneClickBetHandler.show();
y(a);OneClickBetHandler.pending=[];a.unbind("click").click(function(){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())a.hasClass("select")?(a.removeClass("select"),p(0,PageConfig.oneClickBetStakeIndex,PageConfig.isConfirmOneClickBet)):(a.addClass("select"),p(1,PageConfig.oneClickBetStakeIndex,PageConfig.isConfirmOneClickBet))});e.unbind("click").click(function(){if(0!=PageConfig.isConfirmOneClickBet){var h=$j(this);var f=w();h=h.attr("index");PageConfig.oneClickBetStakeIndex!=h&&(e.removeClass("select"),
b.find("[index="+h+"]").addClass("select"),p(PageConfig.isOneClickBet,h,PageConfig.isConfirmOneClickBet),PageConfig.selectBetStake=f[h])}});b.find("#edit").unbind("click").click(function(){0!=PageConfig.isConfirmOneClickBet&&(OneClickBetHandler.view("edit"),c.find("[name=editBetStake]")[0].select())});c.find("#save").unbind("click").click(function(){z(c)});g.find("#ok").unbind("click").click(function(){1==g.find("#dontShow").prop("checked")&&CookieUtil.setCookie("isHideOneClickBetDialog_"+PageConfig.userID,
"1",999);p(PageConfig.isOneClickBet,PageConfig.oneClickBetStakeIndex,1);g.fadeOut();b.removeClass("white-halo");JsCache.get("#oneClickBetDialog").removeClass("white-halo")});d.unbind("click").click(function(){$j(this).select()})};OneClickBetHandler.show=function(){var a=$j("#oneClickSetting");OneClickBetHandler.isEnable()?a.show():a.hide();m();q()};OneClickBetHandler.isEnable=function(){return PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE?PageConfig.ENABLE_ONE_CLICK_BET_ALL_PAGE:0<=location.href.indexOf("fullMarket")||
0<=location.href.indexOf("multiMarkets")||0<=location.href.indexOf("politics")};OneClickBetHandler.isEnableSubmitOneClickBet=function(){return 1==PageConfig.isOneClickBet&&1==PageConfig.isConfirmOneClickBet};OneClickBetHandler.placeBet=function(a,b,e,c,d,g,h,f){var k=parseFloat(a.html());1==f&&(k=parseFloat(a.attr("fullMarketOdds")));isNaN(k)&&(k=1.01);f=k;b=b.attr("eventType");k=BetHandler.getMinBet(e,c,b,f);k=parseFloat(k);var n=a.attr("inPlay");a=a.attr("handicap");parseFloat(PageConfig.selectBetStake)>
k&&(k=parseFloat(PageConfig.selectBetStake));e={sideType:h,odds:f,stake:k,eventType:b,eventId:e,marketId:c.replace("_","."),selectionId:d,inPlay:n,timestamp:(new Date).getTime(),selectionKey:g,handicap:a};OneClickBetHandler.submitBet(e)};OneClickBetHandler.submitBet=function(a){TxnHandler.clickResetBtn();var b=0,e="";PageConfig.ENABLE_LINE_MARKET&&LineMarketHandler.reverseSideType([a]);if(0!=a.length&&a){var c=B(a);$j.ajax({type:"POST",dataType:"JSON",url:"/exchange/member/playerService/exchange",
data:{bets:JSON.stringify([a]),isOneClickBet:1},beforeSend:function(){null!=a&&(OneClickBetHandler.pending.push(a),u(OneClickBetHandler.pending[0]));r(c,!0)},complete:function(){r(c,!1)},success:function(d){try{if(d.error)NoticeHandler.error(d.error);else if(0!=d.result.length){BetHandler.isOnBetting=!1;var g=[],h;for(h in d.result){var f=d.result[h];if("SUCCESS"==f.status){0==b&&""==e&&(b=f.eventId,e=f.marketId);null!=f.unMatchTicket&&DataBase.unMatchTicket.update([f.unMatchTicket]);null!=f.txn&&
DataBase.txn.update([f.txn]);var k=f.eventId+"_"+f.marketId;-1==ArrayUtil.indexOf(g,k)&&g.push(k)}else f.error&&NoticeHandler.error(f.error)}0!=b&&""!=e&&(TxnHandler.setEventIdAndMarketId(b,e,CategoryType.BETFAIR.unique()),b=0,e="");if(0<g.length)for(d=0;d<g.length;d++)k=g[d].split("_"),BetHandler.getWinLoss(k[0],k[1]);setTimeout(function(){TxnHandler.getUnMatchTicketsAndTxns()},250);TxnHandler.updateOpenBetSelectionBox();TxnHandler.addBlankSelectOption(PageConfig.selectEventId,PageConfig.selectMarketId);
TxnHandler.checkToHideOpenBets()}}catch(n){Trace.printStackTrace(n)}finally{0<OneClickBetHandler.pending.length&&OneClickBetHandler.pending.shift(),u(OneClickBetHandler.pending[0]),r(c,!1)}},error:function(d){Trace.printStackTrace(d)}});JsCache.get("#confirmBetList").hide();JsCache.get("#confirmBetFullBtn").hide()}};OneClickBetHandler.placeFancyBet=function(a,b,e,c,d,g,h){var f=DataBase.fancyBetMarkets.get(e,c);if(null==f)Trace.log("onclickbet fancy market"+c+" is null");else{a=parseFloat(f.min);
f=parseFloat(f.max);var k=parseFloat(PageConfig.selectBetStake);k<a?NoticeHandler.error("[Bet "+c+"_"+FancySideType.getInstanceOf(d).name+"] "+I18N.get("msg.member.minBet")):k>f?NoticeHandler.error("[Bet "+c+"_"+FancySideType.getInstanceOf(d).name+"] "+I18N.get("msg.member.maxBet")):(b={eventType:b,eventId:e,marketId:c,sideType:d,runs:g,odds:h,stake:k,timestamp:(new Date).getTime()},FancyBetHandler.submitBet(b,null,null,1,TopMenuHandler.isAcceptAnyOdds("fancyBet")?1:0))}};OneClickBetHandler.placeFeedingSiteBet=
function(a,b,e,c,d,g){a=DataBase.feedingSiteMarkets.get(e,c);if(null==a)Trace.log("oneClickBet FeedingSite market"+c+" is null");else{var h=parseFloat(a.min),f=parseFloat(a.max),k=parseFloat(PageConfig.selectBetStake);k<h?NoticeHandler.error("[Bet "+c+"_"+d+"] "+I18N.get("msg.member.minBet")):k>f?NoticeHandler.error("[Bet "+c+"_"+d+"] "+I18N.get("msg.member.maxBet")):(b={eventType:b,eventId:e,marketId:c,selectionId:d,odds:g,stake:k,betfairEventId:a.betfairEventId,timestamp:(new Date).getTime()},FeedingSiteBetHandler.submitBet(b,
null,null,1))}};OneClickBetHandler.placeSportsBookBet=function(a,b,e,c,d,g,h){var f=DataBase.sportsBookMarkets.get(b,c,d);if(null==f)Trace.log("oneClickBet sportsBookBet market"+d+" is null");else{var k=parseFloat(f.min),n=parseFloat(f.max),t=parseFloat(PageConfig.selectBetStake);t<k?NoticeHandler.error("[Bet "+d+"_"+g+"] "+I18N.get("msg.member.minBet")):t>n?NoticeHandler.error("[Bet "+d+"_"+g+"] "+I18N.get("msg.member.maxBet")):(a=a.prop("handicap"),e={apiSiteType:b,eventType:e,eventId:c,marketId:d,
selectionId:g,odds:h,stake:t,betfairEventId:f.betfairEventId,handicap:a,timestamp:(new Date).getTime()},SportsBookBetHandler.submitBet(e,b,TopMenuHandler.isAcceptAnyOdds("sportsBook")?1:0,null,null,1))}};OneClickBetHandler.placeBookMakerBet=function(a,b,e,c,d,g,h){var f=DataBase.bookMakerMarkets.get(e,c);if(null==f)Trace.log("oneClickBet bookMakerBet market"+c+" is null");else{a=parseFloat(f.min);f=parseFloat(f.max);var k=parseFloat(PageConfig.selectBetStake);k<a?NoticeHandler.error("[Bet "+c+"_"+
d+"] "+I18N.get("msg.member.minBet")):k>f?NoticeHandler.error("[Bet "+c+"_"+d+"] "+I18N.get("msg.member.maxBet")):BookMakerBetHandler.submitBet({eventType:b,eventId:e,marketId:c,selectionId:d,sideType:g,odds:h,stake:k},null,null,1,TopMenuHandler.isAcceptAnyOdds("fancyBet")?1:0)}};OneClickBetHandler.placeFinancialBet=function(a,b,e,c,d,g,h){var f=DataBase.financialMarkets.get(b,e,c);if(null==f)Trace.log("onclickbet financial market"+c+" is null");else{a=parseFloat(f.min);f=parseFloat(f.max);var k=
parseFloat(PageConfig.selectBetStake);k<a?NoticeHandler.error("[Bet "+c+"_"+FancySideType.getInstanceOf(d).name+"] "+I18N.get("msg.member.minBet")):k>f?NoticeHandler.error("[Bet "+c+"_"+FancySideType.getInstanceOf(d).name+"] "+I18N.get("msg.member.maxBet")):FinancialBetHandler.submitBet({apiSite:b,eventId:e,marketId:c,sideType:d,price:g,odds:h,stake:k},b,TopMenuHandler.isAcceptAnyOdds("financialBet")?1:0,null,null,!0)}};var l=null,C=[{name:"normal",elem:["#oneClickBetStakeBox"]},{name:"edit",elem:["#editOneClickBetStakeBox"]}];
OneClickBetHandler.view=function(a){UiUtils.view(a,C)};OneClickBetHandler.showMsg=function(a,b,e,c,d){var g=$j(".matched-wrap").find("#oneClickMsg");g.removeClass("success").removeClass("error").addClass(a);if(null!=b)g.html(b);else if(null!=d){a="";a=SideType.getInstanceOf(d.sideType);b="txn"==c?"Bet Matched ":"Bet Unmatched ";c="txn"==c?d.stake:d.lastPrice;var h=CurrencyType.getInstanceOf(PageConfig.playerCurrency);CurrencyUtil.updateSetting({currencySymbol:h.symbol});a=b+StringUtil.ucfirst(a.name)+
" "+d.selectionName+" "+CurrencyUtil.formatter(c)+" at odds "+d.odds;g.html(a)}e&&setTimeout(function(){g.fadeOut()},2E3);g.fadeIn()}})();

