"undefined"==typeof RacingSportUtil&&(RacingSportUtil={});
(function(){RacingSportUtil.initQueryRacingByDay=function(d,b,n){$j.ajax({type:"POST",dataType:"JSON",url:(PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost?QueryDataSubDomainUtil.queryHost:"")+PageConfig.queryRacingByDayPath,data:{isInit:!0,dayType:d,eventType:b,marketTs:-1,queryPass:PageConfig.queryPass},xhrFields:{withCredentials:!0},success:n,error:function(h){PageConfig.enableQueryDataSubdomain&&null!=QueryDataSubDomainUtil.queryHost&&!QueryDataSubDomainUtil.isLineDown&&
(QueryDataSubDomainUtil.queryHost=null,QueryDataSubDomainUtil.isLineDown=!0);Trace.error(h)}})};var E=function(d){d.find("#closeInfo").hide()},F=function(d){d.find("#closeInfo").show()};RacingSportUtil.initRenderRacing=function(d){for(var b=new TreeMap,n=new TreeMap,h=0;h<d.length;h++){var g=d[h],a=g.countryCode;if(null!=a){var c=b.get(a);null==c&&(c=[],b.put(a,c));c[c.length]=g}}b.keySet().sort(function(k,e){return k.localeCompare(e)});d=$j("#contentBox");for(h=0;h<b.keySet().length;h++){a=b.keySet()[h];
var l=$j("#countryGroup_"+a);0==l.length&&(l=$j("#countryGroupTemplate").clone(),l.attr("id","countryGroup_"+a),d.append(l),UiUtils.bindToExpand(l.find(".to-expand"),E,F));var t=RacingSportUtil.getCountryName(a);l.find("#heading").html(t);t=!1;c=b.get(a);for(var u=0;u<c.length;u++){g=c[u];var p=$j("#racingBox_"+g.id);0==p.length&&(p=$j("#racingBoxTemplate").clone(),p.attr("id","racingBox_"+g.id),l.find("#gameList").append(p));p.css("display","block");p.find("#eventName").html(g.name);p.find("#placeInfo").html("--").hide();
var B=p.find("#timeRacing");g.markets.sort(function(k,e){return 0==k.marketTime.localeCompare(e.marketTime)?k.marketName.localeCompare(e.marketName):k.marketTime.localeCompare(e.marketTime)});if(0<g.markets.length){for(var w=null,r=0;r<g.markets.length;r++){var f=g.markets[r];if("WIN"==f.marketType&&!(MarketUtil.isClosed(f.status)||EventUtils.isCloseSite(g.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(f.closeSite,PageConfig.webSiteType))){w=f;break}}null!=w&&(r=n.get(a),(null==r||0>w.marketTime.localeCompare(r))&&
n.put(a,w.marketTime))}w=!1;for(r=0;r<g.markets.length;r++)if(f=g.markets[r],"WIN"==f.marketType&&!(MarketUtil.isClosed(f.status)||EventUtils.isCloseSite(g.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(f.closeSite,PageConfig.webSiteType))){w=!0;var x=PageConfig.fullMarketPath+"?eventType="+g.eventType+"&eventId="+f.eventId+"&marketId="+f.marketId,y=f.marketTime.split(" ")[1];"WIN"!=f.marketType&&(y=y+" "+f.marketType);0==$j("#market_"+f.marketId.replace(".","_")).length&&(1==f.inPlay?
(B.append('<li><a id="market_'+f.marketId.replace(".","_")+'" title="'+f.marketName+'" href="'+x+'" marketDateTime="'+f.marketDateTime+'" class="in-play">'+y+"</a></li>"),"0"!=f.streamingChannel?p.find("#streamingIcon").show():p.find("#streamingIcon").hide()):B.append('<li><a id="market_'+f.marketId.replace(".","_")+'" title="'+f.marketName+'" href="'+x+'" marketDateTime="'+f.marketDateTime+'">'+y+"</a></li>"));x=p.attr("firstMarketTime");(null==x||0>f.marketTime.localeCompare(x))&&p.attr("firstMarketTime",
f.marketTime)}w?t=!0:$j("#racingBox_"+g.id).remove()}g=l.find(".to-expand").find("#closeInfo");l=l.find("[id^=racingBox_]");var z=0,q=c="",A=0,C=(new Date).getTime();l.each(function(){var k=$j(this).find("#timeRacing").find("li");A+=k.length;for(var e=0;e<k.length;e++){var m=k.get(e);m=$j(m).find("a").attr("marketDateTime");if(0<=m-C){if(0==z||m<z)z=m;q=(z-C)/6E4+""}}});0<q.indexOf(".")&&(q=q.split(".")[0]);60<parseInt(q)&&(c=parseInt(q)/60+"",0<c.indexOf(".")&&(c=c.split(".")[0],q=q-60*parseInt(c)+
"",c="in "+c+" hrs "));""==c&&(c="in ");"0"!=q&&(q+=" mins");l="(Next "+c+q+")";"(Next in 0)"==l&&(l="(Next race starting soon)");1<A?g.html("Races "+A+" "+l):g.html("Race "+A+" "+l);t||$j("#countryGroup_"+a).remove()}for(h=0;h<n.keySet().length;h++)a=n.keySet()[h],$j("#countryGroup_"+a).attr("firstMarketTime",n.get(a));b=d.children();b.sort(function(k,e){k=$j(k);e=$j(e);var m=k.attr("firstMarketTime"),v=e.attr("firstMarketTime");if(null==m||null==v)Trace.error(k),Trace.error(e);return null==m&&null==
v?0:null==m?1:null==v?-1:0==m.localeCompare(v)?(k=k.find("#heading").html(),e=e.find("#heading").html(),k.localeCompare(e)):m.localeCompare(v)});d.append(b);b.each(function(){$this=$j(this);var k=$this.find("[id^=racingBox_]");k.sort(function(e,m){e=$j(e);m=$j(m);var v=e.attr("firstMarketTime"),D=m.attr("firstMarketTime");return 0==v.localeCompare(D)?(e=e.find("#eventName").html(),m=m.find("#eventName").html(),e.localeCompare(m)):v.localeCompare(D)});$this.append(k)})};RacingSportUtil.updateMarkets=
function(d){for(var b=0;b<d.length;b++){var n=d[b];n.markets.sort(function(u,p){return u.marketDateTime>p.marketDateTime?1:u.marketDateTime>p.marketDateTime?-1:0});for(var h=$j("#racingBox_"+n.id),g=0;g<n.markets.length;g++){var a=n.markets[g];if("WIN"==a.marketType){var c=$j("#market_"+a.marketId.replace(".","_"));if(0<c.length){if(1==a.inPlay?(0==c.hasClass("in-play")&&c.addClass("in-play"),"0"!=a.streamingChannel?h.find("#streamingIcon").show():h.find("#streamingIcon").hide()):c.removeClass("in-play"),
MarketUtil.isClosed(a.status)||EventUtils.isCloseSite(n.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(a.closeSite,PageConfig.webSiteType))1==a.inPlay&&h.find("#streamingIcon").hide(),c.parent().fadeOut("slow"),setTimeout(function(u){return function(){$j("#market_"+u).parent().remove();0==h.find("li").length&&h.remove()}}(a.marketId.replace(".","_")),5E3)}else if(!(MarketUtil.isClosed(a.status)||EventUtils.isCloseSite(n.closeSite,PageConfig.webSiteType)||MarketUtil.isCloseSite(a.closeSite,
PageConfig.webSiteType))){b=h.find("#timeRacing").clone();c=a.marketTime.split(" ")[1];var l=PageConfig.fullMarketPath+"?eventType="+n.eventType+"&eventId="+a.eventId+"&marketId="+a.marketId;1==a.inPlay?(b.append('<li><a id="market_'+a.marketId.replace(".","_")+'" title="'+a.marketName+'" href="'+l+'" marketDateTime="'+a.marketDateTime+'" class="in-play">'+c+"</a></li>"),"0"!=a.streamingChannel?racingBoxTemplate.find("#streamingIcon").show():racingBoxTemplate.find("#streamingIcon").hide()):b.append('<li><a id="market_'+
a.marketId.replace(".","_")+'" title="'+a.marketName+'" href="'+l+'" marketDateTime="'+a.marketDateTime+'">'+c+"</a></li>");var t=[];b.find("li").each(function(){t.push($j(this))});h.find("#timeRacing").find("li").remove();for(b=0;b<t.length;b++)h.find("#timeRacing").append(t[b])}}}}};RacingSportUtil.getCountryNameWithType=(d,b)=>"GROUP"!=d?b:RacingSportUtil.getCountryName(b);RacingSportUtil.getCountryName=d=>{if(2==d.length){var b=CountryCodeType.getInstanceByShortCode(d);return null==b?d:b.countryName}return 3==
d.length?(b=CountryCodeType.getInstanceOf(d),null==b?d:b.countryName):d}})();

