"undefined"==typeof CommonTransferWalletHandler&&(CommonTransferWalletHandler={});
(function(){CommonTransferWalletHandler.init=function(){var a=$j("#commonDialogWrap");SlideBarUtil.init($j("#commonSlideBar"),a.find("#commonDeposit"),a.find("#commonZeroBtn"),a.find("#commonMaxBtn"))};CommonTransferWalletHandler.validatePageNumber=function(a){a.value=a.value.replace(/[\D]|^0[\d]+/,"")};CommonTransferWalletHandler.openDepositPage=function(a,c,b,d,e,g,k){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var l=VendorSiteType.getInstanceOf(a);$j("#commonTitle").html(c);
$j("#commonVendorBalanceTitle").html(l.aliasEventName+" Balance");$j("#commonCancelBtn").removeClass("disable");$j("#commonDepositAndLogin").addClass("disable");CommonTransferWalletHandler.bindCloseButtonEvent();CommonTransferWalletHandler.initResetPasswordDiv();CommonTransferWalletHandler.bindResetPasswordCloseButtonEvent();var f=$j("#vendorRules");f.hide();f.empty();$j("#commonDeposit").val("");SlideBarUtil.changeSlideBarByValue($j("#commonSlideBar"),0);var n=$j("#commonDialogWrap"),r=$j("#vendorResetPasswordDiv");
$j("#vendorResetPassword").unbind("onclick");$j.ajax({type:"POST",url:PageConfig.vendorControllerPath+"queryVendorCurrencyInfo",data:{vendorSite:a},beforeSend:function(){},complete:function(){},success:function(h){if(null!=h)if(h.error)CommonTransferWalletHandler.showMessage(h.error);else{var m=CurrencyType.getInstanceOf(h.currencyType),p=n.find("#commonPlayerBalance"),q=n.find("#commonPlayerVendorBalance"),t=CommonTransferWalletHandler.formatCurrency(m,h.betCredit);m=CommonTransferWalletHandler.formatCurrency(m,
h.vendorPlayerBalance,2);PageConfig.isMobileOrTablet?(UiUtils.removeContents(p),UiUtils.removeContents(q),p.find("span").after(t),q.find("span").after(m)):(p.html(t),q.html(m));h.isEnableVendorLogin&&CommonTransferWalletHandler.bindLoginButtonEvent(a,b,d,e,g,k);h.usingVendorAccount&&n.find("#openResetPasswordBtn").show().bind("click",function(){$j("#vendorResetPassword").html("Reset Password").unbind("click").bind("click",function(){CommonTransferWalletHandler.updatePassword(a)});$j("#vendorResetPasswordDiv").show()});
h.isFirstLogin&&(n.find("#openResetPasswordBtn").addClass("disable").unbind("click"),r.find("#isFirstLogin").val(h.isFirstLogin));h.rk&&r.find("#rk").val(h.rk);h.lrk&&(PageConfig.valid=h.lrk);$j("#vendorResetPassword").bind("click",function(){CommonTransferWalletHandler.updatePassword(a)});VendorSiteType.MT5.value==a&&(f.show(),f.append("<strong>Rules:</strong> In Sky Trader Trade (bets) should be kept minimum for 15 minutes (profit before 15 min trade will be voided)"));SlideBarUtil.updateAttr($j("#commonSlideBar"),
Math.floor(h.betCredit))}}});$j("#common_transfer_to_go").css("display",PageConfig.isMobileOrTablet?"flex":"block")}};CommonTransferWalletHandler.checkAndGetVendorPlayerPw=function(){var a={},c=$j("#loginPassword").val(),b=$j("#updatePassword").val(),d=$j("#updatePasswordConfirm").val(),e=$j("#rk").val(),g=/^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,8}$/;if(null==c||0==c.length||null==b||null==d||0==b.length||0==d.length)CommonTransferWalletHandler.showResetPasswordMessage(I18N.get("msg.error.account.passwordEmpty"));
else if(g.test(b))if(g.test(d))if(b!=d)CommonTransferWalletHandler.showResetPasswordMessage(I18N.get("msg.error.validation.passwordNotMatch"));else return c=EncryptUtil.mask(EncryptUtil.mask(c)+PageConfig.valid),b=CryptoJS.enc.Utf8.parse(b),g=CryptoJS.enc.Utf8.parse(e),e=CryptoJS.AES.encrypt(b,g,{mode:CryptoJS.mode.ECB,padding:CryptoJS.pad.Pkcs7}),b=CryptoJS.enc.Utf8.parse(d),d=CryptoJS.AES.encrypt(b,g,{mode:CryptoJS.mode.ECB,padding:CryptoJS.pad.Pkcs7}),a.lp=c,a.lpValid=PageConfig.valid,a.up=e.toString(),
a.upc=d.toString(),a;else CommonTransferWalletHandler.showResetPasswordMessage(I18N.get("msg.error.validation.mt5.passwordFormat","update password confirm"));else CommonTransferWalletHandler.showResetPasswordMessage(I18N.get("msg.error.validation.mt5.passwordFormat","update password"))};CommonTransferWalletHandler.updatePassword=function(a){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin()){var c=CommonTransferWalletHandler.checkAndGetVendorPlayerPw();$j.ajax({type:"POST",url:PageConfig.vendorControllerPath+
"updatePassword",data:{vendorSite:a,lp:c.lp,valid:c.lpValid,up:c.up,upc:c.upc},beforeSend:function(){$j("#resetVendorPasswordErrorMsg").html("");$j("#vendorResetPassword").unbind("onclick").addClass("disable")},complete:function(){$j("#vendorResetPassword").bind("onclick",function(){CommonTransferWalletHandler.updatePassword(a)}).removeClass("disable")},success:function(b){null!=b&&(PageConfig.valid=b.lrk,$j("#rk").val(b.rk),b.error?CommonTransferWalletHandler.showResetPasswordMessage(b.error):CommonTransferWalletHandler.showResetPasswordMessage("Update Password Success"))}})}};
CommonTransferWalletHandler.loginAndDeposit=function(a,c,b,d,e,g){if("undefined"==typeof LoginHandler||LoginHandler.userIsLogin())if(PageConfig.isAllowVendorMap.get(a)){CommonTransferWalletHandler.hideMessage();CommonTransferWalletHandler.hideResetPasswordMessage();var k={};if(g)k=CommonTransferWalletHandler.checkAndGetVendorPlayerPw();else if(VendorSiteType.MT5.value==a&&"true"==$j("#isFirstLogin").val()){$j("#vendorResetPasswordDiv").show();$j("#vendorResetPasswordTitle").html("Reset Sky Trader Password For First Login");
$j("#vendorResetPassword").html("Update And Login");$j("#vendorResetPassword").unbind("click").bind("click",function(){CommonTransferWalletHandler.loginAndDeposit(a,c,b,d,e,!0)});return}var l=""===$j("#commonDeposit").val()?0:$j("#commonDeposit").val();CommonTransferWalletHandler.unBindEvent();e?(g="/exchange/member/vendorController/loginAndLaunchGame",k={vendorSite:a,platform:c,gameCode:d,depositBalance:l}):(g="/exchange/member/vendorController/login",k={vendorSite:a,platform:c,gameType:b,gameCode:d,
depositBalance:l,lp:k.lp,valid:k.lpValid,up:k.up,upc:k.upc});$j.ajax({type:"POST",url:g,data:k,async:!1,beforeSend:function(){},complete:function(){},success:function(f){null!=f&&(PageConfig.valid=f.lrk,$j("#rk").val(f.rk),f.error?(CommonTransferWalletHandler.showMessage(f.error),CommonTransferWalletHandler.bindLoginButtonEvent(a,c,b,d,e),CommonTransferWalletHandler.bindCloseButtonEvent()):f.depositMsg&&""!==f.depositMsg?(CommonTransferWalletHandler.showMessage(f.depositMsg),CommonTransferWalletHandler.bindLoginButtonEvent(a,
c,b,d,e),CommonTransferWalletHandler.bindCloseButtonEvent()):f.success&&($j("#isFirstLogin").val(!1),$j("#common_transfer_to_go").hide(),e?window.open(f.success):"string"===typeof a&&Number(a)===VendorSiteType.ROYAL.value||a===VendorSiteType.ROYAL.value?window.open(f.success,"_blank",`height=${screen.height},width=${screen.width}, location=no`):window.open(f.success,"_blank","height=1000,width=1256, location=no")))}})}else NoticeHandler.error("Not allow to play this game!")};CommonTransferWalletHandler.mobileLoginAndDeposit=
function(a,c,b,d,e,g,k){if(MobileLoginHandler.userIsLogin()){var l=""===$j("#commonDeposit").val()?0:$j("#commonDeposit").val();CommonTransferWalletHandler.unBindEvent();var f={};if(k)f=CommonTransferWalletHandler.checkAndGetVendorPlayerPw();else if("true"==$j("#isFirstLogin").val()){$j("#vendorResetPasswordDiv").show();$j("#vendorResetPasswordTitle").html("Reset Sky Trader Password For First Login");$j("#vendorResetPassword").html("Update And Login");$j("#vendorResetPassword").unbind("click").bind("click",
function(){CommonTransferWalletHandler.mobileLoginAndDeposit(a,c,b,d,e,g,!0)});return}g?MobileCommonCasinoHandler.loginAndLaunchGame(a,c,d,e,l):MobileCommonCasinoHandler.login(a,c,b,d,l,f)}};CommonTransferWalletHandler.formatCurrency=function(a,c,b){return CurrencyUtil.formatter(c,{precision:b,separateSign:",",currencySymbol:a.symbol,formatter:function(d,e){e=0==StringUtil.getlength(StringUtil.trim(e.currencySymbol))?"":e.currencySymbol;return 0==d.indexOf("-")?"("+e+d.replace("-","")+")":e+d},"trailingZeros,":!1})};
CommonTransferWalletHandler.bindLoginButtonEvent=function(a,c,b,d,e,g){$j("#commonDeposit").prop("disabled",!1);$j("#commonDepositAndLogin, #commonCancelBtn").removeClass("disable");$j("#commonDepositAndLogin").on("click",function(){PageConfig.isMobileOrTablet?CommonTransferWalletHandler.mobileLoginAndDeposit(a,c,b,d,e,g):CommonTransferWalletHandler.loginAndDeposit(a,c,b,d,g)})};CommonTransferWalletHandler.initResetPasswordDiv=function(){$j("#vendorResetPasswordDiv").hide();$j("#updatePassword").val("");
$j("#updatePasswordConfirm").val("");$j("#loginPassword").val("");$j("#resetVendorPasswordErrorMsg").html("");$j("#openResetPasswordBtn").hide();$j("#openResetPasswordBtn").removeClass("disable")};CommonTransferWalletHandler.bindResetPasswordCloseButtonEvent=function(){$j("#closeVendorResetPasswordDiv").on("click",function(){$j("#vendorResetPasswordDiv").hide()})};CommonTransferWalletHandler.bindCloseButtonEvent=function(){$j("#closeCommonDepositModal, #commonCancelBtn").on("click",function(){CommonTransferWalletHandler.unBindEvent();
$j("#common_transfer_to_go").hide();$j("#commonErrorMsg").hide()})};CommonTransferWalletHandler.unBindEvent=function(){$j("#commonDeposit").prop("disabled",!0);$j("#commonDepositAndLogin, #commonCancelBtn").addClass("disable");$j("#closeCommonDepositModal, #commonCancelBtn, #commonDepositAndLogin").unbind("click")};CommonTransferWalletHandler.showMessage=function(a){a=I18N.get(a,a);PageConfig.isMobileOrTablet?alert(a):NoticeHandler.error(a);$j("#commonErrorMsg").html(a);$j("#commonErrorMsg").show()};
CommonTransferWalletHandler.showResetPasswordMessage=function(a){a=I18N.get(a,a);PageConfig.isMobileOrTablet?alert(a):NoticeHandler.error(a);$j("#resetVendorPasswordErrorMsg").html(a);$j("#resetVendorPasswordErrorMsg").show()};CommonTransferWalletHandler.hideResetPasswordMessage=function(a){$j("#resetVendorPasswordErrorMsg").html("");$j("#resetVendorPasswordErrorMsg").hide()};CommonTransferWalletHandler.hideMessage=function(){$j("#commonErrorMsg").html("");$j("#commonErrorMsg").hide()}})();

